import { StudyWeek } from "@/lib/types";
import { LAB_TROUBLESHOOTING, LAB_WORKSHOP } from "@/content/workshops/lab-virtualbox";
import { LAB_CHECKPOINT_GUIDED, LAB_HOSTONLY_GUIDED, LAB_TROUBLE_GUIDED } from "@/content/guided/lab-hostonly";
import { LAB_MS2_GUIDED } from "@/content/guided/lab-ms2";
import { LINUX_FS_WORKSHOP, LINUX_SHELL_WORKSHOP, LINUX_TROUBLESHOOTING } from "@/content/workshops/linux-fundamentals";
import { NET_IP_WORKSHOP, NET_PORTS_WORKSHOP, NET_TROUBLESHOOTING } from "@/content/workshops/networking-fundamentals";

/**
 * Semana 0 — Lab. Kali = SO principal del PC. VirtualBox = SOLO las víctimas.
 */
export const labWeek: StudyWeek = {
  id: "m0-w0",
  monthId: "m0",
  title: "Semana 0 — Lab: Kali (host) + víctimas en VirtualBox",
  goal: "Lab aislado + Linux mínimo + redes mínimas (IPv4/CIDR/puertos). Sin eso no empieces Nmap de la Semana 1.",
  detailed: true,
  blocks: [
    {
      id: "m0-w0-b1",
      weekId: "m0-w0",
      order: 1,
      title: "Red Host-Only: el host Kali ve la VM",
      titleEn: "Host-only network: Kali host reaches the guest VM",
      objective: "Ver vboxnet0 en Kali, anotar tu IP (suele ser 192.168.56.1) y dejar lista la red para la víctima del bloque 2.",
      objectiveEn: "Identify vboxnet0 on the Kali host and write down LHOST (often 192.168.56.1).",
      durationMin: 50,
      type: "practice",
      theoryEs:
        "Kali es el SO del PC (atacante). VirtualBox solo corre víctimas. Host-Only (vboxnet0) es el switch virtual: te ves con la VM y ella no sale a Internet. NAT = VM sale a Internet (no es cómo atacas). Bridged = la víctima entra en tu LAN doméstica (no lo uses). LHOST = tu IP en vboxnet0. RHOSTS = IP de la víctima. Leer este párrafo no basta: hay un taller debajo y recall obligatorio.",
      theoryEn:
        "Attacker = Kali bare metal. Targets = VirtualBox guests on Host-Only. LHOST = your vboxnet0 IP. RHOSTS = guest IP. Do not Bridged an intentionally vulnerable VM onto your home LAN.",
      examPhrases: [
        "attacker machine / local host (LHOST)",
        "target host / remote host (RHOSTS)",
        "host-only adapter",
        "do not expose the lab to the Internet",
        "private IP / subnet / CIDR",
      ],
      practiceSteps: [
        "Confirma Kali host (no Kali-VM): cat /etc/os-release | head -3",
        "Verifica VirtualBox: virtualbox --help | head -1  (si falla: sudo apt install -y virtualbox virtualbox-qt)",
        "File → Tools → Network Manager → Create Host-Only Network (vboxnet0). IPv4 192.168.56.1 / 255.255.255.0. DHCP ON opcional (.100–.254).",
        "En Kali: ip addr   — localiza vboxnet0. Anota: nombre, UP/DOWN, inet (IP/máscara).",
        "En Kali: ip route  — confirma 192.168.56.0/24 (o tu prefijo) dev vboxnet0. Eso NO es la ruta default de Internet.",
        "Anota LHOST=<inet de vboxnet0> en ~/ejpt-lab.txt. Esa IP es el atacante, no la víctima.",
        "Di en voz alta (sin leer): diferencia NAT / Bridged / Host-Only y por qué Host-Only en MS2. Luego los recall.",
        "STOP. No importes la víctima todavía si vboxnet0 no está UP. El guest es el bloque 2.",
      ],
      workshop: LAB_WORKSHOP,
      guidedLab: [...LAB_HOSTONLY_GUIDED, ...LAB_TROUBLE_GUIDED, ...LAB_CHECKPOINT_GUIDED],
      troubleshooting: LAB_TROUBLESHOOTING,
      subtopics: ["lab-vbox"],
      drills: [
        {
          id: "d1",
          promptEs: "Comando para listar interfaces (vas a buscar vboxnet0).",
          promptEn: "Command to list interfaces (you are looking for vboxnet0).",
          answer: "ip a",
          subtopicId: "lab-vbox",
          explanation:
            "No es nmap ni ping. Primero identificas interfaces del host Kali para ver si existe vboxnet0 y anotar LHOST.",
          howToEs: "Escribe el comando corto de iproute2 para ver direcciones. Suele aceptarse también: ip addr",
          conceptQuestion: "¿Qué interfaz Host-Only buscas y para qué sirve su IP?",
          conceptAnswer: "vboxnet0",
        },
        {
          id: "d2",
          promptEs: "Comando para ver las rutas (buscar 192.168.56.0/24 en vboxnet0).",
          promptEn: "Command to show routes (look for the lab subnet on vboxnet0).",
          answer: "ip route",
          subtopicId: "lab-vbox",
          explanation:
            "ip addr lista IPs. ip route dice por qué interfaz se alcanza cada red. El lab no es la default via wlan0.",
          howToEs: "Dos palabras: ip route",
        },
        {
          id: "d3",
          promptEs: "¿Qué función cumple Host-Only en este lab?",
          promptEn: "What is Host-Only for in this lab?",
          answer: "aislar atacante y victima sin internet",
          answerKeywords: ["aisl"],
          subtopicId: "lab-vbox",
          explanation:
            "No es 'para que la VM tenga WiFi'. Host-Only crea un switch virtual: Kali y la víctima se ven; la víctima no sale a Internet ni a tu LAN doméstica.",
          howToEs: "En una frase: aislamiento / lab local / sin exponer la víctima. Debe aparecer la idea de aislar.",
        },
        {
          id: "d4",
          promptEs: "¿Qué es vboxnet0?",
          promptEn: "What is vboxnet0?",
          answer: "interfaz virtual host-only del host",
          answerKeywords: ["vboxnet"],
          subtopicId: "lab-vbox",
          explanation:
            "No es la IP de Metasploitable. Es la NIC virtual en TU Kali (el host) que representa el switch Host-Only.",
          howToEs: "Di que es la interfaz Host-Only del host (puedes escribir vboxnet0).",
        },
        {
          id: "d5",
          promptEs: "¿Cuál es LHOST en este lab?",
          promptEn: "What is LHOST in this lab?",
          answer: "IP del atacante en vboxnet0",
          answerKeywords: ["vboxnet"],
          subtopicId: "lab-vbox",
          explanation:
            "LHOST no es la víctima. Local Host = TU Kali en la red de lab (inet de vboxnet0), a donde vuelve una reverse shell.",
          howToEs: "Di que es TU IP en vboxnet0 (atacante). Debe aparecer vboxnet.",
        },
        {
          id: "d6",
          promptEs: "¿Cuál es RHOST / RHOSTS?",
          promptEn: "What is RHOST / RHOSTS?",
          answer: "IP de la victima",
          answerKeywords: ["victima"],
          subtopicId: "lab-vbox",
          explanation: "Remote Host = objetivo. En el lab: IP del guest (MS2/Kioptrix), no vboxnet0.",
          howToEs: "Palabra clave: víctima (o target / objetivo).",
        },
        {
          id: "d7",
          promptEs: "¿Por qué NO pones Metasploitable en Bridged sobre tu WiFi de casa?",
          promptEn: "Why not Bridged an intentionally vulnerable VM onto your home Wi-Fi?",
          answer: "expone una maquina vulnerable en la lan domestica",
          answerKeywords: ["expon"],
          subtopicId: "lab-vbox",
          explanation:
            "Bridged la convierte en un vecino más de tu router. MS2 está diseñado para ser explotado. Host-Only la deja solo al alcance de tu Kali.",
          howToEs: "Habla de red doméstica / LAN / Internet / exposición. Evita 'porque sí'.",
        },
      ],
      glossary: [
        { en: "bare metal / host OS", es: "Kali instalado en el disco, no en una VM" },
        { en: "guest VM", es: "máquina virtual víctima" },
        { en: "host-only adapter (vboxnet0)", es: "LAN de laboratorio en el host" },
        { en: "LHOST", es: "IP de TU Kali en esa LAN (atacante)" },
        { en: "RHOSTS", es: "IP de la víctima (guest)" },
        { en: "NAT", es: "la VM sale a Internet a través del host" },
        { en: "bridged adapter", es: "la VM se comporta como un PC más en la LAN física" },
        { en: "subnet / CIDR", es: "rango y máscara (ej. 192.168.56.0/24)" },
      ],
      comparisonTable: {
        caption: "Modos de red (víctimas: solo Host-Only)",
        headers: ["Modo", "Camino", "¿Atacas al guest?", "¿Guest a Internet?", "Úsalo en MS2?"],
        rows: [
          ["NAT", "VM → Host → Internet", "Incómodo / IPs ocultas", "Sí", "No (único NIC)"],
          ["Bridged", "VM → router → LAN casa", "Sí, pero en tu casa", "Sí", "No"],
          ["Host-Only", "Host ↔ vboxnet0 ↔ guest", "Sí, aislado", "No", "Sí"],
        ],
      },
      resources: [
        { label: "VirtualBox Manual — Host-Only Networking", url: "https://www.virtualbox.org/manual/ch06.html#network_hostonly", platform: "Docs" },
      ],
      closingChecklist: [
        "Kali operativo como SO del PC (no una VM de Kali)",
        "VirtualBox abre y vboxnet0 está UP",
        "Identifiqué vboxnet0 en ip addr (IP + máscara + UP)",
        "Identifiqué la ruta 192.168.56.0/24 (o mi prefijo) en ip route",
        "IP de Kali/LHOST escrita en ~/ejpt-lab.txt",
        "Puedo explicar NAT vs Bridged vs Host-Only sin leer",
        "Sé por qué no Bridged una VM vulnerable en la LAN de casa",
        "Recall de este bloque acertados (no solo leí el taller)",
      ],
    },
    {
      id: "m0-w0-b2",
      weekId: "m0-w0",
      order: 2,
      title: "Importar Metasploitable 2 (guest)",
      titleEn: "Import Metasploitable 2 as a VirtualBox guest",
      objective: "La VM arranca, tiene IP en 192.168.56.0/24, y desde Kali host: nmap -sV -p21,445 muestra vsftpd y samba.",
      objectiveEn: "From the Kali host, nmap -sV -p21,445 against MS2 must show vsftpd and samba.",
      durationMin: 50,
      type: "practice",
      theoryEs:
        "Metasploitable 2 es un Ubuntu viejo hecho para romperlo: vsftpd 2.3.4 (backdoor), Samba, DistCC. Login de consola: msfadmin / msfadmin. Adapter 1 = Host-Only. Quita NAT. Si no, la VM sale a Internet y es un riesgo.",
      theoryEn:
        "Metasploitable 2 is an intentionally vulnerable Linux VM. Console login msfadmin/msfadmin. Nic 1 = Host-Only only. You will use it for scanning, SMB enum, and the vsftpd 2.3.4 exploit.",
      examPhrases: ["service version detection (-sV)", "open ports 21/tcp 445/tcp", "intentionally vulnerable"],
      practiceSteps: [
        "Descarga oficial Metasploitable 2 e importa el .vmdk (Linux/Ubuntu, 512 MB).",
        "Adapter 1 = Host-Only (mismo nombre que vboxnet en Kali). Adapter 2 off. Sin NAT/Bridged.",
        "Arranca. Login msfadmin/msfadmin. En el GUEST: ifconfig o ip a — anota LA inet que salga (RHOST).",
        "En Kali host: ping -c 3 <IP_VICTIMA que viste>. Si falla, no asumas apagada: adaptador, misma /24, ruta.",
        "nmap -sn <SUBRED de ip route, no un /24 de un blog>. Identifica el guest vs tu Kali.",
        "nmap -sV <IP_VICTIMA>. Interpreta PORT/STATE/SERVICE. Escribe TARGET_MS2= en ~/ejpt-lab.txt.",
      ],
      guidedLab: LAB_MS2_GUIDED,
      subtopics: ["lab-vbox", "nmap-basic"],
      troubleshooting: LAB_TROUBLESHOOTING.filter((t) =>
        ["no-ping", "split-nets", "wrong-adapter", "vm-wont-start", "kali-no-ip"].includes(t.id)
      ),
      drills: [
        {
          id: "d1",
          promptEs: "Credenciales de consola MS2 (user/pass).",
          promptEn: "Metasploitable 2 console credentials (user/pass).",
          answer: "msfadmin/msfadmin",
        },
        {
          id: "d2",
          promptEs: "nmap versiones contra la IP de TU víctima (escribe el patrón; sustituye la IP).",
          promptEn: "Version scan against YOUR target IP (pattern).",
          answer: "nmap -sV",
          answerKeywords: ["nmap", "-sv"],
          subtopicId: "nmap-basic",
          explanation: "-sn no da versiones. Ya tienes un host: preguntas qué servicio hay. La IP es la que descubriste, no un ejemplo.",
          howToEs: "Debe aparecer nmap y -sV. La IP la pones tú.",
        },
        {
          id: "d3",
          promptEs: "Ping de 3 paquetes a la víctima (patrón; usa TU IP).",
          promptEn: "3 ICMP echoes to your guest.",
          answer: "ping -c 3",
          answerKeywords: ["ping", "-c"],
          subtopicId: "lab-vbox",
          explanation: "Sin -c el ping no para. IP de TU guest, no 8.8.8.8.",
          howToEs: "ping -c y un número de paquetes. La IP es la tuya.",
        },
      ],
      glossary: [
        { en: "guest", es: "VM víctima" },
        { en: "baseline scan", es: "primer nmap guardado" },
      ],
      resources: [
        { label: "Metasploitable 2 download (SourceForge)", url: "https://sourceforge.net/projects/metasploitable/files/Metasploitable2/", platform: "Local" },
        { label: "Rapid7 Metasploitable 2 exploitability guide", url: "https://docs.rapid7.com/metasploit/metasploitable-2-exploitability-guide/", platform: "Docs" },
      ],
      closingChecklist: [
        "Victim operativo (login msfadmin/msfadmin)",
        "Adapter 1 = Host-Only, NAT off",
        "IP de la víctima identificada y escrita (TARGET_MS2)",
        "ping -c 3 desde Kali host funciona",
        "nmap -sV muestra vsftpd y samba; -oA ~/ms2_baseline existe",
        "LHOST y RHOSTS no son la misma IP",
      ],
    },
    {
      id: "m0-w0-b3",
      weekId: "m0-w0",
      order: 3,
      title: "DVWA en Docker (en el Kali host)",
      titleEn: "Run DVWA in Docker on the Kali host",
      objective: "http://127.0.0.1:4280 abre DVWA; login admin/password; security = low.",
      objectiveEn: "Browse http://127.0.0.1:4280, login admin/password, set DVWA security to low.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "DVWA corre en TU Kali (Docker), no en VirtualBox. Puerto 4280 en localhost. Mes 2 (SQLi/XSS/LFI) usa esta URL. Si docker no existe: sudo apt update && sudo apt install -y docker.io && sudo usermod -aG docker $USER y CIERRA SESIÓN (logout) y vuelve a entrar.",
      theoryEn:
        "DVWA is a local web target for SQL injection, XSS, and file inclusion. Security level low = no filters. This is not a VM.",
      examPhrases: ["SQL injection", "cross-site scripting (XSS)", "local file inclusion (LFI)", "security level: low"],
      practiceSteps: [
        "On Kali host: docker --version",
        "If missing: sudo apt update && sudo apt install -y docker.io && sudo systemctl enable --now docker && sudo usermod -aG docker $USER — then log out and log in",
        "docker run --rm -d --name dvwa -p 4280:80 vulnerables/web-dvwa",
        "Firefox: http://127.0.0.1:4280 — username admin password password — Create / Reset Database if asked",
        "DVWA Security → low → Submit. You must see the left menu: Brute Force, SQL Injection, XSS, File Inclusion",
        "Add to ~/ejpt-lab.txt: DVWA=http://127.0.0.1:4280",
      ],
      subtopics: ["lab-vbox", "web-sqli"],
      drills: [
        {
          id: "d1",
          promptEs: "Comando docker para DVWA en el puerto 4280.",
          promptEn: "Docker command to bind DVWA on host port 4280.",
          answer: "docker run --rm -d --name dvwa -p 4280:80 vulnerables/web-dvwa",
        },
      ],
      glossary: [
        { en: "bind port 4280:80", es: "puerto del host 4280 → 80 del contenedor" },
        { en: "security level low", es: "sin filtros; para practicar el payload crudo" },
      ],
      resources: [
        { label: "DVWA GitHub", url: "https://github.com/digininja/DVWA", platform: "Kali" },
      ],
      extraResources: [
        { label: "Fallback: Metasploitable 2 already serves web apps on TCP/80", url: "https://docs.rapid7.com/metasploit/metasploitable-2-exploitability-guide/", platform: "Local" },
      ],
      closingChecklist: [
        "http://127.0.0.1:4280 carga",
        "admin/password y security low",
      ],
    },
    {
      id: "m0-w0-b4",
      weekId: "m0-w0",
      order: 4,
      title: "Kioptrix Level 1 (segunda guest)",
      titleEn: "Kioptrix Level 1 — second guest VM",
      objective: "Segunda IP en 192.168.56.0/24 distinta a MS2; nmap -sC -sV -p- guardado. No explotar hoy.",
      objectiveEn: "Find a second host on the lab LAN and save nmap -sC -sV -p- . Do not exploit yet.",
      durationMin: 50,
      type: "practice",
      theoryEs:
        "Kioptrix 1 = Samba/Apache antiguos. Sustituye a HTB Lame. Import OVA o disco VMware. Misma receta: Adapter 1 Host-Only, NAT off.",
      theoryEn:
        "Second Linux target for enumeration practice. Today you only scan. Exploitation is week 4.",
      examPhrases: ["default NSE scripts (-sC)", "full port scan (-p-)", "do not skip version detection"],
      practiceSteps: [
        "Download: https://www.vulnhub.com/entry/kioptrix-level-1-1,22/",
        "VirtualBox → Import (OVA) or New + existing disk. Network: Host-Only vboxnet0 only.",
        "Start VM. On Kali host: nmap -sn 192.168.56.0/24 — you must see TWO guest IPs (MS2 + Kioptrix), plus .1 (you).",
        "nmap -sC -sV -p- <IP_KIOPTRIX> -oA ~/kioptrix1",
        "Write TARGET_K1=... in ~/ejpt-lab.txt. Stop. No Metasploit today.",
      ],
      subtopics: ["lab-vbox", "nmap-scripts"],
      drills: [
        {
          id: "d1",
          promptEs: "Host discovery en 192.168.56.0/24",
          promptEn: "Host discovery on 192.168.56.0/24",
          answer: "nmap -sn 192.168.56.0/24",
        },
      ],
      glossary: [{ en: "OVA", es: "VM empaquetada para importar" }],
      resources: [
        { label: "VulnHub — Kioptrix Level 1", url: "https://www.vulnhub.com/entry/kioptrix-level-1-1,22/", platform: "VulnHub" },
      ],
      closingChecklist: [
        "Dos IPs de guests distintas en nmap -sn",
        "Archivo ~/kioptrix1.nmap (o .gnmap/.xml por -oA) existe",
      ],
    },
    {
      id: "m0-w0-b5",
      weekId: "m0-w0",
      order: 5,
      title: "Cierre de lab: 4 líneas en un archivo",
      titleEn: "Lab freeze: four lines in one file",
      objective: "Tener ~/ejpt-lab.txt con LHOST, TARGET_MS2, TARGET_K1, DVWA y no tocar más descargas hoy.",
      objectiveEn: "Freeze lab IPs in ~/ejpt-lab.txt. No more VM downloads today.",
      durationMin: 25,
      type: "checkpoint",
      theoryEs:
        "TDAH: si sigues bajando VMs, no empiezas Nmap. Mínimo = MS2 + Kioptrix + DVWA. Kali ya está. Nada de Windows pirata.",
      theoryEn:
        "Scope lock. Extra VMs are optional after week 4, not now.",
      examPhrases: ["document your findings", "target IP address"],
      comparisonTable: {
        caption: "Download list (locked)",
        headers: ["Asset", "Runs where", "URL / command"],
        rows: [
          ["Kali", "Bare metal (you already have it)", "—"],
          ["Metasploitable 2", "VirtualBox guest", "sourceforge.net/projects/metasploitable"],
          ["Kioptrix 1", "VirtualBox guest", "vulnhub.com kioptrix-level-1"],
          ["DVWA", "Docker on Kali host", "docker run ... -p 4280:80"],
        ],
      },
      practiceSteps: [
        "nano ~/ejpt-lab.txt and keep EXACTLY this shape:",
        "LHOST=192.168.56.1",
        "TARGET_MS2=192.168.56.101",
        "TARGET_K1=192.168.56.102",
        "DVWA=http://127.0.0.1:4280",
        "cat ~/ejpt-lab.txt — if a line is missing, go back to that block. Then mark this block done.",
        "Siguiente (no Nmap todavía): bloques Linux de esta misma semana.",
      ],
      subtopics: ["lab-vbox"],
      resources: [
        { label: "Metasploitable 2", url: "https://sourceforge.net/projects/metasploitable/files/Metasploitable2/", platform: "Local" },
        { label: "VulnHub Kioptrix 1", url: "https://www.vulnhub.com/entry/kioptrix-level-1-1,22/", platform: "VulnHub" },
      ],
      closingChecklist: [
        "~/ejpt-lab.txt tiene 4 líneas",
        "No voy a descargar más VMs hasta terminar Semana 1",
        "Siguiente: Linux mínimo (bloques 6–7), luego Nmap",
      ],
    },
    {
      id: "m0-w0-b6",
      weekId: "m0-w0",
      order: 6,
      title: "Linux mínimo 1 — disco, usuarios, permisos, pipes",
      titleEn: "Minimum Linux 1 — fs, users, perms, pipes",
      objective: "En Kali host: pwd, ls -la, id, leer /etc/passwd, distinguir Permission denied, guardar whoami en un fichero con >.",
      objectiveEn: "On the Kali host: pwd, ls -la, id, read /etc/passwd, tell Permission denied apart from missing files, redirect whoami to a file.",
      durationMin: 50,
      type: "practice",
      theoryEs:
        "El eJPT se juega en una shell. Filesystem, uid y rwx no son 'cultura general': son cómo interpretas un archivo de config o un fallo al leer shadow. Pipes y > son cómo dejas evidencia. No es un curso de admin: es lo mínimo para no estar ciego antes de Nmap.",
      theoryEn:
        "You need the filesystem, identity (id), permissions, and redirects before scanning. This is not a sysadmin track.",
      examPhrases: [
        "current user / uid",
        "permission denied",
        "standard output redirection",
        "/etc/passwd",
      ],
      practiceSteps: [
        "pwd  y  ls -la  — confirma que estás en TU home de Kali, no en una VM guest.",
        "ls -la /  — identifica etc, home, tmp, usr de memoria (nombres, no todos los ficheros).",
        "id  y  whoami  — anota uid. Si eres root en Kali host, lo sabes; no lo confundas con root en MS2.",
        "less /etc/passwd  (q para salir). Localiza tu usuario y root. Campos: user:x:uid:gid:...",
        "ls -l /etc/shadow  — espera Permission denied o que solo root lea. Eso es correcto, no un bug.",
        "whoami > ~/ejpt-who.txt  &&  cat ~/ejpt-who.txt  &&  ip -br a | grep vboxnet",
        "Cierra los ojos: ¿qué diferencia No such file vs Permission denied? Luego recall.",
      ],
      workshop: LINUX_FS_WORKSHOP,
      troubleshooting: LINUX_TROUBLESHOOTING.filter((t) => ["no-such", "denied", "which-host"].includes(t.id)),
      subtopics: ["linux-basic"],
      drills: [
        {
          id: "d1",
          promptEs: "Comando: ¿en qué directorio estoy?",
          promptEn: "Command: where am I in the filesystem?",
          answer: "pwd",
          subtopicId: "linux-basic",
          explanation: "No es ls. pwd imprime el directorio de trabajo. ls lista contenido.",
          howToEs: "Tres letras: pwd",
        },
        {
          id: "d2",
          promptEs: "¿Qué archivo lista las cuentas del sistema (usuarios)?",
          promptEn: "Which file lists system accounts?",
          answer: "/etc/passwd",
          answerKeywords: ["passwd"],
          subtopicId: "linux-basic",
          explanation: "No es /etc/shadow (hashes, root). passwd lista logins y shells.",
          howToEs: "Ruta clásica bajo /etc. Debe aparecer passwd.",
        },
        {
          id: "d3",
          promptEs: "Comando que muestra uid, gid y grupos del usuario actual.",
          promptEn: "Command that shows uid, gid and groups.",
          answer: "id",
          subtopicId: "linux-basic",
          explanation: "whoami solo el nombre. id da números y grupos (sudo, etc.).",
          howToEs: "Dos letras: id",
        },
        {
          id: "d4",
          promptEs: "Permission denied vs No such file: ¿cuál significa 'el archivo existe pero no puedes leerlo'?",
          promptEn: "Which error means the file exists but you cannot read it?",
          answer: "permission denied",
          answerKeywords: ["denied"],
          subtopicId: "linux-basic",
          explanation: "No such file = ruta mala o no existe. Denied = el kernel te bloquea (rwx / uid).",
          howToEs: "Escribe permission denied (o denegado).",
        },
        {
          id: "d5",
          promptEs: "Guarda la salida de whoami en ~/out.txt (sobrescribir).",
          promptEn: "Save whoami stdout to ~/out.txt (overwrite).",
          answer: "whoami > ~/out.txt",
          subtopicId: "linux-basic",
          explanation: ">> añade. | es pipe a otro comando. > escribe el fichero.",
          howToEs: "whoami, espacio, mayor que, ruta. Exacto: whoami > ~/out.txt",
        },
      ],
      glossary: [
        { en: "working directory", es: "directorio actual (pwd)" },
        { en: "uid 0 / root", es: "superusuario" },
        { en: "permission denied", es: "el kernel niega r/w/x" },
        { en: "pipe", es: "conectar stdout de A a stdin de B" },
        { en: "redirection", es: "enviar stdout a un archivo (>, >>)" },
      ],
      comparisonTable: {
        caption: "Errores de shell (diagnóstico rápido)",
        headers: ["Mensaje", "Significa", "Qué haces"],
        rows: [
          ["No such file or directory", "Ruta mal o no existe", "pwd ; ls el padre"],
          ["Permission denied", "Existe, tu uid no tiene permiso", "ls -l ; id. No es nmap."],
          ["command not found", "El binario no está en PATH", "which comando ; apt si es TU Kali"],
        ],
      },
      closingChecklist: [
        "pwd y ls -la sin dudar",
        "Sé qué hay en /etc/passwd vs /etc/shadow",
        "id muestra mi uid",
        "Distingo Permission denied de No such file",
        "whoami > archivo funciona (evidencia en disco)",
        "Recall de este bloque acertados",
      ],
    },
    {
      id: "m0-w0-b7",
      weekId: "m0-w0",
      order: 7,
      title: "Linux mínimo 2 — procesos y SSH al guest",
      titleEn: "Minimum Linux 2 — processes and SSH to the guest",
      objective: "ssh msfadmin@TARGET_MS2, whoami/id dentro del guest, exit a Kali. Distinguir refused vs denied vs timeout.",
      objectiveEn: "SSH into TARGET_MS2 as msfadmin, id inside the guest, exit back to Kali. Tell refused/denied/timeout apart.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "22/tcp abierto no es acceso. SSH es una puerta con credenciales. Practicas contra TU Metasploitable (msfadmin/msfadmin) en Host-Only. Aprendes a leer el prompt: ¿estoy en Kali o en la víctima? nmap se corre en Kali, no 'desde dentro' salvo pivoting.",
      theoryEn:
        "SSH to your own MS2 guest only. Connection refused vs permission denied vs timeout are different faults. Always know which host the prompt is on.",
      examPhrases: [
        "SSH service on tcp/22",
        "connection refused",
        "authentication failed / permission denied",
        "remote login",
      ],
      practiceSteps: [
        "En Kali: hostname ; cat /etc/os-release | head -1 — esto es el HOST.",
        "source ~/ejpt-lab.txt si lo usas, o lee TARGET_MS2. ping -c 1 <IP>",
        "ssh msfadmin@<TARGET_MS2>  — password msfadmin. Primera vez: yes al fingerprint.",
        "Dentro del guest: hostname ; whoami ; id ; exit",
        "De nuevo en Kali: hostname debe volver a ser tu Kali. ip -br a | grep vboxnet",
        "Si falla: Connection refused vs Permission denied vs timeout — usa Si algo falla, no adivines.",
      ],
      workshop: LINUX_SHELL_WORKSHOP,
      troubleshooting: LINUX_TROUBLESHOOTING.filter((t) =>
        ["ssh-refused", "ssh-denied", "which-host"].includes(t.id)
      ),
      subtopics: ["linux-basic", "ftp-ssh-enum"],
      drills: [
        {
          id: "d1",
          promptEs: "SSH como msfadmin a 192.168.56.101",
          promptEn: "SSH as msfadmin to 192.168.56.101",
          answer: "ssh msfadmin@192.168.56.101",
          subtopicId: "linux-basic",
          explanation: "El usuario va ANTES de @. No es ssh 192.168.56.101 msfadmin ni root@.",
          howToEs: "ssh usuario@IP exacto.",
        },
        {
          id: "d2",
          promptEs: "Connection refused en SSH: ¿qué significa?",
          promptEn: "SSH connection refused means?",
          answer: "nada escucha en el puerto 22",
          answerKeywords: ["22"],
          subtopicId: "linux-basic",
          explanation: "Refused = la IP responde pero no hay sshd (o no es el 22). Denied = hay SSH, credenciales mal. Timeout = red.",
          howToEs: "Habla del puerto 22 / sshd caído. No confundas con password mal.",
        },
        {
          id: "d3",
          promptEs: "¿Dónde debes correr nmap en este lab (hoy)?",
          promptEn: "Where do you run nmap in this lab (today)?",
          answer: "en kali host",
          answerKeywords: ["kali"],
          subtopicId: "linux-basic",
          explanation: "No desde dentro de MS2. El atacante es el teclado de Kali. Pivoting es Semana 7.",
          howToEs: "Debe aparecer Kali (host / atacante).",
        },
      ],
      glossary: [
        { en: "sshd", es: "daemon SSH que escucha en 22" },
        { en: "connection refused", es: "nada acepta el TCP en ese puerto" },
        { en: "permission denied (ssh)", es: "auth fallida (user/pass)" },
        { en: "hostname", es: "nombre de esa máquina; sirve para no perderte" },
      ],
      closingChecklist: [
        "ssh msfadmin@MS2 abre shell",
        "whoami dentro del guest es msfadmin",
        "exit me devuelve a Kali (hostname / vboxnet0)",
        "Sé refused vs denied vs timeout",
        "Recall acertados",
        "Siguiente: redes mínimas (IPv4/CIDR/puertos), luego Nmap",
      ],
      resources: [{ label: "man ssh (Kali)", url: "https://manpages.debian.org/ssh", platform: "Docs" }],
    },
    {
      id: "m0-w0-b8",
      weekId: "m0-w0",
      order: 8,
      title: "Redes mínimas 1 — IPv4, CIDR, rutas",
      titleEn: "Minimum networking 1 — IPv4, CIDR, routes",
      objective: "Interpretar vboxnet0 /24: red vs host, LHOST vs RHOSTS, default route ≠ lab. No escanear la LAN de casa.",
      objectiveEn: "Read vboxnet0 /24: network vs host, LHOST vs RHOSTS, default route is not the lab. Do not scan your home LAN.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "IPv4 y /24 no son adorno: son por qué 192.168.56.1 y .101 se ven y 192.168.1.50 no es tu víctima. La ruta default de wlan0 es Internet del host. El lab es 192.168.56.0/24 dev vboxnet0. 127.0.0.1 es DVWA, no MS2.",
      theoryEn:
        "Same /24 = same lab subnet. LHOST is vboxnet0. Do not use wlan0 or 127.0.0.1 as RHOSTS for the VM.",
      examPhrases: ["IPv4 address", "subnet mask / CIDR", "private IP address", "default gateway", "routing table"],
      practiceSteps: [
        "ip addr show vboxnet0 — escribe RED (ej. 192.168.56.0/24), LHOST (inet) y máscara /24.",
        "ip route — marca default (Internet host) vs 192.168.56.0/24 dev vboxnet0 (lab).",
        "cat ~/ejpt-lab.txt — LHOST y TARGET_MS2 mismo prefijo, IPs distintas. Ninguna es 127.0.0.1.",
        "Di en voz alta: por qué no nmap -sn 192.168.1.0/24 'por si acaso'. Luego recall.",
      ],
      workshop: NET_IP_WORKSHOP,
      troubleshooting: NET_TROUBLESHOOTING.filter((t) => ["wrong-slash", "lhost-wlan", "localhost-rhost"].includes(t.id)),
      subtopics: ["net-basic", "lab-vbox"],
      drills: [
        {
          id: "d1",
          promptEs: "¿Qué significa /24 en 192.168.56.0/24?",
          promptEn: "What does /24 mean in 192.168.56.0/24?",
          answer: "los primeros 24 bits son la red",
          answerKeywords: ["24"],
          subtopicId: "net-basic",
          explanation: "No es '24 hosts'. /24 = 24 bits de red (máscara 255.255.255.0). El último octeto distingue hosts.",
          howToEs: "Habla de bits de red o máscara. Debe aparecer 24.",
        },
        {
          id: "d2",
          promptEs: "192.168.56.1 y 192.168.56.101: ¿misma subnet /24?",
          promptEn: "Are 192.168.56.1 and 192.168.56.101 in the same /24?",
          answer: "si misma red 192.168.56.0/24",
          answerKeywords: ["misma"],
          subtopicId: "net-basic",
          explanation: "Mismo prefijo 192.168.56 y /24. 192.168.1.50 no.",
          howToEs: "Sí. Menciona que sí / misma red. (sí se normaliza a si)",
        },
        {
          id: "d3",
          promptEs: "¿Por qué 127.0.0.1 no es RHOSTS de Metasploitable?",
          promptEn: "Why is 127.0.0.1 not Metasploitable's RHOSTS?",
          answer: "localhost es kali / dvwa no la vm",
          answerKeywords: ["local"],
          subtopicId: "net-basic",
          explanation: "127.0.0.1 es este host (Kali). MS2 tiene IP en vboxnet0. DVWA sí es localhost:4280.",
          howToEs: "Palabra local / kali / no es la VM.",
        },
        {
          id: "d4",
          promptEs: "¿Qué interfaz debe usar LHOST en este lab?",
          promptEn: "Which interface should LHOST use in this lab?",
          answer: "vboxnet0",
          answerKeywords: ["vboxnet"],
          subtopicId: "net-basic",
          explanation: "wlan0 es Internet del host. La víctima Host-Only no enruta hacia tu WiFi. vboxnet0 sí.",
          howToEs: "vboxnet0.",
        },
      ],
      glossary: [
        { en: "CIDR", es: "prefijo /n (bits de red)" },
        { en: "private address", es: "RFC1918, no enrutable en Internet" },
        { en: "default route", es: "ruta 0.0.0.0 — Internet del host" },
        { en: "localhost / 127.0.0.1", es: "esta máquina, no el guest" },
      ],
      comparisonTable: {
        caption: "IPs en TU PC (no las mezcles)",
        headers: ["Dirección", "Dónde", "Rol"],
        rows: [
          ["inet vboxnet0", "Host-Only", "LHOST"],
          ["TARGET_MS2", "Guest", "RHOSTS"],
          ["127.0.0.1:4280", "Docker en Kali", "DVWA"],
          ["IP de wlan0", "WiFi real", "Internet del host, no LHOST de reverse shell al guest"],
        ],
      },
      closingChecklist: [
        "Sé qué es /24 en mi lab",
        "LHOST y RHOSTS mismo prefijo, distintas",
        "No usaría 192.168.1.0/24 ni 127.0.0.1 como MS2",
        "ip route: distingo default vs red de lab",
        "Recall acertados",
      ],
    },
    {
      id: "m0-w0-b9",
      weekId: "m0-w0",
      order: 9,
      title: "Redes mínimas 2 — TCP/UDP y puertos de servicio",
      titleEn: "Minimum networking 2 — TCP/UDP and service ports",
      objective: "Asociar 21/22/80/139/445/443 a un protocolo y a una herramienta (no mezclar Gobuster con SMB).",
      objectiveEn: "Map 21/22/80/139/445/443 to a protocol and a next tool. Do not mix Gobuster with SMB.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "IP llega a la máquina; el puerto llega al servicio. TCP vs UDP. Ping ICMP no prueba el 80. 445 → SMB/enum4linux. 80 → HTTP/Gobuster. 22 → SSH/Hydra si hay usuario. HTTPS 443 es HTTP cifrado, no 'otra cosa mágica'. ARP/MITM no es para hoy.",
      theoryEn:
        "Layer 3 vs layer 4. Port numbers pick the next technique. ICMP ping is not TCP/80.",
      examPhrases: [
        "TCP port",
        "UDP port",
        "open / closed / filtered",
        "SMB 445/tcp",
        "HTTP 80/tcp  HTTPS 443/tcp",
      ],
      practiceSteps: [
        "Escribe en papel (o ~/ejpt-lab.txt) la tabla: 21 FTP, 22 SSH, 80 HTTP, 139/445 SMB, 443 HTTPS, 53 DNS.",
        "Al lado de cada uno: ¿Gobuster, Hydra, enum4linux, o ssh? Una herramienta, no tres.",
        "Ping a MS2 (si está up). Recuerda: eso no demuestra que 80 esté open.",
        "Opcional si ya viste nmap: nmap -p22,80,445 <TARGET_MS2> — solo para VER puertos; el taller de flags es Semana 1.",
        "Recall: no mires la tabla.",
      ],
      workshop: NET_PORTS_WORKSHOP,
      troubleshooting: NET_TROUBLESHOOTING.filter((t) => ["ping-not-http"].includes(t.id)),
      subtopics: ["net-basic", "tool-selection"],
      drills: [
        {
          id: "d1",
          promptEs: "Puerto TCP típico de SSH",
          promptEn: "Typical TCP port for SSH",
          answer: "22",
          subtopicId: "net-basic",
          explanation: "22/tcp. 21 es FTP. 445 es SMB.",
          howToEs: "22",
        },
        {
          id: "d2",
          promptEs: "445/tcp abierto: ¿qué enumeras primero (protocolo/familia)?",
          promptEn: "445/tcp open: what do you enumerate first?",
          answer: "SMB",
          answerKeywords: ["smb"],
          subtopicId: "net-basic",
          explanation: "445 es SMB (microsoft-ds). No Gobuster. enum4linux/smbclient más adelante.",
          howToEs: "SMB (o samba / 445).",
        },
        {
          id: "d3",
          promptEs: "80/tcp: ¿Gobuster o Hydra por defecto?",
          promptEn: "80/tcp: Gobuster or Hydra by default?",
          answer: "gobuster",
          answerKeywords: ["gobuster"],
          subtopicId: "net-basic",
          explanation: "HTTP → rutas. Hydra es login (form/ssh). Un 80 no es 'tirar hydra ya'.",
          howToEs: "gobuster (directorios). Hydra solo si hay formulario de login.",
        },
        {
          id: "d4",
          promptEs: "Ping OK y el navegador no carga: ¿contradice que el host esté vivo?",
          promptEn: "Ping works but the browser fails: is the host down?",
          answer: "no el host puede estar vivo sin http",
          answerKeywords: ["no"],
          subtopicId: "net-basic",
          explanation: "ICMP ≠ TCP/80. Host up, servicio web down o filtered.",
          howToEs: "No. Menciona que ping no es HTTP.",
        },
        {
          id: "d5",
          promptEs: "TCP o UDP: ¿cuál usa el handshake SYN (y nmap -sS)?",
          promptEn: "TCP or UDP: which uses the SYN handshake (and nmap -sS)?",
          answer: "TCP",
          answerKeywords: ["tcp"],
          subtopicId: "net-basic",
          explanation: "TCP conecta (SYN). UDP no. -sS es SYN scan sobre TCP.",
          howToEs: "TCP",
        },
      ],
      glossary: [
        { en: "port", es: "número 1–65535 en un host" },
        { en: "TCP handshake", es: "SYN, SYN-ACK, ACK" },
        { en: "filtered", es: "no hay respuesta clara (firewall/drop)" },
        { en: "ICMP echo", es: "ping — no es un puerto de servicio" },
      ],
      comparisonTable: {
        caption: "Puerto → siguiente movimiento (eJPT, no OSCP)",
        headers: ["Puerto", "Servicio", "Siguiente (idea)"],
        rows: [
          ["22", "SSH", "banner / login / Hydra si hay user"],
          ["21", "FTP", "anonymous / nmap ftp-anon"],
          ["80", "HTTP", "curl / Gobuster"],
          ["443", "HTTPS", "igual que HTTP, cifrado en tránsito"],
          ["139/445", "SMB", "enum4linux / smbclient"],
          ["53", "DNS", "recon de nombres, no SMB"],
        ],
      },
      closingChecklist: [
        "22/80/445 no me los invento",
        "445 → SMB, no Gobuster",
        "80 → web, no enum4linux",
        "Ping ≠ puerto 80 open",
        "Recall acertados",
      ],
    },
  ],
};
