import { StudyWeek } from "@/lib/types";

/** MES 2 / SEMANA 8 (global 8) — Privesc Linux/Windows + SIMULACRO #2 + Cierre de Mes 2 */
export const month2Week8: StudyWeek = {
  id: "m2-w8",
  monthId: "m2",
  title: "Semana 8 — Escalada de Privilegios + Simulacro #2 + Cierre Mes 2",
  goal: "Dominar privesc Linux/Windows automatizada y manual, tomar el Simulacro #2, y hacer el diagnóstico honesto de ritmo a mitad de plan.",
  detailed: true,
  blocks: [
    {
      id: "m2-w8-b1",
      weekId: "m2-w8",
      order: 1,
      title: "Privesc Linux: LinPEAS, sudo -l, SUID",
      objective: "Encontrar y explotar un vector de escalada de privilegios en Linux usando LinPEAS y verificación manual (sudo -l, SUID).",
      durationMin: 50,
      type: "practice",
      theoryEs: "LinPEAS automatiza la búsqueda de vectores de privesc (colorea hallazgos por probabilidad). Pero el examen espera que también sepas los checks manuales clave: sudo -l (qué puedes correr como root sin password) y binarios SUID (find / -perm -4000).",
      practiceSteps: [
        "Sube y ejecuta LinPEAS: curl -L <URL_linpeas> -o linpeas.sh && chmod +x linpeas.sh && ./linpeas.sh",
        "Revisa qué comandos puedes correr como root: sudo -l",
        "Busca binarios SUID: find / -perm -4000 -type f 2>/dev/null",
        "Si encuentras un binario SUID/sudo explotable, verifica en GTFOBins cómo abusarlo",
      ],
      subtopics: ["privesc-linux"],
      drills: [
        { id: "d1", promptEs: "Escribe el comando para ver qué puedes ejecutar con sudo sin contraseña.", answer: "sudo -l" },
        { id: "d2", promptEs: "Escribe el comando find para listar todos los binarios con bit SUID activo.", answer: "find / -perm -4000 -type f 2>/dev/null" },
      ],
      glossary: [
        { en: "SUID bit", es: "bit SUID (ejecuta con permisos del propietario)" },
        { en: "privilege escalation", es: "escalada de privilegios" },
      ],
      resources: [
        { label: "TryHackMe — Linux PrivEsc", url: "https://tryhackme.com/room/linuxprivesc", platform: "TryHackMe" },
        { label: "GTFOBins (referencia de binarios explotables)", url: "https://gtfobins.github.io/", platform: "Docs" },
      ],
      closingChecklist: ["Corrí LinPEAS e interpreté sus hallazgos", "Escalé a root en un lab usando sudo -l o un SUID"],
    },
    {
      id: "m2-w8-b2",
      weekId: "m2-w8",
      order: 2,
      title: "Privesc Windows: WinPEAS, servicios mal configurados",
      objective: "Encontrar y explotar un vector de escalada de privilegios en Windows usando WinPEAS y revisión de permisos de servicios.",
      durationMin: 50,
      type: "practice",
      theoryEs: "Igual que LinPEAS pero para Windows: WinPEAS busca servicios con permisos débiles, AlwaysInstallElevated, credenciales guardadas, etc. En meterpreter, getsystem intenta varios métodos automáticos de escalada conocidos.",
      practiceSteps: [
        "Sube y ejecuta WinPEAS (o transfiérelo vía meterpreter: upload winPEAS.exe)",
        "Ejecuta desde la sesión: ./winPEAS.exe",
        "Dentro de meterpreter, intenta escalada automática: getsystem",
        "Revisa servicios con permisos débiles manualmente: accesschk.exe -uwcqv \"Everyone\" *",
      ],
      subtopics: ["privesc-windows"],
      drills: [
        { id: "d1", promptEs: "Dentro de meterpreter, escribe el comando para intentar escalada de privilegios automática.", answer: "getsystem" },
      ],
      glossary: [
        { en: "service misconfiguration", es: "servicio mal configurado" },
        { en: "unquoted service path", es: "ruta de servicio sin comillas" },
      ],
      resources: [{ label: "TryHackMe — Windows PrivEsc", url: "https://tryhackme.com/room/windowsprivesc20", platform: "TryHackMe" }],
      closingChecklist: ["Corrí WinPEAS e interpreté sus hallazgos", "Usé getsystem o exploté un servicio mal configurado en un lab"],
    },
    {
      id: "m2-w8-b3",
      weekId: "m2-w8",
      order: 3,
      title: "Post-explotación: recolección de evidencia",
      objective: "Recolectar sistemáticamente evidencia post-explotación (hashes, archivos sensibles, credenciales) como lo pediría un reporte eJPT.",
      durationMin: 40,
      type: "practice",
      theoryEs: "Post-explotación no es solo 'tener shell', es documentar QUÉ obtuviste: hashes, archivos de config con credenciales, historial de comandos, llaves SSH.",
      practiceSteps: [
        "Busca archivos de configuración con credenciales: grep -ri password /etc/ /var/www/ 2>/dev/null",
        "Revisa historial de bash: cat ~/.bash_history",
        "Busca llaves SSH privadas: find / -name 'id_rsa*' 2>/dev/null",
        "En Windows, busca credenciales guardadas: cmdkey /list",
      ],
      subtopics: ["post-exploit-loot"],
      glossary: [{ en: "credential harvesting", es: "recolección de credenciales" }],
      closingChecklist: ["Encontré al menos 1 credencial adicional post-explotación en un lab"],
    },
    {
      id: "m2-w8-b4",
      weekId: "m2-w8",
      order: 4,
      title: "SIMULACRO COMPLETO #2 (cumulativo Mes 1 + Mes 2)",
      objective: "Responder 15 preguntas en 20 minutos cubriendo TODO lo visto hasta ahora (Meses 1-2), alcanzando 70%+.",
      durationMin: 30,
      type: "simulacro",
      subtopics: [],
      practiceSteps: ["Ve a Simulacros > Simulacro Completo #2 en la app", "20 minutos cronometrados, sin pausar"],
      closingChecklist: ["Tomé el Simulacro #2 en condiciones reales", "Revisé retroalimentación de cada pregunta fallada"],
    },
    {
      id: "m2-w8-b5",
      weekId: "m2-w8",
      order: 5,
      title: "Cierre de Mes 2: diagnóstico honesto de ritmo",
      objective: "Calcular horas invertidas vs. horas necesarias para el mes 3, y ajustar el plan si el ritmo real no alcanza el plazo de 3 meses.",
      durationMin: 30,
      type: "checkpoint",
      theoryEs:
        "A mitad del plan es el punto de control OBLIGATORIO de honestidad (regla fija #8). La app compara tus horas reales registradas contra las horas necesarias para llegar al examen a tiempo. Si hay déficit, te lo dice en número exacto, no en frases motivacionales vacías.",
      practiceSteps: [
        "Ve a la sección Progreso en la app",
        "Revisa el cálculo: horas planeadas vs. horas reales del Mes 1 + Mes 2",
        "Si hay déficit, decide con el asistente si comprimes contenido, agregas horas en próximos días libres del régimen 20x10, o corres el riesgo (no recomendado)",
      ],
      subtopics: [],
      closingChecklist: [
        "Registré mis horas reales de Mes 1 y Mes 2 completas",
        "Leí el diagnóstico honesto de ritmo y tomé una decisión explícita (no lo ignoré)",
      ],
    },
  ],
};
