import { StudyWeek } from "@/lib/types";
import {
  ENUM_FTP_SSH_WORKSHOP,
  ENUM_SMB_MANUAL_WORKSHOP,
  ENUM_SMB_WORKSHOP,
  ENUM_TROUBLESHOOTING,
  TOOL_SELECTION_WORKSHOP,
} from "@/content/workshops/service-enum";
import { GOBUSTER_TROUBLESHOOTING, GOBUSTER_WORKSHOP } from "@/content/workshops/gobuster-fundamentals";
import { HYDRA_TROUBLESHOOTING, HYDRA_WORKSHOP } from "@/content/workshops/hydra-fundamentals";

/**
 * MES 1 / SEMANA 2 — Enumeración por servicio (SMB, FTP, SSH, web) + hueco Gobuster/Hydra/enum4linux.
 * Semana global: 2. Nmap ya está en Semana 1: aquí no se reexplica -sn/-p-.
 */
export const month1Week2: StudyWeek = {
  id: "m1-w2",
  monthId: "m1",
  title: "Semana 2 — Enumeración: SMB, Web, Fuerza bruta",
  goal: "Cerrar el hueco de confusión Gobuster/Hydra/enum4linux: saber EXACTAMENTE cuándo usar cada herramienta, no solo cómo se usa.",
  detailed: true,
  blocks: [
    {
      id: "m1-w2-b1",
      weekId: "m1-w2",
      order: 1,
      title: "Enumeración SMB con enum4linux",
      titleEn: "SMB enumeration with enum4linux",
      objective: "Contra TARGET_MS2 (445): enum4linux -a, anotar workgroup, users, shares. No Gobuster ni Hydra.",
      objectiveEn: "Against TARGET_MS2 port 445: enum4linux -a. Write workgroup, users, shares. Not Gobuster or Hydra.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "SMB 445/139 revela usuarios, shares y a veces política de passwords. enum4linux automatiza eso. -a = todo. No es un exploit. Nmap ya te dijo que 445 está open; hoy extraes el CONTENIDO.",
      theoryEn:
        "445/tcp → enum4linux, not Gobuster. -a full enum. Target = Metasploitable 2 on Host-Only, not your home LAN.",
      examPhrases: ["SMB enumeration", "null session", "shares", "user list"],
      practiceSteps: [
        "SOURCE=$(grep TARGET_MS2 ~/ejpt-lab.txt | cut -d= -f2). Confirma 445: nmap -p139,445 $SOURCE (un check, no rehacer Semana 1).",
        "enum4linux -a $SOURCE | tee ~/ms2_enum4.txt",
        "Extrae a ~/ejpt-lab.txt: workgroup, 2 usuarios, 2 shares. No dejes solo el tee.",
        "enum4linux -U $SOURCE  y  enum4linux -S $SOURCE  — para ver qué cambia vs -a.",
        "Di en voz alta: por qué esto no es Gobuster. Recall.",
      ],
      workshop: ENUM_SMB_WORKSHOP,
      troubleshooting: ENUM_TROUBLESHOOTING.filter((t) => ["smb-on-http", "enum4-fail"].includes(t.id)),
      subtopics: ["enum4linux"],
      drills: [
        {
          id: "d1",
          promptEs: "Enumeración COMPLETA de SMB contra 10.10.10.50 con enum4linux.",
          promptEn: "Full SMB enumeration against 10.10.10.50 with enum4linux.",
          answer: "enum4linux -a 10.10.10.50",
          subtopicId: "enum4linux",
          explanation: "Información SMB, no rutas HTTP ni passwords. Flag de 'all'.",
          howToEs: "enum4linux -a y la IP.",
          conceptQuestion: "¿Gobuster lista usuarios SMB?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "SOLO usuarios vía enum4linux contra 10.10.10.50.",
          promptEn: "Users only via enum4linux against 10.10.10.50.",
          answer: "enum4linux -U 10.10.10.50",
          subtopicId: "enum4linux",
          explanation: "-U users. -S shares. -P política. -a es el combo.",
          howToEs: "-U y la IP.",
        },
        {
          id: "d3",
          promptEs: "SOLO shares vía enum4linux contra 10.10.10.50.",
          promptEn: "Shares only via enum4linux against 10.10.10.50.",
          answer: "enum4linux -S 10.10.10.50",
          subtopicId: "enum4linux",
          explanation: "Shares = carpetas. Entrar es smbclient, otro bloque.",
          howToEs: "-S y la IP.",
        },
      ],
      comparisonTable: {
        caption: "445 open → qué herramienta",
        headers: ["Buscas", "Herramienta", "No uses"],
        rows: [
          ["users / workgroup / policy", "enum4linux", "Gobuster"],
          ["entrar al share / get archivo", "smbclient (siguiente bloque)", "Hydra de primeras"],
          ["READ vs WRITE de un vistazo", "smbmap", "nmap otra vez"],
        ],
      },
      glossary: [
        { en: "share", es: "recurso compartido" },
        { en: "null session", es: "sesión nula (sin autenticación)" },
        { en: "password policy", es: "política de contraseñas" },
        { en: "workgroup", es: "grupo de trabajo" },
      ],
      resources: [
        { label: "Target local — Metasploitable 2 (puerto 445)", url: "https://sourceforge.net/projects/metasploitable/files/Metasploitable2/", platform: "Local" },
        { label: "TryHackMe — Kenobi (opcional)", url: "https://tryhackme.com/room/kenobi", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "Escribo enum4linux -a de memoria",
        "Sé qué información trae -U, -S y -P sin adivinar",
        "Identifiqué al menos un share con acceso anónimo en el lab",
      ],
    },
    {
      id: "m1-w2-b2",
      weekId: "m1-w2",
      order: 2,
      title: "Enumeración manual SMB (smbclient / smbmap)",
      titleEn: "Manual SMB (smbclient / smbmap)",
      objective: "Listar shares (-L -N), entrar a uno, get un archivo, leer smbmap READ/WRITE. Target = MS2.",
      objectiveEn: "smbclient -L -N, connect to a share, get a file, read smbmap permissions on TARGET_MS2.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "enum4linux no te deja 'dentro'. smbclient es el cliente (ls/get). smbmap resume permisos. -N = null session.",
      theoryEn:
        "smbclient is FTP-like for shares. -N = no password. smbmap -H shows READ/WRITE. Still not Gobuster.",
      examPhrases: ["null session", "smbclient", "list shares", "anonymous share"],
      practiceSteps: [
        "SOURCE=$(grep TARGET_MS2 ~/ejpt-lab.txt | cut -d= -f2)",
        "smbclient -L $SOURCE -N",
        "Elige un Sharename de la lista. smbclient //$SOURCE/<share> -N   — ls, get un archivo, exit.",
        "smbmap -H $SOURCE  — marca un READ y un WRITE si existen.",
        "Recuerda: prompt smb:\\\\> no es Kali. exit. Recall.",
      ],
      workshop: ENUM_SMB_MANUAL_WORKSHOP,
      troubleshooting: ENUM_TROUBLESHOOTING.filter((t) => ["smbclient-share"].includes(t.id)),
      subtopics: ["smb-manual"],
      drills: [
        {
          id: "d1",
          promptEs: "Lista shares de 10.10.10.50 SIN credenciales (sesión nula).",
          promptEn: "List shares on 10.10.10.50 with a null session.",
          answer: "smbclient -L 10.10.10.50 -N",
          subtopicId: "smb-manual",
          explanation: "-L lista. -N no pide password. No es enum4linux -S (otro formato).",
          howToEs: "smbclient -L IP -N",
          conceptQuestion: "¿-N pide password?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "Conéctate al share 'anonymous' de 10.10.10.50 sin credenciales.",
          promptEn: "Connect to share 'anonymous' on 10.10.10.50 with no credentials.",
          answer: "smbclient //10.10.10.50/anonymous -N",
          subtopicId: "smb-manual",
          explanation: "UNC //IP/share. El nombre es el share, no el puerto 445.",
          howToEs: "smbclient //IP/anonymous -N",
        },
        {
          id: "d3",
          promptEs: "smbmap: permisos de todos los shares de 10.10.10.50.",
          promptEn: "smbmap: permissions of all shares on 10.10.10.50.",
          answer: "smbmap -H 10.10.10.50",
          subtopicId: "smb-manual",
          explanation: "-H es el host. Buscas READ/WRITE, no rutas HTTP.",
          howToEs: "smbmap -H y la IP.",
        },
      ],
      glossary: [
        { en: "null authentication", es: "autenticación nula" },
        { en: "read/write permissions", es: "permisos de lectura/escritura" },
      ],
      resources: [
        { label: "TryHackMe — Kenobi", url: "https://tryhackme.com/room/kenobi", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "Me conecté a un share y descargué un archivo con smbclient",
        "Interpreté correctamente la salida de smbmap (qué share es READ/WRITE)",
      ],
    },
    {
      id: "m1-w2-b3",
      weekId: "m1-w2",
      order: 3,
      title: "Enumeración web con Gobuster",
      titleEn: "Web enumeration with Gobuster",
      objective: "dir -u -w contra http://TARGET_MS2 (o DVWA local). Anotar 200/301/403. No es Hydra ni SMB.",
      objectiveEn: "dir -u -w against http://TARGET_MS2 (or local DVWA). Note 200/301/403. Not Hydra or SMB.",
      durationMin: 50,
      type: "practice",
      theoryEs:
        "Gobuster brutea RUTAS HTTP, no passwords. -u URL, -w wordlist, -x extensiones. 403 también cuenta. Solo tu lab (MS2 Host-Only o DVWA :4280).",
      theoryEn:
        "Gobuster is path brute-force on HTTP(S), not credentials. Target your MS2 or DVWA only.",
      examPhrases: ["directory brute-force", "wordlist", "HTTP 403", "hidden directory"],
      practiceSteps: [
        "curl -I http://$(grep TARGET_MS2 ~/ejpt-lab.txt | cut -d= -f2)/  — si no hay HTTP, no Gobuster. DVWA: curl -I http://127.0.0.1:4280/",
        "ls /usr/share/wordlists/dirb/common.txt",
        "gobuster dir -u http://<TARGET_MS2> -w /usr/share/wordlists/dirb/common.txt",
        "Repite con -x php,txt  (archivos, no solo carpetas).",
        "Anota 3 Status (200/301/403) en ~/ejpt-lab.txt. curl una ruta. No Hydra todavía.",
        "dns -d lab.local es drill de sintaxis, no un dominio público. Recall.",
      ],
      workshop: GOBUSTER_WORKSHOP,
      troubleshooting: GOBUSTER_TROUBLESHOOTING,
      subtopics: ["gobuster-dir"],
      drills: [
        {
          id: "d1",
          promptEs: "Gobuster modo dir: directorios en http://10.10.10.60 wordlist dirb/common.txt",
          promptEn: "Gobuster dir mode: directories on http://10.10.10.60 with dirb/common.txt",
          answer: "gobuster dir -u http://10.10.10.60 -w /usr/share/wordlists/dirb/common.txt",
          subtopicId: "gobuster-dir",
          explanation: "Modo dir, -u URL con http, -w wordlist. No es Hydra. No es 445.",
          howToEs: "gobuster dir -u http://… -w …/common.txt",
          conceptQuestion: "¿Gobuster prueba passwords SSH?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "El mismo, más archivos .php y .html",
          promptEn: "Same command, also .php and .html files",
          answer: "gobuster dir -u http://10.10.10.60 -w /usr/share/wordlists/dirb/common.txt -x php,html",
          subtopicId: "gobuster-dir",
          explanation: "-x añade extensiones. Sin -x solo 'carpetas' del diccionario.",
          howToEs: "Añade -x php,html al comando dir.",
        },
        {
          id: "d3",
          promptEs: "Modo dns: subdominios de lab.local (sintaxis; no lo lances a internet).",
          promptEn: "dns mode: subdomains of lab.local (syntax; do not run against the public Internet).",
          answer: "gobuster dns -d lab.local -w /usr/share/wordlists/dirb/common.txt",
          subtopicId: "gobuster-dir",
          explanation: "dns -d dominio, no -u. Distinto de dir. No es enum4linux.",
          howToEs: "gobuster dns -d lab.local -w la misma wordlist.",
        },
      ],
      comparisonTable: {
        caption: "Gobuster: qué buscar vs qué no",
        headers: ["Ves", "Herramienta", "Siguiente"],
        rows: [
          ["80/443 open", "gobuster dir", "curl la ruta"],
          ["Status 403", "sigue siendo hallazgo", "no lo tires"],
          ["Formulario /login", "Hydra (después)", "ya no más dirs a ciegas"],
          ["445 open", "enum4linux", "nunca gobuster"],
        ],
      },
      glossary: [
        { en: "directory brute-forcing", es: "fuerza bruta de directorios" },
        { en: "wordlist", es: "lista de palabras" },
        { en: "HTTP status code", es: "código de estado HTTP" },
      ],
      resources: [
        { label: "TryHackMe — Vulnversity (incluye Gobuster + reverse shell)", url: "https://tryhackme.com/room/vulnversity", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "Escribo gobuster dir -u -w de memoria",
        "Sé -x para archivos y que 403 sigue siendo hallazgo",
        "No usé Gobuster contra 445 ni Hydra antes de tener una ruta de login",
      ],
    },
    {
      id: "m1-w2-b4",
      weekId: "m1-w2",
      order: 4,
      title: "Fuerza bruta de credenciales con Hydra",
      titleEn: "Credential brute-force with Hydra",
      objective: "Sintaxis -l/-L -P servicio://IP. Lab: user conocido + lista ≤20 + -t 4. No rockyou entero. No Gobuster.",
      objectiveEn: "Syntax -l/-L -P service://IP. Lab: known user, ≤20-line list, -t 4. Not full rockyou. Not Gobuster.",
      durationMin: 50,
      type: "practice",
      theoryEs:
        "Hydra = passwords de un LOGIN. Necesitas usuario. Hoy lista corta en TU MS2. El drill puede pedir rockyou: eso es el examen, no el hábito del lab.",
      theoryEn:
        "Hydra = credentials against a login. Need a username. Short list on YOUR MS2. Exam syntax may show rockyou.txt.",
      examPhrases: ["brute force", "username list", "password list", "ssh://"],
      practiceSteps: [
        "Confirma USER: msfadmin (Linux mínimo) o uno de enum4linux -U. Sin user → STOP, no Hydra.",
        "head -20 /usr/share/wordlists/rockyou.txt > ~/short-pass.txt   (si solo hay .gz: gzip -dc /usr/share/wordlists/rockyou.txt.gz | head -20 > ~/short-pass.txt). wc -l ~/short-pass.txt",
        "hydra -l msfadmin -P ~/short-pass.txt -t 4 ssh://<TARGET_MS2>",
        "Si hay hit: anótalo. ssh user@IP. No hace falta 'descubrir' msfadmin/msfadmin otra vez.",
        "Opcional FTP: solo si anonymous falló y tienes user. hydra -l USER -P ~/short-pass.txt -t 4 ftp://<TARGET_MS2>",
        "Recall de sintaxis (los drills usan rockyou como en examen). No relances millones de líneas.",
      ],
      workshop: HYDRA_WORKSHOP,
      troubleshooting: HYDRA_TROUBLESHOOTING,
      subtopics: ["hydra-bruteforce"],
      drills: [
        {
          id: "d1",
          promptEs: "Hydra: usuario admin, rockyou, SSH 10.10.10.70 (sintaxis de examen).",
          promptEn: "Hydra: user admin, rockyou, SSH 10.10.10.70 (exam syntax).",
          answer: "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://10.10.10.70",
          subtopicId: "hydra-bruteforce",
          explanation: "-l un user, -P lista, ssh://IP. En TU lab cambia rockyou por ~/short-pass.txt.",
          howToEs: "-l admin -P rockyou ssh://IP",
          conceptQuestion: "¿Gobuster sirve para este login SSH?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "Hydra: lista users.txt y passwords.txt, FTP 10.10.10.70.",
          promptEn: "Hydra: users.txt and passwords.txt, FTP 10.10.10.70.",
          answer: "hydra -L users.txt -P passwords.txt ftp://10.10.10.70",
          subtopicId: "hydra-bruteforce",
          explanation: "-L y -P son LISTAS. ftp:// no es ssh://. Anonymous primero en el bloque FTP.",
          howToEs: "-L users.txt -P passwords.txt ftp://IP",
        },
        {
          id: "d3",
          promptEs: "El de FTP anterior, máximo 4 threads.",
          promptEn: "Previous FTP command, max 4 threads.",
          answer: "hydra -L users.txt -P passwords.txt -t 4 ftp://10.10.10.70",
          subtopicId: "hydra-bruteforce",
          explanation: "-t limita hilos. El guest se cae con demasiados.",
          howToEs: "Añade -t 4.",
        },
      ],
      comparisonTable: {
        caption: "Hydra hoy",
        headers: ["Situación", "Haz", "No"],
        rows: [
          ["User conocido + SSH/FTP", "-l user -P corta -t 4", "rockyou entero"],
          ["22 open, cero users", "nmap -sV / SMB -U", "hydra -l root -P rockyou"],
          ["80 open, buscas /admin", "Gobuster", "Hydra"],
          ["21 anonymous OK", "ftp anonymous", "Hydra primero"],
        ],
      },
      glossary: [
        { en: "brute-force attack", es: "ataque de fuerza bruta" },
        { en: "credential stuffing", es: "relleno de credenciales" },
        { en: "wordlist", es: "lista de palabras" },
        { en: "threads", es: "hilos (procesos en paralelo)" },
      ],
      resources: [
        { label: "TryHackMe — Hydra", url: "https://tryhackme.com/room/hydra", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "Distingo -l/-p (singular) de -L/-P (lista) sin dudar",
        "Escribo ssh:// y ftp:// de memoria",
        "Lab: user conocido + lista ≤20 + -t 4; no rockyou entero ni Hydra sin -l",
      ],
    },
    {
      id: "m1-w2-b5",
      weekId: "m1-w2",
      order: 5,
      title: "PUNTO CRÍTICO: cuándo usar Gobuster vs Hydra vs enum4linux",
      titleEn: "Tool selection: Gobuster vs Hydra vs enum4linux",
      objective: "Dado un puerto o un párrafo, una herramienta en <10 s. Incluye FTP/SSH: no todo es las tres.",
      objectiveEn: "Pick one tool from a port or paragraph in under 10 seconds. FTP/SSH are not Gobuster.",
      durationMin: 45,
      type: "drill",
      theoryEs:
        "Pregunta: ¿qué busco? Rutas HTTP → Gobuster. Password de un login → Hydra. Info SMB → enum4linux. FTP anonymous → ftp/ftp-anon. SSH con user conocido → ssh; sin user → enum otro servicio, no Hydra a ciegas.",
      theoryEn:
        "One question: what are you looking for? Paths vs credentials vs SMB info. FTP anonymous is not Gobuster. SSH open is not Hydra-first.",
      examPhrases: ["which tool", "SMB users", "directory brute force", "credential brute force"],
      workshop: TOOL_SELECTION_WORKSHOP,
      troubleshooting: ENUM_TROUBLESHOOTING.filter((t) =>
        ["smb-on-http", "ftp-hydra-first", "ssh-hydra-no-user"].includes(t.id)
      ),
      comparisonTable: {
        caption: "¿Qué estoy buscando?",
        headers: ["Herramienta", "¿Qué busca?", "¿Contra qué?", "SÍ", "NO"],
        rows: [
          ["Gobuster", "Rutas/archivos", "HTTP/HTTPS", "panel /admin", "usuarios SMB o SSH"],
          ["Hydra", "Password de un login", "SSH/FTP/HTTP-form con USER", "admin conocido en SSH", "21 anónimo primero; 445 info"],
          ["enum4linux", "users/shares/policy", "SMB 445/139", "quién existe en Samba", "directorio web o banner SSH"],
          ["ftp / ftp-anon", "¿anonymous?", "TCP/21", "login anonymous", "gobuster al 21"],
          ["ssh / nmap -sV -p22", "versión o sesión con user", "TCP/22", "msfadmin si ya lo tienes", "hydra sin -l"],
        ],
      },
      practiceSteps: [
        "Lee cada escenario. Responde SOLO la herramienta (una palabra o ftp-anon).",
        "Verifica contra la tabla. Incluye los de FTP/SSH.",
        "Repite sin tabla.",
      ],
      subtopics: ["tool-selection"],
      drills: [
        {
          id: "d1",
          promptEs: "Puerto 445 abierto. ¿Qué usuarios hay?",
          promptEn: "Port 445 open. Which users exist?",
          answer: "enum4linux",
          subtopicId: "tool-selection",
          explanation: "Info SMB, no web ni passwords todavía.",
          howToEs: "enum4linux",
        },
        {
          id: "d2",
          promptEs: "Puerto 80. Panel de login oculto en alguna ruta.",
          promptEn: "Port 80. Hidden login panel somewhere.",
          answer: "gobuster",
          subtopicId: "tool-selection",
          explanation: "Buscas RUTAS HTTP.",
          howToEs: "gobuster",
        },
        {
          id: "d3",
          promptEs: "SSH abierto y usuario 'root' confirmado, sin password.",
          promptEn: "SSH open, user root confirmed, no password.",
          answer: "hydra",
          subtopicId: "tool-selection",
          explanation: "Ya hay USER. Falta password = Hydra, no Gobuster.",
          howToEs: "hydra",
        },
        {
          id: "d4",
          promptEs: "Formulario de login HTTP y usuario conocido. ¿Passwords comunes?",
          promptEn: "HTTP login form, known user, common passwords?",
          answer: "hydra",
          subtopicId: "tool-selection",
          explanation: "Login = credenciales. Gobuster sería si no sabes la ruta del form.",
          howToEs: "hydra",
        },
        {
          id: "d5",
          promptEs: "¿Share SMB anónimo y política de passwords del dominio?",
          promptEn: "Anonymous SMB share and domain password policy?",
          answer: "enum4linux",
          subtopicId: "tool-selection",
          explanation: "SMB info. smbclient entra al share después.",
          howToEs: "enum4linux",
        },
        {
          id: "d6",
          promptEs: "Archivo backup.zip en la raíz de un sitio web.",
          promptEn: "backup.zip at the web root.",
          answer: "gobuster",
          subtopicId: "tool-selection",
          explanation: "Archivo en HTTP. -x zip si hace falta.",
          howToEs: "gobuster",
        },
        {
          id: "d7",
          promptEs: "Puerto 21. ¿Entra anonymous antes de Hydra?",
          promptEn: "Port 21. Check anonymous before Hydra?",
          answer: "ftp",
          answerKeywords: ["ftp"],
          subtopicId: "tool-selection",
          explanation: "Enum FTP (cliente o ftp-anon). Hydra es si anonymous falla y tienes users.",
          howToEs: "ftp o ftp-anon (debe aparecer ftp).",
        },
        {
          id: "d8",
          promptEs: "Puerto 22 open, sin usuarios. Comando para ver la versión SSH de 10.10.10.80 (no Hydra).",
          promptEn: "Port 22 open, no users. Command for SSH version on 10.10.10.80 (not Hydra).",
          answer: "nmap -sV -p22 10.10.10.80",
          subtopicId: "tool-selection",
          explanation: "Sin user no Hydra. Versión primero. Users pueden salir de SMB en otro paso.",
          howToEs: "nmap -sV -p22 y la IP.",
        },
      ],
      glossary: [
        { en: "attack surface", es: "superficie de ataque" },
        { en: "service enumeration", es: "enumeración de servicio" },
      ],
      closingChecklist: [
        "Respondí los 8 escenarios correctamente SIN ver la tabla",
        "Puedo explicar la 'pregunta clave' (¿qué estoy buscando?) en mis propias palabras",
        "FTP 21 ≠ Gobuster; SSH sin user ≠ Hydra primero",
      ],
    },
    {
      id: "m1-w2-b6",
      weekId: "m1-w2",
      order: 6,
      title: "Enumeración de FTP y SSH",
      titleEn: "FTP and SSH enumeration",
      objective: "En MS2: banner 21, anonymous, ftp-anon; versión SSH. searchsploit solo como índice. Hoy no explotas.",
      objectiveEn: "On MS2: FTP banner + anonymous + ftp-anon; SSH version. searchsploit is an index. Do not exploit today.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "21 → ¿anonymous? 22 → versión o ssh con user conocido. Hydra es otro bloque y necesita -l. searchsploit lista exploits públicos; no copies el PoC hoy (Semana 3, LHOST vboxnet0, solo tu VM).",
      theoryEn:
        "FTP anonymous first. SSH version or known-user login. Hydra later with a username. searchsploit ≠ run exploit.",
      examPhrases: ["anonymous FTP", "banner grabbing", "OpenSSH version"],
      practiceSteps: [
        "SOURCE=$(grep TARGET_MS2 ~/ejpt-lab.txt | cut -d= -f2)",
        "nc -nv $SOURCE 21  — lee el banner. Ctrl+C.",
        "ftp $SOURCE  — usuario anonymous, password vacío o email. ls. exit. Si falla, anótalo.",
        "nmap --script ftp-anon -p21 $SOURCE",
        "nmap -sV -p22 $SOURCE  — anota OpenSSH x.y. No hydra rockyou.",
        "searchsploit vsftpd 2.3.4  — anota que EXISTE un hit. NO abras ni ejecutes el exploit. Semana 3.",
        "Recall.",
      ],
      workshop: ENUM_FTP_SSH_WORKSHOP,
      troubleshooting: ENUM_TROUBLESHOOTING.filter((t) =>
        ["ftp-hydra-first", "ssh-hydra-no-user", "searchsploit-run"].includes(t.id)
      ),
      subtopics: ["ftp-ssh-enum"],
      drills: [
        {
          id: "d1",
          promptEs: "NSE: ¿FTP anónimo en 10.10.10.80?",
          promptEn: "NSE: anonymous FTP on 10.10.10.80?",
          answer: "nmap --script ftp-anon -p21 10.10.10.80",
          subtopicId: "ftp-ssh-enum",
          explanation: "Script nombrado + puerto 21. No Gobuster. No Metasploit.",
          howToEs: "--script ftp-anon -p21 y la IP.",
        },
        {
          id: "d2",
          promptEs: "Banner crudo del puerto 21 de 10.10.10.80 (netcat).",
          promptEn: "Raw banner on port 21 of 10.10.10.80 (netcat).",
          answer: "nc -nv 10.10.10.80 21",
          subtopicId: "ftp-ssh-enum",
          explanation: "nc al puerto. No es ssh ni hydra.",
          howToEs: "nc -nv IP 21",
        },
        {
          id: "d3",
          promptEs: "Índice searchsploit de 'vsftpd 2.3.4' (no ejecutar exploit).",
          promptEn: "searchsploit index for vsftpd 2.3.4 (do not run an exploit).",
          answer: "searchsploit vsftpd 2.3.4",
          subtopicId: "ftp-ssh-enum",
          explanation: "Busca en la copia local. Hoy no es use exploit/… ni gcc del .c.",
          howToEs: "searchsploit vsftpd 2.3.4",
          conceptQuestion: "¿Hoy ejecutas el exploit que salga?",
          conceptAnswer: "no",
        },
      ],
      comparisonTable: {
        caption: "FTP vs SSH hoy",
        headers: ["Puerto", "Pregunta", "Herramienta", "No"],
        rows: [
          ["21", "¿anonymous?", "ftp / ftp-anon", "Gobuster; Hydra primero"],
          ["22", "¿versión / sesion con user?", "nmap -sV / ssh user@IP", "enum4linux; hydra sin -l"],
          ["versión conocida", "¿hay hit público?", "searchsploit (índice)", "pegar PoC este bloque"],
        ],
      },
      glossary: [
        { en: "anonymous login", es: "acceso anónimo" },
        { en: "banner grabbing", es: "captura de banner" },
        { en: "known exploit", es: "exploit conocido" },
      ],
      resources: [
        { label: "HackTheBox Starting Point — Fawn (opcional)", url: "https://app.hackthebox.com/starting-point", platform: "HackTheBox" },
        { label: "Metasploitable 2 — FTP 21 (vsftpd, a menudo anónimo)", url: "https://sourceforge.net/projects/metasploitable/files/Metasploitable2/", platform: "Local" },
      ],
      closingChecklist: [
        "Confirmé si el FTP del lab permitía acceso anónimo",
        "Identifiqué la versión exacta de SSH del lab",
        "Usé searchsploit al menos una vez y PARÉ (no corrí el exploit)",
      ],
    },
    {
      id: "m1-w2-b7",
      weekId: "m1-w2",
      order: 7,
      title: "Skill-check Semana 2 + Lab de integración",
      objective: "Aprobar el skill-check de Semana 2 (70%+) y enumerar SMB+web+FTP en Metasploitable 2 (y Kioptrix si da tiempo).",
      durationMin: 50,
      type: "checkpoint",
      theoryEs: "Sin teoría nueva. Verificación de que el hueco #2 (confusión de herramientas) está cerrado. Target: tus VMs locales.",
      practiceSteps: [
        "Toma el skill-check de la app (Simulacros > Skill-checks > Semana 2)",
        "Contra Metasploitable 2: enum4linux -a, smbclient -L -N, ftp anonymous, nmap -sV -p22, gobuster al 80. Hydra SOLO con usuario y lista de 20 passwords, no rockyou entero.",
        "Documenta qué herramienta usaste para cada paso y por qué",
      ],
      subtopics: ["enum4linux", "smb-manual", "gobuster-dir", "hydra-bruteforce", "tool-selection", "ftp-ssh-enum"],
      resources: [
        { label: "Metasploitable 2", url: "https://sourceforge.net/projects/metasploitable/files/Metasploitable2/", platform: "Local" },
        { label: "Kioptrix Level 1", url: "https://www.vulnhub.com/entry/kioptrix-level-1-1,22/", platform: "VulnHub" },
      ],
      closingChecklist: [
        "Aprobé el skill-check de Semana 2 con 70% o más",
        "Enumeré SMB y HTTP en Metasploitable 2 documentando la herramienta de cada paso",
        "Ya no dudo entre Gobuster/Hydra/enum4linux en ningún escenario nuevo",
      ],
    },
  ],
};
