import { StudyWeek } from "@/lib/types";

/** MES 3 / SEMANA 9 (global 9) — Cadena completa de ataque en máquinas reales */
export const month3Week9: StudyWeek = {
  id: "m3-w9",
  monthId: "m3",
  title: "Semana 9 — Cadena completa: Recon -> Explotación -> Post",
  goal: "Comprometer máquinas completas end-to-end sin asistencia, cronometrando cada intento como si fuera examen.",
  detailed: true,
  blocks: [
    {
      id: "m3-w9-b1",
      weekId: "m3-w9",
      order: 1,
      title: "Máquina completa #1 (Linux) cronometrada",
      objective: "Comprometer una máquina Linux completa (recon->shell->privesc->flag) en máximo 90 minutos, sin walkthrough.",
      durationMin: 50,
      type: "practice",
      theoryEs: "Sin teoría nueva. A partir de esta semana cada máquina se hace CONTRA RELOJ, simulando la presión de tiempo real del examen (el eJPT da 48h totales pero cada 'tarea' del examen tiene su propio ritmo esperado).",
      practiceSteps: [
        "Cronómetro en marcha: recon completo (Nmap -p- -sV -sC)",
        "Enumeración de servicios encontrados",
        "Explotación (Metasploit o manual)",
        "Escalada de privilegios (LinPEAS / checks manuales)",
        "Documenta el flujo completo en un mini-reporte propio",
      ],
      subtopics: ["full-chain"],
      resources: [{ label: "HackTheBox Starting Point — Tier 1 (Archetype, Oopsie, Vaccine)", url: "https://app.hackthebox.com/starting-point", platform: "HackTheBox" }],
      closingChecklist: ["Completé la máquina en 90 minutos o menos", "Documenté el flujo completo sin ver walkthrough"],
    },
    {
      id: "m3-w9-b2",
      weekId: "m3-w9",
      order: 2,
      title: "Máquina completa #2 (Windows) cronometrada",
      objective: "Comprometer una máquina Windows completa en máximo 90 minutos, sin walkthrough.",
      durationMin: 50,
      type: "practice",
      subtopics: ["full-chain"],
      practiceSteps: ["Mismo flujo que B1, aplicado a un target Windows"],
      resources: [{ label: "HackTheBox Starting Point — Tier 1 (Windows boxes)", url: "https://app.hackthebox.com/starting-point", platform: "HackTheBox" }],
      closingChecklist: ["Completé la máquina Windows en 90 minutos o menos", "Documenté el flujo completo sin ver walkthrough"],
    },
    {
      id: "m3-w9-b3",
      weekId: "m3-w9",
      order: 3,
      title: "Máquina completa #3 (mixta/web) cronometrada",
      objective: "Comprometer una máquina orientada a explotación web (SQLi/LFI/upload) en máximo 90 minutos.",
      durationMin: 50,
      type: "practice",
      subtopics: ["full-chain", "web-sqli", "web-lfi-rfi"],
      practiceSteps: ["Mismo flujo, priorizando enumeración web y explotación de aplicación"],
      resources: [{ label: "TryHackMe — Jr Penetration Tester path (módulo web restante)", url: "https://tryhackme.com/path/outline/jrpenetrationtester", platform: "TryHackMe" }],
      closingChecklist: ["Completé la máquina en 90 minutos o menos"],
    },
    {
      id: "m3-w9-b4",
      weekId: "m3-w9",
      order: 4,
      title: "Skill-check Semana 9",
      objective: "Aprobar el skill-check integrador de cadena completa (70%+).",
      durationMin: 40,
      type: "checkpoint",
      subtopics: ["full-chain"],
      practiceSteps: ["Toma el skill-check en la app (Simulacros > Skill-checks > Semana 9)"],
      closingChecklist: ["Aprobé el skill-check de Semana 9 con 70% o más"],
    },
  ],
};
