import { StudyWeek } from "@/lib/types";
import {
  NMAP_DISCOVERY_WORKSHOP,
  NMAP_INTEGRATION_WORKSHOP,
  NMAP_NSE_WORKSHOP,
  NMAP_TROUBLESHOOTING,
  NMAP_TYPES_WORKSHOP,
} from "@/content/workshops/nmap-fundamentals";

/**
 * MES 1 / SEMANA 1 — Recon activo y Nmap a fondo
 * Semana global: 1
 * Prerreq Semana 0: lab + Linux (b6–7) + redes (b8–9). Talleres Nmap: WHAT/WHY/WHEN/OUTPUT/NEXT por flag.
 */
export const month1Week1: StudyWeek = {
  id: "m1-w1",
  monthId: "m1",
  title: "Semana 1 — Recon activo y Nmap a fondo",
  goal: "Dominar Nmap (descubrimiento, tipos de escaneo, NSE) y recon pasivo al nivel que exige eJPT: Information Gathering + Footprinting & Scanning.",
  detailed: true,
  blocks: [
    {
      id: "m1-w1-b1",
      weekId: "m1-w1",
      order: 1,
      title: "Host discovery y primer escaneo de puertos",
      titleEn: "Host discovery and first port scan",
      objective: "Desde Kali host: nmap -sn a 192.168.56.0/24, luego nmap -p- -sV a TARGET_MS2, y -oA. Sin apuntes en el drill.",
      objectiveEn: "Run host discovery, then a full TCP version scan against TARGET_MS2, save with -oA.",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "No escanees 65535 puertos de una red /24 a ciegas. Primero -sn (¿quién está vivo?). Luego -p- en UNA IP (todos los TCP; el default de Nmap es solo top 1000). -sV pregunta la versión (vsftpd 2.3.4, no solo 'ftp'). -oA nombre guarda .nmap + .xml + .gnmap. Tu target es la IP de ~/ejpt-lab.txt, no una VPN.",
      theoryEn:
        "eJPT asks for exact flags. -sn = host discovery (no ports). -p- = all TCP ports. -sV = service version detection. -oA file = three output formats. Target = your Metasploitable 2 guest.",
      examPhrases: ["host discovery", "open ports", "service version detection", "full port scan"],
      practiceSteps: [
        "Confirma que Metasploitable 2 está encendida en Host-Only. Desde Kali: ping -c 2 <IP de ~/ejpt-lab.txt>. Si no hay IP, nmap -sn 192.168.56.0/24",
        "Descubre hosts vivos en tu red de lab: nmap -sn 192.168.56.0/24 (ajusta el rango si tu vboxnet es otro)",
        "Escanea TODOS los puertos TCP del host objetivo: nmap -p- <IP>",
        "Repite el escaneo agregando detección de versión: nmap -p- -sV <IP>",
        "Guarda el resultado en los 3 formatos a la vez: nmap -p- -sV <IP> -oA scan_full",
        "Abre scan_full.nmap (less). Anota 3 líneas PORT/STATE/SERVICE. Recall sin apuntes.",
      ],
      workshop: NMAP_DISCOVERY_WORKSHOP,
      troubleshooting: NMAP_TROUBLESHOOTING.filter((t) =>
        ["wrong-range", "default-1000", "from-guest"].includes(t.id)
      ),
      subtopics: ["nmap-basic", "nmap-versioning"],
      drills: [
        {
          id: "d1",
          promptEs: "Hosts vivos en 192.168.56.0/24, sin puertos.",
          promptEn: "Discover live hosts on 192.168.56.0/24, do not scan ports.",
          answer: "nmap -sn 192.168.56.0/24",
          subtopicId: "nmap-basic",
          explanation: "-sV y -p- tocan puertos. Primero: ¿quién está vivo? Flag de host discovery.",
          howToEs: "nmap -sn y el /24. No pongas -sV.",
          conceptQuestion: "¿-sn lista puertos abiertos?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "Todos los TCP + versión en 192.168.56.101.",
          promptEn: "Scan all TCP ports with version detection on 192.168.56.101.",
          answer: "nmap -p- -sV 192.168.56.101",
          subtopicId: "nmap-basic",
          explanation: "Default = top 1000, no 65535. Versión es -sV, no -sn.",
          howToEs: "-p- y -sV contra esa IP.",
          conceptQuestion: "Sin -p-, ¿cuántos puertos prueba Nmap por defecto (orden de magnitud)?",
          conceptAnswer: "1000",
        },
        {
          id: "d3",
          promptEs: "Puertos 22,80,443 y -oA resultado.",
          promptEn: "Scan 22,80,443 and save all 3 formats as resultado.",
          answer: "nmap -p22,80,443 192.168.56.101 -oA resultado",
          subtopicId: "nmap-basic",
          explanation: "-oN es solo texto. -oA escribe .nmap + .xml + .gnmap con el mismo prefijo.",
          howToEs: "-p22,80,443, la IP, -oA resultado.",
        },
      ],
      comparisonTable: {
        caption: "Flag → pregunta que responde",
        headers: ["Flag", "Pregunta", "Siguiente"],
        rows: [
          ["-sn", "¿Quién está vivo?", "Una IP, no más discovery"],
          ["-p-", "¿Qué TCP hay (todos)?", "-sV / NSE"],
          ["-sV", "¿Qué versión?", "enum de ESE servicio"],
          ["-oA", "¿Dónde quedó la evidencia?", "less archivo.nmap"],
        ],
      },
      glossary: [
        { en: "host discovery", es: "descubrimiento de hosts" },
        { en: "open port", es: "puerto abierto" },
        { en: "filtered port", es: "puerto filtrado" },
        { en: "service version detection", es: "detección de versión de servicio" },
      ],
      resources: [
        { label: "Metasploitable 2 — target de este bloque", url: "https://sourceforge.net/projects/metasploitable/files/Metasploitable2/", platform: "Local" },
        { label: "TryHackMe — Nmap (opcional)", url: "https://tryhackme.com/room/furthernmap", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "Puedo escribir de memoria un host discovery scan (-sn) sin ver apuntes",
        "Puedo escribir de memoria un full port scan con versión (-p- -sV)",
        "Sé exportar resultados con -oA sin buscarlo en Google",
        "Leo PORT/STATE/SERVICE/VERSION y elijo el siguiente movimiento (no exploto a ciegas)",
      ],
    },
    {
      id: "m1-w1-b2",
      weekId: "m1-w1",
      order: 2,
      title: "Tipos de escaneo y timing (-sS/-sT/-sU/-T)",
      titleEn: "Scan types and timing templates",
      objective: "Contra TARGET_MS2: un -sS -T4, un -sT sin root, un -sU --top-ports 20. Saber cuándo cada flag.",
      objectiveEn: "Run SYN, connect, and UDP scans against TARGET_MS2. Pick -T4 unless the box is unstable.",
      durationMin: 45,
      type: "drill",
      theoryEs:
        "En TU Kali (root) el default ya es -sS. -sS = SYN, no completa handshake. -sT = connect(), no necesita root. -sU = UDP (lento; DNS/SNMP). -T4 = rápido para lab/examen; -T2 si la VM se cae. No uses -T5 en examen: pierde paquetes.",
      theoryEn:
        "-sS SYN scan (root). -sT TCP connect scan (no root). -sU UDP. -T4 is the usual exam timing. Target the Metasploitable guest IP from ~/ejpt-lab.txt, not a VPN.",
      examPhrases: ["SYN scan", "TCP connect scan", "UDP scan", "timing template -T4"],
      practiceSteps: [
        "Ejecuta un SYN scan explícito: sudo nmap -sS -p- <IP>",
        "Ejecuta un connect scan sin sudo: nmap -sT -p 1-1000 <IP>",
        "Ejecuta un escaneo UDP de los 20 puertos más comunes: sudo nmap -sU --top-ports 20 <IP>",
        "Compara tiempos: repite el mismo escaneo con -T4 y con -T2 y anota la diferencia",
        "Di en voz alta: cuándo -sS vs -sT vs -sU. Luego recall.",
      ],
      workshop: NMAP_TYPES_WORKSHOP,
      troubleshooting: NMAP_TROUBLESHOOTING.filter((t) => ["need-root", "udp-slow"].includes(t.id)),
      subtopics: ["nmap-basic"],
      drills: [
        {
          id: "d1",
          promptEs: "SYN + T4 + todos los puertos a 192.168.56.101",
          promptEn: "SYN scan, -T4, all ports, 192.168.56.101",
          answer: "sudo nmap -sS -T4 -p- 192.168.56.101",
          subtopicId: "nmap-basic",
          explanation: "SYN half-open = -sS y suele necesitar root. -T4 es timing, no un tipo de paquete.",
          howToEs: "sudo, -sS, -T4, -p-, la IP.",
          conceptQuestion: "¿-sS completa el handshake TCP?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "50 UDP más comunes a 192.168.56.101",
          promptEn: "Top 50 UDP ports on 192.168.56.101",
          answer: "sudo nmap -sU --top-ports 50 192.168.56.101",
          subtopicId: "nmap-basic",
          explanation: "UDP es -sU, lento. No uses -p- UDP en un drill de 50 puertos.",
          howToEs: "sudo nmap -sU --top-ports 50 y la IP.",
        },
        {
          id: "d3",
          promptEs: "Connect scan puertos 1-500 (sin sudo)",
          promptEn: "TCP connect scan ports 1-500 (no sudo)",
          answer: "nmap -sT -p 1-500 192.168.56.101",
          subtopicId: "nmap-basic",
          explanation: "connect() = -sT, sin raw sockets. sudo no va en este drill.",
          howToEs: "nmap -sT -p 1-500 y la IP. Sin sudo.",
        },
      ],
      comparisonTable: {
        caption: "-sS vs -sT vs -sU",
        headers: ["Flag", "Qué pregunta", "Root?"],
        rows: [
          ["-sS", "TCP half-open (SYN)", "sí (raw)"],
          ["-sT", "TCP connect completo", "no"],
          ["-sU", "UDP (lento)", "sí típico"],
          ["-T4", "reloj, no tipo de scan", "n/a"],
        ],
      },
      glossary: [
        { en: "SYN scan", es: "escaneo SYN (half-open)" },
        { en: "connect scan", es: "escaneo de conexión completa" },
        { en: "timing template", es: "plantilla de temporización" },
        { en: "stealth", es: "sigilo" },
      ],
      resources: [
        { label: "Nmap Reference Guide (docs oficiales)", url: "https://nmap.org/book/man-port-scanning-techniques.html", platform: "Docs" },
      ],
      closingChecklist: [
        "Explico en una frase la diferencia entre -sS y -sT",
        "Sé cuándo usar -sU y qué desventaja tiene (velocidad)",
        "Escribo -T4 de memoria y sé qué hace",
      ],
    },
    {
      id: "m1-w1-b3",
      weekId: "m1-w1",
      order: 3,
      title: "Nmap Scripting Engine (NSE)",
      titleEn: "Nmap Scripting Engine (NSE)",
      objective: "Contra TARGET_MS2: -sC -sV, ftp-anon en 21, smb-os-discovery en 445. Anota 1 hallazgo concreto (no 'explorar').",
      objectiveEn: "Run default NSE + version detection on TARGET_MS2. Use ftp-anon and smb-os-discovery. Write one finding.",
      durationMin: 50,
      type: "practice",
      theoryEs:
        "-sC = scripts default (seguros). --script vuln = más ruidoso, busca CVEs. En MS2 sirve ftp-anon (¿anonymous login?) y smb-os-discovery (workgroup/OS). Los .nse viven en /usr/share/nmap/scripts/. El examen pide un dato (título HTTP, anonymous FTP), no un ensayo.",
      theoryEn:
        "-sC runs default scripts. --script ftp-anon -p21 checks anonymous FTP. --script smb-os-discovery -p445 fingerprints SMB. Point all of this at TARGET_MS2 on the host-only LAN.",
      examPhrases: ["Nmap Scripting Engine (NSE)", "anonymous FTP", "SMB OS discovery"],
      practiceSteps: [
        "SOURCE=$(grep TARGET_MS2 ~/ejpt-lab.txt | cut -d= -f2). Usa esa IP abajo.",
        "nmap -sC -sV $SOURCE",
        "nmap --script ftp-anon -p21 $SOURCE",
        "nmap --script smb-os-discovery -p445 $SOURCE",
        "nmap --script http-title,http-headers -p80 $SOURCE",
        "ls /usr/share/nmap/scripts/ | grep ftp | head",
        "Escribe UN hallazgo NSE en ~/ejpt-lab.txt. Recall.",
      ],
      workshop: NMAP_NSE_WORKSHOP,
      troubleshooting: NMAP_TROUBLESHOOTING.filter((t) => ["from-guest"].includes(t.id)),
      subtopics: ["nmap-scripts"],
      drills: [
        {
          id: "d1",
          promptEs: "Default scripts + versión a 192.168.56.101",
          promptEn: "Default NSE scripts + version detection on 192.168.56.101",
          answer: "nmap -sC -sV 192.168.56.101",
          subtopicId: "nmap-scripts",
          explanation: "-sC = default, no la categoría vuln. -sV es versión. Van juntos en el primer pase.",
          howToEs: "-sC -sV y la IP.",
          conceptQuestion: "¿-sC es lo mismo que --script vuln?",
          conceptAnswer: "no",
        },
        {
          id: "d2",
          promptEs: "NSE vuln contra 192.168.56.101",
          promptEn: "Run the vuln NSE category against 192.168.56.101",
          answer: "sudo nmap --script vuln 192.168.56.101",
          subtopicId: "nmap-scripts",
          explanation: "Categoría vuln es --script vuln, no -sC. Más ruidoso; verifica el hallazgo.",
          howToEs: "--script vuln y la IP. sudo es aceptable.",
        },
        {
          id: "d3",
          promptEs: "http-title en el puerto 80",
          promptEn: "Get the HTTP title on port 80",
          answer: "nmap --script http-title -p80 192.168.56.101",
          subtopicId: "nmap-scripts",
          explanation: "Un script nombrado + el puerto. No Gobuster aquí: solo el título HTTP.",
          howToEs: "--script http-title -p80 y la IP.",
        },
      ],
      comparisonTable: {
        caption: "NSE: default vs nombrado vs vuln",
        headers: ["Cómo", "Pregunta", "Siguiente"],
        rows: [
          ["-sC", "scripts default + info general", "leer output"],
          ["--script ftp-anon -p21", "¿anonymous FTP?", "enum FTP Semana 2"],
          ["--script smb-os-discovery -p445", "¿OS/workgroup SMB?", "enum4linux"],
          ["--script vuln", "¿CVEs ruidosos?", "verificar, no explotar ciego"],
        ],
      },
      glossary: [
        { en: "NSE (Nmap Scripting Engine)", es: "motor de scripts de Nmap" },
        { en: "default scripts", es: "scripts por defecto" },
        { en: "vulnerability scan", es: "escaneo de vulnerabilidades" },
      ],
      resources: [
        { label: "Nmap NSE docs", url: "https://nmap.org/nsedoc/", platform: "Docs" },
        { label: "Target: Metasploitable 2 guest", url: "https://sourceforge.net/projects/metasploitable/files/Metasploitable2/", platform: "Local" },
      ],
      closingChecklist: [
        "Escribo -sC -sV de memoria",
        "Sé buscar un script NSE por categoría (--script vuln) sin buscarlo en Google",
        "Puedo nombrar 2 scripts NSE específicos para SMB y 2 para HTTP",
      ],
    },
    {
      id: "m1-w1-b4",
      weekId: "m1-w1",
      order: 4,
      title: "Recon pasivo: whois, DNS, theHarvester",
      objective: "Extraer información de un dominio (whois, registros DNS, correos/subdominios) sin tocar directamente al objetivo (recon pasivo).",
      durationMin: 45,
      type: "practice",
      theoryEs:
        "El recon pasivo se hace SIN interactuar directamente con la infraestructura del objetivo (evita alertar). En eJPT aparece como 'Information Gathering': whois da datos de registro de dominio, dig/nslookup consulta DNS, theHarvester agrega correos/subdominios de fuentes públicas (OSINT).",
      practiceSteps: [
        "Consulta datos de registro del dominio: whois <dominio>",
        "Consulta registros DNS tipo A: dig <dominio> A",
        "Consulta registros MX (mail): dig <dominio> MX",
        "Corre theHarvester contra un dominio de laboratorio: theHarvester -d <dominio> -b all",
        "Anota qué diferencia hay entre recon pasivo y activo en tus propias palabras",
      ],
      subtopics: ["passive-recon"],
      drills: [
        { id: "d1", promptEs: "Escribe el comando para consultar el registro whois de 'example.com'.", answer: "whois example.com" },
        { id: "d2", promptEs: "Escribe el comando dig para obtener los registros MX de 'example.com'.", answer: "dig example.com MX" },
        { id: "d3", promptEs: "Escribe el comando theHarvester para buscar correos y subdominios de 'example.com' usando todas las fuentes.", answer: "theHarvester -d example.com -b all" },
      ],
      glossary: [
        { en: "passive reconnaissance", es: "recon pasivo" },
        { en: "active reconnaissance", es: "recon activo" },
        { en: "OSINT", es: "inteligencia de fuentes abiertas" },
        { en: "DNS record", es: "registro DNS" },
      ],
      resources: [
        { label: "TryHackMe — Passive Reconnaissance", url: "https://tryhackme.com/room/passiverecon", platform: "TryHackMe" },
      ],
      closingChecklist: [
        "Explico en una frase la diferencia entre recon pasivo y activo",
        "Escribo whois y dig de memoria",
        "Ejecuté theHarvester al menos una vez contra un dominio real de laboratorio",
      ],
    },
    {
      id: "m1-w1-b5",
      weekId: "m1-w1",
      order: 5,
      title: "Drill combinado + Skill-check Semana 1",
      objective: "Aprobar un mini skill-check de 5 preguntas sobre Nmap y recon pasivo con 80% o más antes de avanzar a la Semana 2.",
      durationMin: 45,
      type: "checkpoint",
      theoryEs: "Sin teoría nueva. Este bloque es 100% verificación: si fallas algo aquí, el sistema te marcará el sub-tema exacto y te dará un mini-repaso antes de dejarte avanzar (regla fija del plan, ver sección Feedback).",
      practiceSteps: [
        "Repite de memoria (sin ver apuntes) los 3 comandos de B1",
        "Repite de memoria los 3 comandos de B2",
        "Repite de memoria los 3 comandos de B3",
        "Toma el skill-check de 5 preguntas en la app (sección Simulacros > Skill-checks > Semana 1)",
      ],
      subtopics: ["nmap-basic", "nmap-scripts", "nmap-versioning", "passive-recon"],
      glossary: [],
      closingChecklist: [
        "Aprobé el skill-check de Semana 1 con 80% o más",
        "Puedo escribir SIN ayuda: host discovery, full port scan, SYN scan con timing, NSE default+vuln, whois/dig",
      ],
    },
    {
      id: "m1-w1-b6",
      weekId: "m1-w1",
      order: 6,
      title: "Lab de integración: Nmap contra Metasploitable 2",
      objective: "En máximo 40 minutos, documentar TODOS los puertos TCP abiertos, versiones y 1 hallazgo NSE de Metasploitable 2, sin walkthrough.",
      durationMin: 50,
      type: "practice",
      theoryEs: "No hay teoría nueva. Examen en miniatura contra tu VM local (no hace falta VPN ni THM).",
      practiceSteps: [
        "Enciende Metasploitable 2. Desde Kali: nmap -sn 192.168.56.0/24 y confirma la IP de ~/ejpt-lab.txt",
        "Objetivo cerrado (40 min): nmap -p- -sV -sC <IP> -oA ms2_full. Anota puertos, versiones, y al menos 1 script NSE (ej. ftp-anon o smb-os-discovery)",
        "Documenta en un archivo: IP, puertos, versiones, hallazgos NSE",
        "Compara tu lista con Rapid7 exploitability guide (recurso extra) SOLO al final, para auditarte",
      ],
      workshop: NMAP_INTEGRATION_WORKSHOP,
      troubleshooting: NMAP_TROUBLESHOOTING.filter((t) =>
        ["wrong-range", "default-1000", "from-guest"].includes(t.id)
      ),
      subtopics: ["nmap-basic", "nmap-scripts", "nmap-versioning"],
      resources: [
        { label: "Metasploitable 2 — guía de servicios (auditoría al final)", url: "https://docs.rapid7.com/metasploit/metasploitable-2-exploitability-guide/", platform: "Docs" },
      ],
      extraResources: [
        { label: "Kioptrix Level 1 — segundo target si acabas antes de 40 min", url: "https://www.vulnhub.com/entry/kioptrix-level-1-1,22/", platform: "VulnHub" },
      ],
      closingChecklist: [
        "Completé el escaneo de Metasploitable 2 sin walkthrough",
        "Documenté puertos, versiones y hallazgos NSE en un archivo propio",
        "Terminé el objetivo cerrado dentro del tiempo (40 min)",
      ],
    },
  ],
};
