import { StudyWeek } from "@/lib/types";

/** MES 3 / SEMANA 9 (global 9) — Cadena completa de ataque en máquinas reales */
export const month3Week9: StudyWeek = {
  id: "m3-w9",
  monthId: "m3",
  title: "Semana 9 — Cadena completa: Recon -> Explotación -> Post",
  goal: "Comprometer máquinas completas end-to-end sin asistencia, cronometrando cada intento como si fuera examen.",
  detailed: true,
  blocks: [
    {
      id: "m3-w9-b1",
      weekId: "m3-w9",
      order: 1,
      title: "Máquina completa #1 (Linux) cronometrada",
      objective: "Comprometer una máquina Linux completa (recon->shell->privesc->flag) en máximo 90 minutos, sin walkthrough.",
      durationMin: 50,
      type: "practice",
      theoryEs: "Sin teoría nueva. A partir de esta semana cada máquina se hace CONTRA RELOJ, simulando la presión de tiempo real del examen (el eJPT da 48h totales pero cada 'tarea' del examen tiene su propio ritmo esperado).",
      practiceSteps: [
        "Cronómetro en marcha: recon completo (Nmap -p- -sV -sC)",
        "Enumeración de servicios encontrados",
        "Explotación (Metasploit o manual)",
        "Escalada de privilegios (LinPEAS / checks manuales)",
        "Documenta el flujo completo en un mini-reporte propio",
      ],
      subtopics: ["full-chain"],
      resources: [{ label: "Kioptrix Level 1 — cadena completa 90 min", url: "https://www.vulnhub.com/entry/kioptrix-level-1-1,22/", platform: "VulnHub" }],
      closingChecklist: ["Completé la máquina en 90 minutos o menos", "Documenté el flujo completo sin ver walkthrough"],
    },
    {
      id: "m3-w9-b2",
      weekId: "m3-w9",
      order: 2,
      title: "Máquina completa #2 (segundo Linux / Samba) cronometrada",
      objective: "Comprometer un segundo vector en Metasploitable 2 o Kioptrix 2 en máximo 90 minutos, sin walkthrough.",
      durationMin: 50,
      type: "practice",
      subtopics: ["full-chain"],
      practiceSteps: ["Mismo flujo que B1. Target: Samba usermap o Kioptrix Level 2 si ya bajaste esa VM."],
      resources: [
        { label: "VulnHub — Kioptrix Level 2", url: "https://www.vulnhub.com/entry/kioptrix-level-11-2,23/", platform: "VulnHub" },
        { label: "Metasploitable 2 — segundo servicio", url: "https://docs.rapid7.com/metasploit/metasploitable-2-exploitability-guide/", platform: "Local" },
      ],
      closingChecklist: ["Completé la segunda máquina/vector en 90 minutos o menos", "Documenté el flujo completo sin walkthrough"],
    },
    {
      id: "m3-w9-b3",
      weekId: "m3-w9",
      order: 3,
      title: "Máquina completa #3 (mixta/web) cronometrada",
      objective: "Comprometer una máquina orientada a explotación web (SQLi/LFI/upload) en máximo 90 minutos.",
      durationMin: 50,
      type: "practice",
      subtopics: ["full-chain", "web-sqli", "web-lfi-rfi"],
      practiceSteps: ["Mismo flujo, priorizando enumeración web y explotación de aplicación"],
      resources: [
        { label: "VulnHub — Mr-Robot:1 (web)", url: "https://www.vulnhub.com/entry/mr-robot-1,151/", platform: "VulnHub" },
        { label: "DVWA — File Inclusion + SQLi encadenados", url: "http://127.0.0.1:4280", platform: "Local" },
      ],
      closingChecklist: ["Completé la máquina en 90 minutos o menos"],
    },
    {
      id: "m3-w9-b4",
      weekId: "m3-w9",
      order: 4,
      title: "Skill-check Semana 9",
      objective: "Aprobar el skill-check integrador de cadena completa (70%+).",
      durationMin: 40,
      type: "checkpoint",
      subtopics: ["full-chain"],
      practiceSteps: ["Toma el skill-check en la app (Simulacros > Skill-checks > Semana 9)"],
      closingChecklist: ["Aprobé el skill-check de Semana 9 con 70% o más"],
    },
  ],
};
