import { LearnArticle } from "@/content/learn-types";

/** Ampliación V8: Windows, OSINT, exploit placeholders, pivoting reasoning. No sustituye fichas previas. */
export const LEARN_CATALOG_V8: LearnArticle[] = [
  {
    id: "win-privs",
    track: "WINDOWS",
    titleEs: "Privilegios y token Windows",
    what: "En Windows el token lleva privilegios (SeDebug, SeImpersonate, SeBackup…). whoami /priv y whoami /all muestran el contexto. No es un exploit: es el mapa del usuario actual.",
    why: "Muchos caminos de privesc dependen de un privilegio concreto o de un servicio mal configurado. Sin el token, un 'potato' es teatro.",
    how: "whoami, whoami /groups, whoami /priv, net user, net localgroup administrators. Servicios: sc query / Get-Service (concepto). Solo lab autorizado, nunca el PC familiar.",
    when: "Tras initial access Windows. Antes de descargar herramientas ruidosas.",
    example: "SeImpersonate Enabled sugiere una familia de técnicas de impersonation — a verificar en lab, no a lanzar a ciegas.",
    mistake: "Ejecutar un binario de privesc porque un blog lo nombró, sin leer privilegios.",
    redTeam: "Enum local primero. AD/BloodHound solo si hay dominio en alcance.",
    recall: "¿whoami /priv es un exploit?",
    recallKeywords: ["no"],
    challenge: "¿El token importa antes que el nombre del CVE?",
    challengeKeywords: ["si"],
  },
  {
    id: "win-sched-acl",
    track: "WINDOWS",
    titleEs: "Tareas, ACL y servicios",
    what: "Scheduled Tasks, servicios con binario escribible, ACL débiles en carpetas de Program Files: son hipótesis clásicas. PowerShell (Get-Acl, Get-ChildItem) y icacls son lectura, no magia.",
    why: "eJPT pide modelo mental si no hay VM Windows a mano. Saber QUÉ buscar evita copiar un checklist de 200 líneas.",
    how: "Pregunta: ¿quién puede escribir el binario del servicio? ¿La tarea corre como SYSTEM? Anota evidencia. Lab propio.",
    when: "Cuando ya eres user bajo en Windows de laboratorio.",
    example: "Un servicio que apunta a C:\\tools\\svc.exe world-writable es más interesante que 50 DLL de System32.",
    mistake: "WinPEAS entero sin leer una sola línea de privilegios.",
    redTeam: "Una hipótesis verificable > un dump.",
    recall: "¿Una tarea SYSTEM con binario escribible es interesante?",
    recallKeywords: ["si"],
    challenge: "¿WinPEAS razona por ti?",
    challengeKeywords: ["no"],
  },
  {
    id: "whois-dns",
    track: "OSINT",
    titleEs: "WHOIS, DNS y superficie pública",
    what: "WHOIS, DNS (A/MX/NS), subdominios y documentos públicos pueden revelar tecnología, rangos y usuarios. Es pasivo. No es nmap del lab Host-Only.",
    why: "La pregunta útil: ¿qué información pública puede cambiar mi estrategia? Un WAF, un correo de admin, un PDF con un software interno.",
    how: "En alcance autorizado: whois, consultas DNS. theHarvester en talleres es extensión, no la ruta mínima eJPT.",
    when: "Passive recon, o si el brief menciona un dominio. No para escanear Internet.",
    example: "MX apunta a un proveedor → hipótesis de webmail, no de MS2:445.",
    mistake: "Creer que OSINT autoriza atacar hosts fuera del CIDR.",
    redTeam: "Público ≠ permiso. Scope escrito manda.",
    recall: "¿WHOIS sustituye nmap del guest?",
    recallKeywords: ["no"],
    challenge: "¿OSINT puede cambiar la hipótesis de users?",
    challengeKeywords: ["si"],
  },
  {
    id: "public-surface",
    track: "OSINT",
    titleEs: "Usuarios, emails y docs públicos",
    what: "Emails, usernames, metadatos de documentos y fingerprints de tecnologías (concepto) alimentan enum posterior (Hydra necesita user; phishing no es eJPT).",
    why: "Sin un nombre, brute es ruido. En el lab, enum4linux a veces da el user que OSINT daría en un dominio real.",
    how: "Anota 3 datos públicos que cambiarían el orden de tus herramientas. No copies dumps de examen.",
    when: "Passive recon y reporting (valores exactos).",
    example: "Un PDF interno con 'intranet' sugiere HTTP interno — luego pivot, no gobuster a Internet.",
    mistake: "Mezclar OSINT con el alcance Host-Only y nmappear la WAN.",
    redTeam: "Cada dato debe conectar con una acción in-scope.",
    recall: "¿Hydra necesita un usuario?",
    recallKeywords: ["si"],
    challenge: "¿Un email público autoriza Hydra en Internet?",
    challengeKeywords: ["no"],
  },
  {
    id: "exploit-placeholders",
    track: "EXPLOITATION",
    titleEs: "Modificar placeholders (RHOST/LHOST)",
    what: "Muchos PoCs públicos son plantillas: RHOST, RPORT, LHOST, LPORT, TARGET, PAYLOAD, URI. Competencia eJPT: leer, entender, sustituir por IPs medidas en TU lab. No es exploit development ni escribir shellcode.",
    why: "El fallo clásico es dejar CHANGE_ME o copiar 192.168.56.1 de un post. La víctima llama a LHOST; si LHOST es wlan0, no hay session.",
    how: "READ → identify variables → ip addr / ip route → modify → run SOLO en lab → troubleshoot (options, NIC, firewall local).",
    when: "Tras match de versión. Nunca contra sistemas de terceros.",
    example: "LHOST=IP vboxnet0, RHOST=IP guest, RPORT del -sV, LPORT libre (4444). PATH del hallazgo HTTP.",
    mistake: "Pegar el .py contra producción 'a ver'.",
    redTeam: "Configuración correcta > 'el exploit está muerto'.",
    recall: "¿LHOST es la víctima?",
    recallKeywords: ["no"],
    challenge: "¿Debes medir LHOST con ip addr?",
    challengeKeywords: ["si"],
  },
  {
    id: "pivot-hops",
    track: "PIVOTING",
    titleEs: "Alcance por hop",
    what: "Cada host ve un conjunto de redes. Kali ve vboxnet. El pivot dual-homed ve vboxnet + interna. El target interno puede no ver Kali. El trabajo es descubrir, no adivinar 10.0.0.0/8.",
    why: "Port forward local (-L), remoto (-R) y SOCKS (-D)/proxychains son herramientas distintas para esa topología.",
    how: "Dibuja: KALI — PIVOT — INTERNAL — TARGET. ping/route desde cada hop (concepto). Si Kali ya hace ping al target, no es pivot.",
    when: "Tras access y evidencia de otra NIC.",
    example: "Timeout desde Kali a 10.13.13.50 + eth1 10.13.13.1 en la víctima = candidato a -L o SOCKS.",
    mistake: "proxychains hacia tu Wi‑Fi doméstica.",
    redTeam: "¿Kali ve el target? Si sí, nmap directo. Si no, puente.",
    recall: "¿-L es SOCKS?",
    recallKeywords: ["no"],
    challenge: "¿Timeout desde Kali sugiere pivot?",
    challengeKeywords: ["si"],
  },
];
