import type { CommandCard } from "@/content/command-bank";

const h = (a: string, b: string, c: string, d: string, e: string): CommandCard["hints"] => [a, b, c, d, e];

/** SRS añadido en V8. No sustituye el banco original. */
export const SRS_V8: CommandCard[] = [
  {
    id: "linux-id",
    category: "Linux",
    subtopicId: "linux-basic",
    fragment: "id",
    toolAnswer: "id",
    toolQuestionEs: "¿Qué comando muestra uid/gid y grupos del usuario actual?",
    toolQuestionEn: "Which command shows uid/gid and groups of the current user?",
    paramQuestionEs: "No hay flags obligatorios. Escribe el comando:",
    paramQuestionEn: "Typical command (no required flags):",
    paramAnswer: "id",
    fullQuestionEs: "¿Quién soy en esta shell?",
    fullQuestionEn: "Who am I in this shell?",
    fullAnswer: "id",
    conceptQuestionEs: "¿id sustituye a sudo -l para privesc?",
    conceptQuestionEn: "Does id replace sudo -l for privesc?",
    conceptKeywords: ["no"],
    explanationEs: "id = contexto. sudo -l / SUID / cron son vectores. Contexto primero, vector después.",
    hints: h("Necesitas saber uid y grupos.", "Comando de una letra/palabra.", "id", "id", "id muestra uid/gid. No es sudo -l."),
  },
  {
    id: "linux-sudo-l",
    category: "Linux",
    subtopicId: "privesc-linux",
    fragment: "sudo -l",
    toolAnswer: "sudo",
    toolQuestionEs: "¿Qué comando lista qué puedes ejecutar con sudo?",
    toolQuestionEn: "Which command lists what you may run with sudo?",
    paramQuestionEs: "Flag para listar privilegios sudo:",
    paramQuestionEn: "Flag that lists sudo privileges:",
    paramAnswer: "-l",
    fullQuestionEs: "Lista tus reglas sudo sin adivinar binarios.",
    fullQuestionEn: "List your sudo rules without guessing binaries.",
    fullAnswer: "sudo -l",
    conceptQuestionEs: "¿sudo -l es LinPEAS?",
    conceptQuestionEn: "Is sudo -l LinPEAS?",
    conceptKeywords: ["no"],
    explanationEs: "sudo -l es evidencia manual. LinPEAS agrega ruido; tú interpretas NOPASSWD y paths.",
    hints: h("Quieres saber si puedes elevar con sudo.", "sudo tiene un flag de listado.", "sudo -l", "sudo -l", "Lista reglas. No ejecutes find / al azar."),
  },
  {
    id: "win-whoami",
    category: "Windows",
    subtopicId: "privesc-windows",
    fragment: "whoami /priv",
    toolAnswer: "whoami",
    toolQuestionEs: "¿Qué comando Windows muestra el usuario y, con flag, privilegios?",
    toolQuestionEn: "Which Windows command shows the user and, with a flag, privileges?",
    paramQuestionEs: "Flag de privilegios:",
    paramQuestionEn: "Privileges flag:",
    paramAnswer: "/priv",
    fullQuestionEs: "Lista privilegios del token actual.",
    fullQuestionEn: "List privileges of the current token.",
    fullAnswer: "whoami /priv",
    conceptQuestionEs: "¿whoami /priv es un exploit?",
    conceptQuestionEn: "Is whoami /priv an exploit?",
    conceptKeywords: ["no"],
    explanationEs: "Es enumeración. SeTokenPrivilege / SeImpersonate cambian la hipótesis. No lances un 'potato' a ciegas.",
    hints: h("Necesitas el token, no un CVE.", "whoami con un flag de privilegios.", "whoami /priv", "whoami /priv", "Token primero. Exploit después, en lab autorizado."),
  },
  {
    id: "win-net-user",
    category: "Windows",
    subtopicId: "privesc-windows",
    fragment: "net user",
    toolAnswer: "net",
    toolQuestionEs: "¿Qué herramienta clásica lista usuarios locales en Windows?",
    toolQuestionEn: "Which classic Windows tool lists local users?",
    paramQuestionEs: "Subcomando de usuarios:",
    paramQuestionEn: "Users subcommand:",
    paramAnswer: "user",
    fullQuestionEs: "Lista usuarios locales.",
    fullQuestionEn: "List local users.",
    fullAnswer: "net user",
    conceptQuestionEs: "¿net user es BloodHound?",
    conceptQuestionEn: "Is net user BloodHound?",
    conceptKeywords: ["no"],
    explanationEs: "net user = local. BloodHound es AD. eJPT: no asumas bosque AD en un lab de una VM.",
    hints: h("Usuarios locales, no AD.", "net …", "net user", "net user", "Local first. Groups: net localgroup administrators."),
  },
  {
    id: "pivot-reachable",
    category: "Pivot",
    subtopicId: "net-pivoting",
    fragment: "ip addr",
    toolAnswer: "ip",
    toolQuestionEs: "¿Qué comando en Linux muestra interfaces y redes visibles en ESE host?",
    toolQuestionEn: "Which Linux command shows interfaces and networks on THAT host?",
    paramQuestionEs: "Subcomando de direcciones:",
    paramQuestionEn: "Addresses subcommand:",
    paramAnswer: "addr",
    fullQuestionEs: "En la víctima: ver si hay una segunda NIC.",
    fullQuestionEn: "On the victim: see if there is a second NIC.",
    fullAnswer: "ip addr",
    conceptQuestionEs: "¿Si Kali ya hace ping al target, necesitas pivot?",
    conceptQuestionEn: "If Kali already pings the target, do you need a pivot?",
    conceptKeywords: ["no"],
    explanationEs: "Pivot = red que Kali NO ve. ip addr en el host comprometido. No inventes 10.0.0.0/8.",
    hints: h("¿El host tiene otra interfaz?", "ip …", "ip addr", "ip addr", "Si Kali ya alcanza el target, no es pivot."),
  },
  {
    id: "pivot-ssh-l",
    category: "Pivot",
    subtopicId: "net-pivoting",
    fragment: "ssh -L",
    toolAnswer: "ssh",
    toolQuestionEs: "¿Qué herramienta hace port forward local clásico?",
    toolQuestionEn: "Which tool does classic local port forwarding?",
    paramQuestionEs: "Flag de local forward:",
    paramQuestionEn: "Local forward flag:",
    paramAnswer: "-L",
    fullQuestionEs: "Concepto: local forward (tú escuchas, el salto sale al interno).",
    fullQuestionEn: "Concept: local forward (you listen, hop reaches internal).",
    fullAnswer: "ssh -L",
    conceptQuestionEs: "¿-L es SOCKS dinámico?",
    conceptQuestionEn: "Is -L dynamic SOCKS?",
    conceptKeywords: ["no"],
    explanationEs: "-L = un puerto. -D = SOCKS. Proxychains usa SOCKS. No mezcles los tres nombres.",
    hints: h("Quieres un puerto local hacia un servicio interno.", "SSH local forward.", "ssh -L", "ssh -L", "-L ≠ -D. -D es SOCKS."),
  },
  {
    id: "privesc-find-suid",
    category: "PrivEsc",
    subtopicId: "privesc-linux",
    fragment: "find / -perm -4000",
    toolAnswer: "find",
    toolQuestionEs: "¿Qué comando busca archivos con un modo de permiso concreto?",
    toolQuestionEn: "Which command searches files with a given permission mode?",
    paramQuestionEs: "Flag de permisos (concepto SUID):",
    paramQuestionEn: "Permission flag (SUID concept):",
    paramAnswer: "-perm",
    fullQuestionEs: "Busca SUID (concepto). Interpreta GTFOBins DESPUÉS.",
    fullQuestionEn: "Find SUID (concept). Interpret GTFOBins AFTER.",
    fullAnswer: "find / -perm -4000",
    conceptQuestionEs: "¿Un SUID es root automático?",
    conceptQuestionEn: "Is every SUID automatic root?",
    conceptKeywords: ["no"],
    explanationEs: "SUID es hipótesis. Hay que ver el binario y si es explotable. find no es LinPEAS.",
    hints: h("Permiso especial de ejecución como dueño.", "find con -perm.", "find / -perm -4000", "find / -perm -4000", "Luego identifica el binario. No copies un one-liner de un blog contra producción."),
  },
  {
    id: "report-evidence",
    category: "Reporting",
    subtopicId: "reporting",
    fragment: "evidence string",
    toolAnswer: "nota",
    toolQuestionEs: "¿Qué guardas en el informe eJPT-style: ensayo o valor exacto?",
    toolQuestionEn: "What do you store in an eJPT-style report: essay or exact value?",
    paramQuestionEs: "Escribe: valor",
    paramQuestionEn: "Write: valor",
    paramAnswer: "valor",
    fullQuestionEs: "El cuestionario pide un string. ¿Qué anotas?",
    fullQuestionEn: "The questionnaire asks for a string. What do you note?",
    fullAnswer: "valor exacto",
    conceptQuestionEs: "¿Un PDF de consultora sustituye el string?",
    conceptQuestionEn: "Does a consulting PDF replace the string?",
    conceptKeywords: ["no"],
    explanationEs: "Pregunta → evidencia → string. El relleno literario no puntúa.",
    hints: h("El examen pide datos, no narrativa.", "Copia el valor que viste.", "valor exacto", "valor exacto", "IP, hash, path, user. No un párrafo."),
  },
  {
    id: "exam-scope",
    category: "Exam",
    subtopicId: "exam-logistics",
    fragment: "scope CIDR",
    toolAnswer: "scope",
    toolQuestionEs: "¿Qué documento/regla define qué IPs puedes atacar?",
    toolQuestionEn: "What defines which IPs you may attack?",
    paramQuestionEs: "Palabra: alcance o scope",
    paramQuestionEn: "Word: scope",
    paramAnswer: "scope",
    fullQuestionEs: "Antes de nmap: ¿qué respetas?",
    fullQuestionEn: "Before nmap: what do you respect?",
    fullAnswer: "scope",
    conceptQuestionEs: "¿El Wi‑Fi de casa está en el scope del lab Host-Only?",
    conceptQuestionEn: "Is home Wi-Fi in Host-Only lab scope?",
    conceptKeywords: ["no"],
    explanationEs: "Alcance escrito. Host-Only ≠ LAN doméstica. Integridad > 'probar una tool'.",
    hints: h("Hay un CIDR autorizado.", "No es wlan0.", "scope", "scope", "Solo el brief / tu vboxnet."),
  },
  {
    id: "osint-whois",
    category: "OSINT",
    subtopicId: "passive-recon",
    fragment: "whois",
    toolAnswer: "whois",
    toolQuestionEs: "¿Qué consulta pública da registro de un dominio (concepto)?",
    toolQuestionEn: "Which public lookup gives domain registration (concept)?",
    paramQuestionEs: "Herramienta CLI típica:",
    paramQuestionEn: "Typical CLI tool:",
    paramAnswer: "whois",
    fullQuestionEs: "Consulta de registro de example.com (concepto, lab/autorizado).",
    fullQuestionEn: "Registration lookup for example.com (concept, authorized).",
    fullAnswer: "whois example.com",
    conceptQuestionEs: "¿WHOIS sustituye a nmap del lab?",
    conceptQuestionEn: "Does WHOIS replace lab nmap?",
    conceptKeywords: ["no"],
    explanationEs: "OSINT cambia estrategia (tecnología, rangos). No es el scan Host-Only.",
    hints: h("Información pública de dominio.", "whois", "whois example.com", "whois example.com", "Público ≠ autorización de ataque."),
  },
  {
    id: "exploit-lhost",
    category: "ExploitMod",
    subtopicId: "msf-lhost-lport",
    fragment: "LHOST",
    toolAnswer: "lhost",
    toolQuestionEs: "En un template de reverse, ¿qué variable es TU IP de atacante?",
    toolQuestionEn: "In a reverse template, which variable is YOUR attacker IP?",
    paramQuestionEs: "Nombre de la variable (LHOST):",
    paramQuestionEn: "Variable name (LHOST):",
    paramAnswer: "LHOST",
    fullQuestionEs: "Indica la variable de la IP de Kali en vboxnet.",
    fullQuestionEn: "Name the Kali vboxnet IP variable.",
    fullAnswer: "LHOST",
    conceptQuestionEs: "¿LHOST es la víctima?",
    conceptQuestionEn: "Is LHOST the victim?",
    conceptKeywords: ["no"],
    explanationEs: "LHOST = tú. RHOST/RHOSTS = objetivo. Copiar un PoC sin cambiar LHOST es el fallo clásico.",
    hints: h("Reverse: la víctima llama a ti.", "Local host.", "LHOST", "LHOST", "Mídelo con ip addr en vboxnet0. No copies un blog."),
  },
  {
    id: "chain-priority",
    category: "Chains",
    subtopicId: "full-chain",
    fragment: "enum before exploit",
    toolAnswer: "enum",
    toolQuestionEs: "Tras puertos open, ¿qué fase va ANTES de exploitation?",
    toolQuestionEn: "After open ports, which phase comes BEFORE exploitation?",
    paramQuestionEs: "Palabra: enum",
    paramQuestionEn: "Word: enum",
    paramAnswer: "enum",
    fullQuestionEs: "80 y 445 abiertos. ¿Primero?",
    fullQuestionEn: "80 and 445 open. First?",
    fullAnswer: "enum",
    conceptQuestionEs: "¿Exploits aleatorios son el siguiente paso?",
    conceptQuestionEn: "Are random exploits the next step?",
    conceptKeywords: ["no"],
    explanationEs: "Cadena: enum del servicio elegido. 80 y 445 son DOS superficies, no un único 'hack'.",
    hints: h("Tienes superficie, no un CVE.", "Enumerar.", "enum", "enum", "Elige una superficie, enumerala, luego hipótesis."),
  },
  {
    id: "msf-options",
    category: "Metasploit",
    subtopicId: "msf-options",
    fragment: "show options",
    toolAnswer: "show",
    toolQuestionEs: "En msfconsole, ¿qué comando lista opciones del módulo?",
    toolQuestionEn: "Which msfconsole command lists module options?",
    paramQuestionEs: "Subcomando: options",
    paramQuestionEn: "Subcommand: options",
    paramAnswer: "options",
    fullQuestionEs: "Ver RHOSTS/LHOST requeridos.",
    fullQuestionEn: "List required RHOSTS/LHOST.",
    fullAnswer: "show options",
    conceptQuestionEs: "¿run sin options es metodología?",
    conceptQuestionEn: "Is run without options methodology?",
    conceptKeywords: ["no"],
    explanationEs: "options son el examen. Un módulo sin LHOST de vboxnet no es 'el exploit falló'.",
    hints: h("Necesitas ver qué hay que setear.", "show …", "show options", "show options", "Luego set RHOSTS y LHOST reales."),
  },
  {
    id: "web-param",
    category: "Web",
    subtopicId: "web-sqli",
    fragment: "parameter",
    toolAnswer: "parametro",
    toolQuestionEs: "Sin ver un parámetro HTTP, ¿hay inyección obvia?",
    toolQuestionEn: "Without seeing an HTTP parameter, is injection obvious?",
    paramQuestionEs: "Escribe: no",
    paramQuestionEn: "Write: no",
    paramAnswer: "no",
    fullQuestionEs: "Primera evidencia para SQLi: ¿qué miras?",
    fullQuestionEn: "First SQLi evidence: what do you look at?",
    fullAnswer: "parametro",
    conceptQuestionEs: "¿sqlmap a ciegas contra / es el primer paso?",
    conceptQuestionEn: "Is blind sqlmap against / the first step?",
    conceptKeywords: ["no"],
    explanationEs: "Request → parámetro. Manual antes que la tool. 80 open ≠ SQLi.",
    hints: h("La inyección vive en un input.", "Query string, cookie, body.", "parametro", "parametro", "Si no hay param, no hay SQLi obvio."),
  },
];
