import { V6Skill } from "@/content/v6/types";

export const V6_SKILLS: V6Skill[] = [
  {
    id: "lab",
    titleEs: "Laboratorio VirtualBox",
    whyEs: "Campo de tiro aislado. Sin esto, todo lo demás es teoría o delito.",
    phaseId: "p0",
    prereqIds: [],
    subtopicIds: ["lab-vbox"],
    learnIds: ["ipv4"],
    lessonIds: ["c00-d1", "c00-d2", "c00-d3", "c00-d4", "c00-d6"],
    workshopIds: ["dvwa", "ms3"],
    trainHrefs: ["/laboratorio", "/focus/m0-w0-b1"],
    recallCategories: ["Lab"],
    boss: { titleEs: "Lab checkpoint", href: "/laboratorio" },
    difficulty: 2,
    track: "ejpt-prep",
  },
  {
    id: "networking",
    titleEs: "Networking",
    whyEs: "LHOST, CIDR y puertos deciden si el paquete llega. Open ≠ vulnerable.",
    phaseId: "p1",
    prereqIds: ["lab"],
    subtopicIds: ["net-basic", "net-mitm"],
    learnIds: ["ipv4", "cidr", "subnetting", "arp", "dns", "dhcp", "routing", "udp", "sockets", "protocols", "gateway"],
    lessonIds: ["c00-d2", "c01-d4", "c07-d2", "c07-d5"],
    workshopIds: ["wireshark", "scapy"],
    trainHrefs: ["/train/5min", "/learn/cidr"],
    recallCategories: ["Lab", "Nmap"],
    boss: { titleEs: "Networking boss", href: "/learn/cidr" },
    difficulty: 2,
    track: "ejpt-prep",
  },
  {
    id: "linux",
    titleEs: "Linux",
    whyEs: "La shell es el barrio. Denied, SUID y pipes son el idioma del loot.",
    phaseId: "p2",
    prereqIds: ["lab"],
    subtopicIds: ["linux-basic"],
    learnIds: ["linux-fs", "linux-users", "sudo", "processes", "cron", "linux-ssh", "env-path", "pipes-redir", "proc", "suid-caps"],
    lessonIds: ["c00-d5"],
    workshopIds: [],
    trainHrefs: ["/clase/c00-d5", "/focus/m0-w0-b6"],
    recallCategories: ["Lab"],
    boss: { titleEs: "Linux enum boss", href: "/clase/c00-d5" },
    difficulty: 2,
    track: "ejpt-prep",
  },
  {
    id: "recon",
    titleEs: "Reconnaissance",
    whyEs: "Activo vs pasivo, alcance, capas. Discovery no es versioning.",
    phaseId: "p3",
    prereqIds: ["lab", "networking"],
    subtopicIds: ["passive-recon", "nmap-basic"],
    learnIds: ["host-discovery", "attack-surface"],
    lessonIds: ["c01-d1", "c00-d4"],
    workshopIds: ["theharvester", "recon-ng"],
    trainHrefs: ["/train/whats-next"],
    recallCategories: ["Nmap"],
    boss: { titleEs: "Recon boss", href: "/clase/examen/w1" },
    difficulty: 2,
    track: "ejpt-prep",
  },
  {
    id: "nmap",
    titleEs: "Nmap",
    whyEs: "Cada flag responde una pregunta. Interpretar el output es la nota.",
    phaseId: "p3",
    prereqIds: ["recon", "networking"],
    subtopicIds: ["nmap-basic", "nmap-versioning", "nmap-scripts"],
    learnIds: ["port-scan", "banner-nse"],
    lessonIds: ["c01-d2", "c01-d3", "c01-d4", "c01-d5", "c01-d6"],
    workshopIds: ["nmap"],
    trainHrefs: ["/train/decisions", "/train/arcade/nmap-rush", "/memory"],
    recallCategories: ["Nmap"],
    boss: { titleEs: "Nmap interpretation", href: "/train/decisions" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "enumeration",
    titleEs: "Enumeration",
    whyEs: "El puerto manda la herramienta. Mezclar Gobuster/Hydra/enum4linux es el hueco clásico.",
    phaseId: "p4",
    prereqIds: ["nmap"],
    subtopicIds: ["tool-selection", "enum-dns-svc", "enum-snmp", "enum-smtp", "enum-db"],
    learnIds: ["enum-dns-svc", "enum-snmp", "enum-smtp", "enum-db"],
    lessonIds: ["c02-d5", "c02-d6"],
    workshopIds: ["hacktricks"],
    trainHrefs: ["/train/decisions", "/train/whats-next"],
    recallCategories: ["SMB", "Web", "Hydra"],
    boss: { titleEs: "Enum boss", href: "/train/decisions" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "smb",
    titleEs: "SMB",
    whyEs: "Shares y users son loot de fase 2. Gobuster no habla 445.",
    phaseId: "p4",
    prereqIds: ["enumeration"],
    subtopicIds: ["enum4linux", "smb-manual"],
    learnIds: [],
    lessonIds: ["c02-d1", "c02-d2"],
    workshopIds: ["enum4linux", "smbmap", "impacket"],
    trainHrefs: ["/train/10min"],
    recallCategories: ["SMB"],
    boss: { titleEs: "SMB enum", href: "/clase/c02-d2" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "http-enum",
    titleEs: "HTTP enumeration",
    whyEs: "Rutas, status codes, params. 403 existe. Sin 80/443 no hay Gobuster.",
    phaseId: "p4",
    prereqIds: ["enumeration"],
    subtopicIds: ["gobuster-dir"],
    learnIds: ["enum-http", "web-dirs"],
    lessonIds: ["c02-d3", "c05-d1"],
    workshopIds: ["gobuster", "ffuf", "dirsearch", "nikto"],
    trainHrefs: ["/train/arcade/port-hunt"],
    recallCategories: ["Web"],
    boss: { titleEs: "HTTP dirs", href: "/clase/c02-d3" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "ssh-ftp",
    titleEs: "SSH / FTP",
    whyEs: "Banner, anonymous, reutilización de creds. Hydra necesita user.",
    phaseId: "p4",
    prereqIds: ["enumeration"],
    subtopicIds: ["ftp-ssh-enum", "hydra-bruteforce"],
    learnIds: ["enum-ssh"],
    lessonIds: ["c02-d4", "c02-d6"],
    workshopIds: ["hydra", "ssh-audit"],
    trainHrefs: ["/train/15min"],
    recallCategories: ["Hydra"],
    boss: { titleEs: "FTP/SSH enum", href: "/clase/c02-d6" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "vuln",
    titleEs: "Vulnerability analysis",
    whyEs: "Identificar ≠ explotar. Versión cercana no es garantía.",
    phaseId: "p5",
    prereqIds: ["nmap", "enumeration"],
    subtopicIds: ["vuln-assessment"],
    learnIds: ["cve-select"],
    lessonIds: ["c04-d1"],
    workshopIds: ["exploitdb", "nuclei", "searchsploit-kali"],
    trainHrefs: ["/clase/c04-d1"],
    recallCategories: ["Nmap"],
    boss: { titleEs: "searchsploit match", href: "/clase/c04-d1" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "metasploit",
    titleEs: "Metasploit",
    whyEs: "search → options → LHOST vboxnet → session → sysinfo. Hueco declarado.",
    phaseId: "p6",
    prereqIds: ["vuln", "networking"],
    subtopicIds: ["msf-search-use", "msf-options", "msf-lhost-lport", "msf-sysinfo", "msf-hashdump", "msf-multihandler", "msfvenom"],
    learnIds: ["msf-flow", "payloads"],
    lessonIds: ["c03-d1", "c03-d2", "c03-d3", "c03-d4", "c03-d5", "c03-d6"],
    workshopIds: ["msf"],
    trainHrefs: ["/memory"],
    recallCategories: ["Metasploit", "Meterpreter"],
    boss: { titleEs: "MSF chain", href: "/clase/examen/w3" },
    difficulty: 4,
    track: "ejpt-prep",
  },
  {
    id: "exploitation",
    titleEs: "Exploitation",
    whyEs: "Reverse vs bind, match de SO, una cadena con evidencia.",
    phaseId: "p6",
    prereqIds: ["metasploit"],
    subtopicIds: ["exploit-linux", "exploit-windows", "reverse-vs-bind"],
    learnIds: ["manual-exploit"],
    lessonIds: ["c04-d2", "c04-d3", "c04-d4", "c04-d5", "c04-d6"],
    workshopIds: [],
    trainHrefs: ["/train/whats-next"],
    recallCategories: ["Metasploit"],
    boss: { titleEs: "Exploit boss", href: "/clase/examen/w4" },
    difficulty: 4,
    track: "ejpt-prep",
  },
  {
    id: "web",
    titleEs: "Web fundamentals",
    whyEs: "Request/response, cookies, authn vs authz. El resto de bugs vive aquí.",
    phaseId: "p7",
    prereqIds: ["http-enum"],
    subtopicIds: ["web-auth-bypass"],
    learnIds: ["http-basics", "cookies-sess", "authn-authz", "idor"],
    lessonIds: ["c05-d1", "c05-d5", "c06-d3", "c06-d4"],
    workshopIds: ["zap", "owasp-cheats"],
    trainHrefs: ["/learn/http-basics"],
    recallCategories: ["Web"],
    boss: { titleEs: "HTTP inspection", href: "/clase/c05-d1" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "sqli",
    titleEs: "SQL injection",
    whyEs: "Manual primero. sqlmap después. 80 open no implica SQLi.",
    phaseId: "p7",
    prereqIds: ["web"],
    subtopicIds: ["web-sqli"],
    learnIds: ["sqli"],
    lessonIds: ["c05-d2", "c05-d3", "c05-d6"],
    workshopIds: ["sqlmap", "payloads"],
    trainHrefs: ["/learn/sqli"],
    recallCategories: ["Web"],
    boss: { titleEs: "SQLi boss", href: "/clase/c05-d2" },
    difficulty: 4,
    track: "ejpt-prep",
  },
  {
    id: "xss",
    titleEs: "XSS",
    whyEs: "Corre en el navegador. Reflected / stored / DOM.",
    phaseId: "p7",
    prereqIds: ["web"],
    subtopicIds: ["web-xss"],
    learnIds: ["xss"],
    lessonIds: ["c05-d4"],
    workshopIds: [],
    trainHrefs: ["/learn/xss"],
    recallCategories: ["Web"],
    boss: { titleEs: "XSS tipos", href: "/clase/c05-d4" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "lfi",
    titleEs: "LFI / RFI",
    whyEs: "Include local vs remoto. passwd es el ping. LFI ≠ RCE.",
    phaseId: "p7",
    prereqIds: ["web"],
    subtopicIds: ["web-lfi-rfi"],
    learnIds: ["lfi", "upload-rce"],
    lessonIds: ["c06-d1", "c06-d2", "c06-d6"],
    workshopIds: ["commix"],
    trainHrefs: ["/learn/lfi"],
    recallCategories: ["Web"],
    boss: { titleEs: "LFI boss", href: "/clase/c06-d1" },
    difficulty: 4,
    track: "ejpt-prep",
  },
  {
    id: "privesc-linux",
    titleEs: "Privesc Linux",
    whyEs: "sudo -l, SUID, cron, PATH. LinPEAS clasifica; tú interpretas.",
    phaseId: "p8",
    prereqIds: ["linux", "exploitation"],
    subtopicIds: ["privesc-linux"],
    learnIds: ["privesc-linux-c", "suid-caps", "sudo", "cron"],
    lessonIds: ["c08-d1", "c08-d2", "c08-d5"],
    workshopIds: ["peass", "linenum", "gtfo"],
    trainHrefs: ["/learn/privesc-linux-c"],
    recallCategories: ["Lab"],
    boss: { titleEs: "Linux privesc", href: "/clase/examen/w8" },
    difficulty: 4,
    track: "ejpt-prep",
  },
  {
    id: "privesc-windows",
    titleEs: "Privesc Windows",
    whyEs: "Modelo mental si no hay VM Windows. No el PC de la familia.",
    phaseId: "p8",
    prereqIds: ["exploitation"],
    subtopicIds: ["privesc-windows"],
    learnIds: ["win-users", "win-ps", "win-smb-privesc"],
    lessonIds: ["c08-d3"],
    workshopIds: ["lolbas", "netexec", "bloodhound"],
    trainHrefs: ["/learn/win-users"],
    recallCategories: [],
    boss: { titleEs: "Windows modelo", href: "/clase/c08-d3" },
    difficulty: 4,
    track: "red-team-foundation",
  },
  {
    id: "post",
    titleEs: "Post-exploitation",
    whyEs: "sysinfo, loot, hashes. Qué información cambia el next step.",
    phaseId: "p9",
    prereqIds: ["exploitation"],
    subtopicIds: ["post-exploit-loot", "msf-sysinfo"],
    learnIds: ["shell-stab", "loot-creds", "post-net"],
    lessonIds: ["c03-d5", "c08-d4", "c08-d6"],
    workshopIds: ["john", "hashcat", "cyberchef"],
    trainHrefs: ["/clase/c08-d4"],
    recallCategories: ["Meterpreter"],
    boss: { titleEs: "Loot format", href: "/clase/c08-d4" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "pivoting",
    titleEs: "Pivoting",
    whyEs: "Otra red que Kali no ve. Forward/SOCKS. Una NIC ≠ pivot.",
    phaseId: "p10",
    prereqIds: ["networking", "post"],
    subtopicIds: ["net-pivoting"],
    learnIds: ["portfwd", "socks-proxy", "multi-net", "routing"],
    lessonIds: ["c07-d1", "c07-d2", "c07-d3", "c07-d4", "c07-d5", "c07-d6"],
    workshopIds: ["internal-all", "bettercap", "responder"],
    trainHrefs: ["/learn/portfwd"],
    recallCategories: [],
    boss: { titleEs: "Pivot boss", href: "/clase/examen/w7" },
    difficulty: 4,
    track: "red-team-foundation",
  },
  {
    id: "chains",
    titleEs: "Attack chains",
    whyEs: "Método bajo reloj. 80 y 445 juntos: una superficie, luego la otra.",
    phaseId: "p11",
    prereqIds: ["nmap", "enumeration", "exploitation", "web"],
    subtopicIds: ["full-chain"],
    learnIds: ["attack-surface"],
    lessonIds: ["c09-d1", "c09-d2", "c09-d3", "c09-d4", "c09-d5", "c09-d6", "c12-d5"],
    workshopIds: ["ippsec"],
    trainHrefs: ["/train/whats-next", "/simulacro/reasoning"],
    recallCategories: [],
    boss: { titleEs: "Chain timed", href: "/clase/c09-d1" },
    difficulty: 5,
    track: "ejpt-prep",
  },
  {
    id: "reporting",
    titleEs: "Reporting",
    whyEs: "Pregunta → evidencia → string exacto. eJPT no es un ensayo.",
    phaseId: "p12",
    prereqIds: ["chains"],
    subtopicIds: ["reporting"],
    learnIds: [],
    lessonIds: ["c10-d1", "c10-d2", "c10-d3", "c10-d4", "c10-d5", "c10-d6"],
    workshopIds: ["cyberchef"],
    trainHrefs: ["/clase/examen/w10"],
    recallCategories: [],
    boss: { titleEs: "Reporting exam", href: "/clase/examen/w10" },
    difficulty: 3,
    track: "ejpt-prep",
  },
  {
    id: "exam-prep",
    titleEs: "Preparación eJPT (interna)",
    whyEs: "Mocks de academia y logística. No es el criterio oficial de INE.",
    phaseId: "p13",
    prereqIds: ["reporting", "chains"],
    subtopicIds: ["exam-logistics"],
    learnIds: [],
    lessonIds: ["c06-d5", "c11-d1", "c11-d2", "c11-d3", "c11-d4", "c11-d5", "c11-d6", "c12-d1", "c12-d2", "c12-d3", "c12-d4", "c12-d5", "c12-d6"],
    workshopIds: ["ejpt-angelist", "ejpt-neil", "ejpt-dragkob"],
    trainHrefs: ["/simulacro", "/simulacro/full"],
    recallCategories: [],
    boss: { titleEs: "Mock interno", href: "/simulacro/full" },
    difficulty: 5,
    track: "ejpt-prep",
  },
];

export function getSkill(id: string) {
  return V6_SKILLS.find((s) => s.id === id);
}

export function skillBySubtopic(subtopicId: string) {
  return V6_SKILLS.find((s) => s.subtopicIds.includes(subtopicId));
}

export function skillsRequiring(skillId: string) {
  return V6_SKILLS.filter((s) => s.prereqIds.includes(skillId));
}

/** Talleres no listados en un skill: se asignan por id de herramienta. */
const WORKSHOP_FALLBACK: Record<string, string> = {
  nmap: "nmap",
  msf: "metasploit",
  gobuster: "http-enum",
  hydra: "enumeration",
  enum4linux: "smb",
  sqlmap: "sqli",
  seclists: "http-enum",
  peass: "privesc-linux",
  linenum: "privesc-linux",
  dvwa: "web",
  ms3: "lab",
  ffuf: "http-enum",
  httpx: "http-enum",
  nuclei: "vuln",
  impacket: "smb",
  john: "post",
  hashcat: "post",
  gtfo: "privesc-linux",
  lolbas: "privesc-windows",
  payloads: "web",
  hacktricks: "enumeration",
  "awesome-pt": "enumeration",
  "secret-knowledge": "networking",
  "owasp-cheats": "web",
  ippsec: "chains",
  exploitdb: "vuln",
  nikto: "vuln",
  zap: "web",
  wireshark: "networking",
  scapy: "networking",
  responder: "privesc-windows",
  bettercap: "networking",
  theharvester: "recon",
  "ssh-audit": "ssh-ftp",
  commix: "lfi",
  wfuzz: "http-enum",
  fuzzdb: "web",
  cyberchef: "post",
  netexec: "smb",
  bloodhound: "privesc-windows",
  "internal-all": "pivoting",
  "cheatsheets-coreb1t": "exam-prep",
  "searchsploit-kali": "vuln",
  dirsearch: "http-enum",
  smbmap: "smb",
  "recon-ng": "recon",
  "ejpt-angelist": "exam-prep",
  "ejpt-neil": "exam-prep",
  "ejpt-dragkob": "exam-prep",
};

export function skillForWorkshop(workshopId: string) {
  return V6_SKILLS.find((s) => s.workshopIds.includes(workshopId)) ?? getSkill(WORKSHOP_FALLBACK[workshopId] ?? "");
}

export function skillForLearn(learnId: string) {
  return V6_SKILLS.find((s) => s.learnIds.includes(learnId));
}

export function skillForLesson(lessonId: string) {
  return V6_SKILLS.find((s) => s.lessonIds.includes(lessonId));
}
