import { lesson, Q, S } from "@/content/course/helper";

export const W01 = [
  lesson(
    "c01-d1",
    1,
    1,
    "RECON",
    "Recon activo vs pasivo y el alcance",
    15,
    "passive-recon",
    [
      S("Pasivo", "No envías paquetes al target: whois, registros públicos, lo que el brief ya te dio. En eJPT el peso es bajo frente al lab, pero existe: nombres, rangos escritos. No es 'hackear Google'."),
      S("Activo", "Tocas el objetivo: ICMP, TCP, UDP. nmap es activo. Solo dentro del CIDR autorizado. El lab Host-Only es tu sandbox; el examen, el VPN de INE."),
      S("Capas", "Discovery de hosts ≠ scan de puertos ≠ detección de versión ≠ NSE. Cada flag responde una pregunta. Saltar a exploits es fallar el método, no 'ir más rápido'."),
      S("Notas", "El examen pide valores exactos. Si no anotas IPs y puertos, repetirás scans y perderás reloj. Un bloc > memoria heroica."),
    ],
    [
      Q("Nmap es…", ["Pasivo", "Activo", "Un exploit", "DHCP"], 1, "Envía paquetes."),
      Q("¿El primer movimiento en un rango nuevo?", ["Hydra", "Host discovery / leer el brief", "XSS", "hashdump"], 1, "¿Quién está vivo?"),
      Q("¿OSINT sustituye nmap en eJPT lab?", ["Sí", "No", "Solo ARP", "Solo si /16"], 1, "Lab = activo autorizado."),
      Q("Escanear 192.168.1.0/24 de casa…", ["Es eJPT", "No está en tu alcance de lab", "Es Host-Only", "Es DVWA"], 1, "Otra red."),
      Q("Anotar IPs sirve para…", ["Decoración", "No repetir trabajo y responder preguntas exactas", "LHOST mágico", "Bridged"], 1, "Evidence."),
    ],
    "Brief de tu lab",
    ["Escribe CIDR, IPs conocidas, regla de no-WiFi-casa", "No lances herramientas nuevas hoy si el discovery de semana 0 falló"],
    "Método antes de herramientas. Eso es eJPT."
  ),
  lesson(
    "c01-d2",
    1,
    2,
    "NMAP",
    "Puertos: default vs -p- vs lista",
    16,
    "nmap-basic",
    [
      S("Default", "Sin -p, nmap cubre los 1000 puertos más comunes, no los 65535. Un servicio en 31337 no aparecerá. En eJPT, si el brief huele a puerto alto, -p- o -p 1-65535 (más lento)."),
      S("Tiempo", "-p- en un /24 entero te come el examen. Primero hosts vivos, luego 1000, luego -p- en el RHOST que importa."),
      S("TCP vs UDP", "El scan típico es TCP. SNMP (161/udp) y DNS (53/udp) no salen igual. -sU es otro mundo: lento, ruidoso; úsalo cuando el brief o un 161 lo pida."),
      S("Estados", "open = hay servicio. closed = responde rechazo. filtered = no sabes (drop/firewall). open ≠ vulnerable."),
    ],
    [
      Q("Nmap sin -p cubre…", ["Todos los puertos", "Los 1000 más comunes (típico)", "Solo 80", "Solo UDP"], 1, "Top 1000."),
      Q("-p- significa…", ["Ping only", "Todos los puertos TCP (lento)", "NSE", "Versión"], 1, "Full port TCP."),
      Q("161/udp es típico de…", ["HTTP", "SNMP", "SMB", "SSH"], 1, "SNMP."),
      Q("open quiere decir…", ["Root", "Hay algo escuchando", "CVE confirmado", "Hydra listo"], 1, "Puerta, no exploit."),
      Q("¿-p- primero en /16 del examen?", ["Sí", "No: vivos, luego foco", "Solo UDP", "Solo -sn"], 1, "Reloj."),
    ],
    "Un port scan al guest",
    ["nmap -sV <RHOST> (1000). Guarda output", "Si tienes tiempo de lab: nmap -p- --min-rate razonable SOLO a ese RHOST"],
    "Un puerto oculto es una pregunta del examen que casi se te escapa."
  ),
  lesson(
    "c01-d3",
    1,
    3,
    "NMAP",
    "-sV y banners: versioning",
    16,
    "nmap-versioning",
    [
      S("Por qué versión", "searchsploit y Metasploit viven de producto+versión. '80 open http' no elige módulo. 'Apache 2.2.8' sí acota. -sV habla con el servicio."),
      S("-sC", "Scripts default NSE (descubrimiento). Complementa -sV. No es un exploit pack. Lee el output: usuarios, http-title, ssh-hostkey."),
      S("Falsos", "Un banner puede mentir. Igual es tu mejor pista. Confirma en enum (smb, http)."),
      S("Combinar", "nmap -sV -sC -oN notas.txt <RHOST>. El -oN es evidencia para ti, no para INE como archivo, pero te salva el reloj."),
    ],
    [
      Q("-sV detecta…", ["Solo hosts", "Versión de servicios", "Hashes SAM", "XSS"], 1, "Version detection."),
      Q("¿open http basta para elegir exploit?", ["Sí", "No: quieres versión/tecnología", "Sí si es 80", "Sí con Hydra"], 1, "Enum primero."),
      Q("-sC es…", ["Crash del target", "Scripts NSE por defecto", "UDP full", "Bridged"], 1, "Default scripts."),
      Q("-oN sirve para…", ["Explotar", "Guardar output en archivo", "LHOST", "Pivot"], 1, "Notas."),
      Q("Banner vs verdad", ["Siempre 100% fiel", "Pista fuerte, a veces mentira", "Inútil", "Solo UDP"], 1, "Confirma."),
    ],
    "Version scan al guest",
    ["nmap -sV -sC -oN ~/lab/ms2-sv.txt <RHOST>", "Resalta 3 versiones que podrías buscar luego (sin explotar todavía si vas por el plan)"],
    "La versión es el puente entre nmap y el módulo."
  ),
  lesson(
    "c01-d4",
    1,
    4,
    "NMAP",
    "TCP handshake, -sS y -sT",
    15,
    "nmap-basic",
    [
      S("TCP", "SYN, SYN-ACK, ACK. Los servicios eJPT típicos (22,80,445,21) son TCP. Reverse shells también."),
      S("-sS", "SYN scan: no completa el handshake. Rápido, necesita raw sockets (root). En Kali local suele ser el default."),
      S("-sT", "Connect scan: handshake completo. Si no eres root o hay restricción, aparece. Más ruidoso en logs."),
      S("ICMP", "Ping no prueba el 80. Host down en -sn tampoco niega un puerto filtrado distinto. Interpreta, no asumas."),
    ],
    [
      Q("Handshake TCP tiene…", ["Dos pasos", "SYN / SYN-ACK / ACK", "Solo ACK", "ARP"], 1, "Tres vías."),
      Q("-sS es…", ["UDP", "SYN scan", "Gobuster", "Hydra"], 1, "Half-open."),
      Q("Ping OK implica HTTP up", ["Sí", "No", "Solo en /24", "Solo MS2"], 1, "ICMP ≠ TCP/80."),
      Q("-sT completa…", ["El handshake TCP", "AXFR", "SMB null", "XSS"], 0, "Connect scan: conexión completa."),
      Q("¿filtered significa vulnerable?", ["Sí", "No: no tienes respuesta útil", "Sí si 445", "Sí si -sS"], 1, "No sabes."),
    ],
    "Observar tipos de scan",
    ["Compara tiempo: nmap -sT -p 22,80,445 <RHOST> vs default", "Anota si algún puerto cambia de estado"],
    "El paquete que envías cambia lo que ves. Eso es oficio, no magia."
  ),
  lesson(
    "c01-d5",
    1,
    5,
    "NMAP",
    "NSE: cuándo y cuándo no",
    15,
    "nmap-scripts",
    [
      S("NSE", "Scripts Lua: vuln, auth, discovery, brute. Categoría vuln no es un pase de INE: puede ser ruidosa o crash. En lab, --script=safe o default (-sC) primero."),
      S("smb-enum*", "Familia útil cuando 445 está open. Sigue siendo enum, no shell."),
      S("No sustituye", "Gobuster no es NSE http. Hydra no es NSE brute obligatorio. Elige la herramienta de la familia del puerto."),
      S("eJPT", "Te pueden preguntar interpretación, no que memorices 400 script names. Entiende categorías y un ejemplo smb/http."),
    ],
    [
      Q("NSE corre…", ["Solo exploits kernel", "Scripts sobre servicios detectados", "Solo ARP", "Solo UDP"], 1, "Scripts."),
      Q("¿--script vuln lo primero siempre?", ["Sí", "No: default/safe y enum primero", "Sí en examen", "Sí sin -sV"], 1, "Ruido."),
      Q("445 open → familia NSE razonable", ["http-enum", "smb-* / enum SMB", "dns-axfr", "snmp-brute ya"], 1, "Puerto manda."),
      Q("NSE brute vs Hydra", ["Son el mismo binario", "Misma idea (creds), distinta herramienta; no las mezcles a ciegas", "NSE es Gobuster", "Hydra es -sV"], 1, "Familia creds."),
      Q("¿NSE te da root solo?", ["Sí", "No", "En /24 sí", "Si -A"], 1, "Enum/info."),
    ],
    "Un script default ya lo corriste con -sC; lee el archivo",
    ["Relee http-title / smb de tu -sC", "No lances vuln masivo hoy"],
    "Scripts son lupa, no dinamita."
  ),
  lesson(
    "c01-d6",
    1,
    6,
    "NMAP",
    "Leer un output como en el examen",
    16,
    "nmap-basic",
    [
      S("Prioridad", "FTP 21 (anon?), HTTP 80 (dirs), SMB 139/445 (users/shares), SSH 22 (creds más tarde). No Hydra al primer open."),
      S("Sin versión", "Si el output de práctica no tiene VERSION, tu siguiente movimiento puede ser -sV, no msf."),
      S("Varios open", "No es un único vector. Anota tres superficies. Elige UNA para enum profundo (TDAH: una)."),
      S("Cierre semana", "Skill: interpretar. El examen no te abraza si memorizaste flags y no sabes qué hacer con 445 open."),
    ],
    [
      Q("445 open, siguiente familia", ["Gobuster", "SMB enum (enum4linux/smbclient)", "sqlmap", "XSS"], 1, "SMB."),
      Q("80 open, siguiente familia", ["enum4linux", "HTTP (curl/Gobuster)", "hashdump", "ARP spoof"], 1, "Web."),
      Q("22 open sin usuario", ["Hydra ya", "Banner/enum users en otros servicios primero", "pivot", "LFI"], 1, "No brute ciego."),
      Q("¿Exploits aleatorios tras nmap sin -sV?", ["Buena idea", "Mala metodología", "Obligatorio eJPT", "Solo FTP"], 1, "Identifica primero."),
      Q("Una misión TDAH significa…", ["5 exploits", "Un servicio a enumerar ahora", "Todo el /16", "Bridged"], 1, "Uno."),
    ],
    "Informe de 8 líneas",
    ["De tu nmap real: lista puertos, 1 prioridad, 1 herramienta, 1 cosa que NO harás (Hydra ciego / Bridged / casa)"],
    "Interpretar es la nota. Escanear es el medio."
  ),
];
