import { lesson, Q, S } from "@/content/course/helper";

export const W02 = [
  lesson(
    "c02-d1",
    2,
    1,
    "ENUM",
    "SMB: qué es y por qué eJPT lo ama",
    16,
    "enum4linux",
    [
      S("Puerto", "139/tcp netbios-ssn y 445/tcp microsoft-ds. No es HTTP. Gobuster no lista shares. SMB habla de discos, a veces usuarios y políticas."),
      S("Null session", "Sin password, a veces el servidor igual lista. En MS2 clásico hay jugo. Primero enum, luego (si acaso) un módulo Samba que coincida con -sV."),
      S("Users", "Nombres de usuario son munición para SSH/Hydra. Por eso SMB suele ir ANTES que brute a 22."),
      S("Herramientas", "enum4linux -a, smbclient -L, smbmap. Elige una y termínala. No abras tres y las dejes a medias (TDAH)."),
    ],
    [
      Q("445 es familia…", ["HTTP", "SMB", "DNS", "SNMP"], 1, "SMB."),
      Q("Gobuster contra 445…", ["Correcto", "Incorrecto: herramienta web", "Igual que smbclient", "Es -sV"], 1, "Puerto manda."),
      Q("Usuarios SMB sirven para…", ["XSS", "Posible brute SSH/otros logins", "LHOST", "AXFR"], 1, "Creds con nombre."),
      Q("¿Exploit Samba de memoria sin versión?", ["Sí", "No: enum + versión primero", "Sí en eJPT siempre", "Sí si 139"], 1, "Método."),
      Q("enum4linux es…", ["Dirbust web", "Enum SMB/Unix-like", "Handler msf", "sqlmap"], 1, "SMB."),
    ],
    "enum4linux a TU guest",
    ["enum4linux -a <RHOST> | tee ~/lab/smb.txt", "Anota users y shares. No lances Hydra todavía"],
    "Shares y users son loot de fase 2. Trátalos como oro."
  ),
  lesson(
    "c02-d2",
    2,
    2,
    "ENUM",
    "smbclient y smbmap (manos)",
    15,
    "smb-manual",
    [
      S("smbclient -L", "Lista shares. //RHOST/share para entrar. Anonymous o guest a veces basta. Comandos ftp-like: ls, get, cd."),
      S("smbmap", "Vista rápida de permisos READ/WRITE. WRITE en un share puede ser vector de drop (lab). No lo hagas en redes ajenas."),
      S("Archivos", "txt, scripts, backups. El examen pregunta contenidos. get + leer > presumir que 'hay un share'."),
      S("Windows vs MS2", "En Windows el modelo de usuarios es otro (Mes 2-3). Hoy Linux-like MS2. No mezcles hashdump SAM aquí."),
    ],
    [
      Q("smbclient -L lista…", ["Rutas HTTP", "Shares SMB", "NSE", "Rutas CIDR"], 1, "Shares."),
      Q("¿get en smbclient?", ["Ping", "Descarga un archivo del share", "Hydra", "Pivot"], 1, "Loot."),
      Q("hashdump SAM en MS2 Linux", ["Correcto", "Incorrecto: eso es Windows", "Obligatorio", "Es -sV"], 1, "SO distinto."),
      Q("Share WRITE en lab…", ["Ataca el router de casa", "Puede ser vector; solo tu VM", "Siempre ilegal", "Es Gobuster"], 1, "Autorizado."),
      Q("Una herramienta a fondo vs tres a medias", ["Tres", "Una y termina (TDAH)", "Ninguna", "Solo msf"], 1, "Cierre."),
    ],
    "Entra a un share",
    ["smbclient -L //<RHOST> -N  (o con user que enumeraste)", "Si hay share accesible: ls y get de un fichero de texto"],
    "Manos en el share. Eso no lo da un PDF."
  ),
  lesson(
    "c02-d3",
    2,
    3,
    "WEB",
    "Gobuster: directorios, no passwords",
    16,
    "gobuster-dir",
    [
      S("Qué brute-forcea", "Rutas y archivos HTTP(S). Wordlist + URL base. Status 200, 301, 403 importan. 403 = existe."),
      S("Qué NO", "No adivina SSH. No habla SMB. Si no hay 80/443, Gobuster no es el siguiente paso."),
      S("Wordlist", "dirb common, seclists. En examen no inventes una wordlist de 80 millones si el reloj duele: común + extensiones (.php)."),
      S("vhost/dns", "Hay modos. Hoy dir. Si el título HTTP es un vhost distinto, anótalo para más adelante."),
    ],
    [
      Q("Gobuster dir va contra…", ["445", "HTTP(S) rutas", "22 sin URL", "161/udp"], 1, "Web."),
      Q("403 en Gobuster", ["No existe", "Existe, acceso prohibido", "Host down", "Igual 404"], 1, "Hallazgo."),
      Q("¿Gobuster con solo 22 open?", ["Sí", "No hay HTTP", "Sí si -x php", "Sí con -N"], 1, "Puerto."),
      Q("Wordlist enorme en examen", ["Siempre mejor", "Puede comerse el reloj; empieza razonable", "Obligatorio", "Sustituye nmap"], 1, "Tiempo."),
      Q("200 vs 404", ["Da igual", "200 se sirve; 404 el servidor dice que no está", "404 es root", "200 es SMB"], 1, "Códigos."),
    ],
    "Gobuster a http del guest",
    ["gobuster dir -u http://<RHOST>/ -w /usr/share/wordlists/dirb/common.txt", "Anota 200 y 403. Abre los 200 en el navegador del lab"],
    "Una ruta oculta vale más que diez exploits de memoria."
  ),
  lesson(
    "c02-d4",
    2,
    4,
    "CREDS",
    "Hydra: brute de login, no de dirs",
    16,
    "hydra-bruteforce",
    [
      S("Qué necesita", "Servicio de autenticación (ssh, ftp, http-post-form…) + usuario o lista + wordlist. Sin usuario, estás adivinando dos ejes: malo para el reloj y para el guest."),
      S("Cuándo", "Tras enum que te dio un nombre (SMB, web, ftp banner). Lockouts existen: en lab MS2 a veces no, en examen sé conservador."),
      S("No es Gobuster", "Si lo mezclas, es el hueco que declaraste. Puerto 80 sin form ≠ Hydra. Puerto 22 sin user ≠ Hydra primero."),
      S("Ética", "Solo lab/examen. Hydra contra el SSH de un amigo no es práctica eJPT."),
    ],
    [
      Q("Hydra brute-forcea…", ["Directorios web", "Credenciales de un servicio", "CIDR", "ARP"], 1, "Logins."),
      Q("22 open, cero users", ["Hydra ya", "Enum users primero (p. ej. SMB)", "Gobuster 22", "sqlmap"], 1, "Nombre primero."),
      Q("Gobuster vs Hydra", ["Iguales", "Rutas HTTP vs passwords de servicio", "Ambos SMB", "Ambos NSE"], 1, "Familias."),
      Q("¿Hydra al router de casa?", ["Sí", "No", "Si olvidaste el wifi", "Si es /24"], 1, "No autorizado."),
      Q("http-form Hydra requiere…", ["Solo 80 open", "Un formulario/login real", "445", "LHOST"], 1, "Superficie de login."),
    ],
    "NO lances Hydra a ciegas; prepara insumos",
    ["Del SMB de ayer, copia 1 username", "Escribe (no ejecutes si no hay user) cómo sería hydra ssh con ESE user y rockyou recortada en lab"],
    "La disciplina de no brute-ciego te va a salvar el examen."
  ),
  lesson(
    "c02-d5",
    2,
    5,
    "ENUM",
    "Tabla: Gobuster vs Hydra vs enum4linux",
    18,
    "tool-selection",
    [
      S("Regla de oro", "El puerto y el protocolo eligen la herramienta, no tu herramienta favorita. 445→SMB. 80→web dirs. 22/21 con USER→Hydra. Si dudas, enum más, brute menos."),
      S("Errores clásicos", "Gobuster a 445. Hydra a 80 sin login. enum4linux a http://. msfsearch antes de leer nmap."),
      S("Orden razonable", "nmap → priorizar superficie → UNA herramienta de esa familia → anotar → siguiente superficie. No paralelices cinco brutes."),
      S("Examen", "Te pondrán un output y 'what next'. La respuesta es metodología, no el binario más cool de Twitter."),
    ],
    [
      Q("80 open, sin form, primero", ["Hydra ssh", "Gobuster/curl", "enum4linux", "hashdump"], 1, "HTTP."),
      Q("445 open primero", ["Gobuster", "enum4linux/smbclient", "sqlmap", "AXFR"], 1, "SMB."),
      Q("Users de SMB + 22", ["Gobuster", "Hydra ssh puede entrar en cola", "LFI", "ARP"], 1, "Creds con nombre."),
      Q("¿La herramienta favorita manda?", ["Sí", "No: el servicio manda", "Sí en eJPT", "Sí si Kali"], 1, "Puerto."),
      Q("Cinco brutes en paralelo", ["Óptimo TDAH", "Malo: ruido y cero cierre", "Obligatorio", "Sustituye nmap"], 1, "Una misión."),
    ],
    "Decision drill en papel",
    ["Dado: 21,22,80,445 open. Escribe 1-2-3 prioridad y herramienta. Compara con TRAIN/decisions"],
    "Esta tabla ES tu hueco. Cada acierto aquí vale una semana de YouTube."
  ),
  lesson(
    "c02-d6",
    2,
    6,
    "ENUM",
    "FTP y SSH: banners, anon, keys",
    15,
    "ftp-ssh-enum",
    [
      S("FTP 21", "Banner + anonymous. ls/get. No es SMB. Si anon OK, loot. Si no, user de SMB a veces reutiliza."),
      S("SSH 22", "Banner de versión (OpenSSH x.y). Auth por password o key. Hydra solo con user. No es dirbust."),
      S("Reutilización", "Password de FTP en SSH es clásico de lab. Prueba ordenada, no 50 combinaciones mentales sin anotar."),
      S("Cierre", "Semana 2 = elegir herramienta. Si aún mezclas Gobuster/Hydra, repite d5 mañana, no pases de largo."),
    ],
    [
      Q("FTP anonymous es…", ["NSE kernel", "Login ftp sin password / user anonymous", "Gobuster", "Pivot"], 1, "Anon."),
      Q("SSH banner te da…", ["Root", "Pista de versión", "Shares", "Cookies"], 1, "Versión."),
      Q("¿Gobuster a 22?", ["Sí", "No", "Con -x php", "Con -N"], 1, "No HTTP."),
      Q("Reusar password FTP→SSH en lab", ["Nunca se da", "A menudo merece una prueba ordenada", "Es Bridged", "Es LFI"], 1, "Labs clásicos."),
      Q("Si mezclas las tres tools…", ["Estás listo INE", "Repite la tabla d5", "Instala más tools", "Bridged"], 1, "Hueco declarado."),
    ],
    "FTP al guest",
    ["ftp <RHOST> prueba anonymous", "Si entra: ls. Si no: anota el banner y sigue"],
    "Tres protocolos, tres familias. Ya no son 'comandos sueltos'."
  ),
];
