import { lesson, Q, S } from "@/content/course/helper";

export const W03 = [
  lesson(
    "c03-d1",
    3,
    1,
    "MSF",
    "msfconsole: search y use",
    16,
    "msf-search-use",
    [
      S("Qué es", "Metasploit es un marco: exploits, payloads, auxiliaries, post. No es 'el botón de eJPT'. Primero nmap+enum. Luego search con producto y versión."),
      S("search", "search vsftpd, search type:exploit apache. Lee rank, date, targets. Un resultado no es una orden de ejecución."),
      S("use", "use exploit/... carga el módulo. info lee descripción. Si el target no coincide (Windows vs Linux), no es tu módulo."),
      S("Auxiliary", "scanners y brute dentro de msf. Siguen siendo enum. No sustituyen enum4linux por deporte, pero existen."),
    ],
    [
      Q("Antes de search…", ["Hydra a /16", "Identificar servicio+versión", "XSS", "Bridged"], 1, "Datos."),
      Q("use hace…", ["Scan /24", "Carga un módulo", "Snapshot", "AXFR"], 1, "Cargar."),
      Q("¿Un search = explotado?", ["Sí", "No: hay que set y comprobar opciones", "Sí si rank excellent", "Sí en Linux"], 1, "Faltan options."),
      Q("Auxiliary es típico de…", ["Solo payloads", "Scanners/brute, no necesariamente shell", "Solo pivot", "Solo SAM"], 1, "No shell."),
      Q("Módulo Windows vs MS2 Linux", ["Da igual", "El target SO debe coincidir", "mfs corrige solo", "Usa Gobuster"], 1, "Match."),
    ],
    "Entrar a msfconsole",
    ["msfconsole, search vsftpd (o el banner que TÚ tengas)", "info de UN módulo. No exploits todavía si quieres seguir el ritmo; o explota SOLO MS2 Host-Only"],
    "search es biblioteca. Tú eres el bibliotecario."
  ),
  lesson(
    "c03-d2",
    3,
    2,
    "MSF",
    "show options, set, RHOSTS",
    16,
    "msf-options",
    [
      S("show options", "Required vs optional. RHOSTS casi siempre. RPORT a veces. Si required está vacío, run va a fallar o a hacer el ridículo."),
      S("set", "set RHOSTS <guest>. set RPORT si no es el default. show options otra vez. Paranoia barata."),
      S("check", "Algunos módulos tienen check. No todos. Un check verde no es sesión."),
      S("Errores", "RHOSTS=127.0.0.1. RHOSTS=LHOST. RHOSTS=IP de wlan0. Todos clásicos."),
    ],
    [
      Q("RHOSTS es…", ["Kali", "La(s) víctima(s)", "VPN de casa", "8.8.8.8"], 1, "Remote."),
      Q("Required vacío…", ["Da igual", "No corras todavía", "Mejor", "Es LHOST"], 1, "Rellena."),
      Q("check equivale a shell", ["Sí", "No", "En vsftpd sí", "Si rank great"], 1, "Check ≠ session."),
      Q("RHOSTS=127.0.0.1 hacia MS2", ["Correcto", "Incorrecto", "Default bueno", "Igual vboxnet"], 1, "Loopback."),
      Q("Tras set…", ["Salir", "show options de nuevo", "Bridged", "Gobuster"], 1, "Verifica."),
    ],
    "Configurar sin disparar (o disparar en lab)",
    ["use un módulo que coincida con TU -sV", "set RHOSTS, show options. Screenshot mental: todo required lleno"],
    "Las options son el examen. El exploit es el teatro."
  ),
  lesson(
    "c03-d3",
    3,
    3,
    "MSF",
    "LHOST, LPORT y la flecha reverse",
    18,
    "msf-lhost-lport",
    [
      S("Reverse", "La víctima inicia TCP a LHOST:LPORT. LHOST = IP de Kali en vboxnet (ip addr), no wlan0, no 127.0.0.1, no un número de un PDF de 2018."),
      S("LPORT", "Puerto donde TÚ escuchas. Que no esté ocupado. 4444 es costumbre, no magia. Si el brief/firewall del examen bloquea, cambia."),
      S("Bind", "La víctima escucha; tú conectas a RHOST:puerto. LHOST importa menos. En NAT de examen, reverse suele ser más feliz."),
      S("Handler", "exploit/multi/handler + mismo payload. Si el exploit 'gana' y 0 sessions: flecha, payload mismatch, o LHOST."),
    ],
    [
      Q("En reverse, ¿quién inicia TCP?", ["Kali siempre", "La víctima hacia LHOST:LPORT", "Nmap", "DHCP"], 1, "Víctima llama."),
      Q("LHOST en Host-Only", ["wlan0", "IP Kali vboxnet", "1.1.1.1", "Guest IP"], 1, "Medir."),
      Q("0 sessions con exploit 'ok'", ["Culpa de INE", "Revisa LHOST/payload/listener", "Instala Windows", "Bridged ya"], 1, "Flecha."),
      Q("Bind vs reverse", ["Iguales", "Quién escucha cambia", "Bind necesita Gobuster", "Reverse es UDP"], 1, "Flecha."),
      Q("LPORT", ["Puerto de SMB", "Donde escuchas tú", "Siempre 80", "CIDR"], 1, "Listener."),
    ],
    "Dibuja la flecha",
    ["Papel: Kali IP, guest IP, flecha reverse", "ip addr confirma LHOST. set LHOST esa IP en un handler de prueba (lab)"],
    "Este era tu hueco. Cada reverse que nace es un voto de confianza."
  ),
  lesson(
    "c03-d4",
    3,
    4,
    "MSF",
    "payloads y multi/handler",
    16,
    "msf-multihandler",
    [
      S("Payload", "Qué código corre tras el exploit: meterpreter vs shell, reverse vs bind, tcp vs http (concepto). Debe coincidir con el handler."),
      S("set payload", "A veces el default vale. Si cambias exploit, revisa payload. Windows payload a Linux = teatro."),
      S("Handler primero", "En reverse, el listener debe estar UP antes de que la víctima llame. Orden: handler → exploit. O el módulo lanza ambos; igual entiende el orden lógico."),
      S("msfvenom", "Genera binarios/payloads. En eJPT aparece. LHOST/LPORT iguales que el handler. No lo dispares a Internet."),
    ],
    [
      Q("Payload y handler deben…", ["Ser distintos siempre", "Coincidir", "Usar Gobuster", "Ser UDP"], 1, "Match."),
      Q("Listener reverse se pone…", ["Después de que falle", "Antes de que la víctima llame", "En wlan0 solo", "En MS2"], 1, "Orden."),
      Q("Payload Windows a MS2 Linux", ["Ideal", "Malo", "Default eJPT", "Es -sV"], 1, "SO."),
      Q("msfvenom sirve para…", ["Dirbust", "Generar payload", "DHCP", "AXFR"], 1, "Generar."),
      Q("¿Meterpreter es obligatorio siempre?", ["Sí", "No: a veces shell basta", "Sí en FTP", "Sí sin LHOST"], 1, "Contexto."),
    ],
    "Handler en lab",
    ["use exploit/multi/handler, set payload compatible, set LHOST vboxnet, exploit -j", "No apuntes el payload a nada fuera del lab"],
    "Handler listo = menos '¿por qué no hay session?'."
  ),
  lesson(
    "c03-d5",
    3,
    5,
    "MSF",
    "Post mínimo: sysinfo, getuid, shell",
    15,
    "msf-sysinfo",
    [
      S("Session", "sessions -i N. getuid / sysinfo / sysinfo en meterpreter. En shell: whoami, id, uname -a, hostname."),
      S("Evidence", "El examen quiere un valor, no tu ego. Copia usuario y SO. hashdump es Windows; no lo esperes en MS2 Linux igual que en un DC."),
      S("Estabilizar", "python pty, script, stty — conceptos. Una shell cruda se muere con Ctrl+C. Practica en lab, no en el primer minuto del examen."),
      S("Privesc", "Si ya eres root, documenta y para. Si eres msfadmin, entonces enum de privesc (semana 8), no kernel roulette."),
    ],
    [
      Q("Primera pregunta post-ex", ["¿XSS?", "¿Quién soy / qué SO?", "¿Hydra?", "¿Bridged?"], 1, "Identidad."),
      Q("hashdump en Linux MS2", ["Igual que SAM", "No es el mismo mundo que Windows SAM", "Obligatorio", "Es Gobuster"], 1, "SO."),
      Q("Ya eres root", ["Kernel exploit igual", "Evidencia y para si el objetivo está", "Pivot a casa", "Hydra"], 1, "Reloj."),
      Q("sysinfo es…", ["NSE", "SO/arquitectura en meterpreter", "DHCP", "Wordlist"], 1, "Post."),
      Q("Ctrl+C en shell cruda", ["Siempre seguro", "Puede matar la sesión", "Setea LHOST", "Abre 445"], 1, "Estabiliza."),
    ],
    "Si tienes sesión en MS2",
    ["whoami / getuid, uname o sysinfo, anota", "Si no tienes sesión aún: no te adelantes; cierra options y LHOST primero"],
    "Post-ex es contestar el cuestionario, no coleccionar shells."
  ),
  lesson(
    "c03-d6",
    3,
    6,
    "MSF",
    "Flujo completo search→set→run (lab)",
    18,
    "msf-search-use",
    [
      S("Cadena", "nmap -sV → coincidencia → search → use → set RHOSTS/LHOST → payload → run → sysinfo. Si saltas un eslabón, debug ese eslabón, no 'otro CVE'."),
      S("vsftpd 2.3.4", "Clásico MS2. Si tu versión no es esa, NO fuerces el módulo. El examen te premiará el match, no el meme."),
      S("Fallo", "Checklist: red, LHOST, RHOSTS, payload, puerto ocupado, VM hung. Snapshot."),
      S("Cierre Mes 1 msf", "Repite el flujo de memoria en TRAIN 5 min. El hueco se cierra con repetición, no con un vídeo de 2 horas."),
    ],
    [
      Q("Si el módulo no coincide con -sV…", ["run igual", "No lo uses", "Bridged", "Hydra"], 1, "Match."),
      Q("Orden útil", ["run → nmap", "Identificar → search → set → run → post", "Hydra → nmap", "XSS → SMB"], 1, "Flujo."),
      Q("Puerto LPORT ocupado", ["Da igual", "Cambia LPORT o mata el proceso", "Cambia RHOSTS a 8.8.8.8", "Gobuster"], 1, "Listener."),
      Q("Memorizar un solo CVE para todo eJPT", ["Estrategia", "Mala: cada box es un match", "Oficial INE", "Sustituye enum"], 1, "Método."),
      Q("¿Vídeo de 2h cierra el hueco?", ["Sí", "No: repetición del flujo en lab", "Sí si 4K", "Sí con racha"], 1, "Práctica."),
    ],
    "Una cadena en MS2 Host-Only",
    ["Ejecuta el flujo completo UNA vez contra TU guest (autorizado)", "Escribe los set que usaste (LHOST medido)"],
    "Una cadena real. Eso no te lo quita nadie el día del examen."
  ),
];
