import { lesson, Q, S } from "@/content/course/helper";

export const W04 = [
  lesson(
    "c04-d1",
    4,
    1,
    "VULN",
    "De versión a CVE: searchsploit",
    15,
    "vuln-assessment",
    [
      S("Identificar ≠ explotar", "Tienes producto+versión. searchsploit 'vsftpd 2.3.4'. Lee, no copies el primer .c a Internet. En lab, prefiere módulo msf que coincida o exploit que entiendas."),
      S("Nessus", "Concepto: scanner de vulns. eJPT puede mencionar hallazgos. No sustituye tu cerebro ni tu nmap."),
      S("False positives", "Un CVE en una versión cercana no es 'run'. Confirmas servicio real."),
      S("Notas", "Guarda el nombre del exploit y por qué lo elegiste. El examen pregunta el porqué implícito en el resultado."),
    ],
    [
      Q("searchsploit busca…", ["Shares", "Exploits públicos por keyword/versión", "DHCP", "Wordlists HTTP"], 1, "Exploit-DB."),
      Q("¿Primer .c de Internet en el examen?", ["Siempre", "Peligro: entiende o usa flujo msf conocido en lab", "Obligatorio", "Es Gobuster"], 1, "Control."),
      Q("Versión cercana ≠", ["Pista", "Garantía de exploit", "LHOST", "CIDR"], 1, "Confirma."),
      Q("Nessus es…", ["Un payload", "Scanner de vulnerabilidades (concepto)", "Host-Only", "DVWA"], 1, "Scanner."),
      Q("Identificar es paso…", ["Después de root", "Antes de explotar", "Inútil", "Solo Windows"], 1, "Cadena."),
    ],
    "searchsploit con TU banner",
    ["searchsploit '<producto> <versión>' de tu -sV", "Anota 1 candidato y si hay módulo msf. No ataques fuera del lab"],
    "Elegir con versión es madurez. Google a ciegas no."
  ),
  lesson(
    "c04-d2",
    4,
    2,
    "EXPLOIT",
    "Explotación Linux de servicio (concepto + lab MS2)",
    16,
    "exploit-linux",
    [
      S("Servicio", "Un daemon (ftp, samba, distcc…) con bug. No es LFI todavía. El vector es el puerto que enumeraste."),
      S("Manual vs msf", "Manual: entiendes el trigger. msf: velocidad si el módulo es el correcto. eJPT admite ambos; el reloj ama claridad."),
      S("Estabilidad", "Un exploit puede tirar el servicio. Snapshot. No lances 8 módulos seguidos al mismo puerto."),
      S("Éxito", "Sesión o prueba de concepto en lab. Luego post. No celebres el 'Exploit completed' sin getuid."),
    ],
    [
      Q("Vector típico Mes 1", ["XSS stored de banco", "Servicio vulnerable en puerto open", "ARP a casa", "AXFR Google"], 1, "Servicio."),
      Q("8 módulos seguidos", ["Pro", "Puede tumbar el lab; uno y observa", "Obligatorio", "Sustituye -sV"], 1, "Cuidado."),
      Q("Exploit completed sin session", ["Aprobado", "No es initial access todavía", "Root", "Pivot"], 1, "Verifica."),
      Q("Snapshot sirve…", ["De adorno", "Si el servicio muere", "Como LHOST", "Como wordlist"], 1, "Lab."),
      Q("Manual vs msf", ["Guerra religiosa", "Elige el que controlas y coincide", "Solo manual eJPT", "Solo msf INE"], 1, "Control."),
    ],
    "Un exploit en MS2 (Host-Only)",
    ["Un solo vector que coincida. Listener listo. Anota getuid", "Si falla: checklist LHOST, no cambies a Bridged"],
    "Initial access es un hito. Respira. Luego notas."
  ),
  lesson(
    "c04-d3",
    4,
    3,
    "EXPLOIT",
    "Reverse vs bind (fijación)",
    15,
    "reverse-vs-bind",
    [
      S("Dibujo", "Reverse: víctima → tú. Bind: tú → puerto nuevo en víctima. NAT/firewall del examen suele querer reverse."),
      S("nc", "nc -lvnp LPORT espera reverse. nc RHOST PORT conecta a bind. nc -e no es universal en Debian/Kali moderno."),
      S("Fallos", "Listener después. LHOST wlan0. Payload bind con cabeza reverse."),
      S("Práctica", "Aunque MS2 Host-Only permita ambos, el examen te preguntará la flecha."),
    ],
    [
      Q("Reverse: ¿quién llama?", ["Atacante al bind", "Víctima a LHOST:LPORT", "DHCP", "Gobuster"], 1, "Víctima."),
      Q("nc -lvnp es típico de…", ["Cliente bind", "Listener reverse", "SMB", "SQL"], 1, "Escucha."),
      Q("nc -e en todos los Linux", ["Sí universal", "No", "Solo /24", "Solo UDP"], 1, "No asumas."),
      Q("NAT del examen favorece…", ["Bind siempre", "A menudo reverse", "ARP spoof casa", "Bridged"], 1, "Salida de la víctima."),
      Q("LHOST en bind", ["Siempre crítico igual que reverse", "Menos crítico que en reverse", "Es RHOSTS", "Es CIDR"], 1, "Tú inicias."),
    ],
    "Ensayo mental 60s",
    ["Sin PC: explica reverse a voz alta", "Con PC: un listener nc en vboxnet (lab) aunque no lo conectes aún"],
    "Si la flecha está clara, Metasploit deja de ser brujería."
  ),
  lesson(
    "c04-d4",
    4,
    4,
    "WINDOWS",
    "Explotación Windows (concepto eJPT)",
    15,
    "exploit-windows",
    [
      S("Diferencias", "Usuarios, SMB más 'nativo', PowerShell, SAM/hashes, a menudo meterpreter windows. No trates un DC como MS2."),
      S("SMB Windows", "Shares, eternas vulns históricas (lab). Enum igual: smbclient/crackmapexec conceptos. Alcance."),
      S("Payload", "windows/meterpreter/reverse_tcp ≠ linux/x86. El mismatch es el error #1."),
      S("Este plan", "Si no tienes VM Windows vulnerable Host-Only, estudia el concepto y practica Linux. No ataques PCs de la familia."),
    ],
    [
      Q("Payload linux a Windows", ["Perfecto", "Incorrecto", "Default", "Es -sC"], 1, "SO."),
      Q("SAM/hashes viven en…", ["MS2 passwd igual", "Mundo Windows (concepto)", "Gobuster", "DNS"], 1, "Windows."),
      Q("¿Atacas el laptop de un familiar?", ["Sí es LAN", "No", "Si es /24", "Si olvidó password"], 1, "Alcance."),
      Q("Enum SMB en Windows…", ["Inútil", "Sigue siendo prioridad si 445 open", "Solo Gobuster", "Solo XSS"], 1, "445."),
      Q("PowerShell es…", ["Solo Linux", "Shell/admin en Windows (concepto)", "Nmap", "DVWA"], 1, "Windows."),
    ],
    "Mapa conceptual Windows",
    ["Escribe 5 diferencias Linux vs Windows para eJPT", "Si tienes VM Windows de lab: nmap -sV Host-Only. Si no: no inventes un target"],
    "Concepto hoy. Lab Windows solo si es TU VM."
  ),
  lesson(
    "c04-d5",
    4,
    5,
    "CADENA",
    "Mes 1 integrado: de nmap a evidencia",
    18,
    "full-chain",
    [
      S("Historia", "Discovery → puertos → versiones → enum (SMB/HTTP/FTP) → match → exploit → whoami → notas. Si cuentas otra historia, estás improvisando."),
      S("TDAH", "Un box, un vector. MS2 tiene muchos: no los colecciones todos el mismo día."),
      S("Skill-check", "Esta semana el plan tiene checkpoint. Úsalo. Fallar aquí es barato; en INE no."),
      S("Huecos", "Si Gobuster/Hydra aún bailan, TRAIN decisions + clase c02-d5 otra vez."),
    ],
    [
      Q("Paso 1 de la historia", ["Exploit", "Recon/discovery", "hashdump", "XSS"], 1, "Recon."),
      Q("Coleccionar 9 shells MS2 en un día", ["Óptimo TDAH", "Ruido; cierra una cadena con notas", "Oficial", "Sustituye examen"], 1, "Cierre."),
      Q("Fallar skill-check de semana", ["Fin del plan", "Remedia el subtema y sigue", "Bridged", "Borra progreso"], 1, "Ciclo."),
      Q("Evidence es…", ["Sentir que eres hacker", "Valores anotados (user, archivo, versión)", "Más CVE", "Hydra"], 1, "Examen."),
      Q("¿Saltar enum porque 'ya sé msf'?", ["Sí", "No", "En /24 sí", "Si racha 7"], 1, "Método."),
    ],
    "Cadena cronometrada 45 min",
    ["Timer. MS2. Una cadena. Parar. Escribir evidencias", "No abras YouTube a mitad"],
    "Mes 1 no pide perfección. Pide una historia repetible."
  ),
  lesson(
    "c04-d6",
    4,
    6,
    "CADENA",
    "Cierre Mes 1 y puente a web",
    15,
    "full-chain",
    [
      S("Qué ya eres", "Alguien que mide LHOST, elige herramienta por puerto, y no brute-ciego. Eso es más que 50 POCs."),
      S("Mes 2", "HTTP de verdad: params, SQLi, XSS, LFI. DVWA local. No dejes morir el lab de MS2: lo usarás en cadenas."),
      S("Simulacros", "Aún no el full 15q si el plan lo pone en semana 6. Esta semana: examen de curso + skill-check del plan."),
      S("Descanso", "Día 7: paseo. El cerebro consolida. No 'un nmap más' a las 2am si estás frito."),
    ],
    [
      Q("Mes 2 enfatiza…", ["Solo ARP casa", "Web (DVWA) + luego red/privesc", "Borrar Kali", "Bridged MS2"], 1, "Web."),
      Q("¿Dejas morir MS2?", ["Sí", "No: sigue siendo campo de cadenas", "Sí tras Hydra", "Sí si 403"], 1, "Lab."),
      Q("Estudiar frito a las 2am", ["Siempre útil", "A menudo inútil; descansa", "Obligatorio eJPT", "Sube racha más"], 1, "TDAH."),
      Q("Elegir tool por puerto", ["Ya no importa", "Sigue importando todo el trimestre", "Solo Mes 1", "Solo Windows"], 1, "Siempre."),
      Q("Esta web vs INE", ["Son lo mismo", "Aquí entrenas; INE certifica", "Racha 90 = diploma", "64 fichas = aprobado"], 1, "Honestidad."),
    ],
    "Lista de 5 cosas que ya haces sin Google",
    ["Escríbelas. Si no llegas a 5, repite semanas 2-3, no huyas a SQLi"],
    "Puente. No quemes la etapa. El examen es un método, no un meme de SQLi."
  ),
];
