import { lesson, Q, S } from "@/content/course/helper";

function W(
  id: string,
  week: number,
  day: number,
  track: string,
  titleEs: string,
  minutes: number,
  sub: string,
  a: string,
  b: string,
  c: string,
  d: string,
  quiz: ReturnType<typeof Q>[],
  labT: string,
  lab: string[],
  pep: string
) {
  return lesson(id, week, day, track, titleEs, minutes, sub, [S("Qué", a), S("Por qué eJPT", b), S("Cómo en lab", c), S("Error típico", d)], quiz, labT, lab, pep);
}

export const W05 = [
  W("c05-d1", 5, 1, "WEB", "HTTP de pentester: métodos, status, params", 16, "gobuster-dir",
    "HTTP es petición/respuesta. GET lleva params en la URL. POST en el cuerpo. Cookies viajan en headers. Status 200/301/302/401/403/404/500 cambian tu siguiente movimiento.",
    "Casi todo el Mes 2 y mucho eJPT web es leer una petición. Si no ves el parámetro, no hay SQLi ni LFI.",
    "Burp o las DevTools del navegador contra DVWA localhost. Intercepta un login. Anota método y campos. No apuntes Burp a Internet.",
    "Tratar 403 como 404. Ignorar cookies de sesión. Fuzzear sin ver el request.",
    [Q("GET vs POST", ["Iguales siempre", "Dónde viajan los datos cambia", "POST es SMB", "GET es Hydra"], 1, "Método."), Q("401 sugiere…", ["Share SMB", "Falta autenticación", "UDP", "Root"], 1, "Authn."), Q("Sin parámetro visible…", ["SQLi seguro", "Aún no hay inyección obvia", "Pivot", "LHOST"], 1, "Enum web."), Q("DVWA se ataca en…", ["Wi‑Fi ajena", "localhost autorizado", "8.8.8.8", "Bridged casa"], 1, "Local."), Q("500 puede indicar…", ["Éxito root", "Error de servidor (pista de inyección a veces)", "Host-Only caído", "ARP"], 1, "Error.")],
    "Intercepta 1 request DVWA", ["Abre DVWA local security low", "Anota URL, método, parámetros de 1 formulario"], "Si ves el request, ya eres más pentester web que quien solo lanza sqlmap."),
  W("c05-d2", 5, 2, "WEB", "SQL injection: detección manual", 18, "web-sqli",
    "La app concatena input en SQL. Una comilla ' rompe la sintaxis (error o comportamiento raro). Boolean (OR 1=1) cambia el resultado. UNION necesita número de columnas.",
    "eJPT espera que sepas detectar y extraer algo (versión, users) en un lab tipo DVWA, no un paper de 2010.",
    "DVWA SQLi low: prueba ' en id. ORDER BY n. UNION SELECT. Solo ese laboratorio.",
    "sqlmap a ciegas contra un host que no es tuyo. O pensar que 80 open = SQLi.",
    [Q("80 open implica SQLi", ["Sí", "No", "Si es PHP", "Si 443 closed"], 1, "Hace falta param."), Q("Una comilla sirve para…", ["LHOST", "Romper SQL y detectar", "SMB", "NSE"], 1, "Detección."), Q("UNION necesita…", ["Hydra", "Saber columnas visibles", "Bridged", "IPv6"], 1, "Columnas."), Q("¿Practicar SQLi en la web del banco?", ["Sí", "No", "Si es /24", "Si hay racha"], 1, "Ilegal."), Q("information_schema sirve para…", ["ARP", "Metadatos de tablas/columnas (MySQL)", "Gobuster", "SAM"], 1, "Enum SQL.")],
    "DVWA SQLi low", ["Rompe con '", "Llega a extraer @@version o equivalente en el lab"], "Manual primero. sqlmap después. Ese orden te aprueba más que el inverso."),
  W("c05-d3", 5, 3, "WEB", "sqlmap: flags que sí importan", 15, "web-sqli",
    "sqlmap -u URL --dbs / -D db --tables / -T t --dump. --cookie si hay sesión. --batch para no pulsar y. --level/--risk suben agresividad (lab).",
    "En examen puede ahorrar tiempo SI ya viste el parámetro. Sin entender el request, sqlmap es un palo de ciego.",
    "Apunta sqlmap SOLO a DVWA local. Copia la URL con el param id.",
    "Olvidar cookie y decir 'no es injectable'. O --dump de una BD enorme y quedarte sin reloj.",
    [Q("--dbs lista…", ["Shares", "Bases de datos", "Puertos UDP", "Users Linux"], 1, "DBs."), Q("Sesión login requiere…", ["Nada", "A menudo --cookie", "LHOST", "SMB"], 1, "Cookie."), Q("¿sqlmap a un sitio random?", ["OK", "No", "Si HTTP", "Si MySQL"], 1, "Alcance."), Q("--dump hace…", ["Nmap", "Vuelca datos de tabla", "Pivot", "Hydra"], 1, "Dump."), Q("¿sqlmap sustituye ver el request?", ["Sí", "No", "En eJPT oficial sí", "Si --risk 3"], 1, "Entiende.")],
    "sqlmap a DVWA", ["Una URL local con id=", "--dbs y para. No dumps masivos innecesarios"], "Automatizar sin entender es suspender con estilo."),
  W("c05-d4", 5, 4, "WEB", "XSS: reflected vs stored vs DOM (concepto)", 16, "web-xss",
    "XSS ejecuta JS en el navegador de la víctima. Reflected: el payload vuelve en esa respuesta. Stored: se guarda y pega a otros. DOM: el JS de la página concatena inseguro.",
    "eJPT: identificar tipo y un payload de prueba en DVWA, no montar un botnet. Cookie theft es concepto; no robes sesiones ajenas.",
    "DVWA XSS reflected/stored low. Un alert(1) de laboratorio. Observa si persiste.",
    "Confundir XSS con SQLi. O lanzar payloads a un foro real.",
    [Q("XSS corre en…", ["El kernel", "El navegador", "vboxnet", "SNMP"], 1, "Browser."), Q("Stored vs reflected", ["Iguales", "Stored persiste; reflected en esa request", "Stored es SMB", "Reflected es LFI"], 1, "Persistencia."), Q("alert(1) en DVWA sirve para…", ["Root", "Probar ejecución JS en lab", "Hydra", "AXFR"], 1, "PoC lab."), Q("¿XSS a usuarios reales de Internet?", ["Práctica eJPT", "No", "Si es HTTP", "Si stored"], 1, "Ilegal."), Q("Cookie de sesión + XSS es…", ["LHOST", "Concepto de robo de sesión (lab)", "Nmap", "CIDR"], 1, "Impacto.")],
    "DVWA XSS low", ["Reflected: prueba un payload de lab", "Stored: observa si otro 'usuario' lo vería (concepto)"], "JS en el browser no es SQL en el servidor. Sepáralos."),
  W("c05-d5", 5, 5, "WEB", "Cookies, sesión, authn vs authz", 15, "web-auth-bypass",
    "Authn: quién eres (login). Authz: qué puedes (admin vs user). Cookie de sesión es un ticket. IDOR: cambiar id=1 a id=2 y ver datos ajenos.",
    "Muchos 'bypasses' eJPT son authz rota o cookies predecibles, no magia JWT de congreso.",
    "DVWA / apps locales: login, mira Cookie, prueba un id de otro objeto si el ejercicio lo trae.",
    "Pensar que 403 se 'bypassea' siempre con un header de blog. O brute login sin user.",
    [Q("Authn es…", ["Qué puedes hacer", "Quién eres", "CIDR", "SUID"], 1, "Identidad."), Q("Authz es…", ["Handshake TCP", "Permisos tras identificar", "Solo SMB", "Solo NSE"], 1, "Autorización."), Q("IDOR típico", ["Cambiar LHOST", "Cambiar un id de objeto", "nmap -sn", "Hydra /16"], 1, "Referencia insegura."), Q("Cookie sirve para…", ["ARP", "Mantener sesión HTTP", "Versión kernel", "Wordlist"], 1, "Sesión."), Q("403 siempre se bypass", ["Sí", "No: a veces es authz real", "Si Gobuster", "Si XSS"], 1, "No recetas.")],
    "Cookie en DevTools", ["Login DVWA, copia el nombre de la cookie (no la compartas)", "Cierra sesión y mira qué pasa si falta"], "Login ≠ poder. El examen ama esa diferencia."),
  W("c05-d6", 5, 6, "WEB", "Cierre SQLi/XSS: qué entra al simulacro", 15, "web-sqli",
    "Del banco de preguntas: detección, UNION conceptual, sqlmap --dbs, tipos XSS, 403 vs 404. Practica marcar, no solo leer.",
    "Semana 6 traerá LFI y el primer simulacro completo del plan. No llegues sin haber tocado DVWA.",
    "Repite 10 preguntas del examen de esta semana hasta 80% interno.",
    "Ver 4 horas de XSS y cero clics. El simulacro no perdona eso.",
    [Q("UNION es de…", ["XSS", "SQLi", "ARP", "SSH"], 1, "SQL."), Q("Tipos XSS a distinguir", ["TCP/UDP", "Reflected/stored/DOM", "SYN/ACK", "GET only"], 1, "Tres."), Q("¿Simulacro se aprueba leyendo?", ["Sí", "No: hay que marcar bajo tiempo", "Si racha 30", "Si 64 fichas"], 1, "Examen."), Q("DVWA security low es para…", ["Producción", "Aprender el bug sin WAF", "Casa Bridged", "INE live"], 1, "Lab."), Q("sqlmap --dbs vs --dump", ["Iguales", "Listar DBs vs volcar tabla", "Ambos nmap", "Ambos XSS"], 1, "Flags.")],
    "Mini simulacro mental", ["5 preguntas de esta semana en papel, 5 minutos", "Las que falles: relee d2-d4"], "Marcar bien bajo reloj es una skill aparte. Entrénela."),
];

export const W06 = [
  W("c06-d1", 6, 1, "WEB", "LFI: path traversal y /etc/passwd", 16, "web-lfi-rfi",
    "La app incluye ficheros locales según un parámetro (page=). ../ sube directorios. /etc/passwd es el ping de LFI en Linux.",
    "eJPT: leer archivos, a veces logs. No es RCE hasta que hay un paso extra (wrappers, logs) y solo en lab.",
    "DVWA File Inclusion low. page=../../../../etc/passwd. Encoding si filtra.",
    "LFI contra un CMS de Internet. O confundir LFI con SQLi.",
    [Q("LFI lee…", ["Solo JS del browser", "Archivos del servidor", "SMB only", "UDP"], 1, "Local files."), Q("/etc/passwd en LFI es…", ["Root garantizado", "Prueba de lectura Linux", "SAM", "Gobuster"], 1, "PoC."), Q("../ hace…", ["SQL UNION", "Subir en el árbol de dirs", "Hydra", "SYN"], 1, "Traversal."), Q("¿LFI = RCE siempre?", ["Sí", "No, hace falta más", "En /24 sí", "Si 80"], 1, "Separar."), Q("Filtro de ../ a veces se gana con…", ["Bridged", "Encoding / wrappers (lab)", "ARP casa", "msf hashdump"], 1, "Bypass lab.")],
    "DVWA LFI", ["Lee /etc/passwd", "Anota cuántos ../ necesitaste"], "Si lees passwd, entendiste inclusión. El resto es variación."),
  W("c06-d2", 6, 2, "WEB", "RFI y wrappers (concepto, lab only)", 15, "web-lfi-rfi",
    "RFI incluye un recurso remoto si allow_url_include y el param acepta URL. php://filter puede leer fuente. Son técnicas de lab DVWA/allow, no recetas para la web ajena.",
    "Saber el nombre y el riesgo basta para muchas preguntas. Ejecutar solo en DVWA.",
    "Si DVWA RFI está cerrado, no fuerces php.ini. Lee la teoría y sigue.",
    "Bajar un webshell a un host que no es tuyo 'para probar RFI'.",
    [Q("RFI implica…", ["Solo /etc/passwd", "Incluir recurso remoto (si está permitido)", "SMB null", "CIDR"], 1, "Remote."), Q("php://filter sirve para…", ["Nmap", "Leer/transformar streams PHP (lab)", "Hydra", "ARP"], 1, "Wrapper."), Q("allow_url_include off…", ["RFI fácil", "RFI a menudo muerto", "Siempre RCE", "LHOST"], 1, "Config."), Q("¿Webshell en terceros?", ["eJPT", "Ilegal", "Si HTTP", "Si racha"], 1, "No."), Q("LFI vs RFI", ["Igual", "Local vs remoto", "TCP vs UDP", "GET vs ARP"], 1, "Origen.")],
    "Concepto en notas", ["Escribe 4 líneas LFI vs RFI", "No busques RFI en Internet live"], "Nombres claros. Manos solo en DVWA."),
  W("c06-d3", 6, 3, "WEB", "Auth bypass clásicos (lab)", 15, "web-auth-bypass",
    "SQL en el login (' OR '1'='1), cookies default, default creds (admin/admin), IDOR a panel. Cada uno es un bug distinto. No los mezcles en la cabeza.",
    "eJPT web: prueba ordenada en DVWA brute/login. Default creds también en apps de lab (MS2 web).",
    "DVWA brute y login. Observa el POST. No Hydra todavía si puedes SQLi de login en low.",
    "OR 1=1 en un login de producción ajeno. O 50 creds a mano sin anotar.",
    [Q("SQLi en login es…", ["LFI", "Auth bypass posible", "SMB", "NSE"], 1, "Bypass."), Q("admin/admin en lab…", ["Nunca", "A veces el primer try razonable", "Solo INE", "Solo UDP"], 1, "Defaults."), Q("IDOR al panel", ["Cambiar LPORT", "Acceder objeto/función de otro rol", "nmap -sn", "searchsploit"], 1, "Authz."), Q("¿OR 1=1 en el banco?", ["Lab eJPT", "No", "Si WAF off", "Si GET"], 1, "Ilegal."), Q("Brute web necesita…", ["Solo 80", "Form + user/wordlist o lógica SQLi", "445", "vboxnet DHCP"], 1, "Superficie.")],
    "DVWA login", ["Una técnica: SQLi low O brute controlado", "Anota cuál usaste y por qué no la otra"], "Un bypass, una nota. No una sopa de payloads."),
  W("c06-d4", 6, 4, "WEB", "Upload y command injection (concepto)", 16, "web-auth-bypass",
    "Upload: el servidor guarda un fichero. Si ejecuta PHP/ASP que subiste, RCE. Extensiones, content-type, path. Command injection: input a un shell del SO (; | &&).",
    "eJPT: reconocer el patrón. Practicar solo DVWA. No subas shells a Internet.",
    "DVWA command injection / upload si está en tu pack. Payload de lab mínimo para ver el eco de un comando.",
    "Confundir command injection con SQLi. O webshell a un WordPress ajeno.",
    [Q("Command injection pega en…", ["Solo SQL", "El SO vía shell", "Solo ARP", "Solo cookies"], 1, "OS."), Q("Upload peligroso cuando…", ["Es un txt leído", "El servidor ejecuta lo subido", "Es 404", "Es SMB 445"], 1, "Ejecución."), Q("; en un param de ping…", ["CIDR", "Puede encadenar comandos (lab)", "LHOST", "Gobuster"], 1, "Encadenar."), Q("¿Webshell a terceros?", ["Sí", "No", "Si PHP", "Si 80"], 1, "No."), Q("SQLi vs command injection", ["Iguales", "SQL vs OS shell", "Ambos NSE", "Ambos SMB"], 1, "Capa.")],
    "DVWA command injection low", ["Un comando inofensivo de lab (id / whoami) si el ejercicio lo permite", "No encadenes destructivo (rm)"], "El eco de whoami en una web es RCE. Trátalo con respeto."),
  W("c06-d5", 6, 5, "EXAM", "Simulacro #1 del plan: cómo sentarlo", 16, "exam-logistics",
    "15 preguntas, 20 min, 70% interno de la app. Acumulativo hasta semana 6. Inglés en prompts. No es el examen INE: es el gimnasio.",
    "Fallar aquí es el punto: remedia subtema, no 'otra box random'. Cooldown si full fail el mismo día.",
    "EXAM en la nav. Full simulacro cuando el plan lo abra. Ambiente: timer, sin Discord.",
    "Hacerlo con 40 pestañas. O repetir hasta memorizar las 15 de ese sorteo (el banco es más grande).",
    [Q("Umbral interno full", ["10%", "70% en esta app", "100%", "INE oficial 70 idéntico siempre"], 1, "Interno 70."), Q("Idioma de prompts", ["Solo ES", "EN + apoyo ES", "Latín", "Binario"], 1, "Examen real EN."), Q("Al fallar un subtema", ["Saltas Mes 3", "Remedias ese ID", "Borras lab", "Bridged"], 1, "Ciclo."), Q("¿Este simulacro es INE?", ["Sí", "No", "Si 90%", "Si racha"], 1, "Gimnasio."), Q("20 minutos enseñan…", ["LHOST", "Gestión de reloj", "SMB only", "XSS stored"], 1, "Tiempo.")],
    "Simulacro o skill-check", ["Una pasada cronometrada esta semana", "Lista los 3 subtemas flojos"], "El reloj es un enemigo entrenable. Hoy le haces sparring."),
  W("c06-d6", 6, 6, "WEB", "Cierre web Mes 2a", 14, "web-lfi-rfi",
    "Ya tocas SQLi, XSS, LFI, bypass. El resto del Mes 2 es red y privesc. No abandones DVWA: 20 min semanales de mantenimiento.",
    "Preguntas mezcladas: el examen no avisa el tema. Por eso el banco aleatorio.",
    "Examen de curso semana 6. Luego un descanso real.",
    "Creer que web ya está porque alert(1) una vez.",
    [Q("Mantener DVWA sirve para…", ["Nada", "No olvidar params bajo reloj", "Bridged", "SAM"], 1, "Retención."), Q("El examen avisa el tema", ["Sí", "No", "Siempre web", "Siempre SMB"], 1, "Mezcla."), Q("LFI se parece más a…", ["Hydra ssh", "Incluir ficheros", "enum4linux", "DHCP"], 1, "Include."), Q("¿Web cerrada para siempre?", ["Sí tras d4", "No: vuelve en cadenas Mes 3", "Sí si 70%", "Sí si XSS"], 1, "Vuelve."), Q("Descanso post simulacro", ["Debilidad", "Consolidación", "Borrar Kali", "NAT only"], 1, "TDAH.")],
    "Checklist web", ["SQLi detect, un XSS lab, un LFI passwd, un bypass o brute", "Lo que falte: una clase, no cinco YouTubes"], "Web no se 'completa'. Se mantiene. Como nmap."),
];
