import { lesson, Q, S } from "@/content/course/helper";

function W(
  id: string,
  week: number,
  day: number,
  track: string,
  titleEs: string,
  minutes: number,
  sub: string,
  a: string,
  b: string,
  c: string,
  d: string,
  quiz: ReturnType<typeof Q>[],
  labT: string,
  lab: string[],
  pep: string
) {
  return lesson(id, week, day, track, titleEs, minutes, sub, [S("Qué", a), S("Por qué eJPT", b), S("Cómo en lab", c), S("Error típico", d)], quiz, labT, lab, pep);
}

export const W07 = [
  W("c07-d1", 7, 1, "NET", "ARP, sniffing y por qué NO en tu Wi‑Fi", 16, "net-mitm",
    "ARP resuelve IP→MAC en la LAN. Spoofing/MITM envenena esa tabla. Sniffing captura tráfico. En Host-Only entre TUS VMs puede estudiarse el concepto; en la Wi‑Fi doméstica es atacar a tu familia y quizá un delito.",
    "eJPT menciona ARP/MITM. Entiende el modelo. No necesitas un ataque real a humanos.",
    "ip neigh en Kali. Dibuja Kali-guest. Opcional: herramienta MITM SOLO guest-a-guest si construyes esa red. Si no, quédate en el dibujo.",
    "ettercap hacia 192.168.1.0/24 de casa 'porque es lab'.",
    [Q("ARP traduce…", ["DNS a HTTP", "IPv4 a MAC en L2", "Puerto a PID", "Hash a user"], 1, "L2."), Q("MITM en Wi‑Fi de casa", ["eJPT", "Fuera de este plan", "Obligatorio", "Si WPA2"], 1, "No."), Q("ARP cruza routers", ["Sí", "No", "Si /16", "Si UDP"], 1, "Mismo L2."), Q("Sniffing es…", ["Dirbust", "Capturar tráfico", "sqlmap", "SUID"], 1, "Captura."), Q("ip neigh muestra…", ["Shares", "Tabla de vecinos ARP", "XSS", "SAM"], 1, "Vecinos.")],
    "Tabla ARP del lab", ["ping al guest, ip neigh", "Escribe: 'no spoof a wlan0'"], "Concepto sí. Víctimas humanas no."),
  W("c07-d2", 7, 2, "NET", "Routing: por qué el guest no ve wlan0", 15, "net-basic",
    "Cada interfaz una red. Rutas dicen por dónde sale. El guest Host-Only no tiene ruta a tu Wi‑Fi. Por eso LHOST wlan0 falla.",
    "Pivoting nace de 'hay otra ruta en la víctima'. Sin segunda red, no hay pivot que inventar.",
    "ip route en Kali y, si hay shell, en el guest. Compara.",
    "Añadir default route loca y romper Internet del host. O pivot a 8.8.8.8.",
    [Q("LHOST wlan0 a guest Host-Only", ["Correcto", "Mal: el guest no rutea ahí", "Default msf", "Igual vboxnet"], 1, "Otra NIC."), Q("Pivot requiere…", ["80 open", "Una red que Kali no ve y la víctima sí", "XSS", "Gobuster"], 1, "Otra red."), Q("ip route es…", ["Wordlist", "Tabla de rutas", "NSE", "Cookie"], 1, "Rutas."), Q("Una NIC en MS2…", ["Siempre hay pivot", "A menudo NO hay pivot", "Siempre DC", "Siempre SAM"], 1, "No inventes."), Q("default via wlan0 es…", ["Ruta del lab vboxnet", "Internet del host, no el lab", "RHOSTS", "Hydra"], 1, "Otra salida.")],
    "Compara rutas", ["ip route Kali: marca vboxnet vs default", "En guest (si shell): ip route / ifconfig"], "Dibujar rutas evita el 50% de reverses muertos."),
  W("c07-d3", 7, 3, "PIVOT", "Port forwarding: idea", 16, "net-pivoting",
    "Reenvías un puerto: Kali:local → víctima:remoto o al revés. Sirve para alcanzar un servicio que solo escucha en una red interna.",
    "eJPT: si hay dual-homed host, forward/SOCKS. Si no, no montes un circus.",
    "Concepto en papel. ssh -L / chisel / msf portfwd — nombres. Practica solo si tu lab tiene 2 redes. No abras puertos a Internet.",
    "portfwd hacia tu banco. O creer que forward sustituye nmap inicial en vboxnet.",
    [Q("Port forward…", ["Borra rutas", "Reenvía un puerto a través de un host", "Es Gobuster", "Es XSS"], 1, "Reenvío."), Q("¿Forward el día 1 de MS2 1 NIC?", ["Sí", "No suele hacer falta", "Obligatorio", "Si 22"], 1, "No inventes."), Q("ssh -L es…", ["UDP scan", "Forward local (concepto)", "sqlmap", "SUID"], 1, "SSH fwd."), Q("¿Forward a Internet ajena?", ["Lab", "No", "Si SOCKS", "Si 4444"], 1, "Alcance."), Q("nmap inicial vs pivot", ["Pivot primero siempre", "Primero ves lo que Kali ya alcanza", "Iguales", "Pivot es -sn"], 1, "Orden.")],
    "Diagrama dual-homed", ["Dibuja host con eth0 lab y eth1 10.0.0.0/24 ficticia", "Marca dónde pondrías un forward (concepto)"], "Si no hay segunda red, tu skill es NO pivotar."),
  W("c07-d4", 7, 4, "PIVOT", "SOCKS y proxychains (concepto)", 15, "net-pivoting",
    "SOCKS es un proxy genérico. proxychains envuelve nmap/otros por ese proxy. Así escaneas la red interna desde Kali 'como si' estuvieras detrás de la víctima.",
    "Pregunta de examen: para qué sirve, no memorizar 15 flags. Lab avanzado si tienes 2 redes.",
    "Lee man proxychains una vez. No lo apuntes a producción.",
    "proxychains nmap a tu ISP. O SOCKS abierto 0.0.0.0 en un café.",
    [Q("SOCKS es…", ["Un payload Windows", "Un proxy de túnel", "Un status HTTP", "Un tipo XSS"], 1, "Proxy."), Q("proxychains sirve para…", ["LHOST mágico", "Pasar herramientas por el proxy", "Dirbust SMB", "DHCP"], 1, "Wrap."), Q("¿SOCKS público en café?", ["eJPT", "Pésima idea", "Obligatorio", "Si racha"], 1, "No."), Q("Herramientas por SOCKS", ["Solo hydra casa", "Las que configures (lab interno)", "Solo ARP Wi‑Fi", "Solo DVWA.com"], 1, "Interno."), Q("¿SOCKS sustituye enum SMB local?", ["Sí", "No", "Si 445", "Si -sU"], 1, "Otra fase.")],
    "Ficha SOCKS", ["4 líneas: qué, cuándo, qué no", "Sin abrir proxy a 0.0.0.0"], "Túneles son Mes 2. No son el Mes 0."),
  W("c07-d5", 7, 5, "NET", "UDP, SNMP, DNS interno", 15, "net-basic",
    "UDP no tiene handshake TCP. nmap -sU es lento. SNMP 161/udp community strings (public). DNS 53 AXFR si el NS del lab lo permite.",
    "Si el brief muestra 53 o 161, no te quedes en TCP 1000. Si no, no gastes 40 min de -sU /16.",
    "En lab: nmap -sU -p 53,161 <RHOST> si quieres ver. AXFR solo a TU DNS de lab.",
    "AXFR contra dns.google. SNMP walk a la impresora de la oficina.",
    [Q("SNMP puerto típico", ["80", "161/udp", "445", "22"], 1, "161."), Q("AXFR es…", ["Exploit kernel", "Transferencia de zona DNS (enum)", "Hydra", "LFI"], 1, "DNS enum."), Q("-sU por defecto en nmap TCP", ["Sí cubre UDP", "No", "Solo 161", "Solo 53"], 1, "Hay que pedirlo."), Q("community public…", ["Root Windows", "A menudo default SNMP (lab)", "LHOST", "Cookie"], 1, "Default."), Q("AXFR a DNS público", ["Lab eJPT", "No", "Si UDP", "Si /24 casa"], 1, "Alcance.")],
    "UDP puntual", ["Si tu nmap TCP no mostró 53/161, un -sU corto a esos puertos en el guest", "No -sU masivo"], "UDP es el cajón que el default no abre. Ábrelo solo si huele."),
  W("c07-d6", 7, 6, "NET", "Cierre redes + simulacro en la cabeza", 14, "net-pivoting",
    "Mes 2b: no MITM a humanos, sí rutas, sí pivot conceptual, sí UDP cuando toca. Simulacro #2 del plan se acerca: mezcla web+red.",
    "Preguntas combinadas: LHOST + 445 + SQLi. Entrena cambio de contexto.",
    "Examen de curso semana 7. TRAIN 10 min.",
    "Estudiar solo pivot porque 'da miedo' y olvidar SMB.",
    [Q("MITM a la familia", ["Parte del curso", "Prohibido aquí", "Si Host-Only… no, sigue siendo no a humanos", "Si racha 14"], 1, "No."), Q("Cambio de contexto examen", ["Un tema por día INE", "Mezclan", "Solo web", "Solo msf"], 1, "Mezcla."), Q("Pivot sin 2 redes", ["Obligatorio", "No lo inventes", "Usa wlan0", "Usa 8.8.8.8"], 1, "Honestidad."), Q("LHOST sigue importando", ["Ya no", "Sí", "Solo Mes 1", "Solo bind"], 1, "Siempre."), Q("UDP default scan", ["Incluido", "No", "Sí en -sV", "Sí en -sn"], 1, "Apartado.")],
    "Mapa Mes 2", ["Web / red / aún no privesc profundo: 3 cajas", "Una pregunta de cada caja en papel"], "El examen es un mezclador. Tú eres el DJ: no dejes un género."),
];

export const W08 = [
  W("c08-d1", 8, 1, "POST", "Privesc Linux: mapa, no exploits random", 16, "privesc-linux",
    "Eres user. Quieres root. Mapa: sudo -l, SUID, cron, capabilities, passwords en ficheros, kernel (último y peligroso). LinPEAS es un acelerador, no un cerebro.",
    "eJPT: conceptos y un camino en lab. No descargues 20 kernel exploits del año pasado a ciegas.",
    "En sesión MS2: sudo -l, id, find SUID básico. Interpreta. Snapshot.",
    "curl un exploit.sh de un foro y | bash como root en el host Kali.",
    [Q("sudo -l muestra…", ["Rutas HTTP", "Qué puedes correr con sudo", "ARP", "NSE"], 1, "sudo."), Q("SUID corre como…", ["Siempre nobody", "A menudo el dueño del binario", "Siempre guest", "UDP"], 1, "Dueño."), Q("LinPEAS es…", ["El examen INE", "Enum automatizado de privesc", "Gobuster SMB", "sqlmap"], 1, "Enum."), Q("Kernel exploit primero siempre", ["Sí", "No: sudo/SUID/cron primero", "En /24 sí", "Si -sV"], 1, "Orden."), Q("| bash un script de foro en Kali", ["Pro", "Pésima idea", "eJPT oficial", "Si HTTPS"], 1, "No.")],
    "sudo -l en MS2", ["Si hay sesión: sudo -l e id", "Si no: consola msfadmin y lo mismo (es user, no siempre root)"], "Mapa > payload. El payload sin mapa es lotería."),
  W("c08-d2", 8, 2, "POST", "Cron, PATH, writable scripts", 15, "privesc-linux",
    "Cron corre como un usuario (a menudo root). Si el script es escribible por ti, ganas. PATH hijack: el cron llama un binario relativo y tú pones uno en un dir escribible.",
    "Clásico de labs. Busca /etc/cron*, crontab, timers. No lo busques en el PC de tu jefe.",
    "ls -la /etc/cron* en el guest. Anota owners y write.",
    "Modificar cron del host Kali 'para practicar' y romper actualizaciones.",
    [Q("Cron de root + script writable", ["Inútil", "Vector clásico", "Solo Windows", "Solo XSS"], 1, "Vector."), Q("PATH hijack necesita…", ["SQLi", "Búsqueda relativa + dir writable", "Bridged", "AXFR"], 1, "PATH."), Q("¿crontab del jefe?", ["Lab", "No", "Si Linux", "Si /24"], 1, "Alcance."), Q("/etc/cron* se lista con…", ["gobuster", "ls / lectura de ficheros", "hydra", "sqlmap"], 1, "FS."), Q("Privesc es post-ex", ["Antes de nmap", "Después de ser user no-root", "Igual que -sn", "Igual que DVWA login"], 1, "Fase.")],
    "Enum cron", ["Lista crons en el guest", "No edites nada en Kali host"], "Writable + root cron = historia fácil. Búscala antes que el kernel."),
  W("c08-d3", 8, 3, "POST", "Privesc Windows (concepto)", 16, "privesc-windows",
    "Servicios unquoted, AlwaysInstallElevated, tokens, UAC (concepto), scheduled tasks, PowerShell, SAM si ya eres SYSTEM no hace falta. WinPEAS analogía de LinPEAS.",
    "Preguntas de examen más que lab si no tienes VM Windows. No uses el Windows de tu casa como target.",
    "Ficha de 8 viñetas. Si tienes VM lab: whoami /priv (concepto).",
    "Ejecutar exploits Windows contra el PC familiar.",
    [Q("Unquoted service path es…", ["SQLi", "Vector Windows clásico (concepto)", "Nmap -sU", "LFI"], 1, "Servicio."), Q("WinPEAS es…", ["Payload linux", "Enum privesc Windows", "DVWA", "vboxnet"], 1, "Enum."), Q("PC Windows de casa como lab eJPT", ["Ideal Bridged", "No", "Si desactivas AV", "Si /24"], 1, "No."), Q("whoami /priv (concepto)", ["Linux passwd", "Privilegios del token Windows", "SMB share", "Cookie"], 1, "Token."), Q("SAM dump es…", ["Linux shadow igual", "Hashes Windows (cuando el contexto lo permite)", "Gobuster", "AXFR"], 1, "Windows.")],
    "Ficha Windows", ["8 viñetas privesc Windows sin explotar nada", "Cero ataques a hosts domésticos"], "Concepto sólido > 0 labs pirata en el PC de alguien."),
  W("c08-d4", 8, 4, "POST", "Loot: qué guardar para el cuestionario", 15, "post-exploit-loot",
    "Flags, hashes si piden, archivos de usuario, versión, ifconfig, proof.txt. El eJPT no es un PDF de 40 páginas OSCP; es respuestas cortas exactas.",
    "Si no anotas, reexplotas. El reloj odia el déjà vu.",
    "Plantilla de notas: IP, puertos, users, creds, flag, cómo. Una cadena MS2.",
    "hashdump inútil en Linux por costumbre. O screenshots de 80 MB y cero texto copiable.",
    [Q("Formato eJPT típico", ["Ensayo OSCP", "Respuestas cortas / valores", "Solo video", "Solo root sin preguntas"], 1, "Q&A."), Q("Reexplotar porque no anotaste", ["Élite", "Pierde reloj", "Obligatorio", "Sustituye enum"], 1, "Notas."), Q("proof.txt es…", ["NSE", "Evidencia de acceso (lab/exam style)", "Wordlist", "Cookie XSS"], 1, "Proof."), Q("¿Notas en la cabeza?", ["Suficiente", "No", "Si IQ", "Si racha 90"], 1, "Escribe."), Q("Loot es fase…", ["Antes de -sn", "Post access", "Solo TRAIN arcade", "Solo LEARN ficha"], 1, "Post.")],
    "Plantilla", ["Copia una plantilla de 8 campos y rellénala con MS2", "Guárdala fuera de la sesión volátil"], "El examen paga evidencias. Las shells son el medio."),
  W("c08-d5", 8, 5, "POST", "Cuándo NO hacer privesc", 14, "privesc-linux",
    "Si ya eres root/SYSTEM y la pregunta está contestada: para. Si el objetivo es un archivo de user: no hace falta kernel. Reloj > ego.",
    "Muchos suspenden por irse a privesc brillante y no copiar el flag que ya tenían.",
    "Relee tus notas de una cadena: ¿qué preguntarían? Contéstalo. Para.",
    "Kernel exploit 'por si acaso' y tumbar el box del examen.",
    [Q("Ya root y tienes el valor", ["Sigue explotando", "Documenta y pasa a otra pregunta", "Pivot a casa", "Hydra"], 1, "Reloj."), Q("Flag en home de user", ["Kernel primero", "Léelo como user", "Bridged", "AXFR"], 1, "Mínimo."), Q("Tumbar el box del examen", ["Divertido", "Catastrófico", "Reset gratis siempre", "INE agradece"], 1, "Estabilidad."), Q("Ego vs reloj", ["Ego", "Reloj", "Igual", "Racha"], 1, "Reloj."), Q("Privesc es obligatorio en cada IP", ["Sí", "No", "En /24 sí", "Si 445"], 1, "Depende objetivo.")],
    "Auditoría de una cadena", ["Mira tus notas: 2 valores que INE podría pedir", "Marca si ya los tenías sin root"], "Parar también es una skill de examen."),
  W("c08-d6", 8, 6, "POST", "Cierre Mes 2", 15, "full-chain",
    "Tienes web, red conceptual, privesc mapa, loot. Mes 3 es encadenar bajo tiempo y logística INE. No es contenido infinito nuevo.",
    "Simulacros #1/#2 deberían existir en tu historial. Si no, EXAM full esta semana.",
    "Examen curso s8. Una máquina cronometrada 50 min (MS2 o Kioptrix lab).",
    "Empezar a leer OSCP forums y olvidar eJPT.",
    [Q("Mes 3 enfatiza…", ["Solo XSS nuevo", "Cadenas + reporting + logística", "Borrar lab", "MITM casa"], 1, "Integrar."), Q("¿Foros OSCP ahora?", ["Sustituyen eJPT", "Distraen; cierra eJPT primero", "Obligatorio", "Dan LHOST"], 1, "Foco."), Q("Simulacros en historial", ["Adorno", "Gimnasio de reloj", "INE mismo", "SMB only"], 1, "Gym."), Q("50 min una máquina", ["Poco serio", "Entrena corte de tiempo", "Sustituye 3 meses", "Es Bridged"], 1, "Corte."), Q("Contenido Mes 3", ["Otro Kali", "Menos temas nuevos, más integración", "Solo ARP", "Solo DVWA"], 1, "Integrar.")],
    "Box 50 min", ["Timer. Una víctima lab. Parar. Notas estilo examen", "Sin nuevas tools a mitad"], "Mes 2 cerrado con una historia, no con 40 pestañas."),
];
