import { lesson, Q, S } from "@/content/course/helper";

function W(
  id: string,
  week: number,
  day: number,
  track: string,
  titleEs: string,
  minutes: number,
  sub: string,
  a: string,
  b: string,
  c: string,
  d: string,
  quiz: ReturnType<typeof Q>[],
  labT: string,
  lab: string[],
  pep: string
) {
  return lesson(id, week, day, track, titleEs, minutes, sub, [S("Qué", a), S("Por qué eJPT", b), S("Cómo en lab", c), S("Error típico", d)], quiz, labT, lab, pep);
}

export const W09 = [
  W("c09-d1", 9, 1, "CHAIN", "Máquina completa: reloj y alcance", 16, "full-chain",
    "Una IP, un CIDR, un timer. Misma historia Mes 1, más web si hay 80. No abras 6 writeups. Kioptrix/MS2/VulnHub que TÚ bajaste Host-Only.",
    "Mes 3 simula el estrés de 'varias preguntas sobre la misma red'.",
    "50–70 min. Una box. Notas. Parar aunque no sea root.",
    "Leer el writeup a los 5 minutos. O atacar un HTB live sin suscripción/alcance claro.",
    [Q("Writeup a los 5 min", ["Óptimo", "Quema el aprendizaje", "Oficial eJPT", "Sustituye nmap"], 1, "Resiste."), Q("Varias preguntas una red", ["Raro", "Estilo examen", "Solo OSCP", "Solo web"], 1, "eJPT."), Q("Parar sin root", ["Fracaso total", "Aún puedes tener valores", "Borra Kali", "Bridged"], 1, "Loot."), Q("HTB live sin alcance", ["Igual lab", "Otro contrato; aquí Host-Only/INE", "Siempre OK", "Si free"], 1, "Alcance."), Q("Timer sirve para…", ["Ansiedad inútil", "Cortar perfeccionismo", "LHOST", "XSS"], 1, "Corte.")],
    "Box cronometrada", ["Elige MS2 o Kioptrix lab", "50 min, notas, stop"], "El reloj te entrena. El writeup te adula. Elige el reloj."),
  W("c09-d2", 9, 2, "CHAIN", "Cuando hay 80 y 445 juntos", 15, "tool-selection",
    "No es elegir el 'mejor'. Es orden: versiones, SMB users, HTTP dirs, luego el vector más barato. TDAH: un hilo 20 min, luego el otro.",
    "El examen pondrá ambos. Quien solo sabe msf samba o solo Gobuster se atasca.",
    "En MS2: 15 min SMB enum, 15 min Gobuster, 15 min decidir. Escribe la decisión.",
    "Paralelo Hydra+Gobuster+msf y cero lectura de output.",
    [Q("80+445", ["Solo uno existe en eJPT", "Enum ambos, prioriza", "Solo Hydra", "Solo XSS"], 1, "Ambos."), Q("20 min un hilo", ["Debilidad", "TDAH-friendly", "Prohibido", "Solo Mes 0"], 1, "Foco."), Q("Decisión escrita", ["Inútil", "Evita ping-pong", "Es LHOST", "Es Bridged"], 1, "Commit."), Q("Tres tools sin leer", ["Élite", "Caos", "Método INE", "Remediation"], 1, "Lee."), Q("Vector barato significa…", ["Más CVEs", "Menos pasos hasta evidencia", "Más brute", "Más YouTube"], 1, "Camino corto.")],
    "Dos superficies, una decisión", ["MS2: SMB y HTTP. Elige UN vector para explotar hoy", "El otro queda anotado"], "Priorizar es el examen. Explotar es el final del cuento."),
  W("c09-d3", 9, 3, "CHAIN", "Segunda máquina, mismas reglas", 16, "full-chain",
    "Transferencia: el método viaja, los CVEs no. Kioptrix 1 no es MS2. nmap de cero. No copies LHOST del cuaderno de 2019 sin medir.",
    "Demuestra que no memorizaste un box, memorizaste un oficio.",
    "Otra VM Host-Only. Discovery. Si no tienes segunda VM, rehaz MS2 desde snapshot limpio sin memoria.",
    "Importar 10 OVAs y no terminar ninguna.",
    [Q("CVEs viajan solos", ["Sí", "No: el método sí, el CVE no", "Siempre vsftpd", "Siempre Samba"], 1, "Método."), Q("LHOST del cuaderno viejo", ["Sagrado", "Hay que medir otra vez", "Siempre .1", "Siempre wlan0"], 1, "Mide."), Q("Snapshot limpio MS2", ["Trampa", "Válido si no hay 2ª VM", "Inútil", "Es Bridged"], 1, "Reset."), Q("10 OVAs a medias", ["Productivo", "Antipattern TDAH", "Plan oficial", "Mes 3 required"], 1, "Una."), Q("Discovery en cada box", ["Opcional", "Obligatorio", "Solo la primera", "Solo si 80"], 1, "Siempre.")],
    "Box B o MS2 reset", ["nmap -sn del /24 otra vez", "No asumas IPs"], "Oficio = volver a empezar sin drama."),
  W("c09-d4", 9, 4, "CHAIN", "Atasco: I'M STUCK de la app", 14, "full-chain",
    "La app tiene pistas por niveles. Usarlas no es trampa: es andamiaje. En INE no estarán. Por eso luego Exam Reasoning sin pistas.",
    "Calibrar cuándo pides pista vs cuándo enumeras 10 min más.",
    "Focus/Stuck en una operación. Máximo nivel 2 hoy. Luego 10 min tú.",
    "Abrir writeup completo y decir que 'usaste la app'.",
    [Q("Pistas de la app en INE", ["Igual", "No estarán", "Sí nivel 5", "Sí si pagas"], 1, "No."), Q("10 min más de enum vs pista", ["Siempre pista ya", "A menudo enum primero", "Siempre writeup", "Siempre msf"], 1, "Enum."), Q("Exam Reasoning", ["Con pistas", "Sin recetas; metodología", "Solo arcade", "Solo LEARN"], 1, "Método."), Q("Writeup completo", ["Andamiaje fino", "Quema la box", "Skill-check", "LHOST"], 1, "Quema."), Q("Atasco es…", ["Fin de carrera", "Dato para remediar subtema", "Señalar Bridged", "Borrar progreso"], 1, "Señal.")],
    "Una stuck honesta", ["Quédaste atascado: escribe el último output", "Una pista app O 10 min enum, no ambos a la vez"], "Nombrar el atasco es ya enumerar tu cabeza."),
  W("c09-d5", 9, 5, "EXAM", "Exam Reasoning Mode", 16, "full-chain",
    "Te dan un nmap. No te dan el comando. Explicas primero/prioridad/herramienta/post. Es el gimnasio del 'what would you do'.",
    "INE no es exactamente eso, pero el músculo es el mismo: decidir.",
    "/simulacro/reasoning. Completa un escenario. Sin Google.",
    "Responder 'nmap' a todo. O 'metasploit' a todo.",
    [Q("Respuesta 'siempre msf'", ["Método", "Pereza", "Oficial", "LHOST"], 1, "No."), Q("Primero ante nmap multi-open", ["Exploit random", "Priorizar enum", "Pivot", "XSS"], 1, "Prioriza."), Q("Reasoning sin Google", ["Inútil", "Entrena examen", "Solo TDAH malo", "Solo Mes 0"], 1, "Gym."), Q("Herramienta la elige…", ["Twitter", "El servicio", "La racha", "El arcade"], 1, "Servicio."), Q("Post-ex pregunta…", ["Otro CVE ya", "Quién soy / evidencia", "Bridged", "AXFR"], 1, "Identidad.")],
    "Un escenario reasoning", ["Completa EXAM → reasoning", "Relee explicaciones de lo fallado"], "Decidir en frío. El lab en caliente sale de aquí."),
  W("c09-d6", 9, 6, "CHAIN", "Cierre semana cadenas", 14, "full-chain",
    "Dos boxes o dos resets. Un reasoning. Notas con valores. Eso es Mes 3 semana 1, no un curso de 400 CVEs.",
    "Si aún mezclas Gobuster/Hydra, esa es la remediación, no 'más pivot'.",
    "Examen curso s9. TRAIN decisions.",
    "Añadir 3 distros nuevas.",
    [Q("400 CVEs", ["Plan Mes 3", "Distracción", "Garantía INE", "Sustituye LHOST"], 1, "No."), Q("Hueco tools", ["Ignorar", "Remediar ahora", "Mes 5", "Windows only"], 1, "Ahora."), Q("Valores en notas", ["Ego", "Formato examen", "Arcade", "Bridged"], 1, "Q&A."), Q("Nueva distro esta semana", ["Necesaria", "Ruido", "Arregla Hydra", "Arregla SQLi"], 1, "Ruido."), Q("Mes 3 semana 1 éxito", ["Root en 12 boxes", "Método repetido bajo reloj", "MITM casa", "OSCP lab"], 1, "Método.")],
    "Lista de 3 remediaciones", ["Subtemas flojos del reasoning/simulacro", "Una clase o drill cada uno, no 30"], "Cerrar huecos > coleccionar distros."),
];

export const W10 = [
  W("c10-d1", 10, 1, "REPORT", "Qué pregunta eJPT (estilo)", 15, "reporting",
    "Versión de un servicio, un hash, un archivo, un usuario, a veces un flag. No un executive summary de consultora.",
    "Entrenas copiar exacto: espacios, mayúsculas. Un hash mal copiado es cero.",
    "De tus notas MS2, redacta 8 preguntas que INE podría hacer y respóndelas.",
    "Escribir un PDF de 20 páginas y no poder decir la versión de vsftpd.",
    [Q("eJPT se parece más a…", ["Informe OSCP largo", "Cuestionario de valores", "Video demo", "Entrevista RRHH"], 1, "Q&A."), Q("Hash mal copiado", ["Aproximado vale", "Cero", "70% interno", "Redondeo"], 1, "Exacto."), Q("Executive summary", ["Centro eJPT", "No es el formato principal", "Sustituye nmap", "Obligatorio INE 20p"], 1, "No."), Q("Versión de servicio", ["Inútil", "Muy preguntada", "Solo XSS", "Solo pivot"], 1, "Versión."), Q("8 auto-preguntas", ["Perder tiempo", "Simulacro casero", "Bridged", "Arcade"], 1, "Gym.")],
    "8 Q&A de tu lab", ["Escríbelas y escóndete la respuesta 1 h", "Autoevalúa"], "El reporte eJPT cabe en un bloc. Llénalo de hechos."),
  W("c10-d2", 10, 2, "REPORT", "Notas durante vs después", 14, "reporting",
    "Durante: IP, comando, output clave. Después: limpiar. Si dejas todo para el final, el examen se acaba.",
    "Habitúate a anotar EN el minuto del hallazgo.",
    "En la próxima cadena, bloc al lado. Prohibido 'luego lo apunto'.",
    "Screenshots sin recortar y cero texto. O notas en el guest que se borra.",
    [Q("Anotar luego", ["Óptimo", "El examen se acaba", "INE recomienda", "Más exacto"], 1, "Ahora."), Q("Notas en la VM víctima", ["Seguras", "Pueden morir con la sesión", "Mejor que Kali", "Automáticas"], 1, "En atacante."), Q("Screenshot único método", ["Suficiente", "Complemento; copia texto", "Prohibido", "Sustituye whoami"], 1, "Texto."), Q("Output clave es…", ["Todo el -p-", "La línea que responde la pregunta", "El ASCII art msf", "El help de nmap"], 1, "Señal."), Q("Bloc al lado", ["Infantil", "Profesional de examen", "Solo TDAH", "Solo Mes 0"], 1, "Pro.")],
    "Regla de oro", ["Un hallazgo = una línea ahora", "Practica en un nmap de 5 min"], "La memoria de trabajo en examen es pequeña. El papel es grande."),
  W("c10-d3", 10, 3, "REPORT", "Inglés de examen (frases)", 15, "exam-logistics",
    "Which of the following, What is the version, Submit the hash, Identify the user. Lees EN, piensas método, respondes valor.",
    "No traduce palabra por palabra el output. Traduce la TAREA.",
    "Glosario EN/ES de la app 10 min. 5 prompts EN del banco.",
    "Congelarse porque la pregunta está en inglés aunque sabes el concepto.",
    [Q("Idioma eJPT", ["Solo ES", "Principalmente EN", "Latín", "Flags binarios"], 1, "EN."), Q("Traducir el output entero", ["Necesario", "Traduce la tarea, no el dump", "INE exige", "Sustituye nmap"], 1, "Tarea."), Q("Congelarse por EN", ["Inevitable", "Se entrena con prompts EN", "Mejor abandonar", "Cambia el examen a ES"], 1, "Entrena."), Q("Submit the hash pide…", ["Un ensayo", "El hash exacto", "Un CVE", "Un LHOST"], 1, "Valor."), Q("Glosario de la app", ["Adorno", "Entrenamiento de lectura", "SMB tool", "Pivot"], 1, "Lectura.")],
    "5 prompts EN", ["Banco / skill-check: lee EN primero 10s sin ES", "Luego ES si hace falta"], "El inglés no es el pentest. Es el envoltorio. Ábrelo cada día."),
  W("c10-d4", 10, 4, "REPORT", "Evidencia mínima por fase", 15, "post-exploit-loot",
    "Recon: hosts. Scan: puertos+versiones. Enum: users/shares/rutas. Exploit: tipo de acceso. Post: whoami + archivo. Eso es un informe eJPT disfrazado de notas.",
    "Si una fase no tiene línea, esa fase no 'pasó' para el cuestionario.",
    "Audita notas de una box: ¿faltan fases?",
    "10 páginas de recon y cero post. O al revés.",
    [Q("Fase sin línea", ["Igual pasó", "No puedes responderla", "INE infiere", "Racha cubre"], 1, "No pasó."), Q("whoami es fase…", ["Recon", "Post", "DNS", "Gobuster"], 1, "Post."), Q("Users/shares son…", ["Exploit", "Enum", "Pivot obligatorio", "XSS"], 1, "Enum."), Q("10 páginas recon", ["Perfecto eJPT", "Desbalance; falta exploit/post", "Sustituye lab", "Evita inglés"], 1, "Balance."), Q("Versiones viven en…", ["Solo post", "Scan/enum", "Solo Hydra", "Solo LFI"], 1, "Scan.")],
    "Auditoría 5 fases", ["Recon/scan/enum/exploit/post: 1 línea cada", "Rellena agujeros en lab, no en teoría infinita"], "Cinco líneas > cinco capítulos."),
  W("c10-d5", 10, 5, "EXAM", "Simulacro estilo reporting", 15, "reporting",
    "Coge 10 preguntas del banco de reporting/full-chain/logistics. Marca. Mira explicaciones.",
    "El músculo de 'respuesta corta' se entrena aparte del lab.",
    "EXAM skill-check de la semana del plan + examen curso s10.",
    "Decir 'ya labo' y no marcar nunca.",
    [Q("Marcar preguntas", ["Inferior al lab", "Complementario y obligatorio en este curso", "Solo Mes 0", "Solo LEARN"], 1, "Ambos."), Q("Respuesta corta se entrena…", ["Solo con root", "Marcando bajo tiempo", "Con MITM casa", "Con 10 OVAs"], 1, "Quiz."), Q("Explicación al fallar", ["Perder tiempo", "Remediación", "LHOST", "Bridged"], 1, "Aprende."), Q("Solo labear sin quiz", ["Cubre eJPT 100%", "Deja hueco de formato examen", "Oficial INE", "Mejor TDAH"], 1, "Hueco."), Q("Banco reporting", ["Inútil", "Gimnasio de formato", "SMB", "ARP"], 1, "Formato.")],
    "10 marcas", ["10 preguntas reporting/chain", "An<fim-middle>ota 2 errores de formato (exactitud)"], "Lab + marcas. Los dos motores del trimestre."),
  W("c10-d6", 10, 6, "REPORT", "Cierre reporting", 14, "reporting",
    "Ya sabes qué guardar y en qué idioma llega la pregunta. Semana 11 es logística VPN/día D. No es un CVE nuevo.",
    "Si tus notas siguen siendo screenshots caóticos, esta es la semana de limpiar plantilla, no de otra box.",
    "Limpia UNA plantilla y úsala el resto del Mes 3.",
    "Nueva plantilla cada día.",
    [Q("Semana 11", ["Otro SQLi", "Logística examen", "MITM", "10 distros"], 1, "Logística."), Q("Plantilla nueva cada día", ["Pro", "Ruido; una y reutiliza", "INE pide", "TDAH óptimo"], 1, "Una."), Q("Screenshots caóticos", ["Listos INE", "Hay que extraer valores", "Sustituyen hash", "Valen 70%"], 1, "Extrae."), Q("CVE nuevo esta semana", ["Prioridad", "No es el cuello de botella", "Obligatorio", "Arregla LHOST"], 1, "No."), Q("Reporting cerrado significa…", ["PDF 40p", "Puedes extraer valores bajo reloj", "Root 12 boxes", "Racha 90"], 1, "Valores.")],
    "Plantilla final", ["1 página. 5 fases. Úsala mañana", "Tira las 7 plantillas anteriores"], "Una plantilla. Como una navaja. No un cajón de navajas."),
];

export const W11 = [
  W("c11-d1", 11, 1, "INE", "Qué es el eJPT (expectativas honestas)", 16, "exam-logistics",
    "Certificación de nivel junior de INE/eLearnSecurity. Examen práctico con cuestionario sobre un lab VPN. Tiempo limitado. No es OSCP. No es 'root todas las boxes del mundo'.",
    "Esta app no es INE. Umbrales 70/85/90 son internos. El corte real lo pone el proveedor.",
    "Lee la página oficial de INE para duración y reglas actuales (cambian). No te fíes de un tweet de 2021.",
    "Creer que racha 90 aquí = diploma. O que un writeup de examen filtrado es ética.",
    [Q("eJPT vs OSCP", ["Idénticos", "eJPT es junior; otro formato", "eJPT más duro siempre", "Mismo informe 20p"], 1, "Distintos."), Q("Esta app certifica", ["Sí", "No", "Si 90%", "Si 78 clases"], 1, "No."), Q("Reglas INE", ["Fijas 2018", "Verifica oficiales actuales", "Las de Reddit", "Las de esta web"], 1, "Oficial."), Q("Writeups filtrados de examen", ["Estudio válido", "Hacen trampa y queman el valor", "Requeridos", "Sustituyen lab"], 1, "No."), Q("VPN del examen", ["Tu wlan0 casa", "El acceso que INE te da", "vboxnet", "Tor"], 1, "INE.")],
    "Ficha oficial", ["Abre el overview oficial INE eJPT (docs)", "Anota duración y tipo de examen según la fuente oficial HOY"], "Expectativa adulta. Luego disciplina. Ese es el combo."),
  W("c11-d2", 11, 2, "INE", "VPN, Kali y el día antes", 16, "exam-logistics",
    "El día D no es para actualizar Kali ni descubrir que VirtualBox no abre. VPN de examen se prueba ANTES según instrucciones oficiales. Lab local (vboxnet) no es la VPN de INE: son redes distintas.",
    "Quemar 40 min de examen en drivers es una forma tonta de suspender.",
    "Checklist: Kali actualizado la semana anterior (no la noche antes), notas plantilla, agua, timer, DND en el teléfono.",
    "apt full-upgrade 10 min antes. O examinarte en la laptop de un amigo sin tus notas.",
    [Q("Actualizar Kali en el minuto 0", ["Pro", "Riesgo tonto", "Obligatorio INE", "Setea LHOST"], 1, "Antes."), Q("vboxnet = VPN INE", ["Sí", "No", "Si /24", "Si Host-Only"], 1, "Distintas."), Q("Probar VPN", ["El mismo día solo", "Antes, según INE", "Nunca", "En Bridged casa"], 1, "Antes."), Q("Teléfono durante examen", ["Twitch", "DND / lejos", "Writeups", "Hydra cloud"], 1, "Foco."), Q("Notas plantilla", ["Prohibidas siempre (verifica reglas oficiales)", "Prepara lo que las reglas permitan; no copies dumps de examen", "Un PDF de 200 CVEs", "Las de Reddit"], 1, "Reglas.")],
    "Checklist día -1", ["7 ítems: sueño, Kali, plantilla, reglas oficiales, agua, sitio, hora", "Nada de distro nueva"], "El examen se pierde en la logística más que en un NSE."),
  W("c11-d3", 11, 3, "INE", "Gestión de tiempo en el lab de examen", 16, "exam-logistics",
    "Triage: hosts fáciles primero. No te cases con una IP 3 horas. Marca preguntas, vuelve. El cuestionario manda, no tu novela de privesc.",
    "Misma idea que simulacro 20 min a otra escala.",
    "Simulacro full + una box 50 min el mismo día (cansancio). Aprende a cortar.",
    "Perfeccionar un kernel en IP 1 y no tocar IP 2 que tenía FTP anon.",
    [Q("3 h en una IP", ["Siempre correcto", "A menudo mal triage", "INE óptimo", "Sustituye enum"], 1, "Corta."), Q("Preguntas primero vs root primero", ["Root ego", "Cuestionario manda", "Igual", "Racha manda"], 1, "Q&A."), Q("Hosts fáciles", ["Dejarlos para el final", "Triage temprano", "Ignorar", "Solo Windows"], 1, "Puntos."), Q("Cansancio se entrena", ["No", "Sí: dos bloques el mismo día", "Solo café", "Solo arcade"], 1, "Simula."), Q("FTP anon en IP 2", ["Menos cool que kernel IP 1", "Puede ser más puntos", "Ilegal", "No es eJPT"], 1, "Puntos.")],
    "Triage en papel", ["Simula 3 IPs ficticias con nmaps cortos", "Ordena cuál atacar 1-2-3 y por qué"], "Triage es puntuación. El kernel es cine."),
  W("c11-d4", 11, 4, "INE", "Qué no hacer (integridad)", 15, "exam-logistics",
    "No dumps, no compartir el lab, no atacar fuera del VPN, no collab en vivo si las reglas lo prohíben. El certificado es tuyo o no lo es.",
    "Hacer trampa te deja sin oficio cuando el trabajo pida el mismo músculo.",
    "Relee honor code oficial. Punto.",
    "Comprar dumps. Pedir a un amigo que te entre por AnyDesk.",
    [Q("Dumps de examen", ["Estudio", "Trampa", "Remediation", "LEARN"], 1, "Trampa."), Q("Atacar fuera del VPN INE", ["Bonus", "Rompe alcance", "Host-Only INE", "Lab extra"], 1, "Alcance."), Q("AnyDesk a un amigo durante examen", ["Teamwork", "Normalmente prohibido", "LHOST", "TDAH ok"], 1, "Integridad."), Q("El oficio post-cert", ["Da igual", "Lo vas a necesitar", "Solo el PDF", "Solo racha"], 1, "Oficio."), Q("Honor code", ["Adorno", "Reglas que lees en oficial", "De esta app", "De Twitter"], 1, "Oficial.")],
    "Honor", ["Lee el code de conducta oficial", "Escribe 1 frase: 'mi alcance mañana es solo X'"], "Integridad no da puntos extra. Quitarla te los anula todos."),
  W("c11-d5", 11, 5, "INE", "Plan de 48 h pre-examen", 15, "exam-logistics",
    "T-48: simulacro full, no contenido nuevo. T-24: checklist, sueño. T-0: agua, VPN, triage. Contenido nuevo T-12h es pánico disfrazado de ética de trabajo.",
    "Tu disciplina: no abras un CVE virgen la noche antes.",
    "Agenda literal en el calendario.",
    "Comprar otro curso de 40 h el día anterior.",
    [Q("Contenido nuevo T-12h", ["Óptimo", "Pánico", "Requerido INE", "Sube racha útil"], 1, "No."), Q("T-48 mejor uso", ["10 OVAs", "Simulacro + repaso huecos", "MITM casa", "Nueva distro"], 1, "Gym."), Q("Sueño", ["Opcional", "Parte del plan", "Debilidad", "Sustituible con café 2L"], 1, "Plan."), Q("Otro curso 40h T-1", ["Sabio", "Ruido", "Arregla LHOST", "Arregla SQLi"], 1, "Ruido."), Q("T-0 es…", ["Aprender NSE nuevo", "Ejecutar el método", "Instalar Arch", "Bridged MS2"], 1, "Ejecutar.")],
    "Bloques T-48/24/0", ["Escríbelos en papel con horas", "Compromiso de no CVE nuevo"], "El plan de 3 meses se juega en 48 h de no sabotearte."),
  W("c11-d6", 11, 6, "INE", "Cierre logística", 14, "exam-logistics",
    "Sabes qué es el examen, qué no es esta web, cómo triar, cómo no hacer trampa, cómo no pánico-estudiar. Semana 12 es consolidación: menos nuevo, más repetición.",
    "Si la VPN oficial cambió, tu nota de d1 manda, no este párrafo.",
    "Examen curso s11. Un full simulacro.",
    "Saltar semana 12 porque 'ya sé'.",
    [Q("Semana 12", ["Nuevo framework", "Consolidar", "OSCP start", "10 distros"], 1, "Repetir."), Q("Esta web vs INE (otra vez)", ["Iguales", "Gimnasio vs juez", "Racha = diploma", "64 fichas = diploma"], 1, "Juez INE."), Q("Saltar consolidación", ["Ahorra tiempo", "Pierde retención", "Élite", "INE recomienda"], 1, "Retén."), Q("Nota d1 reglas", ["Fija 2020", "Tú la actualizaste con fuente oficial", "De Reddit", "De HTB"], 1, "Oficial."), Q("Full simulacro s11", ["Tarde", "A tiempo", "Inútil", "Trampa"], 1, "A tiempo.")],
    "Full simulacro", ["EXAM full. Remedia 2 subtemas", "Nada de contenido nuevo tras ello hoy"], "Logística lista. Ahora que el cerebro no improvises el día D."),
];

export const W12 = [
  W("c12-d1", 12, 1, "FIX", "Repaso hueco: tools", 16, "tool-selection",
    "Gobuster / Hydra / enum4linux otra vez. Si lo fallas aquí, el examen lo olerá.",
    "Tu hueco declarado. Cerrarlo vale más que un CVE nuevo.",
    "TRAIN decisions + clase c02-d5 + 10 marcas del banco tool-selection.",
    "Decir 'ya lo pillé' sin marcar 10/10 conceptuales.",
    [Q("80 sin form", ["Hydra", "Gobuster/curl", "enum4linux", "hashdump"], 1, "HTTP."), Q("445", ["Gobuster", "SMB enum", "sqlmap", "XSS"], 1, "SMB."), Q("22 sin user", ["Hydra ya", "Enum user primero", "LFI", "AXFR"], 1, "User."), Q("Tres tools son…", ["Intercambiables", "Familias distintas", "Solo msf", "Solo Windows"], 1, "Familias."), Q("Este hueco vs CVE nuevo", ["CVE", "Cerrar el hueco", "Igual", "Ninguno"], 1, "Hueco.")],
    "10 marcas tools", ["Hasta 80% en tool-selection", "Si no: otra vez d5 semana 2"], "El hueco no se negocia. Se perfora con repetición."),
  W("c12-d2", 12, 2, "FIX", "Repaso hueco: Metasploit flujo", 16, "msf-lhost-lport",
    "search → use → set RHOSTS/LHOST → payload → run → sysinfo. Mide vboxnet. Dibuja reverse.",
    "Segundo hueco declarado. Sin esto, MSF es teatro.",
    "Una cadena MS2 cronometrada 25 min. Solo flujo, no 5 módulos.",
    "Cambiar payload 8 veces. O LHOST wlan0 'porque ayer funcionó en un vídeo'.",
    [Q("LHOST Host-Only", ["wlan0", "IP vboxnet medida", "127.0.0.1", "Guest"], 1, "Mide."), Q("0 sessions", ["INE roto", "Flecha/payload/options", "Instala Windows", "Gobuster"], 1, "Debug."), Q("5 módulos 25 min", ["Pro", "Un flujo completo mejor", "Oficial", "TDAH óptimo"], 1, "Uno."), Q("show options", ["Adorno", "Ver required", "NSE", "AXFR"], 1, "Required."), Q("sysinfo cuándo", ["Antes de nmap", "Tras session", "En DVWA", "Con Hydra"], 1, "Post.")],
    "Cadena 25 min", ["Un módulo que coincida. Notas LHOST", "Stop"], "Flujo lento y correcto. El examen no da puntos por pánico."),
  W("c12-d3", 12, 3, "FIX", "Repaso web mínimo", 15, "web-sqli",
    "Comilla, UNION conceptual, 403, LFI passwd, XSS tipo. DVWA 30 min. No PortSwigger entero.",
    "Web vuelve en el cuestionario. 30 min bastan si ya lo tocaste en Mes 2.",
    "DVWA low: 1 SQLi, 1 XSS, 1 LFI. Parar.",
    "Empezar Web Academy completa semana 12.",
    [Q("Semana 12 Web Academy full", ["Plan", "Scope creep", "Obligatorio", "Arregla SMB"], 1, "No."), Q("403", ["No existe", "Existe forbidden", "Root", "SMB"], 1, "Existe."), Q("LFI passwd", ["Windows SAM", "Prueba Linux lectura", "Hydra", "Pivot"], 1, "LFI."), Q("Comilla en id", ["LHOST", "Detección SQLi", "NSE", "ARP"], 1, "SQLi."), Q("30 min DVWA s12", ["Poco", "Mantenimiento correcto", "Sustituye 3 meses", "Trampa"], 1, "Mantén.")],
    "DVWA tríptico", ["SQLi / XSS / LFI una vez cada uno", "Sin nuevas categorías"], "Mantenimiento. Como estirar antes del partido."),
  W("c12-d4", 12, 4, "FIX", "Simulacro final interno", 18, "exam-logistics",
    "Full 15q 20min. Objetivo interno 70% mínimo, 85% confort. No es INE. Si <70, remedia, no reserves el examen por ego.",
    "La reserva del examen real es tuya cuando TÚ veas consistencia (varios simulacros), no cuando la racha sea bonita.",
    "EXAM full. Silencio. Como día D.",
    "Hacerlo 8 veces el mismo día memorizando el sorteo.",
    [Q("70% interno", ["Diploma INE", "Umbral de esta app", "OSCP", "Garantía"], 1, "Interno."), Q("<70 y reservar INE por ego", ["Valiente", "Imprudente", "Método", "TDAH bueno"], 1, "Espera."), Q("Varios simulacros", ["Trampa", "Consistencia", "Inútil", "Solo uno vale"], 1, "Serie."), Q("8 veces el mismo sorteo", ["Maestría", "Memorizar el examen de juguete", "INE", "LHOST"], 1, "Overfit."), Q("Silencio", ["Opcional", "Simula día D", "Prohibido", "Mejor Twitch"], 1, "Simula.")],
    "Un full serio", ["Una pasada. Remedia. No repetición inmediata del mismo set", "Agenda INE solo si TÚ decides"], "El número interno te informa. No te certifica."),
  W("c12-d5", 12, 5, "FIX", "Caja relámpago 40 min", 16, "full-chain",
    "Última cadena lab. Método completo. Parar. Dormir temprano si el examen es pronto.",
    "Confianza de músculo, no de contenido nuevo.",
    "MS2 o Kioptrix. 40 min. Plantilla s10.",
    "Nueva VM 'porque esta ya me la sé' y perderte en importar ova.",
    [Q("Nueva OVA s12 d5", ["Necesaria", "Alto riesgo de caos", "Arregla Hydra", "Oficial"], 1, "No."), Q("40 min", ["Inútil", "Corte de pánico", "Largo de más", "Sustituye INE"], 1, "Corte."), Q("Confianza viene de…", ["Leer más PDF", "Repetir el oficio", "Comprar curso", "Racha sola"], 1, "Oficio."), Q("Dormir", ["Debilidad", "Parte del cierre", "Luego del apt upgrade", "Tras 4 boxes"], 1, "Cierre."), Q("Plantilla s10", ["Vieja", "Úsala", "Cámbiala otra vez", "Tírala"], 1, "Úsala.")],
    "40 min cadena", ["Timer. Plantilla. Stop", "Nada de importar OVAs"], "El último lab es un recordatorio, no una odisea."),
  W("c12-d6", 12, 6, "FIX", "Cierre del trimestre", 15, "exam-logistics",
    "Tres meses: lab, nmap, tools, msf, web, red conceptual, privesc mapa, cadenas, reporting, logística. La disciplina fue tuya. El contenido, esta pista de 78 clases + plan + LEARN + TRAIN.",
    "No hay garantía. Hay preparación. Si suspendes, el oficio queda: remedia y repite INE cuando toque.",
    "Examen curso s12. Lista de 5 fortalezas y 3 huecos honestos.",
    "Borrar el lab 'porque ya examiné'. Puede hacer falta un retake.",
    [Q("Garantía de aprobado", ["Sí con racha 90", "No", "Sí con 78 clases", "Sí con MS2 root"], 1, "No."), Q("Suspender INE", ["Borrar Kali", "Oficio queda; remedia", "Fin", "Culpa de vboxnet"], 1, "Sigue."), Q("Borrar lab al instante", ["Limpio", "Puede hacer falta retake", "Obligatorio", "INE pide"], 1, "Guarda."), Q("78 clases = diploma", ["Sí", "No", "Si 100% quiz", "Si 90 días"], 1, "No."), Q("Huecos honestos hoy", ["Vergüenza", "Plan de retake/repaso", "Hay que esconderlos", "Son LHOST siempre"], 1, "Plan.")],
    "Carta a ti día D", ["5 fortalezas, 3 huecos, 1 frase de alcance", "Guarda el lab"], "Se acabó el trimestre de contenido. Empieza el oficio, con o sin PDF de INE."),
];
