export type ConceptDiagnosis =
  | "knowledge_gap"
  | "terminology"
  | "command_recall"
  | "interpretation"
  | "reasoning"
  | "decision"
  | "execution"
  | "methodology"
  | "retention";

export interface ConceptLesson {
  id: string;
  titleEs: string;
  keywords: string[];
  diagnosis: ConceptDiagnosis;
  needToKnow: string;
  what: string;
  purpose: string;
  whyHere: string;
  how: string;
  example?: string;
  exampleExplain?: string;
  observe?: string;
  applied?: string;
  remember: [string, string] | [string, string, string];
  transferEs?: string;
  deepenHref?: string;
}

/** Mini-lecciones. No incluyen la respuesta de un ítem concreto. */
export const CONCEPT_LESSONS: ConceptLesson[] = [
  {
    id: "nmap-sv",
    titleEs: "Nmap: detección de versiones (-sV)",
    keywords: ["-sv", "sV", "version", "versiones", "banner", "servicio"],
    diagnosis: "command_recall",
    needToKnow: "La pregunta pide identificar qué pregunta hace Nmap cuando quieres saber QUÉ hay detrás de un puerto abierto.",
    what: "Nmap es un escáner. -sV pide servicio y versión en los puertos que ya te importan (ssh OpenSSH x.y, http Apache…).",
    purpose: "Decidir qué enumerar después (SMB vs HTTP vs SSH) y si un match de CVE es hipótesis o ruido.",
    whyHere: "No evalúa ‘lanzar Nmap’. Evalúa si distingues discovery, puertos y versión.",
    how: "Primero hay un host up y puertos. Luego -sV pregunta al servicio. El banner es hipótesis, no un exploit confirmado.",
    example: "nmap -sV 10.10.10.5",
    exampleExplain: "nmap = escáner. -sV = versión. 10.10.10.5 = RHOST (la víctima). Esperas líneas tipo 22/tcp open ssh OpenSSH…",
    observe: "Producto + versión. Open ≠ vulnerable.",
    applied: "Si ves 445/tcp open microsoft-ds, el next step es enumerar SMB, no Gobuster.",
    remember: ["-sV = qué servicio/versión.", "No sustituye -sn (quién está vivo).", "Versión cercana ≠ explotado."],
    transferEs: "Si el output dice 80/tcp open http Apache 2.4, ¿qué enumeras primero y por qué?",
    deepenHref: "/learn/banner-nse",
  },
  {
    id: "nmap-sn",
    titleEs: "Nmap: host discovery (-sn)",
    keywords: ["-sn", "discovery", "vivos", "ping scan", "quién está"],
    diagnosis: "command_recall",
    needToKnow: "Hay que separar ‘quién está vivo’ de ‘qué puertos tiene’.",
    what: "-sn es host discovery: pregunta qué IPs responden en un CIDR. No lista 80/445.",
    purpose: "Acotar el alcance autorizado antes de gastar el reloj en -p- o -sV.",
    whyHere: "La pregunta distingue discovery de enumeración de servicios.",
    how: "Mides el CIDR del lab (vboxnet). nmap -sn ese CIDR. Anotas Kali vs guest.",
    example: "nmap -sn 192.168.56.0/24",
    exampleExplain: "-sn = vivos. El /24 es el alcance. No es un scan de versiones.",
    observe: "IPs up. Identifica cuál eres tú.",
    remember: ["-sn = quién.", "-sV = qué versión.", "No escanees un /8 ‘por si acaso’."],
    deepenHref: "/learn/host-discovery",
  },
  {
    id: "nmap-p-",
    titleEs: "Nmap: puertos (-p- vs default)",
    keywords: ["-p-", "puertos", "1000", "todos los tcp", "port scan"],
    diagnosis: "methodology",
    needToKnow: "El reloj importa: no todos los scans valen igual al inicio.",
    what: "-p- recorre los 65535 TCP. El default de Nmap son ~1000 comunes.",
    purpose: "Encontrar servicios en puertos altos cuando el brief lo sugiere. No como primer comando contra un /24.",
    whyHere: "Evalúa prioridad: vivos → host que importa → puertos, no teatro.",
    how: "Host up primero. Luego default o lista. -p- en UN host, no en toda la LAN el primer minuto.",
    example: "nmap -p- 10.10.10.5",
    exampleExplain: "Un RHOST, todos los TCP. Lento. Úsalo cuando ya sabes que está vivo.",
    remember: ["Open = listener, no exploit.", "-p- no es el primer minuto del examen.", "Un /24 con -p- te come el reloj."],
    deepenHref: "/learn/port-scan",
  },
  {
    id: "host-only",
    titleEs: "Host-Only vs NAT vs Bridged",
    keywords: ["host-only", "bridged", "nat", "vboxnet", "virtualbox"],
    diagnosis: "terminology",
    needToKnow: "El modo de red decide si el ataque llega al guest o a la Wi‑Fi de casa.",
    what: "Host-Only es un switch privado Kali↔guest. NAT = el guest sale a Internet. Bridged = el guest en tu LAN.",
    purpose: "Laboratorio aislado y autorizado. Metasploitable no se ofrece a la familia.",
    whyHere: "La pregunta distingue dónde atacas, no ‘qué es VirtualBox’ en abstracto.",
    how: "Adapter 1 del guest = Host-Only. LHOST = IP de Kali en esa NIC. Ping al guest.",
    observe: "Misma /24. Ping. Ninguna víctima en Bridged.",
    remember: ["Ataque del lab = Host-Only.", "NAT no es RHOST.", "Bridged casi nunca en este plan."],
    deepenHref: "/laboratorio",
  },
  {
    id: "lhost-rhost",
    titleEs: "LHOST y RHOST",
    keywords: ["lhost", "rhost", "rhosts", "127.0.0.1", "wlan0", "loopback"],
    diagnosis: "execution",
    needToKnow: "Un reverse o un módulo mienten si las IPs están mal medidas.",
    what: "LHOST = tu Kali en la NIC que la víctima alcanza (vboxnet). RHOST = IP del guest. 127.0.0.1 eres tú.",
    purpose: "Que el paquete llegue. show options no adivina tu red.",
    whyHere: "Evalúa medición, no memorizar 192.168.56.1 de un blog.",
    how: "ip addr en Kali. IP del guest. Misma /24. Luego set LHOST / RHOSTS.",
    example: "ip addr",
    exampleExplain: "Busca la NIC del lab, no wlan0 ni loopback.",
    remember: ["LHOST se mide.", "RHOST nunca es 127.0.0.1 de Kali.", "Ping antes de Metasploit."],
    deepenHref: "/learn/ipv4",
  },
  {
    id: "smb-enum",
    titleEs: "Enumeración SMB",
    keywords: ["smb", "445", "139", "shares", "enum4linux", "smbclient"],
    diagnosis: "decision",
    needToKnow: "El puerto elige la herramienta: 445 no se dirbustea.",
    what: "SMB comparte archivos/impresoras (139/445). Enumerar = users y shares, no explotar todavía.",
    purpose: "Users que luego sirvan en SSH/FTP. Shares con READ = loot. ACCESS DENIED también es dato.",
    whyHere: "Evalúa next step cuando ves 445, no tu tool favorita.",
    how: "Puerto open → smbclient/enum4linux. Lee el output. Una superficie cada vez.",
    example: "smbclient -L //10.10.10.5 -N",
    exampleExplain: "-N = sin password (null si el server lo permite). IPC$ es normal.",
    applied: "21,22,80,445 open: SMB es una pregunta, HTTP otra. Elige una ahora.",
    remember: ["445 → SMB, no Gobuster.", "Denied es hallazgo.", "Users de SMB pueden reutilizarse."],
    deepenHref: "/learn/smb",
  },
  {
    id: "http-dirs",
    titleEs: "HTTP y directorios",
    keywords: ["gobuster", "403", "80/tcp", "http", "dirs", "dirb"],
    diagnosis: "decision",
    needToKnow: "80/443 hablan HTTP. Gobuster prueba rutas, no shares.",
    what: "HTTP es petición/respuesta. Gobuster fuerza directorios contra un wordlist.",
    purpose: "Encontrar login, uploads, paneles. 403 ≠ fin de superficie.",
    whyHere: "Evalúa si eliges la familia HTTP cuando el puerto es 80.",
    how: "HTTP abierto → gobuster/curl. Cambia extensiones si no es PHP.",
    example: "gobuster dir -u http://10.10.10.5/ -w <wordlist>",
    exampleExplain: "-u = URL. 200/301/403 son resultados. 403 sigue existiendo.",
    remember: ["80 → HTTP.", "403 no es 404.", "No Gobuster a 445."],
    deepenHref: "/learn/web-dirs",
  },
  {
    id: "hydra-user",
    titleEs: "Hydra y usuarios",
    keywords: ["hydra", "brute", "fuerza bruta", "rockyou"],
    diagnosis: "methodology",
    needToKnow: "Sin usuario, brute es ruido y puedes bloquear cuentas.",
    what: "Hydra prueba logins (SSH/FTP/HTTP) cuando YA tienes un user.",
    purpose: "Last resort en lab. No es el primer comando del día.",
    whyHere: "Evalúa disciplina: enum primero, brute después.",
    how: "Copia el user de SMB/FTP. Escribe el comando. Luego, si el alcance lo permite, lánzalo.",
    remember: ["Hydra necesita user.", "No brute a /16.", "El puerto y el user mandan."],
    deepenHref: "/learn/enum-ssh",
  },
  {
    id: "ftp-ssh",
    titleEs: "FTP y SSH: banner y anonymous",
    keywords: ["ftp", "ssh", "anonymous", "puerto 21", "puerto 22", "openssh"],
    diagnosis: "interpretation",
    needToKnow: "Open significa listener, no credenciales.",
    what: "FTP (21) a veces permite anonymous. SSH (22) es shell cifrada: password o key.",
    purpose: "Loot barato (anon) o acceso con user conocido. No dirbustear el 22.",
    whyHere: "Evalúa qué preguntas haces a 21 y 22, no un exploit de memoria.",
    how: "Banner. Anonymous FTP. User de SMB hacia SSH. Hydra solo con user.",
    remember: ["22 open ≠ login.", "Anonymous FTP primero si existe.", "Hydra no adivina el user."],
    deepenHref: "/learn/enum-ssh",
  },
  {
    id: "msf-options",
    titleEs: "Metasploit: show options",
    keywords: ["metasploit", "msf", "show options", "msfconsole", "módulo"],
    diagnosis: "execution",
    needToKnow: "search no es ‘explotado’. Faltan options medidas.",
    what: "Metasploit empaqueta módulos. show options lista required: RHOSTS, a menudo LHOST.",
    purpose: "Un flujo repetible: search → use → options → run → verificar sesión.",
    whyHere: "Evalúa si rellenas IPs reales, no si conoces el nombre del módulo.",
    how: "Servicio+versión primero. use. show options. set. check si existe. run. id/sysinfo.",
    remember: ["Required vacío = fail.", "LHOST = vboxnet.", "Un check verde no es sesión."],
    deepenHref: "/learn/msf-flow",
  },
  {
    id: "reverse-shell",
    titleEs: "Reverse shell vs bind",
    keywords: ["reverse", "bind", "listener", "payload", "handler"],
    diagnosis: "reasoning",
    needToKnow: "Quién inicia el TCP decide si el payload nace.",
    what: "Reverse: la víctima conecta a TU listener (LHOST:LPORT). Bind: tú conectas a un puerto en ella.",
    purpose: "En lab Host-Only ambos pueden valer. Reverse es el patrón típico si hay NAT/firewall hacia dentro.",
    whyHere: "Evalúa dirección de la conexión, no el nombre del CVE.",
    how: "Listener en Kali coincidiendo payload/LPORT. LHOST que el guest pueda alcanzar.",
    remember: ["Reverse sale hacia ti.", "Bind espera en la víctima.", "LHOST mal = silencio."],
    deepenHref: "/learn/revbind",
  },
  {
    id: "sqli",
    titleEs: "SQL injection: el parámetro",
    keywords: ["sqli", "sql injection", "sqlmap", "comilla", "union"],
    diagnosis: "reasoning",
    needToKnow: "80 open no es SQLi. Hace falta un parámetro que llegue a la consulta.",
    what: "La app concatena input en SQL. Una comilla rompe la sintaxis. UNION necesita columnas.",
    purpose: "Extraer datos en un lab que TÚ controlas (DVWA). No contra sitios ajenos.",
    whyHere: "Evalúa detección y método, no sqlmap a ciegas.",
    how: "Ve el request. Prueba el campo a mano. Luego la tool si hay evidencia.",
    remember: ["Sin parámetro no hay SQLi.", "Manual antes de sqlmap.", "DVWA localhost, no el banco."],
    deepenHref: "/learn/sqli",
  },
  {
    id: "xss",
    titleEs: "XSS",
    keywords: ["xss", "script", "reflected", "stored", "innerhtml"],
    diagnosis: "knowledge_gap",
    needToKnow: "XSS ejecuta script en el navegador de la víctima, no en SMB.",
    what: "Inyectas HTML/JS que corre en el contexto de la app. Reflected vs stored cambia persistencia.",
    purpose: "Robar sesión o demostrar impacto en lab. No es un exploit de kernel.",
    whyHere: "Evalúa el modelo (el navegador confía en la página), no un payload famoso.",
    how: "Campo de texto → prueba. Observa si se refleja o se guarda.",
    remember: ["XSS = navegador.", "No es SQLi.", "Lab propio."],
    deepenHref: "/learn/xss",
  },
  {
    id: "lfi",
    titleEs: "LFI / inclusión de ficheros",
    keywords: ["lfi", "rfi", "path traversal", "include", "/etc/passwd", "file="],
    diagnosis: "interpretation",
    needToKnow: "Sin parámetro de path no hay LFI.",
    what: "La app incluye un fichero local según un parámetro (page=, file=).",
    purpose: "Leer ficheros en lab Linux. RFI es inclusión remota: otro problema.",
    whyHere: "Evalúa si identificas inclusión, no un wordlist al azar.",
    how: "Parámetro de fichero. Path conocido. 404 no es ‘casi’.",
    remember: ["Hace falta el parámetro.", "Evidencia, no adivinar.", "404 ≠ LFI."],
    deepenHref: "/learn/lfi",
  },
  {
    id: "privesc",
    titleEs: "Privilege escalation",
    keywords: ["privesc", "sudo -l", "suid", "escalada", "root", "linpeas"],
    diagnosis: "methodology",
    needToKnow: "Sin shell de user no hay privesc. id primero.",
    what: "Pasar de un user bajo a uno más alto en la MISMA máquina.",
    purpose: "Leer lo que el examen pide (flags, hashes) cuando el user no basta.",
    whyHere: "Evalúa orden: acceso → contexto (id, sudo -l) → vector. No un kernel al azar.",
    how: "id. sudo -l. Denied es hallazgo. SUID. Kernel es last resort de lab.",
    remember: ["id primero.", "LinPEAS no razona el examen.", "Denied cuenta."],
    deepenHref: "/learn/privesc-linux-c",
  },
  {
    id: "pivot",
    titleEs: "Pivoting: cuándo",
    keywords: ["pivot", "socks", "port forward", "pivoting", "otra red"],
    diagnosis: "decision",
    needToKnow: "Pivot es conectividad que TÚ no tienes y la víctima sí.",
    what: "Usar un host comprometido como puente hacia una red que Kali no alcanza.",
    purpose: "Enumerar/atacar el interior. Si Kali ya hace ping, no inventes SOCKS.",
    whyHere: "Evalúa el CUÁNDO, no el flag de chisel.",
    how: "Dibuja dos redes. ¿Qué IP ves? ¿Cuál no? Entonces forward/SOCKS.",
    remember: ["Si ya hay ping, no es pivot.", "Otra red = otro CIDR.", "Puente, no magia."],
    deepenHref: "/learn/portfwd",
  },
  {
    id: "scope",
    titleEs: "Alcance y autorización",
    keywords: ["autoriz", "alcance", "wi-fi", "casa", "terceros", "ine"],
    diagnosis: "methodology",
    needToKnow: "Privado ≠ autorizado. eJPT empieza por el brief.",
    what: "Alcance = hosts que TÚ puedes tocar: VMs Host-Only, DVWA local, VPN INE el día del examen.",
    purpose: "No convertir práctica en incidente.",
    whyHere: "Evalúa ética y método, no un flag de Nmap.",
    how: "Nombra dueño y red. Si no puedes, no escaneas.",
    remember: ["Alcance escrito.", "Host-Only / localhost / INE.", "La LAN familiar no entra."],
    deepenHref: "/clase/c00-d1",
  },
  {
    id: "enum-vs-exploit",
    titleEs: "Enumerar vs explotar",
    keywords: ["enumer", "next step", "what next", "prioridad", "vector"],
    diagnosis: "decision",
    needToKnow: "Varios puertos open = varias preguntas, no un único recetario.",
    what: "Enumeración = preguntar al servicio. Explotar = hipótesis con evidencia de versión/acceso.",
    purpose: "El examen premia next step con datos.",
    whyHere: "Evalúa observación → hipótesis → acción, no el binario más cool.",
    how: "Lee el output. Elige UNA superficie. Anota. Luego la otra.",
    applied: "21, 22, 80, 445: FTP anon / SMB users / HTTP dirs. Hydra SSH no es el minuto 1.",
    remember: ["El puerto elige la tool.", "Una superficie 20 min.", "Exploitar es el final del cuento."],
    deepenHref: "/train/decisions",
  },
  {
    id: "dvwa",
    titleEs: "DVWA",
    keywords: ["dvwa", "damn vulnerable"],
    diagnosis: "terminology",
    needToKnow: "DVWA es un gimnasio web, no el examen INE.",
    what: "Damn Vulnerable Web Application: web vulnerable a propósito.",
    purpose: "Practicar SQLi/XSS/LFI en localhost/Docker que TÚ controlas.",
    whyHere: "La pregunta usa DVWA como lab, no como target de Internet.",
    how: "Login de lab, security low, elige la vuln, prueba el parámetro a mano.",
    remember: ["Localhost.", "No publiques el contenedor.", "Manual antes de la tool."],
    deepenHref: "/learn/http-basics",
  },
];

export const DIAGNOSIS_LABEL: Record<ConceptDiagnosis, string> = {
  knowledge_gap: "Conocimiento",
  terminology: "Terminología",
  command_recall: "Recall de comando",
  interpretation: "Interpretación",
  reasoning: "Razonamiento",
  decision: "Decisión",
  execution: "Ejecución",
  methodology: "Metodología",
  retention: "Retención",
};
