import { LearnArticle } from "@/content/learn-types";

/** V9.1: reporting + HTTP/API + lectura de PoC. No es un programa aparte. */
export const LEARN_CATALOG_V91: LearnArticle[] = [
  {
    id: "report-finding",
    track: "REPORTING",
    titleEs: "Finding técnico",
    what: "Un finding es un paquete reproducible: activo afectado, vulnerabilidad, descripción, pasos de reproducción, evidencia (comando/request/output), impacto, severidad y remediation. No es un diario ni un dump de herramienta.",
    why: "eJPT y el trabajo junior piden el valor exacto y que otro analista pueda repetir la prueba en lab. Sin repro, no hay hallazgo.",
    how: "Plantilla: (1) asset (IP, host, ruta), (2) vuln, (3) qué observaste, (4) cómo repetirlo, (5) evidencia recortada, (6) impacto, (7) fix razonable. Screenshots solo de TU lab.",
    when: "Al cerrar un lab o un mock interno. No al final de 40 pestañas de ruido.",
    example: "Asset 192.168.56.20 /item?id=1 — SQLi boolean — request recortado — impacto: lectura de DB de lab — remediation: consultas parametrizadas.",
    mistake: "Pegar sqlmap -vv y llamar a eso un informe.",
    redTeam: "La evidencia es el producto. El exploit es un medio.",
    recall: "¿Un finding necesita pasos de reproducción?",
    recallKeywords: ["si"],
    challenge: "¿'La web es insegura' es un finding completo?",
    challengeKeywords: ["no"],
  },
  {
    id: "report-exec-summary",
    track: "REPORTING",
    titleEs: "Executive summary",
    what: "El resumen ejecutivo dice qué importa para quien no va a copiar el request: riesgo de negocio en una o dos frases. No sustituye el finding técnico.",
    why: "En un examen de preguntas cortas casi no se usa. En un informe de lab interno, evita que el técnico y el resumen se mezclen.",
    how: "Una frase: qué sistema, qué pasa si se abusa (en lab), qué priorizar. Sin jerga de flags.",
    when: "Después de tener findings con evidencia. Nunca al inicio 'para rellenar'.",
    example: "La aplicación de inventario de lab permite lectura de la base vía el parámetro id. Prioridad: parametrizar consultas.",
    mistake: "Un executive summary de tres páginas o uno que copia nmap -p-.",
    redTeam: "Dos audiencias: quien valida y quien prioriza.",
    recall: "¿El executive summary sustituye los pasos de repro?",
    recallKeywords: ["no"],
    challenge: "¿Debes mezclar flags de Nmap en el resumen ejecutivo?",
    challengeKeywords: ["no"],
  },
  {
    id: "http-json",
    track: "WEB",
    titleEs: "HTTP, JSON y parámetros",
    what: "Además de formularios HTML, las apps hablan JSON en el body y query strings. Un endpoint /api/v1/item?id=1 es la misma idea que /item.php?id=1: un parámetro que puedes observar y probar a mano.",
    why: "eJPT y el pentest web junior no son una academia de API Gateways. Sí necesitas no quedarte solo en .php porque el taller usaba DVWA.",
    how: "Burp/ZAP o curl: método, headers, cookies, Content-Type. Si ves JSON, no lances sqlmap a ciegas: identifica el parámetro y prueba un input controlado.",
    when: "Cuando gobuster encuentra /api o el JS llama a XHR. Transfer desde HTTP clásico.",
    example: "GET /api/health → 200 JSON. Luego lista rutas en el JS o fuzz de paths. Auth: cookie o header.",
    mistake: "Asumir que sin login.php no hay autenticación.",
    redTeam: "Unknown app → discover endpoints → identify params → validate.",
    recall: "¿JSON en /api elimina la necesidad de enumerar parámetros?",
    recallKeywords: ["no"],
    challenge: "¿Un 401 en /api es el fin de la superficie?",
    challengeKeywords: ["no"],
  },
  {
    id: "rest-params",
    track: "WEB",
    titleEs: "Recon de API (fundamento)",
    what: "REST típico: recursos y verbos (GET/POST/PUT). La recon busca rutas ocultas, verbos inesperados y authn vs authz (puedes autenticarte y aún no deberías ver el recurso de otro usuario).",
    why: "Útil para eJPT cuando la app no parece DVWA. No es un bootcamp de GraphQL/cloud.",
    how: "Descubre: robots, JS, wordlists, 403. Prueba el verbo. Distingue 401 (quién eres) de 403 (no te toca). IDOR es hipótesis de authz.",
    when: "Tras HTTP enum clásico. Si solo hay un form, no inventes microservicios.",
    example: "GET /api/users/1 vs /2 con la misma cookie. Si cambia el objeto, documenta. Lab únicamente.",
    mistake: "Brute force de API en producción o fuera de alcance.",
    redTeam: "Authn ≠ authz. El parámetro sigue siendo el campo de batalla.",
    recall: "¿Authn y authz son lo mismo?",
    recallKeywords: ["no"],
    challenge: "¿Un token válido implica que puedes leer todos los recursos?",
    challengeKeywords: ["no"],
  },
  {
    id: "poc-read-lab",
    track: "EXPLOITATION",
    titleEs: "Leer un PoC en lab",
    what: "Un PoC o un módulo de Metasploit tiene variables: quién es la víctima, quién escucha el reverse, en qué path vive el CGI. Leer es identificar esos huecos. No es desarrollo de malware.",
    why: "eJPT pide identificar/modificar exploits en el sentido de adaptar IPs y opciones, no escribir un 0-day.",
    how: "Busca RHOST, LHOST, LPORT, TARGETURI, path. Sustituye CHANGE_ME por ip addr de TU NIC de lab. Si falla: versión, path, o LHOST en la NIC incorrecta — no 'otro CVE'.",
    when: "Cuando searchsploit o MSF te dan un candidato alineado con un banner medido.",
    example: "path = /cgi-bin/x en el PoC, pero tu gobuster encontró /cgi-bin/old. Adaptas el path, no inventas un kernel exploit.",
    mistake: "Run a ciegas o usar el PoC fuera del lab.",
    redTeam: "Metasploit automatiza opciones. Tú sigues siendo quien mide LHOST.",
    recall: "¿CHANGE_ME se deja en el PoC?",
    recallKeywords: ["no"],
    challenge: "¿Un PoC sustituye medir la NIC del lab?",
    challengeKeywords: ["no"],
  },
];
