import type { CommandCard } from "@/content/command-bank";

const h = (a: string, b: string, c: string, d: string, e: string): CommandCard["hints"] => [a, b, c, d, e];

/** SRS V9.1: metodología / next-step / interpretación. No sustituye el banco. */
export const SRS_V91: CommandCard[] = [
  {
    id: "nmap-8080-next",
    category: "Nmap",
    subtopicId: "nmap-versioning",
    fragment: "8080 next",
    toolAnswer: "version",
    toolQuestionEs: "Nmap detecta un servicio desconocido en 8080. ¿Qué información necesitas ANTES de explotación?",
    toolQuestionEn: "Unknown service on 8080. What do you need before exploitation?",
    paramQuestionEs: "¿Qué flag de Nmap pide versiones/servicios?",
    paramQuestionEn: "Which Nmap flag asks for service/version?",
    paramAnswer: "-sV",
    fullQuestionEs: "¿Qué comando (concepto) pide versiones en puertos conocidos?",
    fullQuestionEn: "Which command asks for versions on discovered ports?",
    fullAnswer: "nmap -sV",
    conceptQuestionEs: "¿8080 open implica automáticamente Tomcat explotable?",
    conceptQuestionEn: "Does 8080 open mean exploitable Tomcat?",
    conceptKeywords: ["no"],
    explanationEs: "Necesitas servicio/versión, HTTP enum si es web, y una hipótesis. No un exploit por el número de puerto.",
    hints: h(
      "No sabes qué habla en 8080.",
      "Pide versiones, no un CVE.",
      "nmap -sV",
      "nmap -sV <host>",
      "Versión → hipótesis. 8080 no es un exploit."
    ),
  },
  {
    id: "smb-next-after-shares",
    category: "SMB",
    subtopicId: "smb-manual",
    fragment: "shares next",
    toolAnswer: "read",
    toolQuestionEs: "Tras listar shares (public READ, ADMIN$ DENIED), ¿qué next step no es 'explotar ADMIN$'?",
    toolQuestionEn: "After listing shares, what is the next step that is not exploiting ADMIN$?",
    paramQuestionEs: "Herramienta típica para listar shares (nombre):",
    paramQuestionEn: "Typical share-listing tool name:",
    paramAnswer: "smbclient",
    fullQuestionEs: "Comando conceptual para listar shares de un host (smbclient -L).",
    fullQuestionEn: "Typical share listing command family.",
    fullAnswer: "smbclient -L",
    conceptQuestionEs: "¿ACCESS DENIED en ADMIN$ es evidencia o un error de tool?",
    conceptQuestionEn: "Is ACCESS DENIED on ADMIN$ evidence or a tool error?",
    conceptKeywords: ["evidencia", "hallazgo", "denied"],
    explanationEs: "Lees public. Denied es hallazgo. No insistas en ADMIN$ por el nombre.",
    hints: h("Hay un share legible.", "Denied no es un 404 de tool.", "smbclient", "smbclient -L", "Loot public; anota denied."),
  },
  {
    id: "web-403-meaning",
    category: "Web",
    subtopicId: "gobuster-dir",
    fragment: "403",
    toolAnswer: "forbidden",
    toolQuestionEs: "Gobuster muestra 403 en /admin. ¿Eso termina la superficie HTTP?",
    toolQuestionEn: "Gobuster 403 on /admin. Does HTTP enum stop?",
    paramQuestionEs: "Código HTTP de 'existe pero no te dejan':",
    paramQuestionEn: "HTTP code for exists-but-forbidden:",
    paramAnswer: "403",
    fullQuestionEs: "¿Qué código anotas como hallazgo (no como fin)?",
    fullQuestionEn: "Which status do you record as a finding?",
    fullAnswer: "403",
    conceptQuestionEs: "¿403 significa que el directorio no existe?",
    conceptQuestionEn: "Does 403 mean the directory does not exist?",
    conceptKeywords: ["no"],
    explanationEs: "403 = el recurso existe con control de acceso. Sigue dirs/params/auth.",
    hints: h("¿Existe el recurso?", "Forbidden ≠ 404.", "403", "403", "Anota /admin y sigue enumerando."),
  },
  {
    id: "report-evidence-field",
    category: "Reporting",
    subtopicId: "reporting",
    fragment: "evidence",
    toolAnswer: "repro",
    toolQuestionEs: "Un finding eJPT-style debe permitir reproducir el resultado. ¿Qué falta si solo escribes 'SQLi'?",
    toolQuestionEn: "What is missing if you only write 'SQLi'?",
    paramQuestionEs: "Campo mínimo además del nombre de la vuln (asset o repro):",
    paramQuestionEn: "Minimum extra field besides vuln name:",
    paramAnswer: "asset",
    fullQuestionEs: "¿Qué identificas primero en un finding (IP/host/ruta)?",
    fullQuestionEn: "What do you identify first in a finding?",
    fullAnswer: "asset",
    conceptQuestionEs: "¿Un ensayo largo sustituye el string exacto de la pregunta?",
    conceptQuestionEn: "Does a long essay replace the exact answer string?",
    conceptKeywords: ["no"],
    explanationEs: "Asset + repro + evidencia. Pregunta corta → string exacto.",
    hints: h("¿Dónde está el bug?", "IP y ruta.", "asset", "asset", "Asset, repro, evidencia, impacto."),
  },
  {
    id: "hash-when-crack",
    category: "Metasploit",
    subtopicId: "msf-hashdump",
    fragment: "crack vs use",
    toolAnswer: "offline",
    toolQuestionEs: "Tienes un hash NTLM de lab. ¿Crackear es siempre el next step?",
    toolQuestionEn: "Is cracking always the next step for an NTLM hash?",
    paramQuestionEs: "¿El hash es la contraseña en claro? (sí/no)",
    paramQuestionEn: "Is a hash the plaintext password?",
    paramAnswer: "no",
    fullQuestionEs: "Respuesta corta: ¿un hash es plaintext?",
    fullQuestionEn: "Is a hash plaintext?",
    fullAnswer: "no",
    conceptQuestionEs: "¿Alcance escrito aplica a hashes y cracking?",
    conceptQuestionEn: "Does written scope apply to hashes and cracking?",
    conceptKeywords: ["si"],
    explanationEs: "A veces reutilizar el secreto (lab) cambia el next step más que crackear 12 horas. Offline vs auth: decide con el objetivo.",
    hints: h("¿Cuál es el objetivo del brief?", "Hash ≠ password.", "no", "no", "Decide crack vs reutilización según el objetivo y el alcance."),
  },
];
