import { SRS_V8 } from "@/content/v8/srs-extra";
import { SRS_V91 } from "@/content/v91/srs";

export interface CommandCard {
  id: string;
  category:
    | "Nmap"
    | "SMB"
    | "Web"
    | "Hydra"
    | "Metasploit"
    | "Meterpreter"
    | "Lab"
    | "Linux"
    | "Windows"
    | "Pivot"
    | "PrivEsc"
    | "Reporting"
    | "Exam"
    | "OSINT"
    | "ExploitMod"
    | "Chains";
  subtopicId: string;
  /** Short command fragment, e.g. nmap -sn */
  fragment: string;
  toolAnswer: string;
  toolQuestionEs: string;
  toolQuestionEn: string;
  paramQuestionEs: string;
  paramQuestionEn: string;
  paramAnswer: string;
  fullQuestionEs: string;
  fullQuestionEn: string;
  fullAnswer: string;
  conceptQuestionEs: string;
  conceptQuestionEn: string;
  conceptKeywords: string[];
  explanationEs: string;
  hints: [string, string, string, string, string];
}

export const COMMAND_BANK_CORE: CommandCard[] = [
  {
    id: "nmap-sn",
    category: "Nmap",
    subtopicId: "nmap-basic",
    fragment: "nmap -sn",
    toolAnswer: "nmap",
    toolQuestionEs: "¿Qué herramienta usarías para descubrir hosts vivos?",
    toolQuestionEn: "Which tool would you use for host discovery?",
    paramQuestionEs: "¿Qué flag hace host discovery SIN escanear puertos?",
    paramQuestionEn: "Which flag does host discovery without port scanning?",
    paramAnswer: "-sn",
    fullQuestionEs: "Descubre hosts vivos en 192.168.56.0/24.",
    fullQuestionEn: "Discover live hosts on 192.168.56.0/24.",
    fullAnswer: "nmap -sn 192.168.56.0/24",
    conceptQuestionEs: "¿Qué hace -sn? (en inglés o español: host discovery / no ports)",
    conceptQuestionEn: "What does -sn do?",
    conceptKeywords: ["host"],
    explanationEs:
      "-sV identifica versiones de servicios. En esta fase todavía no enumeras servicios: primero hay que saber qué hosts están vivos (host discovery).",
    hints: [
      "Antes de enumerar servicios, confirma qué máquinas responden en la red.",
      "Nmap puede hacer un barrido que no toca puertos TCP.",
      "La herramienta es nmap. Busca el flag de ping-scan / host discovery.",
      "nmap -sn 192.168.56.0/24",
      "Host discovery only: nmap -sn <range>. Not -sV.",
    ],
  },
  {
    id: "nmap-p-",
    category: "Nmap",
    subtopicId: "nmap-basic",
    fragment: "nmap -p-",
    toolAnswer: "nmap",
    toolQuestionEs: "¿Qué herramienta escanea puertos TCP?",
    toolQuestionEn: "Which tool scans TCP ports?",
    paramQuestionEs: "¿Qué flag escanea TODOS los puertos TCP (no solo top 1000)?",
    paramQuestionEn: "Which flag scans ALL TCP ports?",
    paramAnswer: "-p-",
    fullQuestionEs: "Escanea todos los TCP de 192.168.56.101 con detección de versión.",
    fullQuestionEn: "Scan all TCP ports on 192.168.56.101 with version detection.",
    fullAnswer: "nmap -p- -sV 192.168.56.101",
    conceptQuestionEs: "¿Por qué -p- y no el default?",
    conceptQuestionEn: "Why -p- instead of the default?",
    conceptKeywords: ["all"],
    explanationEs:
      "Sin -p- Nmap solo prueba el top 1000. Un servicio en un puerto alto no aparece. -sV es versión, no sustituye a -p-.",
    hints: [
      "El default de Nmap no cubre los 65535 puertos.",
      "Hay un flag que significa 'todo el rango TCP'.",
      "Usa nmap con -p- y -sV.",
      "nmap -p- -sV 192.168.56.101",
      "Full TCP + versions: nmap -p- -sV <IP>",
    ],
  },
  {
    id: "nmap-sv",
    category: "Nmap",
    subtopicId: "nmap-versioning",
    fragment: "nmap -sV",
    toolAnswer: "nmap",
    toolQuestionEs: "¿Con qué herramienta ves la versión de un servicio?",
    toolQuestionEn: "Which tool fingerprints service versions?",
    paramQuestionEs: "Flag de service version detection:",
    paramQuestionEn: "Flag for service version detection:",
    paramAnswer: "-sV",
    fullQuestionEs: "Versiones en 192.168.56.101 (puertos por defecto).",
    fullQuestionEn: "Version detection on 192.168.56.101 (default ports).",
    fullAnswer: "nmap -sV 192.168.56.101",
    conceptQuestionEs: "¿Cuándo usas -sV y no -sn?",
    conceptQuestionEn: "When do you use -sV instead of -sn?",
    conceptKeywords: ["version"],
    explanationEs:
      "-sn no toca puertos. -sV habla con el servicio para leer el banner/versión. Solo después de saber que el host está vivo.",
    hints: [
      "Ya tienes un host vivo. Ahora quieres saber QUÉ corre en el puerto.",
      "Nmap puede preguntar la versión al servicio.",
      "Flag -sV.",
      "nmap -sV 192.168.56.101",
      "Service version detection: nmap -sV <IP>",
    ],
  },
  {
    id: "nmap-sc",
    category: "Nmap",
    subtopicId: "nmap-scripts",
    fragment: "nmap -sC",
    toolAnswer: "nmap",
    toolQuestionEs: "¿Qué herramienta corre scripts NSE default?",
    toolQuestionEn: "Which tool runs default NSE scripts?",
    paramQuestionEs: "Flag de scripts default:",
    paramQuestionEn: "Default NSE scripts flag:",
    paramAnswer: "-sC",
    fullQuestionEs: "Scripts default + versión contra 192.168.56.101.",
    fullQuestionEn: "Default scripts + version detection against 192.168.56.101.",
    fullAnswer: "nmap -sC -sV 192.168.56.101",
    conceptQuestionEs: "¿-sC es lo mismo que --script vuln?",
    conceptQuestionEn: "Is -sC the same as --script vuln?",
    conceptKeywords: ["default"],
    explanationEs:
      "-sC son scripts default (más seguros/generales). --script vuln busca CVEs: más ruidoso y distinto.",
    hints: [
      "NSE tiene una categoría 'default' y otra 'vuln'.",
      "El atajo de default es un flag corto -sC.",
      "Combínalo con -sV.",
      "nmap -sC -sV 192.168.56.101",
      "nmap -sC -sV <IP>",
    ],
  },
  {
    id: "nmap-oa",
    category: "Nmap",
    subtopicId: "nmap-basic",
    fragment: "nmap -oA",
    toolAnswer: "nmap",
    toolQuestionEs: "¿Cómo guardas la salida de Nmap en 3 formatos a la vez?",
    toolQuestionEn: "How do you save Nmap output in all 3 formats?",
    paramQuestionEs: "Flag para los 3 formatos (.nmap .xml .gnmap):",
    paramQuestionEn: "Flag for all 3 output formats:",
    paramAnswer: "-oA",
    fullQuestionEs: "Escanea 192.168.56.101 y guarda como ms2 con -oA.",
    fullQuestionEn: "Scan 192.168.56.101 and save as ms2 with -oA.",
    fullAnswer: "nmap -sV 192.168.56.101 -oA ms2",
    conceptQuestionEs: "¿Qué archivos crea -oA nombre?",
    conceptQuestionEn: "What files does -oA name create?",
    conceptKeywords: ["xml"],
    explanationEs: "-oN es texto, -oX XML, -oG greppable. -oA escribe los tres con el mismo prefijo.",
    hints: [
      "No copies la terminal a mano. Nmap puede serializar el scan.",
      "Hay un flag que vuelca tres extensiones a la vez.",
      "-oA <prefijo>",
      "nmap -sV 192.168.56.101 -oA ms2",
      "nmap ... -oA <basename>",
    ],
  },
  {
    id: "nmap-ss",
    category: "Nmap",
    subtopicId: "nmap-basic",
    fragment: "nmap -sS",
    toolAnswer: "nmap",
    toolQuestionEs: "¿Qué herramienta hace un SYN scan TCP?",
    toolQuestionEn: "Which tool does a TCP SYN scan?",
    paramQuestionEs: "Flag del SYN / half-open scan:",
    paramQuestionEn: "Flag for SYN / half-open scan:",
    paramAnswer: "-sS",
    fullQuestionEs: "SYN scan -T4 todos los TCP a 192.168.56.101 (root).",
    fullQuestionEn: "SYN scan -T4 all TCP ports on 192.168.56.101 (root).",
    fullAnswer: "sudo nmap -sS -T4 -p- 192.168.56.101",
    conceptQuestionEs: "¿-sS es lo mismo que -sT?",
    conceptQuestionEn: "Is -sS the same as -sT?",
    conceptKeywords: ["no"],
    explanationEs:
      "-sS es SYN (root, half-open). -sT completa el handshake y no necesita root. -sU es UDP, otro mundo.",
    hints: [
      "Quieres TCP habitual en Kali root, no UDP.",
      "Half-open = no completes el handshake.",
      "sudo nmap -sS. Timing -T4. Puertos -p-.",
      "sudo nmap -sS -T4 -p- 192.168.56.101",
      "Sin root usa -sT, no insistas en -sS.",
    ],
  },
  {
    id: "nmap-ftp-anon",
    category: "Nmap",
    subtopicId: "ftp-ssh-enum",
    fragment: "ftp-anon",
    toolAnswer: "nmap",
    toolQuestionEs: "¿Con qué herramienta preguntas si FTP acepta anonymous?",
    toolQuestionEn: "Which tool checks anonymous FTP?",
    paramQuestionEs: "Script NSE + puerto FTP:",
    paramQuestionEn: "NSE script + FTP port:",
    paramAnswer: "ftp-anon",
    fullQuestionEs: "¿Anonymous FTP en 192.168.56.101?",
    fullQuestionEn: "Anonymous FTP on 192.168.56.101?",
    fullAnswer: "nmap --script ftp-anon -p21 192.168.56.101",
    conceptQuestionEs: "¿Hydra es el primer paso en el puerto 21?",
    conceptQuestionEn: "Is Hydra the first step on port 21?",
    conceptKeywords: ["no"],
    explanationEs: "Primero anonymous (ftp o ftp-anon). Hydra si hay usuario y anonymous falló. No Gobuster.",
    hints: [
      "21/tcp. Pregunta: ¿entra sin cuenta real?",
      "NSE tiene un script con 'anon' en el nombre.",
      "nmap --script … -p21",
      "nmap --script ftp-anon -p21 192.168.56.101",
      "Luego ftp IP con usuario anonymous. No exploit hoy.",
    ],
  },
  {
    id: "enum4linux-a",
    category: "SMB",
    subtopicId: "enum4linux",
    fragment: "enum4linux -a",
    toolAnswer: "enum4linux",
    toolQuestionEs: "¿Qué herramienta enumera usuarios/shares SMB de forma automática?",
    toolQuestionEn: "Which tool auto-enumerates SMB users/shares?",
    paramQuestionEs: "Flag para enumeración COMPLETA:",
    paramQuestionEn: "Flag for a full enumeration:",
    paramAnswer: "-a",
    fullQuestionEs: "Enumeración SMB completa contra 192.168.56.101.",
    fullQuestionEn: "Full SMB enumeration against 192.168.56.101.",
    fullAnswer: "enum4linux -a 192.168.56.101",
    conceptQuestionEs: "¿Gobuster sirve para listar usuarios SMB?",
    conceptQuestionEn: "Does Gobuster list SMB users?",
    conceptKeywords: ["no"],
    explanationEs:
      "Gobuster busca rutas HTTP. Hydra prueba passwords. SMB usuarios/shares = enum4linux (o smbclient). No mezcles la superficie.",
    hints: [
      "El puerto 445 está abierto. Antes de explotar, extrae información sin autenticación.",
      "Hay una herramienta Linux clásica solo para SMB/RPC.",
      "enum4linux con el flag de 'all'.",
      "enum4linux -a 192.168.56.101",
      "enum4linux -a <IP>",
    ],
  },
  {
    id: "smbclient-l",
    category: "SMB",
    subtopicId: "smb-manual",
    fragment: "smbclient -L",
    toolAnswer: "smbclient",
    toolQuestionEs: "¿Con qué herramienta listas shares como si fuera FTP?",
    toolQuestionEn: "Which tool lists SMB shares (FTP-like)?",
    paramQuestionEs: "Flag para listar shares + sesión nula:",
    paramQuestionEn: "Flag to list shares with a null session:",
    paramAnswer: "-L",
    fullQuestionEs: "Lista shares de 192.168.56.101 sin password.",
    fullQuestionEn: "List shares on 192.168.56.101 with a null session.",
    fullAnswer: "smbclient -L 192.168.56.101 -N",
    conceptQuestionEs: "¿Qué hace -N?",
    conceptQuestionEn: "What does -N do?",
    conceptKeywords: ["pass"],
    explanationEs: "-L lista. -N no pide password (null session). No es Hydra ni Gobuster.",
    hints: [
      "Quieres ENTRAR a ver carpetas compartidas, no solo un resumen.",
      "Cliente SMB tipo FTP en Kali.",
      "smbclient -L ... -N",
      "smbclient -L 192.168.56.101 -N",
      "smbclient -L <IP> -N",
    ],
  },
  {
    id: "smbmap",
    category: "SMB",
    subtopicId: "smb-manual",
    fragment: "smbmap -H",
    toolAnswer: "smbmap",
    toolQuestionEs: "¿Qué herramienta muestra permisos READ/WRITE de cada share?",
    toolQuestionEn: "Which tool shows READ/WRITE on each share?",
    paramQuestionEs: "Flag del host:",
    paramQuestionEn: "Host flag:",
    paramAnswer: "-H",
    fullQuestionEs: "Permisos de shares en 192.168.56.101.",
    fullQuestionEn: "Share permissions on 192.168.56.101.",
    fullAnswer: "smbmap -H 192.168.56.101",
    conceptQuestionEs: "¿enum4linux sustituye a smbmap para permisos?",
    conceptQuestionEn: "Does enum4linux replace smbmap for permissions?",
    conceptKeywords: ["no"],
    explanationEs: "smbmap resume READ/WRITE por share. enum4linux -a es más amplio pero menos claro en ACL.",
    hints: [
      "Necesitas saber si un share es escribible.",
      "Herramienta cuyo nombre es map de SMB.",
      "smbmap -H <IP>",
      "smbmap -H 192.168.56.101",
      "smbmap -H <IP>",
    ],
  },
  {
    id: "gobuster-dir",
    category: "Web",
    subtopicId: "gobuster-dir",
    fragment: "gobuster dir",
    toolAnswer: "gobuster",
    toolQuestionEs: "¿Qué herramienta usa fuerza bruta de directorios web?",
    toolQuestionEn: "Which tool brute-forces web directories?",
    paramQuestionEs: "Flag de la wordlist:",
    paramQuestionEn: "Wordlist flag:",
    paramAnswer: "-w",
    fullQuestionEs: "Directorios en http://192.168.56.101 con dirb/common.txt",
    fullQuestionEn: "Brute-force dirs on http://192.168.56.101 with dirb/common.txt",
    fullAnswer: "gobuster dir -u http://192.168.56.101 -w /usr/share/wordlists/dirb/common.txt",
    conceptQuestionEs: "¿Hydra busca /admin oculto en un sitio?",
    conceptQuestionEn: "Does Hydra find a hidden /admin path?",
    conceptKeywords: ["no"],
    explanationEs: "Rutas/archivos = Gobuster. Credenciales de login = Hydra. SMB = enum4linux.",
    hints: [
      "Estás buscando RUTAS en HTTP, no passwords.",
      "Modo dir + URL + wordlist.",
      "gobuster dir -u ... -w ...",
      "gobuster dir -u http://192.168.56.101 -w /usr/share/wordlists/dirb/common.txt",
      "gobuster dir -u <url> -w <wordlist>",
    ],
  },
  {
    id: "gobuster-x",
    category: "Web",
    subtopicId: "gobuster-dir",
    fragment: "gobuster -x",
    toolAnswer: "gobuster",
    toolQuestionEs: "¿Qué herramienta brutea archivos web por extensión?",
    toolQuestionEn: "Which tool brute-forces web files by extension?",
    paramQuestionEs: "Flag de extensiones (php,txt):",
    paramQuestionEn: "Extensions flag (php,txt):",
    paramAnswer: "-x",
    fullQuestionEs: "Dirs + php,txt en http://192.168.56.101 con dirb/common.txt",
    fullQuestionEn: "Dirs + php,txt on http://192.168.56.101 with dirb/common.txt",
    fullAnswer:
      "gobuster dir -u http://192.168.56.101 -w /usr/share/wordlists/dirb/common.txt -x php,txt",
    conceptQuestionEs: "¿-x busca usuarios SMB?",
    conceptQuestionEn: "Does -x find SMB users?",
    conceptKeywords: ["no"],
    explanationEs: "-x son extensiones HTTP. SMB es enum4linux. Passwords son Hydra.",
    hints: [
      "Ya tienes dir -u -w. Faltan archivos, no carpetas.",
      "Un flag corto lista extensiones separadas por coma.",
      "-x php,txt",
      "gobuster dir -u http://192.168.56.101 -w /usr/share/wordlists/dirb/common.txt -x php,txt",
      "gobuster dir -u <url> -w <wl> -x php,txt",
    ],
  },
  {
    id: "hydra-ssh",
    category: "Hydra",
    subtopicId: "hydra-bruteforce",
    fragment: "hydra -l -P",
    toolAnswer: "hydra",
    toolQuestionEs: "¿Qué herramienta hace brute-force de credenciales de un servicio?",
    toolQuestionEn: "Which tool brute-forces service credentials?",
    paramQuestionEs: "Flag de UN usuario (no lista):",
    paramQuestionEn: "Flag for a SINGLE username:",
    paramAnswer: "-l",
    fullQuestionEs: "Brute SSH user admin con rockyou contra 192.168.56.101",
    fullQuestionEn: "Brute SSH as admin with rockyou against 192.168.56.101",
    fullAnswer: "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://192.168.56.101",
    conceptQuestionEs: "¿-L es un usuario o una lista?",
    conceptQuestionEn: "Is -L one user or a list?",
    conceptKeywords: ["list"],
    explanationEs: "-l un user, -L lista. -p un password, -P lista. Gobuster no prueba SSH.",
    hints: [
      "Tienes un LOGIN (SSH), no un directorio web.",
      "Fuerza bruta de credenciales.",
      "hydra -l user -P wordlist ssh://IP",
      "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://192.168.56.101",
      "hydra -l <user> -P <file> ssh://<IP>",
    ],
  },
  {
    id: "hydra-t",
    category: "Hydra",
    subtopicId: "hydra-bruteforce",
    fragment: "hydra -t",
    toolAnswer: "hydra",
    toolQuestionEs: "¿Qué herramienta brutea logins y puede limitar hilos?",
    toolQuestionEn: "Which tool brute-forces logins and can limit threads?",
    paramQuestionEs: "Flag de número de tareas en paralelo:",
    paramQuestionEn: "Parallel tasks flag:",
    paramAnswer: "-t",
    fullQuestionEs: "FTP users.txt + passwords.txt, 4 threads, 192.168.56.101",
    fullQuestionEn: "FTP users.txt + passwords.txt, 4 threads, 192.168.56.101",
    fullAnswer: "hydra -L users.txt -P passwords.txt -t 4 ftp://192.168.56.101",
    conceptQuestionEs: "¿-t 64 es buena idea en MS2?",
    conceptQuestionEn: "Is -t 64 a good idea on MS2?",
    conceptKeywords: ["no"],
    explanationEs: "-t 4 en lab. -L/-P listas. ftp:// no es Gobuster. rockyou entero tampoco.",
    hints: [
      "El guest se cae con demasiados hilos.",
      "Flag corto de threads.",
      "-t 4 junto a -L -P ftp://",
      "hydra -L users.txt -P passwords.txt -t 4 ftp://192.168.56.101",
      "hydra -L … -P … -t 4 ftp://<IP>",
    ],
  },
  {
    id: "msf-search",
    category: "Metasploit",
    subtopicId: "msf-search-use",
    fragment: "search",
    toolAnswer: "search",
    toolQuestionEs: "En msfconsole, ¿qué comando busca un módulo?",
    toolQuestionEn: "In msfconsole, which command finds a module?",
    paramQuestionEs: "Comando para seleccionar el módulo vsftpd backdoor (ruta):",
    paramQuestionEn: "Command to select the vsftpd backdoor module (path):",
    paramAnswer: "use exploit/unix/ftp/vsftpd_234_backdoor",
    fullQuestionEs: "Busca módulos eternalblue.",
    fullQuestionEn: "Search modules related to eternalblue.",
    fullAnswer: "search eternalblue",
    conceptQuestionEs: "¿search lanza el exploit?",
    conceptQuestionEn: "Does search launch the exploit?",
    conceptKeywords: ["no"],
    explanationEs: "search solo lista. Después: use → show options → set → exploit.",
    hints: [
      "Estás DENTRO de msfconsole, no en la shell de Kali.",
      "Primero localizas el módulo por nombre.",
      "El comando es search.",
      "search eternalblue",
      "search <term> then use <path>",
    ],
  },
  {
    id: "msf-options",
    category: "Metasploit",
    subtopicId: "msf-options",
    fragment: "show options",
    toolAnswer: "show options",
    toolQuestionEs: "¿Qué comando lista RHOSTS/LHOST requeridos?",
    toolQuestionEn: "Which command lists required RHOSTS/LHOST?",
    paramQuestionEs: "Asigna la víctima 192.168.56.101:",
    paramQuestionEn: "Set the victim 192.168.56.101:",
    paramAnswer: "set RHOSTS 192.168.56.101",
    fullQuestionEs: "Muestra las opciones del módulo activo.",
    fullQuestionEn: "Show options of the current module.",
    fullAnswer: "show options",
    conceptQuestionEs: "RHOSTS es ¿atacante o víctima?",
    conceptQuestionEn: "Is RHOSTS the attacker or the victim?",
    conceptKeywords: ["victim"],
    explanationEs: "RHOSTS = víctima. LHOST = tu Kali (vboxnet0). No los intercambies.",
    hints: [
      "Antes de exploit, revisa qué parámetros están vacíos.",
      "El comando tiene dos palabras: show ____.",
      "show options",
      "show options",
      "show options then set RHOSTS / LHOST",
    ],
  },
  {
    id: "msf-lhost",
    category: "Metasploit",
    subtopicId: "msf-lhost-lport",
    fragment: "set LHOST",
    toolAnswer: "set LHOST",
    toolQuestionEs: "¿Qué variable es TU IP (reverse shell vuelve aquí)?",
    toolQuestionEn: "Which option is YOUR IP (reverse shell calls back here)?",
    paramQuestionEs: "set LHOST a 192.168.56.1",
    paramQuestionEn: "set LHOST to 192.168.56.1",
    paramAnswer: "set LHOST 192.168.56.1",
    fullQuestionEs: "Configura LHOST 192.168.56.1 y LPORT 4444 (dos líneas con / ).",
    fullQuestionEn: "Set LHOST 192.168.56.1 and LPORT 4444 (two commands joined by /).",
    fullAnswer: "set LHOST 192.168.56.1 / set LPORT 4444",
    conceptQuestionEs: "Si pones la IP de la víctima en LHOST, ¿qué pasa?",
    conceptQuestionEn: "If you put the victim IP in LHOST, what happens?",
    conceptKeywords: ["shell"],
    explanationEs: "La reverse shell intenta conectar a la víctima, no a ti. La sesión nunca llega.",
    hints: [
      "Reverse shell = la víctima llama a TU teléfono.",
      "Local Host = atacante.",
      "set LHOST <tu vboxnet0>",
      "set LHOST 192.168.56.1",
      "LHOST=attacker LPORT=listener RHOSTS=victim",
    ],
  },
  {
    id: "msf-handler",
    category: "Metasploit",
    subtopicId: "msf-multihandler",
    fragment: "use exploit/multi/handler",
    toolAnswer: "use exploit/multi/handler",
    toolQuestionEs: "¿Qué módulo es el listener genérico?",
    toolQuestionEn: "Which module is the generic listener?",
    paramQuestionEs: "Selecciona multi/handler:",
    paramQuestionEn: "Select multi/handler:",
    paramAnswer: "use exploit/multi/handler",
    fullQuestionEs: "Selecciona el listener multi/handler.",
    fullQuestionEn: "Select the multi/handler listener.",
    fullAnswer: "use exploit/multi/handler",
    conceptQuestionEs: "¿El payload del handler debe coincidir con msfvenom?",
    conceptQuestionEn: "Must the handler payload match msfvenom?",
    conceptKeywords: ["yes"],
    explanationEs: "Mismo payload, LHOST y LPORT que el .elf/.exe. Si no, no hay sesión.",
    hints: [
      "El payload lo ejecutaste FUERA de un exploit. Necesitas quien ESCUCHE.",
      "Módulo multi/handler.",
      "use exploit/multi/handler",
      "use exploit/multi/handler",
      "use exploit/multi/handler then set payload/LHOST/LPORT",
    ],
  },
  {
    id: "meter-sysinfo",
    category: "Meterpreter",
    subtopicId: "msf-sysinfo",
    fragment: "sysinfo",
    toolAnswer: "sysinfo",
    toolQuestionEs: "En meterpreter, ¿comando de OS/hostname?",
    toolQuestionEn: "In meterpreter, OS/hostname command?",
    paramQuestionEs: "¿Con qué usuario estás? (comando)",
    paramQuestionEn: "Which user are you? (command)",
    paramAnswer: "getuid",
    fullQuestionEs: "Muestra info del sistema en meterpreter.",
    fullQuestionEn: "Show target system info in meterpreter.",
    fullAnswer: "sysinfo",
    conceptQuestionEs: "¿hashdump funciona siempre?",
    conceptQuestionEn: "Does hashdump always work?",
    conceptKeywords: ["priv"],
    explanationEs: "sysinfo no necesita SYSTEM. hashdump sí (SAM). En Linux no hay SAM.",
    hints: [
      "Ya tienes sesión meterpreter. Recon post-explotación básico.",
      "Un comando, una palabra, info del OS.",
      "sysinfo",
      "sysinfo",
      "sysinfo then getuid then hashdump if Windows + privs",
    ],
  },
  {
    id: "curl",
    category: "Web",
    subtopicId: "web-sqli",
    fragment: "curl",
    toolAnswer: "curl",
    toolQuestionEs: "¿Qué herramienta pides HTTP desde la terminal?",
    toolQuestionEn: "Which tool fetches HTTP from the terminal?",
    paramQuestionEs: "Flag para seguir redirects:",
    paramQuestionEn: "Follow redirects flag:",
    paramAnswer: "-L",
    fullQuestionEs: "GET de http://192.168.56.101/ (simple).",
    fullQuestionEn: "GET http://192.168.56.101/",
    fullAnswer: "curl http://192.168.56.101/",
    conceptQuestionEs: "¿curl sustituye a Gobuster para directorios ocultos?",
    conceptQuestionEn: "Does curl replace Gobuster for hidden dirs?",
    conceptKeywords: ["no"],
    explanationEs: "curl pide UNA URL. Gobuster prueba miles de rutas.",
    hints: [
      "Quieres ver la respuesta HTTP cruda.",
      "Cliente HTTP en CLI.",
      "curl",
      "curl http://192.168.56.101/",
      "curl <url>",
    ],
  },
  {
    id: "searchsploit",
    category: "Lab",
    subtopicId: "vuln-assessment",
    fragment: "searchsploit",
    toolAnswer: "searchsploit",
    toolQuestionEs: "¿Qué herramienta busca exploits públicos offline por nombre/versión?",
    toolQuestionEn: "Which tool searches public exploits offline by name/version?",
    paramQuestionEs: "Comando para Apache 2.4.49:",
    paramQuestionEn: "Command for Apache 2.4.49:",
    paramAnswer: "searchsploit apache 2.4.49",
    fullQuestionEs: "Busca hits de vsftpd 2.3.4 (índice, no ejecutar).",
    fullQuestionEn: "Search hits for vsftpd 2.3.4 (index, do not run).",
    fullAnswer: "searchsploit vsftpd 2.3.4",
    conceptQuestionEs: "¿searchsploit lanza el exploit?",
    conceptQuestionEn: "Does searchsploit launch the exploit?",
    conceptKeywords: ["no"],
    explanationEs: "Es un índice. Luego msf en TU VM. No gcc del .c hoy.",
    hints: [
      "Tienes una versión de nmap. Quieres saber si hay hit público.",
      "Copia local de Exploit-DB.",
      "searchsploit nombre versión",
      "searchsploit vsftpd 2.3.4",
      "Anota el hit. No lo ejecutes.",
    ],
  },
  {
    id: "nc-lvnp",
    category: "Lab",
    subtopicId: "reverse-vs-bind",
    fragment: "nc -lvnp",
    toolAnswer: "nc",
    toolQuestionEs: "¿Qué herramienta usas como listener TCP en Kali?",
    toolQuestionEn: "Which tool do you use as a TCP listener on Kali?",
    paramQuestionEs: "Flags típicos de listener (listen verbose numeric port):",
    paramQuestionEn: "Typical listener flags (listen verbose numeric port):",
    paramAnswer: "-lvnp",
    fullQuestionEs: "Listener en 4444 esperando reverse.",
    fullQuestionEn: "Listener on 4444 waiting for reverse.",
    fullAnswer: "nc -lvnp 4444",
    conceptQuestionEs: "¿En reverse, LHOST es la víctima?",
    conceptQuestionEn: "In reverse, is LHOST the victim?",
    conceptKeywords: ["no"],
    explanationEs: "Tú escuchas. LHOST = vboxnet0. Bind = tú eres el cliente nc IP puerto.",
    hints: [
      "Reverse: la víctima llama. Tú esperas.",
      "Netcat en modo listen.",
      "nc -lvnp y el puerto.",
      "nc -lvnp 4444",
      "No uses wlan0 como LHOST para MS2.",
    ],
  },
];

export const COMMAND_BANK: CommandCard[] = [...COMMAND_BANK_CORE, ...SRS_V8, ...SRS_V91];

export function commandsByCategory() {
  const map = new Map<CommandCard["category"], CommandCard[]>();
  for (const c of COMMAND_BANK) {
    const list = map.get(c.category) ?? [];
    list.push(c);
    map.set(c.category, list);
  }
  return map;
}
