export type HubLayer = "SCAN" | "DEEP" | "RABBIT";
export type HubTrack =
  | "NOTES"
  | "NMAP"
  | "ENUM"
  | "WEB"
  | "MSF"
  | "POST"
  | "WORDLIST"
  | "LAB"
  | "MAP";

export interface HubRepo {
  id: string;
  name: string;
  url: string;
  track: HubTrack;
  layer: HubLayer;
  weeks: number[];
  min: number;
  /** Una línea para ojeada TDAH. */
  scan: string;
  /** Por qué le interesa a altas capacidades: mecanismo, no moraleja. */
  gifted: string;
  /** Cómo usarlo HOY sin derretir el reloj. */
  protocol: string;
  safety: string;
}

function R(p: HubRepo): HubRepo {
  return p;
}

/** Solo enlaces a repos públicos. No clones dumps de examen. Labs: Host-Only / DVWA / INE. */
export const HUB_REPOS: HubRepo[] = [
  R({
    id: "ejpt-angelist",
    name: "dev-angelist/eJPTv2-Notes",
    url: "https://github.com/dev-angelist/eJPTv2-Notes",
    track: "NOTES",
    layer: "SCAN",
    weeks: [1, 2, 3, 4, 5, 11],
    min: 12,
    scan: "Notas eJPTv2 + cheat sheet. Mapa, no biblia.",
    gifted: "Compara su orden mental con el tuyo. Donde discrepes, anota el porqué: ahí está tu modelo.",
    protocol: "Abre el cheat sheet. Extrae 8 comandos que YA usaste en lab. Cierra. No leas el repo entero.",
    safety: "Notas de terceros ≠ brief INE. No copies payloads a redes ajenas.",
  }),
  R({
    id: "ejpt-neil",
    name: "neilmadhava/EJPTv2-Notes",
    url: "https://github.com/neilmadhava/EJPTv2-Notes",
    track: "NOTES",
    layer: "SCAN",
    weeks: [1, 2, 5, 6],
    min: 12,
    scan: "Notas por servicio: SMB, FTP, HTTP, SQL…",
    gifted: "Úsalo como índice invertido: un puerto → un markdown. Entrena retrieval, no coleccionismo.",
    protocol: "Elige UN servicio open en TU nmap. Lee SOLO ese .md. Vuelve al lab.",
    safety: "Solo contra tu guest / DVWA.",
  }),
  R({
    id: "ejpt-dragkob",
    name: "Dragkob/eJPT",
    url: "https://github.com/Dragkob/eJPT",
    track: "NOTES",
    layer: "DEEP",
    weeks: [4, 8, 10, 11],
    min: 15,
    scan: "Cheat sheet de curso + post Linux/Windows.",
    gifted: "Contrasta 'extra CVEs' vs tu método. Si un CVE no sale de TU -sV, es ruido intelectual.",
    protocol: "Skim headings 5 min. Profundiza 10 min en la fase que fallaste hoy.",
    safety: "No es un dump del examen. No lo trates como tal.",
  }),
  R({
    id: "nmap",
    name: "nmap/nmap",
    url: "https://github.com/nmap/nmap",
    track: "NMAP",
    layer: "DEEP",
    weeks: [0, 1],
    min: 12,
    scan: "Fuente de Nmap. Docs/man, no el árbol entero.",
    gifted: "NSE es un runtime Lua sobre sockets. Entender categorías > memorizar 400 scripts.",
    protocol: "docs o man nmap en Kali. 3 flags que no usas. Uno al guest.",
    safety: "Scan solo CIDR autorizado.",
  }),
  R({
    id: "msf",
    name: "rapid7/metasploit-framework",
    url: "https://github.com/rapid7/metasploit-framework",
    track: "MSF",
    layer: "RABBIT",
    weeks: [3, 4],
    min: 12,
    scan: "El framework. No leas 2000 exploits.",
    gifted: "Un módulo = Ruby + datastore (RHOSTS/LHOST). El 'run' es un objeto, no magia.",
    protocol: "Busca en GitHub un módulo cuyo producto coincida con TU -sV. Lee options en msfconsole, no el .rb entero.",
    safety: "Exploit solo MS2/lab. Match de versión.",
  }),
  R({
    id: "gobuster",
    name: "OJ/gobuster",
    url: "https://github.com/OJ/gobuster",
    track: "ENUM",
    layer: "SCAN",
    weeks: [2, 5],
    min: 10,
    scan: "dir / vhost / dns. README de flags.",
    gifted: "Es fuerza bruta de espacio de nombres HTTP, no de passwords. El status code es el oráculo.",
    protocol: "README: 4 flags. Lánzalo a http del guest con wordlist corta.",
    safety: "HTTP de tu lab, no Internet.",
  }),
  R({
    id: "hydra",
    name: "vanhauser-thc/thc-hydra",
    url: "https://github.com/vanhauser-thc/thc-hydra",
    track: "ENUM",
    layer: "SCAN",
    weeks: [2],
    min: 10,
    scan: "Brute de servicios. README + protocolos.",
    gifted: "Dos ejes (user × pass) explotan combinatorio. Por eso el user de SMB primero es información, no ética vacía.",
    protocol: "Lee un módulo (ssh/ftp). Escribe el comando CON user conocido. Ejecuta solo si enumeraste user.",
    safety: "Nunca contra SSH de casa/amigos.",
  }),
  R({
    id: "enum4linux",
    name: "CiscoCXSecurity/enum4linux",
    url: "https://github.com/CiscoCXSecurity/enum4linux",
    track: "ENUM",
    layer: "SCAN",
    weeks: [2],
    min: 10,
    scan: "Wrapper SMB/unix-like. -a es el martillo.",
    gifted: "Es orquestador de rpcclient/smbclient. Si falla, baja una capa: smbclient -L.",
    protocol: "README. enum4linux -a a TU RHOST. Anota users.",
    safety: "445 de tu VM.",
  }),
  R({
    id: "sqlmap",
    name: "sqlmapproject/sqlmap",
    url: "https://github.com/sqlmapproject/sqlmap",
    track: "WEB",
    layer: "DEEP",
    weeks: [5, 6],
    min: 12,
    scan: "Automatiza SQLi. Flags --dbs/--dump/--cookie.",
    gifted: "Es un fuzzer de Gramáticas SQL + tamper. Sin request entendido, es un oráculo ciego caro.",
    protocol: "wiki o -hh. Una URL DVWA. --dbs y para.",
    safety: "Solo DVWA localhost.",
  }),
  R({
    id: "seclists",
    name: "danielmiessler/SecLists",
    url: "https://github.com/danielmiessler/SecLists",
    track: "WORDLIST",
    layer: "SCAN",
    weeks: [2, 5],
    min: 10,
    scan: "Wordlists. Discovery > Passwords enormes en examen.",
    gifted: "El espacio de búsqueda es el arma. Elegir lista = priorizar hipótesis, no 'más grande = mejor'.",
    protocol: "Ubica Discovery/Web-Content. Una lista short al Gobuster del guest.",
    safety: "No descargues 80 GB el día D.",
  }),
  R({
    id: "peass",
    name: "peass-ng/PEASS-ng",
    url: "https://github.com/peass-ng/PEASS-ng",
    track: "POST",
    layer: "DEEP",
    weeks: [8],
    min: 12,
    scan: "LinPEAS/WinPEAS: enum de privesc.",
    gifted: "Clasifica señales (SUID, cron, writable). Tú sigues eligiendo el vector. La tool no razona el examen.",
    protocol: "Lee qué color/prioridad significa. En MS2: corre LinPEAS si ya hay shell. No | bash desde foros raros.",
    safety: "Solo en la víctima de lab. No en tu Kali host como 'práctica'.",
  }),
  R({
    id: "linenum",
    name: "rebootuser/LinEnum",
    url: "https://github.com/rebootuser/LinEnum",
    track: "POST",
    layer: "SCAN",
    weeks: [8],
    min: 10,
    scan: "Script clásico de enum Linux. Más crudo que PEASS.",
    gifted: "Compara output vs LinPEAS: mismo mapa, distinta UX. El mapa es lo que debes internalizar.",
    protocol: "Skim el script headers (qué busca). No memorices 200 checks.",
    safety: "Guest lab.",
  }),
  R({
    id: "dvwa",
    name: "digininja/DVWA",
    url: "https://github.com/digininja/DVWA",
    track: "LAB",
    layer: "SCAN",
    weeks: [0, 5, 6, 12],
    min: 12,
    scan: "Web vulnerable. Docker/local. Security low primero.",
    gifted: "Cada bug es un modelo de confianza roto (SQL concat, include path, innerHTML). Nombra el modelo.",
    protocol: "README setup. Si ya corre en :4280, un ejercicio. Si no, /laboratorio.",
    safety: "localhost. No publiques el contenedor.",
  }),
  R({
    id: "ms3",
    name: "rapid7/metasploitable3",
    url: "https://github.com/rapid7/metasploitable3",
    track: "LAB",
    layer: "RABBIT",
    weeks: [4, 9],
    min: 15,
    scan: "Víctima Windows/Linux empaquetable. Más pesada que MS2.",
    gifted: "Si ya te aburres de MS2, cambia de SO, no de método. El método tiene que sobrevivir al aburrimiento.",
    protocol: "Lee requisitos. NO la importes semana 0. Host-Only si la montas.",
    safety: "Nunca Bridged en LAN familiar.",
  }),
  R({
    id: "ffuf",
    name: "ffuf/ffuf",
    url: "https://github.com/ffuf/ffuf",
    track: "WEB",
    layer: "DEEP",
    weeks: [5, 6],
    min: 12,
    scan: "Fuzzer HTTP rápido. Competidor de Gobuster.",
    gifted: "Filtrar por tamaño/código es un canal de señal. 403 vs 404 es el mismo juego que en clase.",
    protocol: "README. Un fuzz a DVWA o al http del guest. Misma ética que Gobuster.",
    safety: "Lab only. Rate-limit mental.",
  }),
  R({
    id: "httpx",
    name: "projectdiscovery/httpx",
    url: "https://github.com/projectdiscovery/httpx",
    track: "WEB",
    layer: "RABBIT",
    weeks: [5, 9],
    min: 10,
    scan: "Sonda HTTP a escala. Títulos, status, techs.",
    gifted: "Pipeline recon: nmap hosts → httpx → ffuf. Dataflow, no tool-hopping caótico.",
    protocol: "Si tienes 1 HTTP, overkill. Si tienes varias IPs de lab, pruébalo 10 min.",
    safety: "IPs de TU /24 lab.",
  }),
  R({
    id: "nuclei",
    name: "projectdiscovery/nuclei",
    url: "https://github.com/projectdiscovery/nuclei",
    track: "WEB",
    layer: "RABBIT",
    weeks: [4, 9],
    min: 12,
    scan: "Templates YAML de vulns. No sustituye -sV.",
    gifted: "Es pattern-matching distribuido. Falsos positivos enseñan más que un 'critical' verde.",
    protocol: "Un template http contra DVWA. Lee el YAML: qué match declara.",
    safety: "No nuclei-a-Internet. Lab.",
  }),
  R({
    id: "impacket",
    name: "fortra/impacket",
    url: "https://github.com/fortra/impacket",
    track: "ENUM",
    layer: "DEEP",
    weeks: [2, 4, 8],
    min: 12,
    scan: "SMB/psexec/wmiexec en Python. Más Windows que MS2.",
    gifted: "Protocolos implementados, no 'magia psexec'. Lees el wire en código.",
    protocol: "Lista examples/. Uno: smbclient.py contra TU 445. Si es Linux MS2, igual sirve para hablar SMB.",
    safety: "Lab. No DC de empresa.",
  }),
  R({
    id: "john",
    name: "openwall/john",
    url: "https://github.com/openwall/john",
    track: "POST",
    layer: "SCAN",
    weeks: [8, 10],
    min: 10,
    scan: "John the Ripper: hashes offline.",
    gifted: "Offline ≠ Hydra. Cambias de canal (red → CPU). El examen a veces pide el hash, no el crack.",
    protocol: "Formato de un hash que TÚ obtuviste en lab. Si no hay hash, lee modos y cierra.",
    safety: "Solo hashes de tu lab.",
  }),
  R({
    id: "hashcat",
    name: "hashcat/hashcat",
    url: "https://github.com/hashcat/hashcat",
    track: "POST",
    layer: "RABBIT",
    weeks: [8],
    min: 10,
    scan: "Crack GPU. Overkill eJPT a menudo.",
    gifted: "Si te aburre John, Hashcat es el mismo problema con otro coste computacional. No es 'más elite'.",
    protocol: "Ejemplos de -m (hash type). Identifica el tipo. No hace falta GPU hoy.",
    safety: "Hashes lab.",
  }),
  R({
    id: "gtfo",
    name: "GTFOBins/GTFOBins.github.io",
    url: "https://github.com/GTFOBins/GTFOBins.github.io",
    track: "POST",
    layer: "DEEP",
    weeks: [8],
    min: 12,
    scan: "Binarios Unix → privesc/file-read si sudo/SUID.",
    gifted: "Cada binario es un confused deputy. sudo -l te da el nombre; GTFOBins el how. Tú unes.",
    protocol: "Tras sudo -l en MS2, busca UNO. No colecciones 40.",
    safety: "Guest. No tu host.",
  }),
  R({
    id: "lolbas",
    name: "LOLBAS-Project/LOLBAS",
    url: "https://github.com/LOLBAS-Project/LOLBAS",
    track: "POST",
    layer: "DEEP",
    weeks: [8],
    min: 12,
    scan: "Living-off-the-land Windows.",
    gifted: "Simétrico a GTFOBins. Si no tienes VM Windows, es modelo mental, no lab obligatorio.",
    protocol: "Lee 1 binario (certutil o similar). Relaciónalo con 'no traer malware'.",
    safety: "No lo pruebes en el Windows de la familia.",
  }),
  R({
    id: "payloads",
    name: "swisskyrepo/PayloadsAllTheThings",
    url: "https://github.com/swisskyrepo/PayloadsAllTheThings",
    track: "WEB",
    layer: "RABBIT",
    weeks: [5, 6],
    min: 12,
    scan: "Enciclopedia de payloads. Fácil perderse.",
    gifted: "Es un índice de clases de bug. Entra por el bug que YA viste en DVWA, no por 'todo XSS'.",
    protocol: "Carpeta SQLi o XSS o File Inclusion. 12 min. Un payload a DVWA. Stop.",
    safety: "DVWA only. No es un kit contra Internet.",
  }),
  R({
    id: "hacktricks",
    name: "HackTricks-wiki/hacktricks",
    url: "https://github.com/HackTricks-wiki/hacktricks",
    track: "MAP",
    layer: "RABBIT",
    weeks: [2, 7, 8, 9],
    min: 12,
    scan: "Wiki de pentest. Infinita. Timer obligatorio.",
    gifted: "Grafos de ataque. Úsala para UNA pregunta ('445 qué hay'), no para 'leer HackTricks'.",
    protocol: "Search interno: el servicio de hoy. 12 min. Exporta 3 bullets a tu plantilla.",
    safety: "Técnicas de lab/examen autorizado.",
  }),
  R({
    id: "awesome-pt",
    name: "enaqx/awesome-pentest",
    url: "https://github.com/enaqx/awesome-pentest",
    track: "MAP",
    layer: "SCAN",
    weeks: [0, 12],
    min: 10,
    scan: "Lista de listas. Mapa del ecosistema.",
    gifted: "Taxonomía. Si tu cerebro pide 'más tools', este es el sitio para ELEGIR una, no 30.",
    protocol: "Una categoría (scanning). Marca 1 tool que aún no usas. No la instales hoy si no entra en la clase.",
    safety: "Awesome ≠ autorización.",
  }),
  R({
    id: "secret-knowledge",
    name: "trimstray/the-book-of-secret-knowledge",
    url: "https://github.com/trimstray/the-book-of-secret-knowledge",
    track: "MAP",
    layer: "RABBIT",
    weeks: [12],
    min: 12,
    scan: "Compendio sysadmin/security. Scope creep nivel dios.",
    gifted: "Para altas capacidades aburridas en semana 12. Timer. Una rama (networking).",
    protocol: "12 min networking o pentest section. Cierra. Vuelve al simulacro.",
    safety: "No sustituye eJPT.",
  }),
  R({
    id: "owasp-cheats",
    name: "OWASP/CheatSheetSeries",
    url: "https://github.com/OWASP/CheatSheetSeries",
    track: "WEB",
    layer: "DEEP",
    weeks: [5, 6],
    min: 12,
    scan: "Cheats OWASP (defensa). Útil para entender el bug al revés.",
    gifted: "Atacar sin modelo de defensa es memorizar strings. Lee SQL Injection Prevention 10 min.",
    protocol: "Una cheat del bug de DVWA de hoy. Luego el ataque otra vez, más preciso.",
    safety: "Concepto. Lab para la parte ofensiva.",
  }),
  R({
    id: "ippsec",
    name: "ippsec/ippsec.github.io",
    url: "https://github.com/ippsec/ippsec.github.io",
    track: "NOTES",
    layer: "DEEP",
    weeks: [9, 10],
    min: 15,
    scan: "Índice de videos HTB. Busca técnica, no la box entera.",
    gifted: "Patrones repetidos (vhost, SQLi, privesc). Extrae el patrón; no veas 2 h.",
    protocol: "Busca 'smb' o 'sqli'. 1 video a 1.5x. Anota 3 pasos. No la box live de IPPSec si no es tu lab.",
    safety: "No ataques las máquinas del vídeo en producción. Lab propio.",
  }),
  R({
    id: "exploitdb",
    name: "offensive-security/exploitdb",
    url: "https://github.com/offensive-security/exploitdb",
    track: "MSF",
    layer: "DEEP",
    weeks: [4],
    min: 10,
    scan: "DB de searchsploit. En Kali ya está.",
    gifted: "searchsploit es un índice local de este árbol. La skill es query + leer, no copiar el primer .c.",
    protocol: "searchsploit con TU banner. Lee descripción. ¿Hay módulo msf?",
    safety: "Lab match. No el primer PoC de Internet a ciegas.",
  }),
  R({
    id: "nikto",
    name: "sullo/nikto",
    url: "https://github.com/sullo/nikto",
    track: "WEB",
    layer: "SCAN",
    weeks: [5],
    min: 10,
    scan: "Scanner web ruidoso. Hallazgos ≠ exploitable.",
    gifted: "Reglas vs realidad. Úsalo para generar hipótesis, luego verifica a mano (curl).",
    protocol: "nikto -h http://RHOST lab. 3 findings. Verifica 1. Descarta el resto.",
    safety: "Un host lab. Nikto es ruidoso: no Wi‑Fi ajena.",
  }),
  R({
    id: "zap",
    name: "zaproxy/zaproxy",
    url: "https://github.com/zaproxy/zaproxy",
    track: "WEB",
    layer: "RABBIT",
    weeks: [5, 6],
    min: 15,
    scan: "OWASP ZAP: proxy como Burp community.",
    gifted: "Ver el request es el salto cognitivo. El scanner automático es opcional.",
    protocol: "Proxy a DVWA. Intercepta login. No spider all. 15 min.",
    safety: "Proxy solo al lab.",
  }),
  R({
    id: "wireshark",
    name: "wireshark/wireshark",
    url: "https://github.com/wireshark/wireshark",
    track: "NMAP",
    layer: "DEEP",
    weeks: [1, 7],
    min: 12,
    scan: "Captura de paquetes. TCP handshake se VE.",
    gifted: "Si el reverse 'no nace', la verdad está en el pcap, no en el feeling.",
    protocol: "Captura vboxnet 2 min de un nmap. Filtra tcp. Identifica SYN.",
    safety: "Interfaz del lab, no wlan0 de la casa.",
  }),
  R({
    id: "scapy",
    name: "secdev/scapy",
    url: "https://github.com/secdev/scapy",
    track: "NMAP",
    layer: "RABBIT",
    weeks: [1, 7],
    min: 12,
    scan: "Paquetes a mano en Python. Para cerebro aburrido de flags.",
    gifted: "Reimplementar un ping/SYN te clava L3/L4 mejor que 20 PDFs.",
    protocol: "Un ICMP o TCP SYN a TU guest. No un fuzzer.",
    safety: "Guest Host-Only.",
  }),
  R({
    id: "responder",
    name: "lgandx/Responder",
    url: "https://github.com/lgandx/Responder",
    track: "ENUM",
    layer: "RABBIT",
    weeks: [7],
    min: 10,
    scan: "LLMNR/NBT-NS poison. Windows LAN.",
    gifted: "Confianza en nombres. Concepto Mes 2. NO lo lances a la Wi‑Fi familiar.",
    protocol: "Lee README 10 min. Dibuja el ataque. No ejecutes si no hay lab Windows aislado.",
    safety: "Prohibido en LAN doméstica. Solo lab Windows Host-Only/Internal.",
  }),
  R({
    id: "bettercap",
    name: "bettercap/bettercap",
    url: "https://github.com/bettercap/bettercap",
    track: "ENUM",
    layer: "RABBIT",
    weeks: [7],
    min: 10,
    scan: "MITM framework. Misma regla ética que ARP spoof.",
    gifted: "Entiende el modelo (gateway, spoof, sniff). Ejecución solo guest-a-guest.",
    protocol: "Docs: qué módulos existen. Cero wlan0.",
    safety: "No MITM a humanos. Clase c07-d1.",
  }),
  R({
    id: "theharvester",
    name: "laramies/theHarvester",
    url: "https://github.com/laramies/theHarvester",
    track: "NMAP",
    layer: "SCAN",
    weeks: [1],
    min: 10,
    scan: "OSINT pasivo (emails/hosts públicos).",
    gifted: "eJPT es sobre todo activo. Esto es el contraste: pasivo no toca el lab.",
    protocol: "Lee qué fuentes usa. No lo apuntes a tu empleador. Opcional 5 min.",
    safety: "Pasivo ≠ escanear la empresa del vecino.",
  }),
  R({
    id: "ssh-audit",
    name: "jtesta/ssh-audit",
    url: "https://github.com/jtesta/ssh-audit",
    track: "ENUM",
    layer: "SCAN",
    weeks: [2],
    min: 8,
    scan: "Audita config SSH. Banner ≠ hardening.",
    gifted: "Algoritmos y policy. En lab: por qué Hydra a veces es el camino y a veces no.",
    protocol: "ssh-audit a TU :22 de MS2. Anota versión. No 'hack'.",
    safety: "Tu guest.",
  }),
  R({
    id: "commix",
    name: "commixproject/commix",
    url: "https://github.com/commixproject/commix",
    track: "WEB",
    layer: "DEEP",
    weeks: [6],
    min: 10,
    scan: "Command injection automatizado.",
    gifted: "Después de hacerlo a mano en DVWA. Si no hay inyección, la tool miente con estilo.",
    protocol: "Solo si ya viste command injection manual. DVWA.",
    safety: "DVWA. No webs ajenas.",
  }),
  R({
    id: "wfuzz",
    name: "xmendez/wfuzz",
    url: "https://github.com/xmendez/wfuzz",
    track: "WEB",
    layer: "DEEP",
    weeks: [5],
    min: 10,
    scan: "Fuzz clásico. Ancestro de ffuf.",
    gifted: "Misma idea, otra UX. Elegir una y dominarla > tres a medias (TDAH).",
    protocol: "Si ya usas Gobuster, no cambies hoy. Skim. Vuelve.",
    safety: "Lab HTTP.",
  }),
  R({
    id: "fuzzdb",
    name: "fuzzdb-project/fuzzdb",
    url: "https://github.com/fuzzdb-project/fuzzdb",
    track: "WORDLIST",
    layer: "RABBIT",
    weeks: [5, 6],
    min: 10,
    scan: "Payloads de fuzz. Solapa con PayloadsAllTheThings.",
    gifted: "Datasets. Elige 1 archivo para el bug de hoy.",
    protocol: "Una carpeta. Un string a DVWA.",
    safety: "DVWA.",
  }),
  R({
    id: "cyberchef",
    name: "gchq/CyberChef",
    url: "https://github.com/gchq/CyberChef",
    track: "MAP",
    layer: "SCAN",
    weeks: [10],
    min: 10,
    scan: "Horno de encodings (base64, hex). Evidencia de examen.",
    gifted: "Pipelines de transformación. El hash mal copiado es un error de canal, no de pentest.",
    protocol: "Pega un string de lab. Decode. Exactitud.",
    safety: "No subas datos reales de clientes. Lab.",
  }),
  R({
    id: "netexec",
    name: "Pennyw0rth/NetExec",
    url: "https://github.com/Pennyw0rth/NetExec",
    track: "ENUM",
    layer: "RABBIT",
    weeks: [4, 8],
    min: 10,
    scan: "Sucesor de CrackMapExec. Windows/SMB a escala.",
    gifted: "Overkill MS2, útil si montas Windows lab. El patrón: auth + módulo.",
    protocol: "README. Si no hay Windows lab, 8 min de modelo y cierra.",
    safety: "No AD de nadie. Lab.",
  }),
  R({
    id: "bloodhound",
    name: "BloodHoundAD/BloodHound",
    url: "https://github.com/BloodHoundAD/BloodHound",
    track: "POST",
    layer: "RABBIT",
    weeks: [8, 12],
    min: 12,
    scan: "Grafos AD. Fuera de núcleo eJPT. Hoyo para altas capacidades.",
    gifted: "Privesc como camino en un grafo. Transfiere la idea a Linux (cron→SUID) sin instalar AD.",
    protocol: "Lee qué pregunta responde (paths to DA). No instales Neo4j semana 2.",
    safety: "No recolectes AD ajeno.",
  }),
  R({
    id: "internal-all",
    name: "swisskyrepo/InternalAllTheThings",
    url: "https://github.com/swisskyrepo/InternalAllTheThings",
    track: "MAP",
    layer: "RABBIT",
    weeks: [7, 9],
    min: 12,
    scan: "Pentest interno / AD. Complemento de PayloadsAllTheThings.",
    gifted: "eJPT a veces es red interna. Este repo es el 'qué existe', no el 'hazlo en casa'.",
    protocol: "Índice. Una página (pivot o SMB). 12 min.",
    safety: "Concepto + lab propio.",
  }),
  R({
    id: "cheatsheets-coreb1t",
    name: "coreb1t/awesome-pentest-cheat-sheets",
    url: "https://github.com/coreb1t/awesome-pentest-cheat-sheets",
    track: "MAP",
    layer: "SCAN",
    weeks: [1, 2, 3, 12],
    min: 10,
    scan: "Índice de cheat sheets. Elige 1.",
    gifted: "Meta-lista. Evita 15 PDFs. Una sheet por hueco (msf o nmap).",
    protocol: "Abre 1 link nmap o msf. 10 min. Cierra el awesome.",
    safety: "Sheets ≠ alcance.",
  }),
  R({
    id: "searchsploit-kali",
    name: "offensive-security/exploitdb-papers",
    url: "https://github.com/offensive-security/exploitdb-papers",
    track: "MSF",
    layer: "RABBIT",
    weeks: [4],
    min: 10,
    scan: "Papers/docs asociados a Exploit-DB.",
    gifted: "A veces el 'exploit' es un paper. Leer 2 páginas > copiar shellcode.",
    protocol: "Si searchsploit te dio un EDB-ID, busca contexto. Lab.",
    safety: "Comprender ≠ disparar a ciegas.",
  }),
  R({
    id: "dirsearch",
    name: "maurosoria/dirsearch",
    url: "https://github.com/maurosoria/dirsearch",
    track: "ENUM",
    layer: "SCAN",
    weeks: [2, 5],
    min: 8,
    scan: "Otro dirbuster. Si Gobuster te basta, no cambies.",
    gifted: "TDAH: una tool de dirs. Esta es alternativa, no obligación.",
    protocol: "Skim README. Sigue con Gobuster si ya fluye.",
    safety: "HTTP lab.",
  }),
  R({
    id: "smbmap",
    name: "ShawnDEvans/smbmap",
    url: "https://github.com/ShawnDEvans/smbmap",
    track: "ENUM",
    layer: "SCAN",
    weeks: [2],
    min: 10,
    scan: "Permisos de shares en una vista.",
    gifted: "READ/WRITE es el dato. enum4linux lista; smbmap prioriza.",
    protocol: "smbmap -H RHOST en lab. Anota WRITE si hay.",
    safety: "SMB lab.",
  }),
  R({
    id: "recon-ng",
    name: "lanmaster53/recon-ng",
    url: "https://github.com/lanmaster53/recon-ng",
    track: "NMAP",
    layer: "RABBIT",
    weeks: [1],
    min: 10,
    scan: "Framework OSINT. Poco peso eJPT activo.",
    gifted: "Módulos como msf pero para intel. Contraste pedagógico.",
    protocol: "5 min arquitectura. No lo conviertas en el día.",
    safety: "OSINT ético / no doxx.",
  }),
];

export const HUB_TRACKS: HubTrack[] = [
  "NOTES",
  "NMAP",
  "ENUM",
  "WEB",
  "MSF",
  "POST",
  "WORDLIST",
  "LAB",
  "MAP",
];
