import { LearnArticle } from "@/content/learn-types";

function L(
  id: string,
  track: string,
  titleEs: string,
  fields: Omit<LearnArticle, "id" | "track" | "titleEs">
): LearnArticle {
  return { id, track, titleEs, ...fields };
}

const SAFE = " Úsalo solo en DVWA/MS2/examen/lab propio.";

export const LEARN_CATALOG_C: LearnArticle[] = [
  L("http-basics", "WEB", "HTTP", {
    what: "Protocolo petición/respuesta. Métodos GET/POST. Cabeceras (Cookie, Host, User-Agent). Códigos 200 301 302 401 403 404 500. Cuerpo HTML/JSON. HTTPS es HTTP sobre TLS: la lógica de app es la misma.",
    why: "Casi todo eJPT web es leer HTTP. Gobuster lee status. SQLi viaja en parámetros.",
    how: "curl -i, Burp/ZAP opcional, el navegador a TU DVWA. No grabes cookies de bancos.",
    when: "80/443 open o DVWA :4280.",
    example: "GET /login.php HTTP/1.1",
    mistake: "Pensar que HTTPS 'no se puede enumerar'.",
    redTeam: "Cada request es un input. Cada código es un dato." + SAFE,
    recall: "403 significa…",
    recallKeywords: ["forbid", "prohib", "existe"],
    challenge: "¿301 es 'no existe'?",
    challengeKeywords: ["no"],
  }),
  L("cookies-sess", "WEB", "Cookies y sesiones", {
    what: "Cookie: dato que el navegador reenvía. Sesión: estado en servidor (PHPSESSID). Sin cookie, a veces no hay SQLi 'logged in'.",
    why: "sqlmap --cookie. Auth bypass a veces es cookie predecible (lab). No es robar sesiones de terceros.",
    how: "DevTools Application, curl -b. DVWA login te da PHPSESSID.",
    when: "Tras login en DVWA o app del lab.",
    example: "--cookie='PHPSESSID=abc; security=low'",
    mistake: "Pegar cookies de tu banco en sqlmap.",
    redTeam: "La sesión es parte del ataque a ESA app de lab, no un extra." + SAFE,
    recall: "sqlmap a una página tras login suele necesitar…",
    recallKeywords: ["cookie"],
    challenge: "¿PHPSESSID es el password de MySQL?",
    challengeKeywords: ["no"],
  }),
  L("authn-authz", "WEB", "Authn vs Authz", {
    what: "Autenticación: ¿quién eres? Autorización: ¿qué puedes? IDOR es fallar authz (ver /user/2 siendo user 1). Bypass de login es authn.",
    why: "eJPT mezcla brute login, SQLi login, y a veces IDOR simple.",
    how: "Cambiar IDs en URL/body. Probar user/admin. No es un 0-day.",
    when: "Hay objetos numerados o roles.",
    example: "?user_id=1 → 2 y ves otro perfil (lab).",
    mistake: "Llamar IDOR a un 404.",
    redTeam: "Tras login, sigue enumerando objetos. El examen ama el olvido." + SAFE,
    recall: "IDOR es fallo de…",
    recallKeywords: ["autoriz"],
    challenge: "Hydra al login es ¿authn o IDOR?",
    challengeKeywords: ["auth"],
  }),
  L("web-dirs", "WEB", "Directorios y parámetros", {
    what: "Dirs: /admin /uploads. Params: ?id= ?page= ?file=. El ataque web eJPT vive ahí, no en 'el puerto 80' vacío.",
    why: "Gobuster encuentra dirs. SQLi/LFI viven en params.",
    how: "Gobuster -x php,txt. Luego prueba un param a la vez. Burp repeater o curl.",
    when: "Tras 80 open y un poco de crawling.",
    example: "page=index → page=../../etc/passwd (LFI lab).",
    mistake: "Inyectar en todos los params a la vez y no saber cuál.",
    redTeam: "Un param, un hipótesis, un resultado." + SAFE,
    recall: "¿Dónde viaja a menudo LFI?",
    recallKeywords: ["param", "page", "file"],
    challenge: "Gobuster enumera ¿params SQL?",
    challengeKeywords: ["no"],
  }),
  L("sqli", "WEB", "SQL injection", {
    what: "El input se concatena en SQL. ' rompe la query. UNION SELECT extrae. Boolean/time si no hay output. sqlmap automatiza; el examen espera que entiendas UNION y --dbs.",
    why: "Dominio web eJPT. DVWA SQL Injection security low.",
    how: "Manual: ' ORDER BY n, UNION SELECT. sqlmap -u URL --cookie --dbs --tables --dump. Solo DVWA/lab.",
    when: "Param id o login que hable con DB.",
    example: "-1' UNION SELECT 1,@@version,3-- -",
    mistake: "sqlmap --dump contra producción ajena. O UNION sin saber columnas.",
    redTeam: "Primero rompe (error). Luego columnas. Luego datos. sqlmap después." + SAFE,
    recall: "¿UNION SELECT sirve para…?",
    recallKeywords: ["extraer", "datos", "column"],
    challenge: "¿' OR '1'='1 es detección o dump de tablas?",
    challengeKeywords: ["detecc", "login", "bypass", "prueba"],
  }),
  L("xss", "WEB", "XSS", {
    what: "Cross-Site Scripting: JS en el contexto de otro usuario. Reflected (URL), Stored (DB), DOM. En eJPT: payload <script> en DVWA, no campañas reales.",
    why: "Dominio web. Distinto de SQLi (servidor SQL vs navegador).",
    how: "DVWA XSS reflected/stored. Prueba tags. Security low.",
    when: "Campos que se reflejan en HTML.",
    example: "<script>alert(1)</script> en lab.",
    mistake: "XSS 'para robar Facebook' como objetivo de estudio. No.",
    redTeam: "XSS = el navegador de la víctima de lab ejecuta TU html. No es enum SMB." + SAFE,
    recall: "XSS se ejecuta en…",
    recallKeywords: ["navegador", "browser", "cliente"],
    challenge: "¿XSS extrae @@version de MySQL?",
    challengeKeywords: ["no"],
  }),
  L("lfi", "WEB", "LFI / RFI", {
    what: "Local File Inclusion: incluir archivos del disco (page=../../etc/passwd). RFI: incluir URL remota (menos común, allow_url_include). Path traversal es primo.",
    why: "eJPT web. Leer configs, a veces logs para RCE (avanzado, no primer drill).",
    how: "Param file/page. ../ repetido. php wrappers en labs (php://filter) conceptualmente.",
    when: "Param de 'página' o 'idioma'.",
    example: "DVWA File Inclusion.",
    mistake: "LFI contra sitios reales. O confundir con SQLi.",
    redTeam: "LFI = leer. RCE es otro escalón y otro control." + SAFE,
    recall: "LFI incluye archivos de…",
    recallKeywords: ["local", "disco", "servidor"],
    challenge: "/etc/passwd vía LFI: ¿es Windows SAM?",
    challengeKeywords: ["no"],
  }),
  L("upload-rce", "WEB", "Upload y command injection", {
    what: "Upload: el servidor guarda un archivo. Si ejecuta .php en /uploads, RCE de lab. Command injection: input a un comando del SO (; | && ping).",
    why: "eJPT web. DVWA Command Injection y upload si está en el plan.",
    how: "Extensiones, content-type, path. Para command: ; id  o | whoami en DVWA low.",
    when: "Form upload o ping/tool en la app.",
    example: "127.0.0.1; id",
    mistake: "Subir webshells a Internet. O command injection en tu propio router.",
    redTeam: "¿El input llega a un shell del servidor de lab? Entonces es command injection, no SQLi." + SAFE,
    recall: "; id en un campo ping de DVWA es…",
    recallKeywords: ["command", "inyec", "os"],
    challenge: "¿Upload .php en /uploads es SQLi?",
    challengeKeywords: ["no"],
  }),
  L("idor", "WEB", "IDOR", {
    what: "Insecure Direct Object Reference: cambias un ID y accedes al objeto de otro. No hay check de dueño.",
    why: "Authz. Preguntas de examen tipo 'cambia el parámetro'.",
    how: "Burp/curl: incrementa id, user=, invoice=.",
    when: "APIs o PHP con ?id= tras login.",
    example: "/profile?id=1 → id=2",
    mistake: "Llamar IDOR a SQLi.",
    redTeam: "Estás autenticado y AÚN así no deberías ver el recurso. Eso es IDOR." + SAFE,
    recall: "IDOR viola…",
    recallKeywords: ["autoriz"],
    challenge: "¿IDOR requiere romper SQL?",
    challengeKeywords: ["no"],
  }),
  L("cve-select", "EXPLOITATION", "Vuln vs exploit vs CVE", {
    what: "Vulnerabilidad: debilidad. CVE: identificador público. Exploit: código/módulo que la aprovecha. Tener CVE ≠ explotable aquí (versión, OS, config).",
    why: "searchsploit lista; tú filtras. eJPT es proceso, no memorizar CVE.",
    how: "nmap -sV → searchsploit 'producto versión' → msf search. ¿Linux o Windows? ¿remote?",
    when: "Tras versión. No al ver 80 open.",
    example: "vsftpd 2.3.4 → módulo conocido en MS2, no un .c de internet el primer día.",
    mistake: "gcc el primer hit de searchsploit contra lo que sea.",
    redTeam: "El exploit correcto es el que coincide con TU -sV, no el write-up." + SAFE,
    recall: "searchsploit es un…",
    recallKeywords: ["indice", "índice", "lista", "db"],
    challenge: "¿Un CVE de Windows aplica a MS2 Linux?",
    challengeKeywords: ["no"],
  }),
  L("msf-flow", "EXPLOITATION", "Metasploit flujo", {
    what: "search → use → show options → set RHOSTS/LHOST → exploit. Tipos: exploit, auxiliary, payload, post. No sustituye nmap.",
    why: "Hueco típico: el flujo, no 'saberte exploits'.",
    how: "search vsftpd. use ruta. show options. set. exploit. sessions -i.",
    when: "Versión coincidente y lab propio.",
    example: "RHOSTS=guest LHOST=vboxnet si reverse.",
    mistake: "exploit sin show options. LHOST=127.0.0.1.",
    redTeam: "show options es obligatorio. Required vacío = no lances." + SAFE,
    recall: "¿Qué comando muestra opciones del módulo?",
    recallKeywords: ["show options"],
    challenge: "¿search lanza el exploit?",
    challengeKeywords: ["no"],
  }),
  L("payloads", "EXPLOITATION", "Payloads", {
    what: "Qué pasa DESPUÉS si el exploit funciona: meterpreter vs shell, reverse vs bind. msfvenom genera un archivo; no abre sesión solo. multi/handler espera la reverse con el MISMO payload/LHOST/LPORT.",
    why: "Sin payload coherente, 'no session'.",
    how: "msfvenom -p ... -f elf -o. handler: use exploit/multi/handler.",
    when: "Cuando el módulo no trae sesión o el brief pide msfvenom.",
    example: "linux/x86/meterpreter/reverse_tcp LHOST=vboxnet.",
    mistake: "Payload Windows contra MS2. Entregar elf a Internet.",
    redTeam: "Triplete payload-LHOST-LPORT idéntico en veneno y handler." + SAFE,
    recall: "msfvenom ¿abre la sesión solo?",
    recallKeywords: ["no"],
    challenge: "Handler hace falta sobre todo cuando…",
    challengeKeywords: ["msfvenom", "fuera", "archivo", "payload"],
  }),
  L("manual-exploit", "EXPLOITATION", "Explotación manual vs msf", {
    what: "Manual: hablar el protocolo (FTP anon, SMB, HTTP) o un script del lab. msf: módulo ya escrito. eJPT usa ambos. Manual no significa copiar PoC de Exploit-DB y gcc a ciegas el día 1.",
    why: "Semana 4: searchsploit es índice. Preferir msf en MS2 si el módulo existe.",
    how: "Enum → hipótesis → herramienta de ESE servicio. msf si hay módulo. Documenta whoami.",
    when: "Tras ident de vuln.",
    example: "FTP anon get archivo vs exploit vsftpd en msf.",
    mistake: "EternalBlue a un Windows que no es tu lab.",
    redTeam: "La cadena importa más que el nombre del CVE." + SAFE,
    recall: "searchsploit -m copia un archivo. ¿Debes ejecutarlo ya?",
    recallKeywords: ["no"],
    challenge: "¿enum4linux es explotación?",
    challengeKeywords: ["no"],
  }),
  L("shell-stab", "POST", "Estabilizar la shell", {
    what: "Una shell cruda no tiene TAB ni Ctrl+C sanos. python -c pty, export TERM, stty. En meterpreter ya hay sysinfo/getuid. No es obligatorio el primer reverse de 50 min, pero el examen puede pedir comandos.",
    why: "Sin TTY, su y nano fallan. Evidencia peor.",
    how: "python3 -c 'import pty;pty.spawn(\"/bin/bash\")' (concepto). background Ctrl+Z, stty raw -echo, fg (avanzado).",
    when: "Tras access Linux si la shell es inusable.",
    example: "spawn bash en lab.",
    mistake: "Estabilizar 30 min y no anotar whoami.",
    redTeam: "Identidad primero, comodidad después." + SAFE,
    recall: "pty.spawn sirve para…",
    recallKeywords: ["tty", "shell", "bash"],
    challenge: "¿Estabilizar sustituye a getuid?",
    challengeKeywords: ["no"],
  }),
  L("loot-creds", "POST", "Credenciales y hashes", {
    what: "Linux: /etc/shadow (root), configs, history. Windows: SAM/hashdump (privilegios). Hash ≠ password. No crackeas en este entrenador como objetivo principal.",
    why: "eJPT pregunta hashes o users. Lateral movement usa creds.",
    how: "cat configs, grep password, hashdump solo Windows lab. Linux MS2: no SAM.",
    when: "Tras access, con contexto de SO.",
    example: "config.php $db_password.",
    mistake: "hashdump en meterpreter Linux y frustrarte.",
    redTeam: "Loot = archivos y users. El crack es opcional y local." + SAFE,
    recall: "hashdump SAM es de…",
    recallKeywords: ["windows"],
    challenge: "¿/etc/shadow es SAM?",
    challengeKeywords: ["no"],
  }),
  L("post-net", "POST", "Red en post-ex", {
    what: "ifconfig/ip a, arp, /etc/hosts, tablas de ruta, listeners. Descubres OTRA red → pivot. Si solo vboxnet, documenta y no inventes.",
    why: "Pivoting nace de este enum, no de un menú.",
    how: "ip a, ip route, ss -tlnp, cat /etc/hosts.",
    when: "Tras whoami. Antes de 'pivot porque el plan lo dice'.",
    example: "eth1 10.1.1.5/24 que Kali no ve.",
    mistake: "autoroute sin segunda NIC.",
    redTeam: "El mapa interno lo saca la víctima, no tu nmap inicial." + SAFE,
    recall: "Una segunda NIC en la víctima sugiere…",
    recallKeywords: ["pivot", "red"],
    challenge: "¿ip a en Kali muestra las NICs del guest?",
    challengeKeywords: ["no"],
  }),
  L("privesc-linux-c", "POST", "Privesc Linux (concepto)", {
    what: "Pasar de user a root: sudo -l, SUID, cron escribible, capabilities, kernel (último, específico). LinPEAS es ruido si no sabes leer; eJPT premia lo básico hecho a mano.",
    why: "Mes 2. No el día del lab Host-Only vacío.",
    how: "Orden: id → sudo -l → SUID → cron → kernel solo si encaja versión y lab.",
    when: "Shell no root y el objetivo lo pide.",
    example: "NOPASSWD: ALL → root trivial.",
    mistake: "Kernel exploit de 2016 en un kernel que no es.",
    redTeam: "Misconfig > CVE de moda." + SAFE,
    recall: "Primer comando de privesc Linux?",
    recallKeywords: ["sudo"],
    challenge: "¿Si ya eres root, lanzas privesc igual?",
    challengeKeywords: ["no"],
  }),
  L("portfwd", "PIVOTING", "Port forwarding", {
    what: "Reenviar un puerto: lo que llega a Kali:PORT sale al host interno:PORT. SSH -L/-R, chisel, msf portfwd. Sirve para un servicio concreto, no toda la red.",
    why: "Un MySQL interno 127.0.0.1:3306 en la víctima: nmap desde Kali no lo ve. Forward y entonces clientes.",
    how: "ssh -L 3306:127.0.0.1:3306 user@victim (concepto). msf portfwd add.",
    when: "Servicio interno conocido. Lab Mes 2+.",
    example: "Local 127.0.0.1:3306 → victim localhost:3306.",
    mistake: "portfwd de todo /24.",
    redTeam: "Un puerto, un motivo. No es SOCKS todavía." + SAFE,
    recall: "SSH -L es forward…",
    recallKeywords: ["local"],
    challenge: "¿Portfwd sustituye nmap -sn inicial en vboxnet?",
    challengeKeywords: ["no"],
  }),
  L("socks-proxy", "PIVOTING", "SOCKS / proxying", {
    what: "SOCKS: proxy genérico de TCP. proxychains nmap a través del pivot. Más amplio que un solo portfwd. msf autoroute + socks.",
    why: "Cuando hay una red entera detrás, no un puerto.",
    how: "Concepto: tú → SOCKS en Kali → víctima → red 10.x. proxychains. Solo lab.",
    when: "Enum de post-ex mostró otra subnet.",
    example: "proxychains nmap -sT 10.1.1.0/24 (sin -sS a veces).",
    mistake: "SOCKS el día 1 sin segunda red. proxychains contra tu casa.",
    redTeam: "Si no hay ruta, SOCKS no inventa hosts." + SAFE,
    recall: "proxychains sirve para…",
    recallKeywords: ["proxy", "socks", "pivot"],
    challenge: "¿SOCKS es Gobuster?",
    challengeKeywords: ["no"],
  }),
  L("multi-net", "PIVOTING", "Escenarios multi-red", {
    what: "Kali ve red A. Víctima tiene A y B. Targets en B. Tú no tienes L2 en B. Pivot = routing vía víctima.",
    why: "eJPT puede incluir un salto. El HUD RHOST UNKNOWN en B hasta que enum interno.",
    how: "1) comprometer host dual-homed. 2) enum ip a. 3) route/socks/fwd. 4) nmap red B. 5) LHOST sigue siendo alcanzable desde quien llama (a veces el pivot, no Kali directo).",
    when: "Evidencia de dual NIC. No antes.",
    example: "eth0 192.168.56.101, eth1 10.10.10.1",
    mistake: "set LHOST 10.10.10.x desde Kali que no tiene esa NIC.",
    redTeam: "Pregunta: ¿quién puede abrir TCP hacia LHOST? Esa es la geometría." + SAFE,
    recall: "Un host con dos NICs en dos /24 es candidato a…",
    recallKeywords: ["pivot"],
    challenge: "¿LHOST de reverse desde red B es siempre wlan0?",
    challengeKeywords: ["no"],
  }),
  L("win-users", "WINDOWS", "Windows users/groups", {
    what: "SAM, AD si hay dominio. whoami /groups. Administrators vs Users. Services (SYSTEM). eJPT toca Windows menos que Linux en TU lab actual (MS2 es Linux); igual el examen pregunta conceptos.",
    why: "No aplicar hashdump/SAM a MS2. Saber decir 'esto es Windows'.",
    how: "whoami, net user, net localgroup. Meterpreter getuid, hashdump con privs.",
    when: "Sesión Windows de lab legal (MS3 opcional).",
    example: "NT AUTHORITY\\SYSTEM = máximo local.",
    mistake: "hashdump en Linux meterpreter.",
    redTeam: "Identifica el OS en sysinfo ANTES del módulo post." + SAFE,
    recall: "hashdump vuelca…",
    recallKeywords: ["sam", "windows", "hash"],
    challenge: "¿MS2 Metasploitable 2 es Windows?",
    challengeKeywords: ["no"],
  }),
  L("win-ps", "WINDOWS", "PowerShell y servicios", {
    what: "PowerShell es shell + admin. Execution policy no es un muro serio. Servicios (services.msc / sc). Scheduled tasks = cron de Windows.",
    why: "Privesc Windows conceptual: servicio escribible, tarea programada, token. No un kit de C2.",
    how: "Get-Service, schtasks /query. Unquoted path (concepto).",
    when: "Lab Windows. No MS2.",
    example: "Tarea que corre como SYSTEM y el binario es escribible por Users.",
    mistake: "powershell -enc contra máquinas ajenas.",
    redTeam: "Misma pregunta Linux/Windows: ¿quién corre el binario y quién escribe?" + SAFE,
    recall: "Scheduled tasks en Windows equivalen a…",
    recallKeywords: ["cron"],
    challenge: "¿Unquoted service path es un módulo vsftpd?",
    challengeKeywords: ["no"],
  }),
  L("win-smb-privesc", "WINDOWS", "Windows SMB y privesc (concepto)", {
    what: "SMB en Windows es nativo (445). Shares, null session en antiguos, relay (avanzado, no eJPT day-1). Privesc: kernel (MS17 conceptual), servicios, tokens impersonate (meterpreter getsystem a veces).",
    why: "El examen distingue Linux Samba vs Windows AD/SMB. TU MS2 es Samba Linux.",
    how: "enum4linux igual en Samba. En Windows real: net view, smbclient, crackmapexec (si el plan lo llega a cubrir, lab propio).",
    when: "445 en Windows lab. getsystem solo en esa sesión.",
    example: "getsystem falla sin privs: no es 'Metasploit roto', es el contexto.",
    mistake: "EternalBlue a un host que no es tu VM.",
    redTeam: "sysinfo → OS. Luego el catálogo de post correcto." + SAFE,
    recall: "getsystem es típico de…",
    recallKeywords: ["windows", "meterpreter"],
    challenge: "¿getsystem es el primer comando en MS2 Linux?",
    challengeKeywords: ["no"],
  }),
];
