import { LearnArticle } from "@/content/learn-types";

function L(
  id: string,
  track: string,
  titleEs: string,
  fields: Omit<LearnArticle, "id" | "track" | "titleEs">
): LearnArticle {
  return { id, track, titleEs, ...fields };
}

const SAFE = " Solo lab propio / examen autorizado.";

export const LEARN_CATALOG_B: LearnArticle[] = [
  L("linux-fs", "LINUX", "Filesystem", {
    what: "Árbol único desde /. /etc configuración, /home usuarios, /tmp mundo-escribible, /var logs y web, /proc kernel, /usr binarios. No hay C:\\. pwd te dice dónde estás; ls -la qué hay.",
    why: "eJPT y post-ex son 'encontrar un archivo'. Si no navegas, no hay loot ni evidencia.",
    how: "pwd, ls -la, cd, find, locate (si hay DB). Distingue No such file vs Permission denied.",
    when: "Siempre en shell. Tras access, enum del FS es privesc barato.",
    example: "ls -la /etc/passwd es legible; /etc/shadow suele denied.",
    mistake: "Buscar C:\\Windows en MS2 Linux.",
    redTeam: "Empieza por whoami + pwd. Luego archivos de config del servicio que explotaste." + SAFE,
    recall: "¿Dónde suelen estar las configs de sistema?",
    recallKeywords: ["etc"],
    challenge: "/etc/shadow vs passwd: ¿cuál es más sensible?",
    challengeKeywords: ["shadow"],
  }),
  L("linux-users", "LINUX", "Users y groups", {
    what: "passwd lista cuentas (uid). shadow hashes. groups/id muestran pertenencia. uid 0 = root. Un usuario en sudoers no es root todavía: puede ejecutar con privilegio.",
    why: "Initial access como www-data ≠ game over. El examen pregunta quién eres y si puedes sudo.",
    how: "id, whoami, cat /etc/passwd, grep sudo. getent. En MS2 msfadmin es conocido.",
    when: "Tras cualquier shell. Antes de hydra: ¿ya tienes users de SMB?",
    example: "id → uid=1000(msfadmin) gid=1000 groups=sudo?",
    mistake: "hashdump SAM en Linux.",
    redTeam: "User list de enum SMB alimenta SSH. No inventes root/root." + SAFE,
    recall: "uid 0 es…",
    recallKeywords: ["root"],
    challenge: "¿/etc/passwd guarda hashes modernos?",
    challengeKeywords: ["no"],
  }),
  L("sudo", "LINUX", "sudo", {
    what: "Ejecutar como otro usuario (casi siempre root) según /etc/sudoers. sudo -l lista qué puedes. NOPASSWD es un hallazgo de privesc clásico.",
    why: "eJPT Linux privesc: a menudo sudo -l, no un kernel exploit de Internet.",
    how: "sudo -l. Si puedes vim/find/python como root, GTFOBins (concepto: el binario mal permitido).",
    when: "Cuando ya tienes shell de user.",
    example: "(ALL) NOPASSWD: /usr/bin/vim → privesc conocido.",
    mistake: "sudo su sin mirar sudo -l y tirar passwords a ciegas.",
    redTeam: "sudo -l es el primer comando de privesc Linux, junto con SUID." + SAFE,
    recall: "¿Qué comando lista tus reglas sudo?",
    recallKeywords: ["sudo -l", "sudo -l"],
    challenge: "NOPASSWD en un editor: ¿puede ser privesc?",
    challengeKeywords: ["si"],
  }),
  L("processes", "LINUX", "Procesos y services", {
    what: "Un proceso es un programa en ejecución (PID). ps, top. systemctl/service en systemd. Cron lanza jobs. Un servicio vulnerable es un proceso escuchando (ss -tlnp).",
    why: "Post-ex: qué corre como root. Privesc: cron escribible, servicios internos.",
    how: "ps aux, ss -tlnp, systemctl list-units --type=service (si hay).",
    when: "Tras access. En Kali host para ver si docker/dvwa vive.",
    example: "apache2 root vs www-data: distinto impacto.",
    mistake: "Matar procesos en el guest de lab por aburrimiento.",
    redTeam: "Listeners internos (127.0.0.1:xxxx) piden pivot local, no nmap desde Kali." + SAFE,
    recall: "¿Qué muestra puertos escuchando y procesos?",
    recallKeywords: ["ss", "netstat"],
    challenge: "Un servicio en 127.0.0.1:8080 en la víctima: ¿lo ves con nmap desde Kali al RHOST?",
    challengeKeywords: ["no"],
  }),
  L("cron", "LINUX", "cron", {
    what: "Planificador: /etc/crontab, /etc/cron.*, crontab -l. Corre como el dueño del crontab (root en crontab de sistema).",
    why: "Si un script de cron es escribible por tu user, privesc. Clásico eJPT/OSCP-lite.",
    how: "cat /etc/crontab, ls -la scripts, find escribibles.",
    when: "Privesc Linux, no en recon inicial.",
    example: "root corre /usr/local/bin/backup.sh cada minuto y www-data puede escribirlo.",
    mistake: "Editar cron de Kali host pensando que es la víctima.",
    redTeam: "¿Quién ejecuta el script y quién puede escribirlo? Esa diferencia es el exploit de lógica, no un CVE de Twitter." + SAFE,
    recall: "Archivo clásico de cron de sistema?",
    recallKeywords: ["crontab"],
    challenge: "¿Cron es recon de nmap?",
    challengeKeywords: ["no"],
  }),
  L("linux-ssh", "LINUX", "SSH", {
    what: "Secure Shell, 22/tcp. Autenticación password o clave. ssh user@IP. Connection refused ≠ password mal: nada escucha. Permission denied = hay sshd, creds mal. Timeout = red.",
    why: "Acceso legítimo tras hydra/enum. También tú atacas DESDE ssh a tu guest, no al revés el primer día.",
    how: "ssh -v para debug. known_hosts. Claves en ~/.ssh.",
    when: "22 open y tienes user, o el brief da creds.",
    example: "ssh msfadmin@TARGET_MS2",
    mistake: "hydra root + rockyou entero en 50 min contra MS2 inestable.",
    redTeam: "22 open es una puerta, no un 0-day. Enum user primero." + SAFE,
    recall: "SSH denied vs refused: ¿cuál es credenciales?",
    recallKeywords: ["denied"],
    challenge: "¿nmap se corre dentro de MS2 el día 1?",
    challengeKeywords: ["no"],
  }),
  L("env-path", "LINUX", "PATH y variables", {
    what: "PATH = directorios donde la shell busca binarios. env, export, echo $PATH. Un PATH relativo en cron/sudo (curl sin ruta) permite hijack si escribes un binario falso en un dir writable que va antes.",
    why: "Privesc y 'command not found'. Distingue Kali PATH de guest PATH.",
    how: "echo $PATH, which nmap, type sudo.",
    when: "command not found; privesc PATH hijack.",
    example: "which nmap → /usr/bin/nmap en Kali.",
    mistake: "Instalar herramientas DENTRO del guest pensando que es tu atacante.",
    redTeam: "El atacante es Kali host. El guest es el objetivo." + SAFE,
    recall: "¿PATH lista…?",
    recallKeywords: ["directorio", "binario", "ejecut"],
    challenge: "command not found: ¿siempre es Permission denied?",
    challengeKeywords: ["no"],
  }),
  L("pipes-redir", "LINUX", "Pipes y redirección", {
    what: "| conecta stdout de A a stdin de B. > sobrescribe archivo. >> añade. 2> stderr. 2>/dev/null silencia errores. < lee de archivo.",
    why: "Evidencia (guardar nmap), grep, y payloads. El examen espera que sepas > vs |.",
    how: "whoami > /tmp/x; cat /tmp/x. nmap ... | tee file.",
    when: "Siempre en lab. Post-ex para no perder output.",
    example: "2>/dev/null en find para no llenar la pantalla de denied.",
    mistake: "> cuando querías >> y borrar loot.",
    redTeam: "Si no está en un archivo, el scrollback no es evidencia de examen." + SAFE,
    recall: "¿Qué hace 2>/dev/null?",
    recallKeywords: ["stderr", "error"],
    challenge: "| vs >: ¿cuál manda a otro comando?",
    challengeKeywords: ["pipe", "|"],
  }),
  L("proc", "LINUX", "/proc", {
    what: "FS virtual del kernel. /proc/self/environ, cmdline, /proc/net. A veces secretos en environ de un proceso.",
    why: "Post-ex: passwords en cmdline, puertos, PIDs.",
    how: "ls /proc, cat /proc/PID/cmdline, environ (tr '\\0' '\\n').",
    when: "Tras access, enum profunda.",
    example: "Un servicio con --password= en cmdline.",
    mistake: "Creer que /proc es un disco que 'formateas'.",
    redTeam: "Environ y cmdline son loot barato antes de kernel exploits." + SAFE,
    recall: "/proc refleja…",
    recallKeywords: ["kernel", "proceso"],
    challenge: "¿/proc es el sitio para nmap desde Kali?",
    challengeKeywords: ["no"],
  }),
  L("suid-caps", "LINUX", "SUID y capabilities", {
    what: "SUID: el binario corre con uid del dueño (a menudo root). ls -l → s en owner. Capabilities (getcap) son privilegios finos (cap_setuid, cap_net_raw) sin SUID clásico.",
    why: "Privesc Linux #2 después de sudo -l. find / -perm -4000 2>/dev/null.",
    how: "find SUID, getcap -r / 2>/dev/null. Compara con GTFOBins (concepto, no copiar exploits de internet a redes ajenas).",
    when: "User shell, objetivo root.",
    example: "find SUID nmap antiguo con interactive mode (lab old).",
    mistake: "chmod 777 en Kali host como 'solución'.",
    redTeam: "SUID + binario conocido > kernel CVE random." + SAFE,
    recall: "Bit SUID en ls -l se ve como…",
    recallKeywords: ["s"],
    challenge: "¿SUID aplica a Windows SAM?",
    challengeKeywords: ["no"],
  }),
  L("host-discovery", "RECON", "Host discovery", {
    what: "¿Quién está vivo en el rango? nmap -sn. En LAN, ARP. No lista puertos. El default de nmap si omites -sn es scan de puertos a un host, no discovery de /24.",
    why: "No tires -p- a 254 IPs. eJPT da un rango: primero vivos.",
    how: "nmap -sn <CIDR de ip route>. Anota IPs. Tu .1 es Kali.",
    when: "Inicio de box / lab. Si ya tienes RHOST, no loops de -sn.",
    example: "nmap -sn 192.168.56.0/24 → Kali + MS2 + Kioptrix.",
    mistake: "-sn a 192.168.1.0/24 de casa.",
    redTeam: "Discovery ≠ versions. Siguiente: UNA IP, puertos." + SAFE,
    recall: "Flag nmap de host discovery sin puertos?",
    recallKeywords: ["-sn", "sn"],
    challenge: "¿-sn te da vsftpd 2.3.4?",
    challengeKeywords: ["no"],
  }),
  L("port-scan", "RECON", "Port scanning", {
    what: "-sS SYN (root), -sT connect. Default top 1000. -p- todos TCP. -p22,80,445 lista. -F rápido y ciego.",
    why: "Servicio en 8180 no sale en top 1000. eJPT pregunta flags exactos.",
    how: "Tras -sn: nmap -p- o -p- -sV a UNA IP. -oA evidencia.",
    when: "Tienes RHOST. No mezclar con gobuster.",
    example: "nmap -p- -sV TARGET -oA scan",
    mistake: "Relanzar el mismo -p- porque no guardaste.",
    redTeam: "El output es el mapa. La siguiente herramienta sale de las columnas." + SAFE,
    recall: "¿-p- cubre UDP?",
    recallKeywords: ["no"],
    challenge: "Default nmap sin -p-: ¿todos los TCP?",
    challengeKeywords: ["no"],
  }),
  L("banner-nse", "RECON", "Banner y NSE", {
    what: "-sV habla con el servicio (banner/versión). -sC scripts default. --script nombre o categoría. NSE no es Metasploit: informa, a veces enum (ftp-anon, smb-os-discovery).",
    why: "vsftpd 2.3.4 ≠ 'ftp'. searchsploit/msf search necesitan versión.",
    how: "nmap -sC -sV -p21,80,445. Un script: --script ftp-anon -p21.",
    when: "Tras puertos open. vuln category es ruidosa; no es el primer día.",
    example: "ftp-anon: Anonymous FTP login allowed",
    mistake: "-A a toda la /24.",
    redTeam: "NSE = dato. Exploit = otro paso, con autorización." + SAFE,
    recall: "-sV da la columna…",
    recallKeywords: ["version"],
    challenge: "¿-sC lanza exploits de Metasploit?",
    challengeKeywords: ["no"],
  }),
  L("attack-surface", "RECON", "Attack surface", {
    what: "Todo lo que acepta input: puertos, rutas HTTP, shares, logins, params. No es 'un CVE'. Es el conjunto de sitios donde puedes equivocarte o el defensor dejó algo.",
    why: "Priorizar superficie grande (SMB+HTTP) vs SSH sin user.",
    how: "Lista del nmap + gobuster + enum4linux = superficie. Tacha lo enumerado.",
    when: "Tras el primer scan, y cada vez que un hallazgo abre otra puerta.",
    example: "/phpmyadmin + 445 shares + FTP anon = tres superficies.",
    mistake: "Una superficie (22) y hydra 2 horas.",
    redTeam: "Amplía mapa, luego profundiza UNA, no las tres a medias." + SAFE,
    recall: "Attack surface son…",
    recallKeywords: ["servicio", "puerto", "ruta", "input"],
    challenge: "¿Un puerto closed es superficie activa?",
    challengeKeywords: ["no"],
  }),
  L("enum-ssh", "ENUMERATION", "Enum SSH", {
    what: "Banner (versión OpenSSH), users (a veces), auth methods. No es hydra el primer comando. nmap -sV -p22. A veces ssh-audit en lab.",
    why: "Versión puede coincidir con un módulo; user viene de SMB/FTP.",
    how: "nc IP 22, nmap -sV -p22. Hydra solo con -l user y lista corta en lab.",
    when: "22 open.",
    example: "User msfadmin de enum4linux → hydra -l msfadmin -P corta ssh://IP -t 4",
    mistake: "-L rockyou de users contra sshd.",
    redTeam: "SSH es autenticación. Enumera identidad primero." + SAFE,
    recall: "Antes de Hydra SSH necesitas…",
    recallKeywords: ["user", "usuario"],
    challenge: "22 open sin user: ¿Hydra ya?",
    challengeKeywords: ["no"],
  }),
  L("enum-http", "ENUMERATION", "Enum HTTP", {
    what: "Qué hay detrás de 80/443: título, dirs, robots, tecnologías, forms, comments. curl -I, whatweb/httpx (si está), gobuster, navegador al lab.",
    why: "Rutas /admin /uploads cambian el box. Un 403 es hallazgo.",
    how: "curl -i, gobuster dir -u http://IP -w common.txt. Luego mira CADA ruta, no relances rockyou de dirs.",
    when: "80 o 443 open. DVWA en 127.0.0.1:4280 es otro target (local).",
    example: "robots.txt Disallow: /backup",
    mistake: "Gobuster a 445.",
    redTeam: "HTTP enum = mapa de URLs. Login form = otro capítulo (hydra/auth)." + SAFE,
    recall: "Herramienta de dirs en Kali típica eJPT?",
    recallKeywords: ["gobuster"],
    challenge: "403: ¿el path no existe?",
    challengeKeywords: ["no"],
  }),
  L("enum-dns-svc", "ENUMERATION", "Enum DNS (servicio)", {
    what: "Si 53 está open en el target, es un servidor DNS, no solo 'el resolver de Kali'. Pregunta registros, zona, nombres internos.",
    why: "Hostnames = más IPs y roles (dc, mail, www).",
    how: "dig @RHOST version.bind chaos txt; axfr si aplica; nmap -sU -p53 --script dns-* con tino.",
    when: "53 open en el box, no 8.8.8.8.",
    example: "AXFR lista www, ftp, dc.",
    mistake: "AXFR a DNS de tu ISP.",
    redTeam: "El NS del lab es el objetivo. El de Google no." + SAFE,
    recall: "Transferencia de zona se llama…",
    recallKeywords: ["axfr"],
    challenge: "dig @8.8.8.8 al lab MS2: ¿es el DNS de la víctima?",
    challengeKeywords: ["no"],
  }),
  L("enum-snmp", "ENUMERATION", "SNMP", {
    what: "Simple Network Management Protocol, UDP 161. Communities (public/private) como 'passwords' débiles. Puede listar interfaces, procesos, users.",
    why: "Labs antiguos eJPT-like. snmpwalk con public.",
    how: "nmap -sU -p161. snmpwalk -v2c -c public IP. Solo lab.",
    when: "161/udp open o el brief lo menciona.",
    example: "public → lista de interfaces y software.",
    mistake: "snmpwalk a toda tu LAN doméstica.",
    redTeam: "Community strings = credenciales mal puestas. Enum, no DDoS." + SAFE,
    recall: "Puerto SNMP?",
    recallKeywords: ["161"],
    challenge: "SNMP es ¿TCP 80?",
    challengeKeywords: ["no"],
  }),
  L("enum-smtp", "ENUMERATION", "SMTP", {
    what: "Correo 25/tcp. VRFY/EXPN a veces enumeran users. Banner de versión.",
    why: "Users para SSH/hydra. Labs clásicos.",
    how: "nc IP 25, VRFY root. nmap --script smtp-enum-users -p25.",
    when: "25 open.",
    example: "VRFY msfadmin → 250",
    mistake: "Spamear Internet.",
    redTeam: "SMTP enum = nombres, no 'hackear Gmail'." + SAFE,
    recall: "Puerto SMTP?",
    recallKeywords: ["25"],
    challenge: "VRFY sirve para…",
    challengeKeywords: ["user", "usuario"],
  }),
  L("enum-db", "ENUMERATION", "Bases de datos (puerto)", {
    what: "3306 MySQL, 1433 MSSQL, 5432 Postgres, 27017 Mongo. Un puerto DB open no es SQLi web: es un servicio al que te conectas si hay creds o auth débil.",
    why: "Confundir 3306 con inyectar en ?id= es un fallo de razonamiento.",
    how: "nmap -sV -p3306. mysql -h IP -u user -p si tienes creds de loot. SQLi es en HTTP params.",
    when: "Puerto DB open o SQLi en web (otro artículo).",
    example: "Creds en config.php → mysql cliente al 3306 del mismo host.",
    mistake: "sqlmap contra 3306 sin URL HTTP.",
    redTeam: "DB network vs SQLi aplicación: dos caminos." + SAFE,
    recall: "3306 típico?",
    recallKeywords: ["mysql"],
    challenge: "sqlmap -u URL vs mysql -h: ¿cuál es inyección web?",
    challengeKeywords: ["sqlmap", "url"],
  }),
];
