import { LearnArticle } from "@/content/learn-types";
import { LEARN_CATALOG_A } from "@/content/learn-catalog-a";
import { LEARN_CATALOG_B } from "@/content/learn-catalog-b";
import { LEARN_CATALOG_C } from "@/content/learn-catalog-c";
import { LEARN_CATALOG_V8 } from "@/content/v8/learn-v8";
import { LEARN_CATALOG_V9 } from "@/content/v9/learn-v9";
import { LEARN_CATALOG_V91 } from "@/content/v91/learn";

export type { LearnArticle };

/** Núcleo inicial + catálogo amplio (eJPT surface). Un tema = una pantalla. */
export const LEARN_CORE: LearnArticle[] = [
  {
    id: "ipv4",
    track: "NETWORKING",
    titleEs: "IPv4",
    what: "IPv4 es una dirección de 32 bits, escrita en cuatro octetos (0–255), p. ej. 192.168.56.10. Lo que ves en ip addr / ifconfig es un identificador de capa 3 en UNA interfaz: vboxnet0 no es wlan0. 127.0.0.1 es loopback (tú mismo), nunca la víctima. En eJPT y en este lab casi todo es IPv4 privado (10/8, 172.16–31, 192.168/16).",
    why: "Sin IP correcta no hay RHOSTS ni LHOST. El examen vive en rangos privados; el lab Host-Only también. Confundir loopback, Wi‑Fi de casa y vboxnet quema el reloj: nmap, ping y reverse shells van a otra máquina o a ninguna.",
    how: "Anota: (1) IP de Kali en la NIC del lab, (2) IP de la víctima, (3) máscara/CIDR. ip addr + ip route. Host + máscara definen si dos IPs se ven sin router. No copies 192.168.56.1 de un tutorial si tu vboxnet es otro.",
    when: "Al encender VMs, al set LHOST/RHOSTS, al interpretar nmap, al fallar un reverse. Siempre antes de 'lanzar herramientas'.",
    example: "Kali 192.168.56.101 (o .1 en el host) y guest 192.168.56.20 = misma LAN Host-Only. ping -c 1 a la víctima. Si no hay reply, no hay scan útil.",
    mistake: "Usar 127.0.0.1 como RHOST de la VM, o LHOST = IP de wlan0 para un guest que solo ve vboxnet.",
    redTeam: "Primero conectividad (misma subnet, ping/ARP), luego scan. IP mala = tiempo perdido, no 'falla Metasploit'.",
    recall: "¿Cuántos bits tiene IPv4?",
    recallKeywords: ["32"],
    challenge: "¿127.0.0.1 es la víctima Host-Only?",
    challengeKeywords: ["no"],
  },
  {
    id: "cidr",
    track: "NETWORKING",
    titleEs: "CIDR /24",
    what: "CIDR /n = n bits de red. /24 = 255.255.255.0: los tres primeros octetos fijos, el último identifica hosts (~254 útiles; .0 red, .255 broadcast en el caso típico). /16 y /8 son redes más grandes: no las escanees enteras 'por si acaso' en un lab /24.",
    why: "Decide si dos IPs se ven sin router y qué rango pasas a nmap -sn. El brief del examen da un CIDR: es tu autorización de alcance, no un sugerencia.",
    how: "Compara los bits que la máscara fija. 192.168.56.1 y 192.168.56.20 en /24 = misma red. 192.168.56.1 y 192.168.1.20 no. El CIDR correcto sale de ip route / del brief, no de un post de blog.",
    when: "Host discovery, LHOST/RHOST, pivot (otra red = otro CIDR).",
    example: "192.168.56.0/24 cubre .1–.254 en la LAN típica de VirtualBox Host-Only.",
    mistake: "Creer que /24 son 24 hosts, o nmap -sn 10.0.0.0/8 en el examen.",
    redTeam: "Alcance = CIDR autorizado. Fuera de eso no es eJPT, es incidente.",
    recall: "¿Qué significa /24?",
    recallKeywords: ["24"],
    challenge: "56.1 y 56.20 en /24: ¿misma red?",
    challengeKeywords: ["si", "misma"],
  },
  {
    id: "tcp",
    track: "NETWORKING",
    titleEs: "TCP handshake",
    what: "TCP es orientado a conexión: handshake SYN → SYN-ACK → ACK. Después hay un flujo fiable (HTTP, SSH, SMB, FTP). UDP no hace ese handshake (DNS/SNMP típicos). Nmap -sS (SYN scan) usa SYNs a medias: más rápido/sigiloso que un connect completo; en lab Host-Only -sT también vale.",
    why: "La mayoría de servicios eJPT son TCP. Entender open/closed/filtered evita malinterpretar un firewall. Reverse/bind shells son TCP: alguien tiene que iniciar el handshake.",
    how: "Cliente SYN. Servidor SYN-ACK si el puerto escucha. Cliente ACK. 'filtered' = no hay respuesta útil (drop). ping (ICMP) no es TCP y no prueba el 80.",
    when: "Leer nmap, elegir payload reverse vs bind, distinguir ICMP vs puerto.",
    example: "22/tcp open ssh = hay un proceso escuchando TCP/22. No dice 'root' ni 'vulnerable'.",
    mistake: "Pensar que ping OK implica HTTP up, o que open = exploit listo.",
    redTeam: "open ≠ vulnerable. Es una puerta para enumerar, no para searchsploit a ciegas.",
    recall: "Tres pasos del handshake TCP?",
    recallKeywords: ["syn"],
    challenge: "¿Ping OK implica HTTP up?",
    challengeKeywords: ["no"],
  },
  {
    id: "ports",
    track: "NETWORKING",
    titleEs: "Ports",
    what: "Un puerto (1–65535) es una puerta en un host. TCP y UDP tienen espacios distintos: 53/udp ≠ 53/tcp. El número sugiere un servicio (80 HTTP, 445 SMB) pero el banner/versión manda: 8080 puede ser HTTP, 22 puede no ser OpenSSH.",
    why: "El puerto elige la familia de herramientas: 445 ≠ Gobuster; 80 ≠ enum4linux. Hidra contra 22 sin usuario es otra familia (creds), no enum de shares.",
    how: "IP = máquina. Puerto = servicio candidato. Tras -sn, -sV en los open. Anota número + nombre + versión.",
    when: "Tras host discovery, antes de elegir Gobuster/Hydra/enum4linux/msf.",
    example: "80 HTTP, 443 HTTPS, 445 SMB, 139 NetBIOS, 22 SSH, 21 FTP, 3306 MySQL, 161 UDP SNMP.",
    mistake: "Un scan y explotar el primer open, o memorizar 'siempre 445 primero' sin mirar el output.",
    redTeam: "Prioriza superficie de enum (SMB/HTTP/FTP anón) no el puerto más famoso de Twitter.",
    recall: "Puerto típico SMB?",
    recallKeywords: ["445"],
    challenge: "80 → ¿Gobuster o enum4linux por defecto?",
    challengeKeywords: ["gobuster"],
  },
  {
    id: "linux-perms",
    track: "LINUX",
    titleEs: "Permissions",
    what: "En Linux, rwx se aplican a user / group / other. Tu uid/gid decide qué triplet te aplica. El primer carácter de ls -l es el tipo (- archivo, d dir, l link). SUID (s en execute de owner) hace que el binario corra con el uid del dueño: concepto de privesc, no un 'exploit mágico'.",
    why: "Permission denied ≠ No such file. Denied es hallazgo (el objeto existe). En post-ex y en eJPT te preguntan por archivos que un user no lee (shadow) o por binarios especiales.",
    how: "ls -l, id, whoami, find con permisos (en lab). Interpreta denied vs missing. No copies find SUID de Internet contra redes ajenas.",
    when: "Leer configs, ejecutar, privesc Linux, interpretar errores de cat/cp.",
    example: "-rwsr-xr-x root = SUID. /etc/shadow denied para user normal = esperado.",
    mistake: "Tratar denied como 'no existe', o lanzar un kernel exploit porque viste un SUID sin entender el binario.",
    redTeam: "denied = existe. Anótalo. Luego busca otro uid, sudo, o un vector autorizado.",
    recall: "¿Qué significa Permission denied?",
    recallKeywords: ["existe"],
    challenge: "¿SUID corre como el dueño del fichero?",
    challengeKeywords: ["si", "owner", "dueno"],
  },
  {
    id: "recon",
    track: "RECON",
    titleEs: "Passive vs active recon",
    what: "Recon pasivo: no envías paquetes al objetivo (OSINT, whois, info pública). Activo: tocas el target (nmap, banners). eJPT y este lab son sobre todo activos DENTRO del rango autorizado. Host discovery (-sn) ≠ port scan ≠ version scan: son capas.",
    why: "Sin hosts vivos no hay RHOST. Sin puertos no hay enum. El error de examen es saltar a exploits o escanear fuera de alcance (LAN de casa, Internet).",
    how: "Autorización → descubrir hosts en el CIDR → puertos → versiones. nmap es activo. No uses la Wi‑Fi doméstica como 'lab'.",
    when: "Inicio de cada máquina y del examen. Activo solo en lab/INE autorizados.",
    example: "nmap -sn <CIDR de vboxnet>. No 192.168.1.0/24 de casa 'por si hay una Pi'.",
    mistake: "Escanear la LAN doméstica o tratar -sn como -sV.",
    redTeam: "Alcance escrito primero. Luego discovery. Luego enum. Explotar es el paso 4, no el 1.",
    recall: "¿Nmap es pasivo o activo?",
    recallKeywords: ["activ"],
    challenge: "¿-sn lista versiones?",
    challengeKeywords: ["no"],
  },
  {
    id: "smb",
    track: "ENUMERATION",
    titleEs: "SMB enumeration",
    what: "SMB (y NetBIOS 139) expone shares, a veces usuarios y políticas. En MS2/eJPT clásico es superficie enorme: listar shares, null session, archivos. No es HTTP: Gobuster no lista \\share.",
    why: "Usuarios de SMB alimentan SSH/Hydra con nombre conocido. Shares son loot (claves, scripts). Exploits Samba antiguos existen en lab, pero el flujo es enum → versión → módulo que coincida, no 'msf samba' de memoria.",
    how: "enum4linux / smbclient / smbmap contra TU RHOST. Anota users y discos. Hydra SMB solo con usuario y política clara; no es el primer comando.",
    when: "139 o 445 open en el nmap del lab/examen.",
    example: "enum4linux -a <RHOST> en Metasploitable Host-Only.",
    mistake: "Gobuster contra 445, o Hydra root@445 a ciegas.",
    redTeam: "Null/guest session primero. Versión (-sV) antes de searchsploit. Solo lab autorizado.",
    recall: "Herramienta típica SMB enum?",
    recallKeywords: ["enum4linux"],
    challenge: "445 open: ¿siguiente familia?",
    challengeKeywords: ["smb"],
  },
  {
    id: "http-403",
    track: "WEB",
    titleEs: "HTTP 403",
    what: "HTTP 403 Forbidden: el servidor admite que el recurso existe, pero tu identidad/método no pasa. 404 = el servidor dice que no está (a veces miente con custom 404). 200 = se sirve el cuerpo. 301/302 = hay otra URL. 401 = falta autenticación.",
    why: "Gobuster 403 es hallazgo: /admin existe. En eJPT eso cambia el ataque (otro user, otro verbo, otro path). Tratar 403 como 404 te hace abandonar superficie real.",
    how: "Mira status + size. Filtra 404. Anota 200 y 403. curl -I. No es un bypass WAF de conferencia: es leer códigos.",
    when: "Dirbust, cada respuesta rara, DVWA/local.",
    example: "/admin 403 → existe. /n0existe 404 → no gastes Hydra ahí.",
    mistake: "Tratar 403 como 404, o ignorar 200 en paths 'aburridos' (.git, backup).",
    redTeam: "Anota 403. Luego auth, otro vhost, o LFI/upload en OTRA ruta 200 — no 'bypass 403' de receta ciega.",
    recall: "¿403 significa que no existe?",
    recallKeywords: ["no"],
    challenge: "200 vs 403: ¿cuál es 'existe y se sirve'?",
    challengeKeywords: ["200"],
  },
  {
    id: "rhosts",
    track: "EXPLOITATION",
    titleEs: "LHOST vs RHOSTS",
    what: "En Metasploit: RHOSTS = Remote = víctima(s). LHOST = Local = la IP donde TÚ escuchas (handler). LPORT = puerto de escucha. El guest debe poder rutar paquetes a LHOST: en Host-Only eso es la IP de Kali en vboxnet, descubierta con ip addr, no un número memorizado.",
    why: "Reverse shell: la víctima inicia TCP hacia LHOST:LPORT. Si LHOST es wlan0 o 127.0.0.1, la sesión no nace. searchsploit no arregla una IP mala.",
    how: "use exploit/... → show options → set RHOSTS <guest> → set LHOST <vboxnet> → set payload si hace falta → run. Comprueba con ip addr ANTES.",
    when: "Cualquier módulo reverse, msfvenom, handler (exploit/multi/handler).",
    example: "RHOSTS=192.168.56.101 (guest). LHOST=IP de tun/vboxnet de Kali, no 127.0.0.1.",
    mistake: "LHOST=wlan0, 127.0.0.1, o la IP de casa; o RHOSTS=LHOST.",
    redTeam: "Dibuja la flecha: ¿quién llama a quién? Misma IP en payload y handler.",
    recall: "RHOSTS es ¿quién?",
    recallKeywords: ["victima"],
    challenge: "Reverse: ¿quién inicia el TCP?",
    challengeKeywords: ["victima"],
  },
  {
    id: "revbind",
    track: "EXPLOITATION",
    titleEs: "Reverse vs bind",
    what: "Reverse: la víctima abre TCP hacia el atacante (tú escuchas con nc/msf). Bind: la víctima abre un puerto y TÚ te conectas. NAT/firewall del examen suele favorecer reverse: el target puede salir; tú no siempre entras a un puerto nuevo.",
    why: "Elegir mal el payload = 'exploit OK, 0 sessions'. En Host-Only ambos suelen funcionar; igual debes saber la flecha.",
    how: "Reverse: listener en LHOST:LPORT primero. Bind: conectas a RHOST:puerto del payload. nc -e no existe igual en todos los Linux: no memorices un one-liner como si fuera universal.",
    when: "Payloads msfvenom, meterpreter, nc, cuando 'el exploit corre y no hay shell'.",
    example: "nc -lvnp 4444 en Kali espera un reverse. bind_tcp: nmap el puerto nuevo o connect.",
    mistake: "Poner LHOST en un bind como si fuera reverse, o esperar shell sin listener.",
    redTeam: "Flecha TCP en papel. Luego set payload. Solo lab/examen.",
    recall: "¿En reverse quién escucha?",
    recallKeywords: ["atacante", "kali", "lhost", "tu"],
    challenge: "Bind: ¿necesitas LHOST siempre?",
    challengeKeywords: ["no"],
  },
  {
    id: "post",
    track: "POST",
    titleEs: "Post-exploitation mínima",
    what: "Post-explotación = trabajar YA DENTRO: quién eres (whoami/id/getuid), qué SO (sysinfo/uname), red (ip addr, arp), loot permitido (flags, hashes si el brief lo pide). No es 'más exploits al azar'.",
    why: "El examen pregunta valores concretos (usuario, hash, archivo). Privesc sin saber uid es teatro. hashdump/SAM es Windows; Metasploitable Linux no es un DC.",
    how: "Sesión estable → identidad → SO → archivos del objetivo → privesc SOLO si no eres root/SYSTEM y el objetivo lo exige. Anota evidencia.",
    when: "Tras initial access, antes de 'siguiente CVE'.",
    example: "getuid → msfadmin. cat del archivo que pide la pregunta. No kernel exploit de 2012 por deporte.",
    mistake: "hashdump SAM en Linux, o pivot el día 1 sin segunda NIC.",
    redTeam: "Si ya eres root, documenta y para. El reloj del examen premia respuestas, no shells extra.",
    recall: "Dos comandos de identidad en sesión?",
    recallKeywords: ["whoami"],
    challenge: "¿hashdump aplica en MS2 Linux?",
    challengeKeywords: ["no"],
  },
  {
    id: "pivot",
    track: "PIVOTING",
    titleEs: "Why pivot",
    what: "Pivoting: usar un host ya comprometido como puente hacia una red que Kali no ve (segunda NIC, RFC1918 oculta). No es 'nmap otra vez el mismo /24 de vboxnet'. Técnicas de concepto eJPT: rutas, port forward, SOCKS — el detalle de comandos vive en LEARN PIVOTING.",
    why: "El examen puede tener un segmento interno. Si tu nmap inicial no lo ve, no está 'caído': está detrás. Si SOLO hay vboxnet, no inventes un pivot.",
    how: "Comprueba ip addr en la víctima. Si hay otra subnet, entonces forward/SOCKS/ruta. Autorreglas: solo rangos del brief.",
    when: "Tras access + evidencia de otra red. No el día 1 de un lab de una NIC.",
    example: "Víctima eth0=192.168.56.20 y eth1=10.1.1.1 → 10.1.1.0/24 es candidata a pivot.",
    mistake: "Pivoting sustituyendo el nmap inicial, o meterpreter route hacia tu Wi‑Fi de casa.",
    redTeam: "¿Kali ve el target? Si sí, no es pivot. Si no, puente. Nunca pivot a Internet de terceros.",
    recall: "¿Pivot = atacar una red que no ves desde Kali?",
    recallKeywords: ["si", "red"],
    challenge: "¿Pivoting sustituye a nmap inicial en vboxnet?",
    challengeKeywords: ["no"],
  },
];

export const LEARN_ARTICLES: LearnArticle[] = [
  ...LEARN_CORE,
  ...LEARN_CATALOG_A,
  ...LEARN_CATALOG_B,
  ...LEARN_CATALOG_C,
  ...LEARN_CATALOG_V8,
  ...LEARN_CATALOG_V9,
  ...LEARN_CATALOG_V91,
];

export const LEARN_PLANNED: { track: string; titles: string[] }[] = [];
