import { LearnArticle } from "@/content/learn-types";

function L(
  id: string,
  track: string,
  titleEs: string,
  fields: Omit<LearnArticle, "id" | "track" | "titleEs">
): LearnArticle {
  return { id, track, titleEs, ...fields };
}

const SAFE =
  " Solo contra lab propio / examen autorizado. No contra redes de casa ni terceros.";

export const LEARN_CATALOG_A: LearnArticle[] = [
  L("subnetting", "NETWORKING", "Subnetting", {
    what: "Dividir un bloque IP en redes más pequeñas. La máscara (CIDR) dice cuántos bits son 'red' y cuántos 'host'. /24 deja 8 bits de host (~254 hosts útiles). /16 deja 16 bits de host. No es magia: es aritmética binaria de la dirección.",
    why: "En eJPT te dan un rango. Si no sabes qué IPs están 'dentro', escaneas de más o te pierdes un segmento. LHOST y RHOSTS tienen que compartir red de capa 3 para verse sin pivot.",
    how: "Anota la red (ej. 10.10.10.0/24). Los hosts válidos no son .0 (red) ni .255 (broadcast en /24 típico). Compara los octetos que la máscara fija. ipcalc/sipcalc ayudan; en el examen debes razonarlo.",
    when: "Al leer el brief, al interpretar ip route, al decidir nmap -sn <CIDR> y no un /16 entero.",
    example: "10.10.10.5/24 y 10.10.11.5/24 NO son la misma /24. 10.10.10.5 y 10.10.10.80 sí.",
    mistake: "Escanear 192.168.1.0/24 'porque es privado' cuando tu lab es 192.168.56.0/24.",
    redTeam: "Primera pregunta: ¿estoy en la misma subnet que el target? Si no, o te equivocaste de NIC, o necesitas pivot." + SAFE,
    recall: "En /24, ¿qué identifica a los hosts?",
    recallKeywords: ["ultimo", "octeto", "8 bits", "host"],
    challenge: "10.1.1.9/24 y 10.1.2.9/24: ¿misma subnet /24?",
    challengeKeywords: ["no"],
  }),
  L("arp", "NETWORKING", "ARP", {
    what: "Address Resolution Protocol: resuelve IPv4 → MAC en la LAN local. '¿Quién tiene 192.168.56.101? Dilo en Ethernet'. No cruza routers: ARP es de la misma L2.",
    why: "Host discovery en LAN a menudo usa ARP. Si dos hosts no están en el mismo broadcast domain, ARP no los une. MITM/ARP spoof es Mes 2: concepto, no tu primer lab Host-Only.",
    how: "El host pregunta en broadcast. Quien tiene esa IP responde con su MAC. ip neigh / arp -a muestra la tabla.",
    when: "Misma LAN (vboxnet). No para alcanzar 8.8.8.8.",
    example: "Tras ping a MS2, ip neigh muestra la MAC del guest.",
    mistake: "Creer que ARP sustituye a nmap de puertos.",
    redTeam: "Si no hay entrada ARP y ping falla, primero L2/misma red, no Metasploit." + SAFE,
    recall: "ARP traduce ¿qué a qué?",
    recallKeywords: ["ip", "mac"],
    challenge: "¿ARP funciona a través de Internet hacia un servidor remoto?",
    challengeKeywords: ["no"],
  }),
  L("dns", "NETWORKING", "DNS", {
    what: "Domain Name System: nombre → IP (A/AAAA), y al revés (PTR). UDP/53 típico; TCP/53 para transferencias grandes. En lab eJPT a veces hay un DNS interno con registros jugosos.",
    why: "Un nombre (intranet.local, dc.corp) cambia el ataque. Zone transfer (AXFR) mal configurado lista hosts. No es 'hackear Google': es el DNS del rango autorizado.",
    how: "dig, host, nslookup. Preguntas A, MX, TXT, AXFR al NS que te autoricen. nmap -sU -p53 si el brief lo pide.",
    when: "Puerto 53 open, o el brief da un dominio interno.",
    example: "dig @<IP_DNS> axfr dominio.local — solo si es TU lab.",
    mistake: "AXFR contra un DNS público de Internet.",
    redTeam: "DNS enum = mapa de nombres. Luego nmap a esas IPs, no a toda la Internet." + SAFE,
    recall: "Puerto típico DNS?",
    recallKeywords: ["53"],
    challenge: "¿AXFR es enumeración o un exploit de kernel?",
    challengeKeywords: ["enum"],
  }),
  L("dhcp", "NETWORKING", "DHCP", {
    what: "Dynamic Host Configuration Protocol: reparte IP, máscara, gateway, DNS. UDP 67/68. En VirtualBox Host-Only el servidor DHCP es opcional del hipervisor, no 'el router de casa'.",
    why: "Si el guest no tiene IP, a veces falta DHCP o debes asignar estático en EL MISMO /24 que Kali.",
    how: "El cliente pide lease. El servidor ofrece. En MS2 antiguo a veces ifconfig manual.",
    when: "Guest sin inet. No es un vector de eJPT central; es lab.",
    example: "Host-Only DHCP .100–.254; Kali host suele ser estática .1",
    mistake: "Esperar dhclient en vboxnet del HOST: el host no se auto-DHCP a sí mismo igual que un guest.",
    redTeam: "Sin IP no hay RHOST. Arregla capa 3 antes de nmap -sV." + SAFE,
    recall: "DHCP reparte principalmente ¿qué?",
    recallKeywords: ["ip"],
    challenge: "¿El host Kali en vboxnet obtiene IP por DHCP de casa (wlan0)?",
    challengeKeywords: ["no"],
  }),
  L("routing", "NETWORKING", "Routing", {
    what: "Tabla de rutas: 'para esta red, sal por esta interfaz / este gateway'. default = 0.0.0.0/0. El lab Host-Only tiene una ruta al /24 por vboxnet; Internet del host va por wlan0/eth0.",
    why: "LHOST equivocado = reverse que no vuelve. Ping a 8.8.8.8 no prueba el lab. ip route es el mapa.",
    how: "ip route. Busca tu CIDR de lab y la default. En pivot: añades rutas hacia la red oculta vía el host comprometido (Mes 2).",
    when: "Siempre que 'no hay conectividad' o prepares reverse/pivot.",
    example: "192.168.56.0/24 dev vboxnet0  vs  default via 192.168.1.1 dev wlan0",
    mistake: "Poner LHOST la IP de wlan0 para un guest que solo ve vboxnet.",
    redTeam: "Dibuja tres cajas: Kali, switch virtual, guest. La flecha reverse termina en vboxnet." + SAFE,
    recall: "¿Qué comando muestra la tabla de rutas en Linux moderno?",
    recallKeywords: ["ip route"],
    challenge: "default via wlan0: ¿es la ruta del lab Host-Only?",
    challengeKeywords: ["no"],
  }),
  L("udp", "NETWORKING", "UDP", {
    what: "User Datagram Protocol: sin handshake. DNS, SNMP, a veces servicios 'silenciosos'. Nmap UDP (-sU) es lento y ruidoso; no es el default de un bloque de 45 min salvo que el brief lo pida.",
    why: "eJPT toca UDP en servicios concretos (53, 161). Pensar que 'todo es TCP 80' te ciega.",
    how: "nmap -sU -p53,161 --max-retries bajos en lab. Interpreta open|filtered con cautela.",
    when: "El brief o un TCP no explica el box (DNS/SNMP).",
    example: "SNMP community public en UDP 161 (lab antiguo).",
    mistake: "-sU a 65535 puertos en 50 minutos.",
    redTeam: "UDP es cirujano: puertos sospechosos, no spray." + SAFE,
    recall: "¿UDP hace handshake SYN?",
    recallKeywords: ["no"],
    challenge: "53/udp típico: ¿qué servicio?",
    challengeKeywords: ["dns"],
  }),
  L("sockets", "NETWORKING", "Sockets", {
    what: "Un socket es IP + puerto + protocolo. 'Hablar con 192.168.56.101:80/tcp' es un socket. El proceso (sshd, apache) escucha. Tú te conectas desde otro socket efímero.",
    why: "open en nmap = hay un proceso escuchando. filtered = no sabes. El siguiente paso es ESE servicio, no 'el host'.",
    how: "ss -tlnp / netstat en el host que controlas. En la víctima, tras access.",
    when: "Post-ex (qué escucha) y al leer nmap.",
    example: "0.0.0.0:22 = SSH en todas las interfaces.",
    mistake: "Confundir puerto abierto con 'ya exploté'.",
    redTeam: "Inventario de listeners = superficie. Prioriza." + SAFE,
    recall: "Un socket une ¿qué tres ideas?",
    recallKeywords: ["ip", "puerto"],
    challenge: "80 open: ¿ya hay shell?",
    challengeKeywords: ["no"],
  }),
  L("protocols", "NETWORKING", "Protocolos comunes", {
    what: "TCP: HTTP 80, HTTPS 443, SSH 22, FTP 21, SMB 139/445, SMTP 25, SQL 3306/1433. UDP: DNS 53, SNMP 161. ICMP: ping, no es un 'puerto de servicio'.",
    why: "El examen y MS2 esperan que el puerto dispare la herramienta correcta.",
    how: "Tabla mental. 445→SMB. 80→web. 21→FTP. 22→SSH. 161→SNMP.",
    when: "Tras cualquier nmap.",
    example: "445 microsoft-ds → enum4linux, no gobuster.",
    mistake: "Hydra a SSH sin usuario porque '22 está open'.",
    redTeam: "Puerto → hipótesis → una herramienta, no tres a la vez." + SAFE,
    recall: "161/udp suele ser…",
    recallKeywords: ["snmp"],
    challenge: "25/tcp típico?",
    challengeKeywords: ["smtp"],
  }),
  L("gateway", "NETWORKING", "Gateway", {
    what: "El default gateway es el salto para salir de tu subnet. En Host-Only a menudo NO hay gateway a Internet para el guest. El .1 suele ser el host (tú), no 'el router de casa'.",
    why: "Si el guest usa gateway equivocado, no habla con Kali o intenta Internet. Reverse no vuelve.",
    how: "ip route en Kali; ifconfig/route en guest. Compara.",
    when: "Ping falla y las IPs 'parecen' del mismo /24.",
    example: "Guest 10.0.2.15 (NAT) vs Kali 192.168.56.1 = redes distintas, no es 'gateway mal puesto' solamente: es el modo de adaptador.",
    mistake: "Copiar gateway 192.168.1.1 del WiFi al guest MS2.",
    redTeam: "Gateway de casa ≠ LHOST de lab." + SAFE,
    recall: "¿El guest Host-Only necesita gateway a Internet para que Kali lo nmap-ee?",
    recallKeywords: ["no"],
    challenge: "¿wlan0 es el gateway del lab vboxnet?",
    challengeKeywords: ["no"],
  }),
];
