import { LearnArticle } from "@/content/learn-types";

/** Ampliación V9: fundamentos Windows / hashes / procesos. No es academia AD. */
export const LEARN_CATALOG_V9: LearnArticle[] = [
  {
    id: "win-processes",
    track: "WINDOWS",
    titleEs: "Procesos Windows (lab)",
    what: "Un proceso corre como un usuario (o SYSTEM). tasklist / Get-Process muestran nombres y, con las herramientas adecuadas, el contexto. No es un dump de malware: es quién tiene un handle a qué.",
    why: "Servicios y tareas programadas son procesos con identidad. Si el binario es escribible o el servicio es de un user privilegiado, eso es hipótesis de privesc — en lab.",
    how: "tasklist, Get-Process, sc query. Relaciona el servicio con la ruta del binario. Solo VM autorizada.",
    when: "Tras whoami. Antes de un exploit de kernel 'porque sí'.",
    example: "Un servicio que corre como SYSTEM y apunta a C:\\opt\\svc.exe es más interesante que notepad.exe del user.",
    mistake: "Matar procesos en el host familiar o tratar tasklist como un exploit.",
    redTeam: "Identidad del proceso > nombre del CVE de moda.",
    recall: "¿tasklist es un exploit?",
    recallKeywords: ["no"],
    challenge: "¿El usuario del servicio importa más que el nombre del binario a ciegas?",
    challengeKeywords: ["si"],
  },
  {
    id: "win-hash-concept",
    track: "WINDOWS",
    titleEs: "Hashes y credenciales (concepto)",
    what: "Windows almacena secretos (NTLM, a veces tickets). Un hash no es la contraseña en claro. Pass-the-hash y cracking son familias distintas: una reutiliza el secreto, la otra intenta recuperarlo. Solo lab.",
    why: "Post-ex y movimiento lateral en eJPT piden el modelo, no un tutorial de Mimikatz en producción.",
    how: "Si encuentras un hash en lab: anótalo exacto. Pregunta: ¿me sirve para autenticar o para crackear offline? No lo lances a Internet.",
    when: "Loot de SAM/lsass en VM, o hashes en shares. Nunca en el PC de casa.",
    example: "Un NTLM de un user de lab puede explicar un share 'ACCESS DENIED' si cambias de identidad — hipótesis, no receta.",
    mistake: "Pegar hashes en foros o usarlos fuera de alcance.",
    redTeam: "Credencial = next step. Hash sin plan = ruido.",
    recall: "¿Un hash NTLM es la contraseña en claro?",
    recallKeywords: ["no"],
    challenge: "¿Alcance escrito aplica también a credenciales?",
    challengeKeywords: ["si"],
  },
  {
    id: "win-when-enum",
    track: "WINDOWS",
    titleEs: "Cuándo enumerar Windows",
    what: "Si el puerto es 445/3389/winrm en un host Windows de lab, la enum (users, shares, servicios) es la pregunta. Si solo hay 80, no inventes AD.",
    why: "Evita el salto 'vi Windows en el título del writeup'. La superficie manda.",
    how: "De nmap: OS/puertos. Luego: ¿SMB habla? ¿Hay creds previas? ¿El objetivo es el host o un share?",
    when: "Tras identificar un host Windows en alcance. No en Kali por aburrimiento.",
    example: "445 open + null session posible → users/shares. 80 only → HTTP.",
    mistake: "BloodHound en un standalone sin dominio.",
    redTeam: "Windows enum es un medio. El objetivo del brief manda.",
    recall: "¿445 open implica dominio Active Directory?",
    recallKeywords: ["no"],
    challenge: "¿Enumerar users/shares antes de nombrar un potato?",
    challengeKeywords: ["si"],
  },
];
